<style>
    .tabelaSomatorios td, th{
        padding: 3px 5px;
    }
</style>

<div class="tabelaSomatorios">
    <table style="border: 1px solid;">
       <thead>
           <tr>
                <th>Somatório por Situação</th>
                <th style="text-align: center;">Quantidade</th>
           </tr>
       </thead>
       <tbody>
           <?php foreach( $this->somatorioSituacao as $desc => $total): ?>
           <tr>
                <td> <?php  echo $desc ?> </td>
                <td style="text-align: center; width: 10%"> <?php  echo $total ?>  </td>   
           </tr>
           <?php endforeach; ?>
       </tbody>
    </table>
</div>