<div style="border: 1px solid #ccc;">
<table class="grid" style="overflow: auto">
    <thead> 
        <tr style="font-weight: bold;">
            <th> N. Solicita&ccedil;&atilde;o </td>
            <th> Data Abertura </td>
            <th> Tempo Total </td>
            <th> &Uacute;ltima Fase </td>
            <th> Data &Uacute;lt. Fase </td>
        </tr>
    </thead>
    <tbody> 
<?php foreach($this->data as $data): ?>
                <tr>
                    <td> <?php echo $data['DOCM_NR_DOCUMENTO']; ?></td>
                    <td> <?php echo $data['DH_CADASTRO']; ?></td>
                    <td> <?php echo $data['TEMPO_TOTAL_FORMATADO']; ?></td>
                    <td> <?php echo $data['DESCRICAO_FASE']; ?></td>
                    <td> <?php echo $data['MOFA_DH_FASE'];  ?></td>
                </tr>
<?php endforeach; ?>
     </tbody>           
    </table>
</div>
<br />
        
       