<script>
	$(function() {
		$( "#DOCM_ID_PCTT" ).combobox();
		$( "#combobox-input-text-DOCM_ID_PCTT" ).attr('style','width: 500px;');
		$( "#combobox-input-button-DOCM_ID_PCTT" ).attr('style','display: none;');
                $( "#PréVisualizar").click(
                    function(){
                        $( "#Formulariomemorando").attr('action','visualizar');
                        $( "#Formulariomemorando").submit();
                    }
                );

                $( "#Salvar").click(
                    function(){
                        $( "#Formulariomemorando").attr('action','save');
                        $( "#Formulariomemorando").submit();
                    }
                );


	});
</script>

<? include('visualizar.phtml'); ?>