<?php
echo $this->partial('_partials/ajax_novadespesa.phtml');
echo $this->partial('_partials/ajax_responsaveis.phtml');
echo $this->partial('_partials/ajuda_informacao.phtml', array('msgAjuda' => $this->msgAjuda,
    'msgInfo' => $this->msgInfo));
?>


<script>

    $(document).ready(function () {

        /*
         * @type String Variável para perfil logado
         */
        var $perfil = "<?php echo $this->perfil; ?>";
        var $status = "<?php echo $this->formulario->SOLD_CD_TIPO_SOLICITACAO->getValue(); ?>";

        if($perfil !== 'planejamento'){
            // $('#SOLD_DS_DESPESA').hide();
        }

        if($perfil == 'seccional'){
            $('#SOLD_CD_TIPO_SOLICITACAO').attr("class","bloqueado");
            /* Pediu para bloquear os campos abaixo para o perfil seccional 2015010001108011080160000130 */
            $('#SOLD_VL_ATENDIDO').attr("class","bloqueado");
            $('#SOLD_DS_JUSTIFICATIVA_SECOR').attr("class","bloqueado");
            

        }

        /* chama a função de regras */
        regras();

        /*
         * Observa a mudança de ano selecionado no campo.
         */
        $(document).change($('#SOLD_AA_SOLICITACAO'), function () {

            /* apos a mudança de ano valida as regras novamente */
            regras();
        });

        function regras() {

            /* desbloqueia os campos, caso estejam bloqueados */
            desbloqueiaCampos();

            /* insere a opção de aprovar solicitações */
            insereAprovar();

            /* recupera o valor selecionado no campo */
            $anoSelecionado = $('#SOLD_AA_SOLICITACAO :selected').text();

            /* regra para o status Em definição */
            if ($anoSelecionado.search('Em definição') === 7) {

                if ($perfil === "dipor") {
                    removeAprovar();
                }
            }

            /* regra para o status Liberado para responsáveis */
            if ($anoSelecionado.search('Liberado para responsáveis') === 7) {

                if (($perfil === "seccional") && $status != 1 || ($perfil === "dipor")) {
                    bloqueiaCampos();
                }

                if ($perfil === "planejamento") {
                    removeAprovar();
                }
            }

            /* regra para o status Bloqueado para consolidação */
            if ($anoSelecionado.search('Bloqueado para consolidação') === 7) {

                if ($perfil === "dipor") {
                    bloqueiaCampos();
                    removeAprovar();
                }

                /* Força o campo Recurso a descentralizar para o valor Não */
                $('#SOLD_IC_REC_DESCENTRALIZADO').val('1').attr('readOnly', 'true');
            }

            /* regra para o status Proposta Liberada para Programação Orçamentária */
            if ($anoSelecionado.search('Proposta Liberada para Programação Orçamentária') === 7) {

                if ($perfil === 'planejamento') {
                    bloqueiaCampos();
                }
            }

            /* regra para o status Em execução */
            if ($anoSelecionado.search('Em execução') === 7) {

                if ($perfil === 'seccional' && $status != 1) {
                    bloqueiaCampos();
                }

                if ($perfil === 'planejamento') {
                    removeAprovar();
                }
            }

            /* regra para o status Encerrado  */
            if ($anoSelecionado.search('Encerrado') === 7) {

                bloqueiaCampos();
            }

        }

        /*
         * Função que bloqueia todos os campos exceto o campo Ano.
         */
        function bloqueiaCampos() {

            $(":input").attr('disabled', 'true').css('background', '#DCDCDC');
            $('#SOLD_AA_SOLICITACAO').removeAttr('disabled').removeAttr('style');
        }

        /*
         * Função que desbloqueia todos os campos.
         */
        function desbloqueiaCampos() {

            $(":input").removeAttr('disabled', 'true').removeAttr('style');
        }

        /*
         * Função que remove a opção de aprovar solicitações.
         */
        function removeAprovar() {

            $('#SOLD_CD_TIPO_SOLICITACAO').find('option[value=2]').remove();
        }

        /*
         * Função que remove a opção de aprovar solicitações.
         */
        function insereAprovar() {

            if ($('#SOLD_CD_TIPO_SOLICITACAO').find('option[value=2]').text().search('Atendida') === -1) {

                $('#SOLD_CD_TIPO_SOLICITACAO').append('<option value="2">Atendida</option>');
            }
        }

    });

</script>

    <style>
        .bloqueado {
            background: #ccc !important;
            pointer-events:none;
        }
    </style>

<?php
echo $this->formulario;
