<?php if (count($this->data)): ?>
<div><a href="sisad/faseadm/form">Novo</a></div>
<table cellspacing="1" border="1">
    <thead>
        <tr>
            <th width="600px"><a href="sisad/faseadm/index/filtro/<?php echo $this->filtro ?>/ordem/FADM_DS_FASE">Descrição</a></th>
            <th width="200px">Fase Ativa</th>
            <th width="200px">Documento da Fase</th>
            <th width="50px">Alterar</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td><?php echo $this->escape($data->FADM_DS_FASE) ?></td>
            <td><?php echo $this->escape($data->FADM_IC_FASE_ATIVA) ?></td>
            <td><?php echo $this->escape($data->FADM_IC_DCTO_FASE) ?></td>
            <td><a href="sisad/faseadm/form/id/<?php echo $data->FADM_ID_FASE ?>" >Editar</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<p>Total: <?php echo $this->data->getTotalItemCount()?></p>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,
                                                                   'ordem'=> $this->ordem))
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif;?>