
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <div class="painel">
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/add">Novo</a>
    </div>
    <table class="grid">
        <thead>
            <tr>
                <th >Editar</th>
                <th >Excluir</th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/list/ordem/CXEN_ID_CAIXA_ENTRADA/direcao/<?php echo $this->direcao ?> ">Id<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/list/ordem/CXEN_DS_CAIXA_ENTRADA/direcao/<?php echo $this->direcao ?> ">Descrição do Caixa<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/list/ordem/TPCX_DS_CAIXA_ENTRADA/direcao/<?php echo $this->direcao ?> ">Tipo da Caixa<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/list/ordem/TPCX_DS_PROPRIETARIO_CAIXA/direcao/<?php echo $this->direcao ?> ">Sistema Proprietário<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td ><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/edit/id/<?php echo $this->escape($data["CXEN_ID_CAIXA_ENTRADA"]); ?>" >Editar</a></td>
                    <td ><a title="Excluir" class="excluir" href="<?php echo $this->baseUrl(); ?>/sisad/caixaentrada/del/id/<?php echo $this->escape($data["CXEN_ID_CAIXA_ENTRADA"]); ?>" >Excluir</a></td>
                    <td><?php echo $this->escape($data["CXEN_ID_CAIXA_ENTRADA"]); ?></td>
                    <td><?php echo $this->escape($data["CXEN_DS_CAIXA_ENTRADA"]); ?></td>
                    <td><?php echo $this->escape($data["TPCX_DS_CAIXA_ENTRADA"]); ?></td>
                    <td><?php echo $this->escape($data["TPCX_DS_PROPRIETARIO_CAIXA"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>
<?php //exit(alksdçfkasçdlkfj); ?>
</form>