<style type="text/css">
dd#GRMA_ID_MARCA-element {

	width:930px;
}
#GRMA_ID_MARCA-element label{
	display:inline-block;
	width:150px;
	/*float:left;*/
	margin:5px 5px;
	padding: 3px 0px;
}

</style>

<script type="text/javascript">
//jQuery.noConflict();
/*
jQuery(document).ready(function($){
    $('br').replaceWith($('jj').html());
    $("#Salvar-element").appendTo("#conteudo dl");
   
});
*/
</script>
<?php echo $this->form; ?>