
<div>
    <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/add">Novo</a>
</div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th >Ações</th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/index/ordem/TIDE_NM_DEFEITO/direcao/<?php echo $this->direcao ?> ">Nome<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/index/ordem/TIDE_DS_DEFEITO/direcao/<?php echo $this->direcao ?> ">Descrição<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/index/ordem/TIDE_CD_MATRICULA_INCLUSAO/direcao/<?php echo $this->direcao ?> ">Cadastrante<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/index/ordem/TIDE_DH_INCLUSAO/direcao/<?php echo $this->direcao ?> ">Data e Hora Inclusão<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/index/ordem/TIDE_IC_ATIVO/direcao/<?php echo $this->direcao ?> ">Ativo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                	<td  width="5%"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/qualidade/edit/id/<?php echo $data["TIDE_ID_TIPO_DEFEITO_SISTEMA"]?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["TIDE_NM_DEFEITO"]); ?></td>
                    <td><?php echo $this->escape($data["TIDE_DS_DEFEITO"]); ?></td>
                    <td><?php echo $this->escape($data["PNAT_NO_PESSOA"]); ?></td>
                    <td><?php echo $this->escape($data["TIDE_DH_INCLUSAO"]); ?></td>
                    <td><?php echo $this->escape($data["TIDE_IC_ATIVO"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
    </table>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
</div>