
<div id="container_pagination">
    <div style="margin-bottom: 5px;">
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/add">Novo</a>
    </div>
    <?php if (count($this->data)): ?>
    <table class="grid">
        <thead>
            <tr>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/index/ordem/MODE_ID_MODELO/direcao/<?php echo $this->direcao ?> ">Editar<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/index/ordem/MODE_DS_MODELO/direcao/<?php echo $this->direcao ?> ">Descrição<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/index/ordem/MARC_DS_MARCA/direcao/<?php echo $this->direcao ?> ">Marca<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/index/ordem/GRUP_DS_GRUPO_MAT_SERV/direcao/<?php echo $this->direcao ?> ">Grupo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td class="painel"><a style="margin-top: 6px;" title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/labmodelo/edit/id/<?php echo $this->escape($data["MODE_ID_MODELO"]); ?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["MODE_DS_MODELO"]); ?></td>
                    <td><?php echo $this->escape($data["MARC_DS_MARCA"]); ?></td>
                    <td><?php echo $this->escape($data["GRUP_DS_GRUPO_MAT_SERV"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7">Total: <?php echo $this->data->getTotalItemCount()?>
               </td>
            </tr>
            <tr>
                <td colspan="7">
                    <?php echo $this->paginationControl($this->data, null, null, null); ?>
                </td>
            </tr>
        </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros.</p>
    <?php endif; ?>
    </div>
