<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
        table {
            width: 100%;
            border: 1px solid #769dc0;
            color: #000000;
        }

        table th {
            text-align: left;
            background: #c3d9ff;
        }

        table td table {
            width: 750px;
            margin: 0 auto;
        }

        table table th {
            font-weight: bold;
        }

        .accordion {
            border: 1px solid #769dc0;
        }

        .accordion th {
            font-weight: bold;
            background: #deedf7 url(images/ui-bg_glass_50_deedf7_1x400.png) 50% 50% repeat-x;
            font-weight: normal;
            color: #000000;
        }

        .accordion td:last-child {
            border-bottom: none;
        }
    </style>
</head>
<body>
<table style="border: none">
    <tr>
        <td style="width: 15%" align="center"><img width="100"
                                                   src="<?php echo $this->baseUrl(); ?>/img/BrasaoBrancoRelatorio.jpg"/>
        </td>
        <td style="width: 35%; font-size: 12px" align="center"><strong>
                PODER JUDICIÁRIO <br/>
                TRIBUNAL REGIONAL FEDERAL DA PRIMEIRA REGIÃO <br/>
                SLA - INFRAESTRUTURA
            </strong></td>
        <td style="width: 50%; font-size: 12px" align="center">
            <strong>
                DATA E HORA DA EMISSÃO: <?php echo $this->sysdate; ?><br/>
                EMITIDO POR: <?php echo $this->emissor ?><br/>
            </strong>
        </td>
    </tr>
</table>
<br/>
<span><strong> Período: </strong>  <?php echo $this->data["DATA_INICIAL"] ?> a  <?php echo $this->data["DATA_FINAL"] ?></span>
<br/><br/>
<table cellspacing="0" cellpadding="5">
    <thead>
    <tr>
        <th>#</th>
        <th>Indicadores de Nível Mínimo de Serviço</th>
        <th>Meta Exigida</th>
        <th>Meta Alcançada</th>
        <th>Glosa</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->indicadoresMinimos as $im): ?>
        <tr>
            <td><?php echo $im["SINS_CD_INDICADOR"]; ?></td>
            <td><?php echo $im["SINS_DS_INDICADOR"]; ?></td>
            <td><?php echo $im["SINS_DS_SINAL_META"] . " " . $im["SINS_NR_META"]; ?></td>
            <td><?php echo $im["META_ALCANCADA"]; ?></td>
            <td><?php echo $im["GLOSA"]; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Início de Atendimentos no Prazo</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>
            <?php $qtdeSolicitacoesIia = count($this->solicitacoesIia); ?>
            <span><strong>Total de Chamados Atendidos: </strong><?php echo $this->totalIiaSolicitacoes; ?></span><br/>
            <span><strong>Chamados com Início de Atendimento no
                    Prazo: </strong><?php echo $this->noPrazoIiaSolicitacoes; ?></span><br/>
            <span><strong>Chamados com Início de Atendimento
                    Ultrapassado: </strong><?php echo $this->foradoPrazoIiaSolicitacoes; ?></span><br/>
            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados com o Início de Atendimento Fora do Prazo</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Nº do Documento</th>
                    <th>Descrição</th>
                    <th>Data do Chamado</th>
                    <th>Data do Primeiro Atendimento</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->solicitacoesIia)): ?>
                    <?php foreach ($this->solicitacoesIia as $iia): ?>
                        <tr>
                            <td><?php echo $iia["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $iia["MOFA_DS_COMPLEMENTO"]; ?></td>
                            <td><?php echo $iia["DATA_CHAMADO"]; ?></td>
                            <td><?php echo $iia["DATA_PRIMEIRO_ATENDIMENTO"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="4">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Soluções dos Chamados Encerradas no Prazo</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>

            <?php $qtdeSolicitacoesIsc = count($this->solicitacoesIsc); ?>
            <span><strong>Total de Chamados
                    Baixados/Encaminhados: </strong><?php echo $this->totalIscSolicitacoes; ?></span><br/>
            <span><strong>Chamados no Prazo: </strong><?php echo $this->totalIscSolicitacoes - $qtdeSolicitacoesIsc; ?></span><br/>
            <span><strong>Chamados com o Prazo Ultrapassado: </strong><?php echo $qtdeSolicitacoesIsc; ?></span><br/>

            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados com o Prazo Ultrapassado</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Nº do Documento</th>
                    <th>Descrição</th>
                    <th>Data do Chamado</th>
                    <th>Data Baixa/Encaminhamento</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->solicitacoesIsc)): ?>
                    <?php foreach ($this->solicitacoesIsc as $isc): ?>
                        <tr>
                            <td><?php echo $isc["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $isc["MOFA_DS_COMPLEMENTO"]; ?></td>
                            <td><?php echo $isc["DATA_CHAMADO"]; ?></td>
                            <td><?php echo $isc["DATA_FIM_CHAMADO"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="4">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Ausência de Prazo</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>

            <span><strong>Total de Chamados: </strong><?php echo $this->totalIapSolicitacoes; ?> </span><br/>
            <span><strong>Chamados no Prazo: </strong><?php echo $this->noPrazoIapSolicitacoes; ?> </span><br/>
            <span><strong>Chamados com Ausência de
                    Prazo: </strong><?php echo $this->foradoPrazoIapSolicitacoes; ?></span><br/>

            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados com Ausência de Prazo</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Descrição</th>
                    <th>Nº do Documento</th>
                    <th>Data do Chamado</th>
                    <th>Data Baixa/Encaminhamento</th>
                    <th>Prazo Acordado</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->solicitacoesIapUltrapassado)): ?>
                    <?php foreach ($this->solicitacoesIapUltrapassado as $iap): ?>
                        <tr>
                            <td><?php echo $iap["MOFA_DS_COMPLEMENTO"]; ?></td>
                            <td><?php echo $iap["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $iap["DATA_CHAMADO"]; ?></td>
                            <td><?php echo $iap["DATA_FIM_CHAMADO"]; ?></td>
                            <td><?php echo $iap["SSPA_DT_PRAZO"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Chamados Reabertos</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>

            <span><strong>Total de Chamados Avaliados: </strong><?php echo $this->totalIcrSolicitacoes; ?></span><br/>
            <span><strong>Chamados Avaliados
                    Positivamente: </strong><?php echo $this->AvaliadasPositivamenteIcrSolicitacoes; ?></span><br/>
            <span><strong>Chamados Reabertos: </strong><?php echo $this->RecusadasIcrSolicitacoes; ?></span><br/>

            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados Reabertos (Recusados em até 5 dias)</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Nº do Documento</th>
                    <th>Data Chamado</th>
                    <th>Data da Baixa</th>
                    <th>Data da recusa</th>
                    <th>Data da avaliação final</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->IcrRecusadasSolicitacoes)): ?>
                    <?php foreach ($this->IcrRecusadasSolicitacoes as $icr): ?>
                        <tr name="rowList" value="<?php echo $this->escape($icr["SSOL_ID_DOCUMENTO"]); ?>">
                        <tr>
                            <td><?php echo $icr["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $icr["DATA_CHAMADO"]; ?></td>
                            <td><?php echo $icr["DATA_BAIXA"]; ?></td>
                            <td><?php echo $icr["DATA_RECUSA"]; ?></td>
                            <td><?php echo $icr["DATA_AVALIACAO_FINAL"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Chamados com Não Conformidade</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>

            <span><strong>Total de Chamados: </strong><?php echo $this->totalIncSolicitacoes; ?> </span><br/>
            <span><strong>Chamados em Conformidade: </strong><?php echo $this->noPrazoIncSolicitacoes; ?> </span><br/>
            <span><strong>Chamados com Não
                    Conformidade: </strong><?php echo $this->foradoPrazoIncSolicitacoes; ?> </span><br/>

            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados com Não Conformidade</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Nº do Documento</th>
                    <th>Data da avaliação</th>
                    <th>Data Encaminhamento</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->solicitacoesIncUltrapassado)): ?>
                    <?php foreach ($this->solicitacoesIncUltrapassado as $inc): ?>
                        <tr>
                            <td><?php echo $inc["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $inc["DATA_AVALIACAO"]; ?></td>
                            <td><?php echo $inc["MOVI_DH_ENCAMINHAMENTO"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="3">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<br/>
<table cellspacing="0" cellpadding="5" class="accordion">
    <thead>
    <tr>
        <th><strong>Índice de Chamados Resolvidos pelo Contratante</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <br/>

            <span><strong>Total de Chamados Avaliados: </strong><?php echo $this->totalIrcSolicitacoes; ?></span><br/>
            <span><strong>Chamados Resolvidos pela Empresa
                    Contratada: </strong><?php echo $this->totalIrcSolicitacoes - $qtdeSolicitacoesIrc; ?></span><br/>
            <span><strong>Chamados Resolvidos pelo Contratante: </strong><?php echo $qtdeSolicitacoesIrc; ?></span><br/>

            <br/>
            <table cellspacing="0" cellpadding="5" style="border-bottom: none">
                <thead style="border-bottom: none">
                <tr style="border-bottom: none">
                    <th colspan="5" style="border-bottom: none">
                        <center>Lista de Chamados Resolvidos pelo Contratante</center>
                    </th>
                </tr>
                </thead>
            </table>
            <table cellspacing="0" cellpadding="5" style="border-top: none">
                <thead>
                <tr>
                    <th>Nº do Documento</th>
                    <th>Descrição</th>
                    <th>Data do Chamado</th>
                    <th>Data Baixa/Encaminhamento</th>
                    <th>Baixa</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($this->solicitacoesIrc)): ?>
                    <?php foreach ($this->solicitacoesIrc as $irc): ?>
                        <tr>
                            <td><?php echo $irc["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php echo $irc["MOFA_DS_COMPLEMENTO"]; ?></td>
                            <td><?php echo $irc["DATA_CHAMADO"]; ?></td>
                            <td><?php echo $irc["DATA_FIM_CHAMADO"]; ?></td>
                            <td><?php echo $irc["MATRICULA_BAIXA_ENCAM"]; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5">Não existem registros.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>


</body>
</html>