<script type="text/javascript">
    $(function() {
        $( ".editar" ).button({
                    icons: {
                        primary: "ui-icon-pencil"
                    }
        }).attr('style','width: 40px; height: 16px;');
        $( ".excluir" ).button({
                    icons: {
                        primary: "ui-icon-trash"
                    }
        }).attr('style','width: 40px; height: 16px;');
     });
</script> 
<?php// echo $this->form;?>
<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/guardiao/papel/add">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th>Alterar</th>
            <th>Excluir</th>
<!--            <th><a href="guardiao/papel/index/ordem/PAPL_ID_PAPEL/direcao/<?php// echo $this->direcao ?> ">Código<span class="<?php //echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>-->
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_NM_PAPEL/direcao/<?php //echo $this->direcao ?> ">-->Nome<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_DS_FINALIDADE/direcao/<?php// echo $this->direcao ?> ">-->Descrição da Finalidade<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_DS_FINALIDADE/direcao/<?php// echo $this->direcao ?> ">-->Controle<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_DS_FINALIDADE/direcao/<?php// echo $this->direcao ?> ">-->Módulo<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_DS_FINALIDADE/direcao/<?php// echo $this->direcao ?> ">-->Sistema<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_DS_FINALIDADE/direcao/<?php// echo $this->direcao ?> ">-->Ativo<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl(); ?>/guardiao/papel/edit/id/<?php echo ($data['PAPL_ID_PAPEL']) ?>"><span class="editar"></span></a</td>
            <td><a href="<?php echo $this->baseUrl(); ?>/guardiao/papel/del/id/<?php echo ($data['PAPL_ID_PAPEL']) ?>"><span class="excluir"></span></a></td>
<!--            <td><?php //echo $this->escape($data['PAPL_ID_PAPEL']) ?></td>-->
            <td><?php echo $this->escape($data['PAPL_NM_PAPEL']) ?></td>
            <td><?php echo $this->escape($data['PAPL_DS_FINALIDADE']) ?></td>
            <td><?php echo $this->escape($data['CONTROLE']) ?></td>
            <td><?php echo $this->escape($data['MODULO']) ?></td>
            <td><?php echo $this->escape($data['SISTEMA']) ?></td>
            <td><?php if($data['PAPL_CD_MATRICULA_EXCLUSAO']){echo "NÃO";} ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="12">Total: <?php /*echo $this->data->getTotalItemCount()*/?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,'ordem'=> $this->ordem))?>
<?php else:?>
    <div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/guardiao/papel/add">Novo</a></div>
    <p>Não existem registros</p>
<?php endif;?>
