<script type="text/javascript">
    $(function() {
        $( ".editar" ).button({
                    icons: {
                        primary: "ui-icon-pencil"
                    }
        }).attr('style','width: 40px; height: 16px;');
        $( ".excluir" ).button({
                    icons: {
                        primary: "ui-icon-trash"
                    }
        }).attr('style','width: 40px; height: 16px;');
     });
</script> 

<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/sisad/cadastrodcmtoext/addtipodoc">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th>Alterar</th>
            <th>Tipo do Documento</th>
            <th>Atuação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl(); ?>/sisad/cadastrodcmtoext/edittipodoc/id/<?php echo $data['DTPD_ID_TIPO_DOC'];?>"><span class="editar"></span></a</td>
            <td><?php echo $this->escape($data['DTPD_NO_TIPO']) ?></td>
            <td><?php 
            if ($this->escape($data['DTPD_IC_ADM_JUD']) == 'JU') {
                echo 'Judicial';
            }elseif($this->escape($data['DTPD_IC_ADM_JUD']) == 'AD'){
                echo 'Administrativo';
            }elseif($this->escape($data['DTPD_IC_ADM_JUD']) == 'AM'){
                echo 'Administrativo e Judicial';
            }
            ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="12">Total: <?php /*echo $this->data->getTotalItemCount()*/?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,'ordem'=> $this->ordem))?>
<?php else:?>
    <div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/sisad/cadastrodcmtoext/add">Novo</a></div>
    <p>Não existem registros</p>
<?php endif;?>