<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<!--<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Esta tela contém <u>todos</u> os documentos criados pelo usuário.</p>
    <ul>
        <li>Ao posicionar o cursor sobre o documento, ele mostra que se deve dar um duplo click para abri-lo (abre a tela <i>Detalhe</i>).</li>
        <li>Na tela <b>Detalhe</b>, estão todas as informações sobre o documento, bem como o <i>Histórico</i> de tramitação e pareceres realizados.</li>
        <li>A opção <b>Responder</b> permite responder a um documento recebido da Caixa da Unidade onde trabalha para a caixa da própria unidade.</li>
        <li><b>Encaminhar</b> realiza o encaminhamento de um documento; este deve estar assinado ou certificado digitalmente. Pode-se encaminhar um documento ou um lote de documentos para uma mesma unidade. Primeiro deve-se escolher os documentos que serão encaminhados e clicar no botão.</li>
        <li>Após a ação <i>Encaminhar</i>, surge a tela acima, onde podemos observar os documentos selecionados e caso deseje não encaminhar algum documento, basta voltar a tela onde estão os documentos e selecionar novamente.</li>
        <li>Em <b>Parecer</b> a qualquer momento o usuário pode gerar um parecer em um documento que está sob a sua responsabilidade. Todas as informações registram data e hora que são mostradas no <i>Histórico</i>.</li>
        <li><b>Arquivar</b> o documento permitirá o arquivamento do documento no arquivo corrente pessoal.</li>
        <li><b>Assinar por Senha</b> - o sistema solicita a senha do usuário para fazer o login. Após digitado. Clicar no botão <i>Assinar</i>. O documento após assinado fica registrado no <i>Histórico</i>.</li>
        <li><b>Pesquisar</b> o documento permite a pesquisa por metadados e por palavras chave.</li>
        <li><b>Cancelar</b> o documento selecionando o documento, este poderá ser cancelado. A exclusão é lógica e não física.</li>
     </ul>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php //echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);
                    
                    var span_id_leitura = $(this_tr).find('span[id=leitura]');
                    span_id_leitura.removeClass('naolido');
                    span_id_leitura.addClass('lido');
                    span_id_leitura.attr('title','Documento lido');
                    $(this_tr).removeClass('naolidoTr');
                    $(this_tr).addClass('lidoTr');
                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );
            
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=cx_pess_entrada]');
            if(acao == 'Encaminhar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/encaminharcaixaunidade');
            }else if(acao == 'Parecer'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/parecer');
            }else if(acao == 'Arquivar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/arquivardocmentrada');
            }else if(acao == 'Cancelar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/cancelardocmentrada');
            }else if(acao == 'Pesquisa'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/pesquisa');
            }else if(acao == 'Assinar por senha'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/assinardocmentrada');
            }
        }
    );
    $('form[name=cx_unid_entrada]').submit(
       function(){
            var formulario_valido = true;
            var documentoSelecionado = $(".nav_check_boxes:checked").val();
            if (documentoSelecionado == undefined){                   
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha um Documento!</div>";
                flashMessages_by_id.hide();
                flashMessages_by_id.html(mensagem);
                flashMessages_by_id.show('pulsate');
                flashMessages_by_id.delay(2000).hide('puff');
                return false;
            }
            grid_tbody_tr.each(
                function(){
                    var this_tr = $(this);
                    var input_check_box = this_tr.find('input');
                    var is_checked_input = input_check_box.attr('checked');
                    if(is_checked_input != undefined){
                        var span_id_leitura = $(this_tr).find('span[id=leitura]');
                        if(span_id_leitura.hasClass('naolido')){
                            var mensagem = "<div class='notice'><strong>Alerta:</strong> Não é possível realizar ações sobre documentos <strong>não</strong> recebidos.</div>";
                            flashMessages_by_id.hide();
                            flashMessages_by_id.html(mensagem);
                            flashMessages_by_id.show('pulsate');
                            flashMessages_by_id.delay(4000).hide('puff');
                            formulario_valido = false;
                        }
                    }
                }
            );
            if(!formulario_valido){
                return false;
            }
       }
    );
     $("#dialog-documentos_detalhe").dialog({
                    title    : 'Detalhe',
                            autoOpen : false,
                            modal    : false,
                            show: 'fold',
                            hide: 'fold',
                            resizable: true,
                            width: 800,
                            height: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
     
     $("#dialog-carrinho_detalhe").dialog({
                    title    : 'Carrinho de Documentos e Processos',
                              autoOpen : false,
                              modal    : false,
                              show: 'fold',
                              hide: 'fold',
                              //resizable: true,
                              width: 800,
                              height: 600,
//                            //maxHeight: 200,
                            maxWidth: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
    
    
    });
</script>
<form method="POST" action="" name="cx_pess_entrada">
<?php if (count($this->data)): ?>
<!--    <div class="containerpainel">
        <div class="painel">
            <input type="submit" title="Encaminha Documento/Processo para caixa da unidade"         name="acao" value="Encaminhar" />
            <input type="submit" title="Dar um parecer no Documento/Processo"                       name="acao" value="Parecer"/>
            <input type="submit" title="Arquivar um Documento/Processo"                             name="acao" value="Arquivar"/>
            <input type="submit" title="Assina por senha Documento/Processo"                        name="acao" value="Assinar por senha" />
            <input type="submit" disabled="disabled" title="Pesquisa Documento/Processo"     disabled="disabled"      name="acao" value="Pesquisa"/>
            <input type="submit" title="Cancelar Documento/Processo"                                name="acao" value="Cancelar"/>
        </div>
    </div>-->
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
<!--                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th></th>-->
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/DTPD_NO_TIPO/direcao/<?php echo $this->direcao ?> ">Tipo<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Número<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Data<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/LOTA_SIGLA_LOTACAO/direcao/<?php echo $this->direcao ?> ">Origem<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/ENCAMINHADOR/direcao/<?php echo $this->direcao ?> ">Encaminhador<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/desarquivarpessoal/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
<!--                <th ><a  href="<?php //echo $this->baseUrl(); ?>/sisad/caixapessoal/novos/ordem/DOCM_NR_DOCUMENTO_RED/direcao/<?php //echo $this->direcao ?> ">visualizar</a></th>-->
            </tr>
        </thead>
                <tbody>
                <?php
                foreach ($this->data as $data):
                    ?>
                    <tr title="Duplo click para Abrir" class="grid_rows <?php// echo $this->escape($data["CLASS_LIDO_TR"]); ?>" name="rowList" value="<?php //echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" > 
<!--                        <td>
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php// echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" name="documento[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                        </td>
                        <td>
                            <span id="leitura" class="<?php// echo $this->escape($data["CLASS_LIDO"]); ?>" title="<?php// echo $this->escape($data["MSG_LIDO"]); ?>"></span>
                        </td>-->
                        <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--                        <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                        <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                        
                        <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO"]) ?></td>
                        <td> <?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>
                        <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                        <td> <?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]) ?></td>
<!--                        <td><a class="<?php //echo $this->escape($data["CLASS_ARQUIVO"]); ?>" target="_blank" title="<?php //echo $this->escape($data["MSG_ARQUIVO"]); ?>" href="<?php //echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/<?php //echo $this->escape($data["DOCM_NR_DOCUMENTO_RED"]) ?> "></a></td>-->
                    </tr>
    <?php endforeach; ?>
            </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)
                ?></td>
            </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    <?php echo $this->form;?>
</div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action;     ?>"/>        
</form>
<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>
<div id="dialog-carrinho_detalhe" style="overflow: scroll;">
</div>