<?php 
    $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<script>

$(function(){
   
   cont = 0;
   $("#UNIDADE, option").each( function(){
       if($(this).val() != ""){
           cont++;
       }
   });    
   if(cont == 0){
        $("#UNIDADE-label").hide();
        $("#UNIDADE-element").hide();
    }
});
$(function(){ 
            $('#ANEXOS').MultiFile({
                STRING: {
                    file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                    remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
                }
            });
        });
</script>

<form method="POST" action="encaminharcaixaunidade" enctype="multipart/form-data" >
<?php if (count($this->data)): ?>
<div class="container_pagination">
<table class="grid">
    <thead>
        <tr>
            <th >Tipo</th>
            <th >Número</th>
            <th >Encaminhador</th>
            <th >Data/Hora Encaminhamento</th>
        </tr>
    </thead>
    <tbody id="documentosList">
    <?php foreach($this->data as $data):?>
        <tr>
            <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--            <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
            <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                        
            <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
            <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
        </tr>
        <?php ?>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td>
        </tr>
    </tfoot>
</table>
</div>
<div id="interno">
<?php 
    echo $this->form->getElement('UNIDADE')->setDescription('Se a unidade não for escolhida o documento será encaminhado para a caixa da unidade da sua lotação.');
    echo $this->form->getElement('MOFA_DS_COMPLEMENTO'); 
?>
</div>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
    <b>Anexos</b></br>
        <input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" accept="pdf" maxlength="20" />
        Até 20 Anexos. </br>
        Somente serão aceitos arquivos com o formato PDF. </br>
        Soma dos arquivos até 50 Megas.</p>
        <span class="msg_alerta"> </span>
    </p>
    <span class="msg_alerta"> </span>
    <input type="submit" name="salvar" value="Salvar" />
</form>