<?php
$this->inlineScript()
        ->appendFile($this->baseUrl() . '/js/tooltipster-1.2/js/jquery.tooltipster.min.js', 'text/javascript');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>
<script type="text/javascript">
	$(function() {
		var dates = $( "#DATA_INICIAL, #DATA_FINAL" ).datepicker({
			dateFormat: 'dd/mm/yy',
			dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
			dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
				'Outubro','Novembro','Dezembro'],
			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
			nextText: 'Próximo',
			prevText: 'Anterior',
			changeMonth: true,
			numberOfMonths: 1,
			changeMonth: true,
			changeYear: true,
			changeMonth: true,
			onSelect: function( selectedDate ) {
				var option = this.id == "DATA_INICIAL" ? "minDate" : "maxDate",
				instance = $( this ).data( "datepicker" );
				date = $.datepicker.parseDate(
				instance.settings.dateFormat ||
					$.datepicker._defaults.dateFormat,
				selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
			}
		});
                $('.tooltip').tooltipster({
                    fixedWidth: 650,
                    position: 'bottom-left'
                });
                $(".tooltip").each(function() {
                    $(this).attr("data-oldhref", $(this).attr("href"));
                    $(this).removeAttr("href");
                });
	}); 
</script>
<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);
                    
                    var span_id_leitura = $(this_tr).find('span[id=leitura]');
                    span_id_leitura.removeClass('naolido');
                    span_id_leitura.addClass('lido');
                    span_id_leitura.attr('title','Documento lido');
                    $(this_tr).removeClass('naolidoTr');
                    $(this_tr).addClass('lidoTr');
                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );
            
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=cx_pess_entrada]');
            if(acao == 'Encaminhar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/documento/encaminhar');
            }else if(acao == 'Parecer'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/parecer');
            }else if(acao == 'Arquivar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/arquivardocmentrada');
            }else if(acao == 'Excluir'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/cancelardocmentrada');
            }else if(acao == 'Pesquisa'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/pesquisa');
            }else if(acao == 'Assinar por senha'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/assinardocmentrada');
            }else if(acao == 'Categorias'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/categorias/categorizar');
            }else if(acao == 'Despacho'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/despacho');
            }
        }
    );
    $('form[name=cx_pess_entrada]').submit(
       function(){
            var formulario_valido = true;
            var documentoSelecionado = $(".nav_check_boxes:checked").val();
            if (documentoSelecionado == undefined){                   
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha um Documento!</div>";
                flashMessages_by_id.hide();
                flashMessages_by_id.html(mensagem);
                flashMessages_by_id.show('pulsate');
                flashMessages_by_id.delay(2000).hide('puff');
                return false;
            }
            grid_tbody_tr.each(
                function(){
                    var this_tr = $(this);
                    var input_check_box = this_tr.find('input');
                    var is_checked_input = input_check_box.attr('checked');
                    if(is_checked_input != undefined){
                        var span_id_leitura = $(this_tr).find('span[id=leitura]');
                        if(span_id_leitura.hasClass('naolido')){
                            var mensagem = "<div class='notice'><strong>Alerta:</strong> Não é possível realizar ações sobre documentos <strong>não</strong> recebidos.</div>";
                            flashMessages_by_id.hide();
                            flashMessages_by_id.html(mensagem);
                            flashMessages_by_id.show('pulsate');
                            flashMessages_by_id.delay(4000).hide('puff');
                            formulario_valido = false;
                        }
                    }
                }
            );
            if(!formulario_valido){
                return false;
            }
       }
    );
     $("#dialog-documentos_detalhe").dialog({
                    title    : 'Detalhe',
                            autoOpen : false,
                            modal    : false,
                            show: 'fold',
                            hide: 'fold',
                            resizable: true,
                            width: 800,
                            height: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
     
     $("#dialog-carrinho_detalhe").dialog({
                    title    : 'Carrinho de Documentos e Processos',
                              autoOpen : false,
                              modal    : false,
                              show: 'fold',
                              hide: 'fold',
                              //resizable: true,
                              width: 800,
                              height: 600,
//                            //maxHeight: 200,
                            maxWidth: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
    
    
    });
</script>
<script type="text/javascript">

 $(function(){
        function h2d(h) {return parseInt(h,16);}
        var labels = $("#CATE_ID_CATEGORIA-element").find('label');
        var cores = $("input[type=checkbox][name=CATE_ID_CATEGORIA[]] ").attr('cores');
        cores = jQuery.parseJSON(cores);
        if(cores){
        $.each(cores, function(chave, cor) {
           $(labels[chave]).css('background-color', cor);
           var cor_numeros = cor.substr(1,cor.length);
           var aux_numeros = h2d(cor_numeros);
           if(aux_numeros >= (h2d('FFFFFF')/2) ){
               $(labels[chave]).css('color', '#000');
           }else{
               $(labels[chave]).css('color', '#FFFFFF');
           }
        });
        }
    });    
    
$(function() {
	
 $("#Filtrar").click( 
            function(){
                form_valido = true;
            }
        );
 
 //Unidade Administrativa
$("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxunidade",
        minLength: 3,
        delay: 500,
        select: function( event, ui ) {
                                if( ui.item.value != null ){ 
                                    $("#MOVI_CD_SECAO_UNID_ORIGEM").val(ui.item.cod_lota);
                                }
                },
        change: function( event, ui ) {
                                if( ui.item.value != null ){  
                                     $("#MOVI_CD_SECAO_UNID_ORIGEM").val(ui.item.cod_lota);
                                }
        }
    }).keyup(
            function(){
                if(this.value == ""){
                    $("#MOVI_CD_SECAO_UNID_ORIGEM").val('');
                }
    });
    
//Assunto
  $("#DOCM_ID_PCTT").autocomplete({
        source: base_url+"/sisad/cadastrodcmto/ajaxassuntodocm",
        minLength: 3,
        delay: 500,
        select: function( event, ui ) {
                                if( ui.item.value != null ){ 
                                    $("#DOCM_ID_PCTT").val(ui.item.label);
                                }
                },
        change: function( event, ui ) {
                                if( ui.item.value != null ){  
                                     $("#DOCM_ID_PCTT").val(ui.item.label);
                                }
        }
    }).keyup(
            function(){
                if(this.value == ""){
                    $("#DOCM_ID_PCTT").val('');
                }
    });
// Fim do assunto

    $('#pesquisar')
        .click(function() {
                var pesq_div = $("#pesq_div")

                if(pesq_div.css('display') == "none"){
                    pesq_div.show('');
                }else{
                    pesq_div.hide('');
                }
        });

    $('#Filtrar').button();

    $("#botao_ajuda_recolhe").click(
       function(){
            $("#pesq_div").hide();
            $("#pesquisar").show();
    });
});

</script>

<fieldset style="display:inline;">
    <legend>Filtro da Caixa</legend>
    <div class="painel">
        <div class="painel" >
            <input type="button" title="Último Filtro" name="acao" value="Filtro" id="pesquisar">
            <a title="Novo Filtro" name="acao" value="Filtrar" id="ultimo_filtro" href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/nova/1" >Limpar Filtro/Retirar Filtro</a>
            &emsp;&emsp;<span style="color: #2E4557;"><strong><?php if( $this->ultima_pesq == true) echo "Filtro Ativo"; else echo "Filtro Inativo"; ?></strong></span>
        </div> 
    </div>
     <div id="pesq_div"  style="display: none;" >
        <?php echo $this->form; ?>
        <span id="botao_ajuda_recolhe" ></span>
    </div>
</fieldset>

<form method="POST" action="" name="cx_pess_entrada">

<?php if (count($this->data)): ?>
    <div class="containerpainel">
        <div class="painel">
            <input type="submit" title="Arquivar um Documento/Processo"                             name="acao" value="Arquivar"/>
            <input type="submit" title="Assina por senha Documento/Processo"                        name="acao" value="Assinar por senha" />
            <input type="submit" title="Criar / Remover Categorias de Documentos/Processos"         name="acao" value="Categorias" />
            <input type="submit" title="Dar um despacho no Documento/Processo"                       name="acao" value="Despacho"/>
            <input type="submit" title="Encaminha Documento/Processo"         name="acao" value="Encaminhar" />
            <input type="submit" title="Dar um parecer no Documento/Processo"                       name="acao" value="Parecer"/>
<!--            <input type="submit" disabled="disabled" title="Pesquisa Documento/Processo"     disabled="disabled"      name="acao" value="Pesquisa"/>-->
<!--            <input type="submit" title="Excluir Documento/Processo"                                name="acao" value="Excluir"/>-->
        </div>
    </div>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/DTPD_NO_TIPO/direcao/<?php echo $this->direcao ?> ">Tipo<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Número<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Data<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/LOTA_SIGLA_LOTACAO/direcao/<?php echo $this->direcao ?> ">Origem<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/AQAT_DS_ATIVIDADE/direcao/<?php echo $this->direcao ?> ">Assunto<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/entrada/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo<span class="<?php if($this->direcao == 'ASC') echo 'ordenacaodesc'; else echo 'ordenacaoasc';  ?>"></span></a></th>
                <th>Categorias</th>
<!--                <th ><a  href="<?php //echo $this->baseUrl(); ?>/sisad/caixapessoal/novos/ordem/DOCM_NR_DOCUMENTO_RED/direcao/<?php //echo $this->direcao ?> ">visualizar</a></th>-->
            </tr>
        </thead>
                <tbody>
                <?php
                $userNs = new Zend_Session_Namespace('userNs');
                $CateDocumento = new Application_Model_DbTable_SadTbCadoCategoriaDoc();
                foreach ($this->data as $data):
                    ?>
                    <tr title="Duplo click para Abrir" class="grid_rows <?php echo $this->escape($data["CLASS_LIDO_TR"]); ?>" name="rowList" value="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" > 
                        <td>
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" name="documento[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                        </td>
                        <td>
                            <span id="leitura" class="<?php echo $this->escape($data["CLASS_LIDO"]); ?>" title="<?php echo $this->escape($data["MSG_LIDO"]); ?>"></span>
                        </td>
                        <td><a href="#" class="tooltip" title="<?php echo $this->escape($data["hint"]); ?>"><?php echo $this->escape($data["DTPD_NO_TIPO"]); ?></a></td>
<!--                        <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                        <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                        
                        <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
                        <td> <?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>
                        <td> <?php echo $this->escape($data["AQAT_DS_ATIVIDADE"]) ?></td>
                        <td> <?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]) ?></td>
                        <td>
                            <?php 
                            $categoriaDoc = $CateDocumento->getCategoriaDocs($data["DOCM_ID_DOCUMENTO"], $userNs->matricula);
                            $cont = 0;
                            if($categoriaDoc != null){ ?>
                                <table>
                                    <tr>
                                        <?php foreach ($categoriaDoc as $categorias_p){ 
                                            if($cont%3 == 0) {
                                                echo '</tr><tr>';
                                            }    
                                        ?>
                                            <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR']?>" title="Nome: <?php echo $categorias_p['CATE_NM_CATEGORIA']?> - Descrição: <?php echo $categorias_p['CATE_DS_OBSERVACAO']?>" > </td>
                                        <?php 
                                        $cont++;
                                        } ?>
                                    </tr>
                                </table>
                                <?php
                            }
                            ?>
                        </td>
                            
<!--                        <td><a class="<?php //echo $this->escape($data["CLASS_ARQUIVO"]); ?>" target="_blank" title="<?php //echo $this->escape($data["MSG_ARQUIVO"]); ?>" href="<?php //echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/<?php //echo $this->escape($data["DOCM_NR_DOCUMENTO_RED"]) ?> "></a></td>-->
                    </tr>
    <?php endforeach; ?>
            </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)
                ?></td>
            </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
</div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action;     ?>"/>        
</form>
<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>
<div id="dialog-carrinho_detalhe" style="overflow: scroll;">
</div>