<?php
$this->inlineScript()
        ->appendFile($this->baseUrl() . '/js/tooltipster-1.2/js/jquery.tooltipster.min.js', 'text/javascript');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
        
    $(function(){
        $("tr[name=rowList]").click(
            function(){
                var solic = $(this).attr('value');               
                var ischecked_solic = $('#'+solic).attr('checked');
                var ischecked_solic_tr = $(this).attr('marcado');
                if( (ischecked_solic == undefined && ischecked_solic_tr == undefined) || (ischecked_solic != undefined && ischecked_solic_tr == undefined) ){
                    $('#'+solic).attr('checked','checked');
                    $(this).attr('marcado','marcado');
                    $(this).addClass('over');
                }else{
                    $('#'+solic).removeAttr('checked');
                    $(this).removeAttr('marcado');
                    $(this).removeClass('over');
                }
                $('#'+solic).focus();
            }
        );
            
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_pess_ranscunho = $('form[name=cx_pess_ranscunho]');
            if(acao == 'Encaminhar'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/encaminhar');
            }else if(acao == 'Parecer'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/parecer');
            }else if(acao == 'Assinar por senha'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/assinarrascunho');
            }else if(acao == 'Arquivar'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/arquivarrascunho');
            }else if(acao == 'Pesquisa'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/pesquisa');
            }else if(acao == 'Excluir'){
                cx_pess_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/cancelarrascunho');
            }
        }
    );
    var xhr;    
    $("tr[name=rowList]").dblclick(
        function(){
            var input_check_box = $(this).find('input');
            value_input_check_box = input_check_box.val();
            input_check_box.attr('checked', 'checked');
            $(this).attr('marcado','marcado');
            $(this).addClass('hover');
            /*var obj = jQuery.parseJSON(value_input)*/;

            if (xhr) {
                xhr.abort();
            }

            url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
            xhr = $.ajax({
            url: url,
            dataType: 'html',
            type: 'POST',
            data: value_input_check_box,
            contentType: 'application/json',
            processData: false, 
            beforeSend:function() {
                $("#dialog-documentos_detalhe").dialog("open");
            },
            success: function(data) {
                $("#dialog-documentos_detalhe").html(data);

            },
            complete: function(){

            },
            error : function(){

            }
            });
        }
    );
    $('form[name=cx_pess_ranscunho]').submit(
       function(){
            var documentoSelecionado = $(".nav_check_boxes:checked").val();
            if (documentoSelecionado == undefined){                   
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha um Documento!</div>";
                flashMessages_by_id.hide();
                flashMessages_by_id.html(mensagem);
                flashMessages_by_id.show('pulsate');
                flashMessages_by_id.delay(2000).hide('puff');
                return false;
            }
       }
    );
    
    $("input[type=checkbox][name=input_check_all_grid]").click(
        function(){
            if($(this).attr('checked')){
                $(".nav_check_boxes").attr('checked','checked');
                $("tr[name=rowList]").addClass('hover');
            }else{
                $(".nav_check_boxes").removeAttr('checked');
                 $("tr[name=rowList]").removeClass('hover');
            }
        }
    );
    
     $("#dialog-documentos_detalhe").dialog({
                    title    : 'Detalhe',
                            autoOpen : false,
                            modal    : false,
                            show: 'fold',
                            hide: 'fold',
                            resizable: true,
                            width: 800,
                            height: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
     
     $("#dialog-carrinho_detalhe").dialog({
                    title    : 'Carrinho de Documentos e Processos',
                              autoOpen : false,
                              modal    : false,
                              show: 'fold',
                              hide: 'fold',
                              //resizable: true,
                              width: 800,
                              height: 600,
//                            //maxHeight: 200,
                            maxWidth: 600,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });

        $('.tooltip').tooltipster({
            fixedWidth: 650,
            position: 'bottom-left'
        });
        $(".tooltip").each(function() {
            $(this).attr("data-oldhref", $(this).attr("href"));
            $(this).removeAttr("href");
        });

    });
</script>

<?php if (count($this->data)): ?>
<div class="containerpainel">
<form method="POST" action="" name="cx_pess_ranscunho">
    <div class="painel">
<!--    <input type="submit" title="Encaminha Documento/Processo"         name="acao" value="Encaminhar" />-->
    <input type="submit" title="Assina por senha Documento/Processo"         name="acao" value="Assinar por senha" />
<!--    <input type="submit" title="Dar um parecer no Documento/Processo" name="acao" value="Parecer"/>-->
<!--    <input type="submit" title="Arquivar um Documento/Processo"        name="acao" value="Arquivar"/>-->
    <input type="submit" title="Pesquisa Documento/Processo"     disabled="disabled"      name="acao" value="Pesquisa"/>
    <input type="submit" title="Excluir Documento/Processo"           name="acao" value="Excluir"/>
    </div>
</div>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th ></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/DTPD_NO_TIPO/direcao/<?php echo $this->direcao ?> ">Tipo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Número<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/DOCM_DH_CADASTRO/direcao/<?php echo $this->direcao ?> ">Data<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/LOTA_SIGLA_LOTACAO/direcao/<?php echo $this->direcao ?> ">Origem<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/AQAT_DS_ATIVIDADE/direcao/<?php echo $this->direcao ?> ">Assunto<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixapessoal/rascunhos/ordem/DOCM_DH_CADASTRO/direcao/<?php echo $this->direcao ?> ">Tempo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
       <tbody>
            <?php foreach ($this->data as $data): ?>
                <tr name="rowList" value="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>">
                    <td>
                        <input  class="nav_check_boxes" id="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" name="documento[]" type="checkbox" value="<?php  echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                    </td>
<!--                    <td><span  class="<?php // echo $this->escape($data["CLASS_LIDO"]); ?>" title="<?php //echo $this->escape($data["MSG_LIDO"]); ?>"></span></td>-->
                    <td></td>
                    <td><a href="#" class="tooltip" title="<?php echo $this->escape($data["hint"]); ?>"><?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></a></td>
<!--                    <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                    <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                        
                    <td style="width: 15%"><?php echo $this->escape($data["DOCM_DH_CADASTRO_CHAR"]) ?></td>
                    <td><?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>
                    <td><?php echo $this->escape($data["AQAT_DS_ATIVIDADE"]) ?></td>
                    <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]) ?></td>
<!--                    <td><a class="<?php //echo $this->escape($data["CLASS_ARQUIVO"]); ?>" target="_blank" title="<?php //echo $this->escape($data["MSG_ARQUIVO"]); ?>" href="<?php //echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/<?php //echo $this->escape($data["DOCM_NR_DOCUMENTO_RED"]) ?> "></a></td>-->
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)
                //-- pagination
                //-- style
                //-- partial
                //-- data
                ?></td>
            </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
</div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action;     ?>"/>   
</form>
<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>
<div id="dialog-carrinho_detalhe" style="overflow: scroll;">
</div>