<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesVistasEncaminhar.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesInteressadosDocumentos.js')); 
     $this->headScript()->appendFile($this->baseUrl().'/js/tinymce/jscripts/tiny_mce/tiny_mce.js')
                        ->appendFile($this->baseUrl().'/js/tinymceForm.js');
     
     
     
         $this->inlineScript()->appendFile(($this->baseUrl() . '/js/multiUpload/jquery.MultiFile.js'))
                         ->appendFile(($this->baseUrl() . '/js/multiUpload/multiFile.js'));
?>
<script type="text/javascript" src="<?Php echo $this->baseUrl('/js/tinymce/jscripts/tiny_mce/tiny_mce.js')?>"></script>
<script type="text/javascript">
$(function() {
        var radio;
        
        $('#ANEXOS').MultiFile({
            STRING: {
                file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
            }
        });
        
        
        $("select[name=TIPO_PARTE] > option[value=U]").remove();
        $("select[name=TIPO_PARTE] > option[value=F]").remove();
        $("select[name=TIPO_PARTE] > option[value=J]").remove();
       
        $("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
           source: "ajaxunidade",
           minLength: 3,
           delay: 100,
           select: function( event, ui ) {
                       $("#DOCM_CD_LOTACAO_REDATORA").val(ui.item.label);
                   }
       });

       $("#DOCM_CD_LOTACAO_REDATORA").autocomplete({
           source: "ajaxunidade",
           minLength: 3,
           delay: 100
       });


       $("#dialog-message").dialog("destroy");

       $("#dialog-message").dialog({
               modal: true,
               width: 380,
               height: 225,
               buttons: {
                       Sim: function() {
                          location.href='ativa';           		
                       }, 
                       Não: function() {
                         $(this).dialog('close');           		
                       }
               }
               });

       $( "#dialog-message" ).bind( "dialogclose", function(event, ui) { });

       /**
        * Para transformar o select em um combo de autocomplete via somente java-script
        **/
       $( "#DOCM_ID_PCTT" ).combobox();
       $( "#combobox-input-text-DOCM_ID_PCTT" ).attr('style','width: 700px;');
       $( "#combobox-input-button-DOCM_ID_PCTT" ).attr('style','display: none;');


       /**
        * Para apresentar a Lista completa de ASSUNTOS
        */
       var botao_detalhe_pctt = $("<input type='button' name='LST_CPT_PCTT' value='Lista completa de Assuntos' />");
       botao_detalhe_pctt.css('position','relative');
       botao_detalhe_pctt.css('display','inline');
       botao_detalhe_pctt.css('float','right');
       botao_detalhe_pctt.css('top','-58px');
       botao_detalhe_pctt.css('left','-70px');
       botao_detalhe_pctt.button();
       $( "#DOCM_ID_PCTT-element").append(botao_detalhe_pctt);
       botao_detalhe_pctt.click(
           function(){
               if($('#detalhe_pctt').attr('id') == undefined){
                   var detalhe_pctt = $("<div id='detalhe_pctt'></div>");
                   var select = $( "#DOCM_ID_PCTT" );
                   select.css('display','block');
                   select.css('width','680px');
                   select.css('height','480px');
                   select.attr('size','20');
                   detalhe_pctt.append(select);
                   $('body').append(detalhe_pctt);
                   detalhe_pctt.dialog({
                               title: 'Lista completa de Assuntos',
                               modal: true,
                               width: 700,
                               height: 600,
                               buttons: {
                                       OK: function() {
                                         $("#DOCM_ID_PCTT").css('display','none');
                                         selected = $("#DOCM_ID_PCTT").children( ":selected" );
                                         $( "#combobox-input-text-DOCM_ID_PCTT" ).val(selected.text());
                                         $( "#DOCM_ID_PCTT-element" ).append(select);
                                         $(this).dialog('close');  
                                         $( "#combobox-input-text-DOCM_ID_PCTT" ).focus();
                                       }
                               }
                               });
                   detalhe_pctt.dialog('open');
               }else{
                   $("#DOCM_ID_PCTT" ).css('display','block');
                   $('#detalhe_pctt').append($("#DOCM_ID_PCTT" ));
                   $('#detalhe_pctt').dialog('open');
               }
           }
       );


          var radioSelecionado  = $("input[type=radio][name=RADIO_TIPO_ARQUIVO]:checked").val();
          
          $("input[type=radio][name=RADIO_TIPO_ARQUIVO]").click(function(){
              radioSelecionado = $(this).val();
              if( $(this).val() == "D"){
                   $(".arquivo").show();
                   $("#editorHtml").hide();
                   $(".PreVisualizar").hide();
              }else if($(this).val() == "E"){
                   $(".arquivo").hide();
                   $("#editorHtml").show();
                   $(".PreVisualizar").show();
              }            
          }); 
          
          
         if( radioSelecionado == "D" ){
               $("#RADIO_TIPO_ARQUIVO-D").attr('checked','checked');
               $(".arquivo").show();
               $("#editorHtml").hide();
               $(".PreVisualizar").hide();
         }else if( radioSelecionado == "E" ){
                   $("#RADIO_TIPO_ARQUIVO-E").attr('checked','checked');
                   $(".arquivo").hide();
                   $("#editorHtml").show();
                   $(".PreVisualizar").show();
         }    
          
         $(function() {

                $( "input[type=submit][name='PreVisualizar']").click(
                    function(){
                        $( "#Formulariominuta").attr('action','visualizar');
                        $( "#Formulariominuta").submit();
                    }
                );

                $( "#Salvar").click(
                    function(){                     
                         
                         //precisa ter parte/vista
                         var $qtdePartesVistas = $("#partes_vistas_encaminhar_adicionadas").find("input[type='checkbox']");
                         if( $qtdePartesVistas.length <= 0 ){
                            alert("É necessário cadastrar pelo menos uma parte/vista no documento!");
                           return false;
                         }
                         
                        if (radioSelecionado == ""){
                           alert("É necessário escolher o Tipo de armazenamento do documento.");
                           return false;                     
                         }else if (radioSelecionado == 'D'){                      
                           if($('input[type=file][name=ANEXOS[]]').val() == ""){
                             alert("É necessário incluir o arquivo.");
                             return false;
                           }
                         }else if (radioSelecionado== 'E'){
                           var conteudo =  tinyMCE.get('elm2').getContent();
                          
                           if(conteudo == ""){
                             alert("É necessário incluir o texto no editor.");
                             return false;
                           }
                         }
                        $( "#Formulariominuta").attr('action','save');
                        $( "#Formulariominuta").submit();
                    }
                );


	});
   });
   
  tinyMCE.init({
		// General options
                mode : "exact",
                elements : "textArea1",
                theme : "advanced",
                theme_advanced_toolbar_location : "top",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
		plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
		//plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		//theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
		theme_advanced_toolbar_align : "left",

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		//template_external_list_url : "lists/template_list.js",
		//external_link_list_url : "lists/link_list.js",
		//external_image_list_url : "lists/image_list.js",
		//media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
                
                
	});
</script>
<?php  if( $this->alert): ?>
<div id="dialog-message" title="Aten&ccedil;&atilde;o" style="display: none; ">
<p>
        <span class="" style="float:left; margin:0 7px 50px 0;"></span>
        <?php echo $this->alert; ?>			
</p>
</div>
<? endif; ?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>
<div id=""><?php echo $this->alert; ?></div>

<form name="Formulariominuta" action="" method="POST" enctype="multipart/form-data" id="Formulariominuta" >
<?php 
    echo $this->form->DOCM_ID_DOCUMENTO;
    echo $this->form->DOCM_NR_DOCUMENTO;
    echo $this->form->DOCM_NR_SEQUENCIAL_DOC;
    echo $this->form->DOCM_DH_CADASTRO;
    echo $this->form->DOCM_CD_MATRICULA_CADASTRO;
    echo $this->form->DOCM_SG_SECAO_GERADORA;
    echo $this->form->DOCM_CD_LOTACAO_GERADORA;
    echo $this->form->DOCM_SG_SECAO_REDATORA;
    echo $this->form->DOCM_CD_LOTACAO_REDATORA;
    echo $this->form->DOCM_ID_TIPO_DOC;
    echo $this->form->DOCM_NR_DCMTO_USUARIO;
    echo $this->form->DOCM_ID_PCTT;
    echo $this->form->DOCM_DS_ASSUNTO_DOC;
    echo $this->form->DOCM_DS_PALAVRA_CHAVE;
    echo $this->form->DOCM_ID_TIPO_SITUACAO_DOC;
    echo $this->form->DOCM_ID_CONFIDENCIALIDADE;
    
    if(!$this->DOCM_NR_DOCUMENTO_RED){
      echo $this->form->RADIO_TIPO_ARQUIVO;
    }else{

    ?>
    
 <div>
   <h2>
    <td> <a target="_blank" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $this->DOCM_ID_DOCUMENTO; ?>/dcmto/<?php echo $this->DOCM_NR_DOCUMENTO_RED; ?> /tipo/<?php echo $this->DOCM_ID_TP_EXTENSAO; ?>"> Versão Escolhida&emsp; </a>&emsp; 
   </h2>
 </div>
 <?php } ?> 

<div id="dialog_cadastra_parte_vista_encaminha">  
    <?php echo $this->partial('_partials/partesVistasEncaminhar.phtml',            
                  array( 'form' => $this->formParte));?>
                             
</div>   

<div id="partes_vistas_encaminhar_adicionadas" style="display: none;"> </div>

<span class="arquivo" style="display: none;"> <?php echo $this->form->DOCM_DS_HASH_RED; ?> </span>
<div id="editorHtml" style="display: none;"> 
    <textarea class="html" id="elm2" cols="60" rows="50" name="TEXTO_HTML" ><?php echo $this->textoHTML; ?></textarea>
</div>
 <?php echo $this->formSisadAnexo->ANEXOS; ?>
<fieldset style="margin-top: 10px; width: 290px;">
    <legend> Cadastro de Partes/Vistas/Encaminhar </legend>
    <input type="button" value="Cadastrar Partes / Vistas / Encaminhar"  class="ui-button ui-widget ui-state-default ui-corner-all cadPartesVistasEncaminhar" name="cadPartesVistasEncaminhar" title="Cadastrar Partes/Vistas/Encaminhar" role="button" aria-disabled="false" style="margin: 10px 0px;"/>
</fieldset>
</div>
<span class="msg_alerta"> </span>
<?php
    echo $this->form->DOCM_NR_DOCUMENTO_RED;
?>

<div class="span-20">
<input id="Salvar" type="submit" name="salvar" value="Salvar" />
<input class="PreVisualizar" style="display: none;" id="PreVisualizar"type="submit" name="PreVisualizar" value="Pré-Visualizar" />
<?php echo $this->form->OBRIGATORIO; ?>
</div>
</form>
