<div style="width: 700px; margin: 0 auto; display: block; /*background:url(<? //echo $this->baseUrl(); ?>/img/brasaoPequeno.jpg) no-repeat center;*/">
<div style="width: 80px;margin: 0 auto;">
</div>
<br />
<div style="width: 500px;display: block;overflow: hidden; margin: 0 auto 0 auto;">
        <p style="text-align:justify"><? echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$this->data["TEXTO_HTML"]; ?></p>
</div>
<br />
</div>