 <?php
    $this->headLink()
        ->prependStylesheet($this->baseUrl().'/js/farbtastic/farbtastic.css','screen, projection');
    $this->HeadScript()
        ->appendFile($this->baseUrl().'/js/farbtastic/farbtastic.js');

    echo $this->headLink(); 
    echo $this->headScript(); ?>
<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
            grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        ); 
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
                    autoOpen : false,
                    modal    : false,
                    show: 'fold',
                    hide: 'fold',
                    resizable: true,
                    width: 800,
                    position: [580,140,0,0],
                    buttons : {
                            Ok: function() {
                                    $(this).dialog("close");
                            }
                    }
       });
       $(".historico").hide('');
      $("#des").hide();
      $("#nova").hide();
       
        $("input[name=categorizar]:radio").click(function() { // attack a click event on all radio buttons with name 'radiogroup'
                if($(this).val() == 'C') {//check which radio button is clicked 
                         $("#cat").show();
                         $("#des").hide();
                         $("#nova").hide();
                } else if($(this).val() == 'D') {
                        $("#cat").hide();
                        $("#des").show();
                        $("#nova").hide();
                } else if($(this).val() == 'N') {
                        $("#cat").hide();
                        $("#des").hide();
                        $("#nova").show();
                } else  {
                       return false;
                }
        });
       $(document).ready(function() {
         $('#colorpicker').farbtastic('#color').removeClass('x-form-text').css('background-image','none');
       });
    });
</script> 
<div class="painel" >
    <a title="Minhas Categorias" name="acao" value="Minhas Categorias" id="Minhas_Categorias" href="<?php echo $this->baseUrl(); ?>/sosti/categorias/index" >Minhas Categorias</a>
</div>
<form method="POST" action="categorizar">
    <table class="grid">
        <thead>
            <tr>
                <th >Selecionar</th>
                <th >Número</th>
                <th >Autor</th>
                <th >Tempo total</th>
                <th >Serviço atual</th>
                <th >Categorias</th>
            </tr>
        </thead>
        <tbody id="documentosList">
            <?php $TimeInterval = new App_TimeInterval(); ?>
            <?php 
            $cont = 0;
            foreach ($this->data as $data): 
                ?>
                <tr>
                    <?php $d = Zend_Json::decode($data);
                        $CateNs = new Zend_Session_Namespace('CateNs');
                        $caso_categoria = new Application_Model_DbTable_SosTbCasoCategoriaSolic();
                        $idDocumento = $d["SSOL_ID_DOCUMENTO"];
						if($CateNs->tipo == 1){
							$identificador = $CateNs->idGrupo;
						}else if($CateNs->tipo == 2){
							$identificador = $CateNs->identificador;
						}else if($CateNs->tipo == 3){
							$identificador = $CateNs->identificador;
						}
                        $categoriasPessoal = $caso_categoria->getCategoriasDocumentoPessoal($idDocumento,$identificador,$CateNs->tipo);  
                        if($cont == 0){
                            $ids = $idDocumento;
                        }else{
                            $ids = $ids.','.$idDocumento;
                        }
                        $cont++;
                    ?>  
                    <td >
                        <input id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" checked="checked" value="<?php echo $this->escape($data); ?>"/>
                    </td>
                    <td> <?php echo $this->escape($d["DOCM_NR_DOCUMENTO"]) ?></td>
                    <td> <?php echo $this->escape($d["NOME_USARIO_CADASTRO"]) ?></td>
                    <td> <?php echo $this->escape($TimeInterval->interval($d["MOFA_DH_FASE"])); ?></td>
                    <td> <?php echo $this->escape($d["SSER_DS_SERVICO"] ) ?></td>
                    <td>
                        <?php 
                        $cont = 0;
                        if($categoriasPessoal != null){ ?>
                            <table>
                                <tr>
                                    <?php foreach ($categoriasPessoal as $categorias_p){ 
                                        if($cont%3 == 0) {
                                            echo '</tr><tr>';
                                        }    
                                    ?>
                                        <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR']?>" title="Nome: <?php echo $categorias_p["CATE_NO_CATEGORIA"]?> - Descrição: <?php echo $categorias_p["CATE_DS_OBSERVACAO"]?>" > </td>
                                    <?php 
                                    $cont++;
                                    } ?>
                                </tr>
                            </table>
                            <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; 
            $caso_categoria = new Application_Model_DbTable_SosTbCasoCategoriaSolic();
            $descategorizar = $caso_categoria->getDescategorizarDocumentos($ids);
            ?>
        </tbody>
        <tfoot><tr><td colspan="7">Total: <?php echo count($this->data); ?></td></tr></tfoot>
    </table>
        <input type="radio" name="categorizar" value="C" checked="checked">Categorizar</input>
        <input type="radio" name="categorizar" value="D">Descategorizar</input>
        <input type="radio" name="categorizar" value="N">Nova Categoria</input>
        </br></br>
        <div id="cat">
            <select name="cat">
            <?php foreach ($this->categorias as $value) { ?>
                <option style="background-color:<?php echo $value["CATE_DS_DESCRICAO_COR"]?>" value="<?php echo $value["CATE_ID_CATEGORIA"]?>" title="Nome: <?php echo $value["CATE_NO_CATEGORIA"]?> - Descrição: <?php echo $value["CATE_DS_OBSERVACAO"]?>"><?php echo $value["CATE_NO_CATEGORIA"]?></option>
             <?php } ?>
            </select>
        </div>
        <div id="des">
            <select name="des">
            <?php foreach ($descategorizar as $descategorizar_p) { ?>
                <option style="background-color:<?php echo $descategorizar_p["CATE_DS_DESCRICAO_COR"]?>" value="<?php echo $descategorizar_p["CATE_ID_CATEGORIA"]?>" title="Nome: <?php echo $descategorizar_p["CATE_NO_CATEGORIA"]?> - Descrição: <?php echo $descategorizar_p["CATE_DS_OBSERVACAO"]?>"><?php echo $descategorizar_p["CATE_NO_CATEGORIA"]?></option>
             <?php } ?>
            </select>
        </div>
        <div id="nova">
            <?php 
                echo $this->form->getElement('CATE_NO_CATEGORIA');
                echo $this->form->getElement('CATE_ID_GRUPO');
                echo $this->form->getElement('CATE_ID_NIVEL');
                echo $this->form->getElement('CATE_DS_OBSERVACAO');
                echo $this->form->getElement('CATE_ID_INDICADOR');
                echo $this->form->getElement('CATE_IC_ATIVO');
                echo $this->form->getElement('CATE_CD_MATRICULA_CATEGORIA');
            ?>
             <input type="text" id="color" name="CATE_DS_DESCRICAO_COR" value="#6c6fd0" style="background-image: none"/>
            <div id="colorpicker"></div>
            <b>Atenção:</b> A nova categoria será inserida as solicitações selecionadas.
        </div>
        </br></br>
        <input type="submit" value="Salvar" name="Salvar">
    <div id="dialog-documentos_detalhe">
        <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
        <div id="dialog-documentos_conteudo"></div>
    </div>
</form>
