<?php

$ptres [ 'campo' ] = 'IMPO_CD_PTRES';
$natureza ['campo'] = 'IMPO_CD_NATUREZA_DESPESA';

echo $this->partial ( '_partials/ajax_ptres.phtml', $ptres );
echo $this->partial ( '_partials/ajax_natureza.phtml', $natureza );
echo $this->partial('_partials/ajuda_informacao.phtml', array('msgAjuda' => $this->msgAjuda,
    'msgInfo' => $this->msgInfo));

?>


<form id="frmImportarfinanceiro" enctype="application/x-www-form-urlencoded" method="post" action="">

<div id="projecaoTabs" class="tabs">
    <ul>
        <li><a href="#"><?php echo $this->telaTitle; ?>:</a></li>
    </ul>

    <div id="projecao">
        <table>
            <tbody>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_ID_IMPORTACAO; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPA_AA_IMPORTACAO; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_UG; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_CONTA_CONTABIL; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_IC_CATEGORIA; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_RESULTADO_PRIMARIO; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_FONTE; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_ESFERA; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_PTRES; ?> </td>                    
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_CD_NATUREZA_DESPESA; ?> </td>                    
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div id="projecaoTabs" class="tabs">
    <ul>
        <li><a href="#projecao">Meses</a></li>
    </ul>

    <div id="projecao">
        <table>
            <tbody>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_JAN; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_FEV; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_MAR; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_ABR; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_MAI; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_JUN; ?> </td>
                </tr>
                <tr>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_JUL; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_AGO; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_SET; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_OUT; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_NOV; ?> </td>
                    <td> <?php echo $this->formulario->IMPO_VL_TOTAL_DEZ; ?> </td>
                </tr>
                <tr>
                    <td><?php echo $this->formulario->IMPO_VL_TOTAL; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<br />
<div id="projecaoTabs" class="tabs">
    <ul>
        <li><a href="#projecao">Associação Manual Inciso</a></li>
    </ul>

    <div id="projecao">
        <table>
            <tbody>
                <tr>
                    <td><?php echo $this->formulario->IMPO_ID_INCISO; ?></td>
                </tr>
                <tr>
                    <td><?php echo $this->formulario->IMPO_ID_ALINEA; ?></td>
                </tr>
                <tr>
                    <td colspan="5"> <?php echo $this->formulario->Enviar; ?> </td>
                </tr>                
            </tbody>
        </table>
    </div>
</div>
</form>
<style>

    .enviar:hover {
        border: 1px solid #769DC0;
        background: #00A6DD url("images/ui-bg_highlight-soft_80_00a6dd_1x100.png") repeat-x scroll 50% 50%;
        font-weight: normal;
        color: #FFF;
    }  
    
</style>
<script type="text/javascript">

$( document ).ready(function() {

    $('#IMPO_CD_VINCULACAO').val(<?php echo substr($this->formulario->IMPO_CD_VINCULACAO->getValue(), 0,3) ?>);

    var url = '<?= $this->baseUrl('orcamento/importarfinanceiro/removeralininciso/cod/')?>';
    var codigo = '<?= $this->formulario->IMPO_ID_IMPORTACAO->getValue() ?>';
    var inciso = '<?= $this->formulario->IMPO_ID_INCISO->getValue() ?>';
    
    if(inciso != ""){
    $('#Enviar').after('\
<a id="Enviar" role="button" class="ceo_salvar ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" alt="Remover" title="Remover" \n\
href="'+url+codigo+'">\n\
<span class="enviar ui-button-text">Remover</span>\n\
</a>');
}
   if($('#IMPO_ID_INCISO').val() != 0) {
       
       $('#IMPO_ID_ALINEA').html("<option>carregando...</option>").fadeIn('slow');

       
        $('.errors').hide();
        $('#IMPO_ID_ALINEA').hide();
        $('#IMPO_ID_INCISO').change();

        var cod = "<?php echo $this->formulario->IMPO_ID_IMPORTACAO->getValue()?>";
        // url: '<?php echo $this->baseUrl(); ?>/orcamento/alinea/alinea/ajaxretornaalinea/cod/'+cod,

        $.ajax({
            url: '<?php echo $this->baseUrl(); ?>/orcamento/alinea/ajaxretornaalinea/cod/'+cod,
            dataType: 'html',
            data: $(this).serialize(),
            type: 'GET',
            processData: false,
            error:function(){
                $('#IMPO_ID_ALINEA').html("<option>Ocorreu um erro ao carregar combo...</option>").fadeIn('slow');
                $('#IMPO_ID_ALINEA').attr('readonly', true);
            },
            success:function(data){
                $('#IMPO_ID_ALINEA').val(data);
            }});          
   }

});
    
    $('#IMPA_AA_IMPORTACAO').attr('readonly', true);
    $('#IMPO_ID_ALINEA').attr('readonly', true);
   

    $('#IMPO_ID_INCISO').change(function(){
        
        if ($(this).val() != 0){        
                var cod = $(this).val();                
                $.ajax({
                    url: '<?php echo $this->baseUrl(); ?>/orcamento/alinea/ajaxcomboalinea/cod/'+cod,
                    dataType: 'html',
                    data: $(this).serialize(),
                    type: 'POST',
                    processData: false,
                    async: false,
                    error:function(){
                        $('#IMPO_ID_ALINEA').html("<option>Ocorreu um erro ao carregar combo...</option>").fadeIn('slow');
                        $('#IMPO_ID_ALINEA').attr('readonly', true);
                    },
                    success:function(data){             
                        setTimeout(function(){ $('#IMPO_ID_ALINEA').html(data) },3000);
                        $('#IMPO_ID_ALINEA').attr('readonly', false);
                        $('#IMPO_ID_ALINEA').removeAttr('style');                        
                    }});  
        }

    });


</script>