<div class="painel">
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/atendentecaixa/add/cx/<?php echo $this->cx; ?>">Novo</a>
    </div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th >Editar</th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/atendentecaixa/list/ordem/NOME_ATENDENTE/direcao/<?php echo $this->direcao ?> ">Atendente<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/atendentecaixa/list/ordem/IC_ATIVIDADE/direcao/<?php echo $this->direcao ?> ">Ativo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td ><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/atendentecaixa/edit/id/<?php echo $this->escape($data["ATCX_ID_CAIXA_ENTRADA"]); ?>/cod_mat/<?php echo $this->escape($data["ATCX_CD_MATRICULA"]); ?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["NOME_ATENDENTE"]); ?></td>
                    <td><?php echo $this->escape($data["IC_ATIVIDADE"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>
<?php //exit(alksdçfkasçdlkfj); ?>
</form>