<?php
/**
  $this->documento;
 */
?>
<div style="height : 569px;" id="leitura_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>" class="leitura_tabs">
    <div id="visualizador_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
        <div class="navegacao_documento navegacao_documento_sem_metadados">
            <button id="esquerda_pular_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>" class="esquerda_pular" title="Volta para a visualização do documento anterior." value="sem_metadados"></button>
            <button id="direita_pular_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>" class="direita_pular" title="Avança para a visualização do documento posterior." value="sem_metadados"></button>
            <button class="fecha_dialog" title="Fecha a visualização do documento sem metadado." value="<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>"></button>
            <center>
                <h2 id="label_leitura_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>"> 
                    <!-- O CONTEÚDO VEM DINAMICAMENTE PELO JQUERY -->
                </h2>
            </center>
        </div>
        <div id="visualizador_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
            <div style="margin-left: 20px" id="resumo_metadados_leitura-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
                <!-- O CONTEÚDO VEM DINAMICAMENTE PELO JQUERY -->
            </div>
            <div id="visualizador_pdf_sem_metadados-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
                <!-- O CONTEÚDO VEM DINAMICAMENTE PELO JQUERY -->
            </div>

            <div class="span-4" id="loading">
                <div style="margin: 1px 0 0 30px;" class="span-1 last"><img src="<?= $this->baseUrl() ?>/img/ajax-loader_1.gif"/></div><div class="span-2"><strong>Aguarde...</strong></div>
            </div>
        </div>
    </div>
</div>