<?php
class Application_Model_DbTable_RhfuncDiretor extends Zend_Db_Table_Abstract
{

	protected $_adapter = 'diretor';
    /**
     * 
     * Identifica se o usuário tem, perfil de diretor.
     * @param string $siglaSecao
     * @param integer $codResponsavel
     */
    public function isDiretor($siglaSecao,$codResponsavel){
    	
        $db = Zend_Db_Table_Abstract::getDefaultAdapter();
    	
    	$stmt = $db->query("SELECT SUM(CONTA)
FROM(
      SELECT 'TITULAR' TIPO,
         COUNT(1) CONTA
      FROM RH_CENTRAL_MOV_FUNCIONAL,
           RH_IDENTIFICACAO_FUNCAO,
           RH_FUNCAO_CONFIANCA,
           RH_TIPO_MOVIMENTACAO_FUNCIONAL,
       RH_PESO_FUNCAO      
      WHERE IFUN_COD_ID_FUNCAO = MVFU_HIFC_IFUN_COD_ID_FUNCAO
      AND   MVFU_TMFU_COD_TIPO_MOV_FUNC = TMFU_COD_TIPO_MOV_FUNC
      AND   TMFU_AUTM_COD_TIPO_MOV = 4
      AND   MVFU_HIFC_IFUN_COD_ID_FUNCAO = IFUN_COD_ID_FUNCAO
      AND   MVFU_HIFC_GRUPO_FUNC_CONF = FCON_GRUPO_FUNC_CONF
      AND   MVFU_HIFC_CATEG_FUNC_CONF = FCON_CATEG_FUNC_CONF
      AND   MVFU_HIFC_COD_FUNC_CONF = FCON_COD_FUNC_CONF
      AND   PEFU_CATEG_FUNCAO = MVFU_HIFC_CATEG_FUNC_CONF
      AND   IFUN_FLAG_ATIVA = 'S'
      AND   FCON_FLAG_ATIVA = 'S'
      AND   PEFU_PESO_FUNCAO >= 30 
      AND   FCON_NFUN_COD_NOME_FUNCAO NOT IN (121,148,154) 
      AND   (MVFU_DAT_FIM_EXERC IS NULL OR TRUNC(MVFU_DAT_FIM_EXERC) >= TRUNC(SYSDATE))
      AND   MVFU_FUNC_SIGLA_SECAO_EXERCE = '$siglaSecao'
      AND   MVFU_FUNC_COD_FUNC_EXERCE = $codResponsavel
  UNION      
      SELECT 'SUBSTITUTO' TIPO,
         COUNT(1) CONTA
      FROM RH_CENTRAL_MOV_FUNCIONAL,
           RH_IDENTIFICACAO_FUNCAO,
           RH_FUNCAO_CONFIANCA, 
       RH_TIPO_MOVIMENTACAO_FUNCIONAL,
       RH_PESO_FUNCAO              
      WHERE IFUN_COD_ID_FUNCAO = MVFU_HIFC_IFUN_COD_ID_FUNCAO
      AND   MVFU_TMFU_COD_TIPO_MOV_FUNC = TMFU_COD_TIPO_MOV_FUNC
  AND   TMFU_AUTM_COD_TIPO_MOV = 5
      AND   MVFU_HIFC_IFUN_COD_ID_FUNCAO = IFUN_COD_ID_FUNCAO
      AND   MVFU_HIFC_GRUPO_FUNC_CONF = FCON_GRUPO_FUNC_CONF
      AND   MVFU_HIFC_CATEG_FUNC_CONF = FCON_CATEG_FUNC_CONF
      AND   MVFU_HIFC_COD_FUNC_CONF = FCON_COD_FUNC_CONF
  AND   PEFU_CATEG_FUNCAO = MVFU_HIFC_CATEG_FUNC_CONF
      AND   IFUN_FLAG_ATIVA = 'S'
  AND   FCON_FLAG_ATIVA = 'S'
  AND   PEFU_PESO_FUNCAO >= 30 
      AND   FCON_NFUN_COD_NOME_FUNCAO NOT IN (121,148,154) 
      AND   MVFU_DAT_FIM_EXERC >= TRUNC(SYSDATE)
      AND   MVFU_DAT_INIC_EXERC <= TRUNC(SYSDATE)
      AND   MVFU_FUNC_SIGLA_SECAO_EXERCE = '$siglaSecao'
      AND   MVFU_FUNC_COD_FUNC_EXERCE = $codResponsavel
  UNION            
  SELECT 'AUTOMATICO' TIPO,
          COUNT(1) CONTA 
  FROM RH_SUBSTITUICAO_AUTOMATICA,
       RH_IDENTIFICACAO_FUNCAO,
       RH_FUNCAO_CONFIANCA,
       RH_PESO_FUNCAO              
  WHERE SBAU_FUNC_SIGLA_SECAO_EXERC = '$siglaSecao'
  AND SBAU_FUNC_COD_FUNC_EXERC = $codResponsavel
  AND SBAU_HIFC_COD_ID_FUNCAO_SUBS = IFUN_COD_ID_FUNCAO
  AND SBAU_HIFC_GRUPO_FUNC_CONF_SUBS = FCON_GRUPO_FUNC_CONF
  AND SBAU_HIFC_CATEG_FUNC_CONF_SUBS = FCON_CATEG_FUNC_CONF
  AND SBAU_HIFC_COD_FUNC_CONF_SUBS = FCON_COD_FUNC_CONF
  AND PEFU_CATEG_FUNCAO = SBAU_HIFC_CATEG_FUNC_CONF_SUBS
  AND IFUN_FLAG_ATIVA = 'S'
  AND FCON_FLAG_ATIVA = 'S'
  AND PEFU_PESO_FUNCAO >= 30
      AND   FCON_NFUN_COD_NOME_FUNCAO NOT IN (121,148,154) 
  AND (SBAU_DAT_FIM_EXERC IS NULL OR TRUNC(SBAU_DAT_FIM_EXERC) >= TRUNC(SYSDATE))
  UNION
  SELECT 'DIRETOR FORO' TIPO,
         COUNT(1) CONTA 
  FROM RH_HIST_FUNCOES_JUIZES
  WHERE HIFJ_FUJU_COD_FUNC_JUIZ = 9
  AND NVL(HIFJ_DATA_FIM,TRUNC(SYSDATE)) >= TRUNC(SYSDATE)
  AND HIFJ_FUNC_SIGLA_SECAO_SUBSECAO = '$siglaSecao'
  AND HIFJ_FUNC_COD_FUNCIONARIO = $codResponsavel)
    	");
    	

 
 return  $stmt->fetch();   	
    }
    
}