<?php
/**
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 *
 */

class Application_Model_DbTable_SosTbMaeqManutencaoEqpto extends Zend_Db_Table_Abstract {
	
        protected $_schema = 'SOS';
        protected $_name = 'SOS_TB_MAEQ_MANUTENCAO_EQPTO';
	protected $_primary = 'MAEQ_ID_MANUTENCAO_EQUIPAMENTO';
	protected $_sequence = 'SOS_SQ_MAEQ';
	
	public function getDadosManutencaoSolicitacao($idDocumento){
		$db = Zend_Db_Table_Abstract::getDefaultAdapter();
		
		$stmt = "SELECT A.MAEQ_ID_MANUTENCAO_EQUIPAMENTO, 
						A.MAEQ_ID_DOCUMENTO,
						SAD_PG_RETORNO_PESSOA.SAD_FU_RETORNA_NOME(A.MAEQ_CD_MATRICULA_RETIRADA)MAEQ_CD_MATRICULA_RETIRADA, 
						TO_CHAR(A.MAEQ_DH_SOLICITACAO_RETIRADA ,'dd/mm/yyyy HH24:MI:SS') MAEQ_DH_SOLICITACAO_RETIRADA,
						A.MAEQ_DS_SOLICITACAO_RETIRADA, 
						A.MAEQ_IC_AUTORIZACAO_RETIRADA,
						SAD_PG_RETORNO_PESSOA.SAD_FU_RETORNA_NOME(A.MAEQ_CD_MATRICULA_AUT_RETIRADA)MAEQ_CD_MATRICULA_AUT_RETIRADA, 
						TO_CHAR(A.MAEQ_DH_AUTORIZACAO_RETIRADA ,'dd/mm/yyyy HH24:MI:SS') MAEQ_DH_AUTORIZACAO_RETIRADA,
						A.MAEQ_DS_AUTORIZA_RETIRADA, 
						SAD_PG_RETORNO_PESSOA.SAD_FU_RETORNA_NOME(A.MAEQ_CD_MATRICULA_DEVOLUCAO)MAEQ_CD_MATRICULA_DEVOLUCAO,
						TO_CHAR(A.MAEQ_DH_DEVOLUCAO_EQUIPAMENTO ,'dd/mm/yyyy HH24:MI:SS') MAEQ_DH_DEVOLUCAO_EQUIPAMENTO, 
						SAD_PG_RETORNO_PESSOA.SAD_FU_RETORNA_NOME(A.MAEQ_CD_MATRICULA_RECEBIMENTO)MAEQ_CD_MATRICULA_RECEBIMENTO,
						TO_CHAR(A.MAEQ_DH_RECEBIMENTO_EQPTO ,'dd/mm/yyyy HH24:MI:SS') MAEQ_DH_RECEBIMENTO_EQPTO, 
						A.MAEQ_DS_RECEBIMENTO_EQPTO
				   FROM SOS.SOS_TB_MAEQ_MANUTENCAO_EQPTO A
				  WHERE A.MAEQ_ID_DOCUMENTO = $idDocumento";
		return  $db->query($stmt)->fetchAll(); 
	}

}