<?php
/**
 * Contém view da action específica
 * 
 * e-Admin
 * e-Orçamento
 * View
 * 
 * @author Anderson Sathler M. Ribeiro <asathler@gmail.com>
 */

/**
 * Disponibiliza as informações a serem exibidas na view
 *
 * @category Orcamento
 * @package Orcamento_Views_Scripts_Extrato_Detalhe
 * @author Anderson Sathler M. Ribeiro <asathler@gmail.com>
 * @license Creative Commons Atribuição 3.0 não adaptada
 *          <http://creativecommons.org/licenses/by/3.0/deed.pt_BR>
 * @ignore Este código é livre para uso dentro do TRF! Fora do TRF pode apenas
 *         servir como fonte de estudo ou base para futuros códigos-fonte sem
 *         nenhuma restrição, salvo pelas informações de @copyright e @author
 *         que devem ser mantidas inalteradas.
 * @copyright Tribunal Regional Federal ©2007-2014 <http://www.trf1.jus.br>
 */
// Define array de ajuda
$ajuda [ 'msgAjuda' ] = $this->msgAjuda;
$ajuda [ 'msgInfo' ] = $this->msgInfo;

// Chama a partial para exibição da ajuda e informação da tela
echo $this->partial ( '_partials/ajuda_informacao.phtml', $ajuda );

// Define array do botão
$botao [ 'nomeController' ] = 'extrato';
$botao [ 'nomeAction' ] = Trf1_Orcamento_Definicoes::ACTION_INDEX;
$botao [ 'nomeClasse' ] = Trf1_Orcamento_Definicoes::CLASSE_CONSULTAR;
$botao [ 'textoBotao' ] = 'Nova consulta';
$botao [ 'textoAlternativo' ] = 'Realizar nova consulta de extrato';

// Chama a partial para exibição de botão
echo $this->partial ( '_partials/botao.phtml', $botao );

// Define array da despesa
$despesa [ 'despesa' ] = $this->despesa;

// Chama a partial para exibição dos dados da despesa
echo $this->partial ( '_partials/despesa_detalhe_extrato.phtml',	$despesa );

// Exibe o grid
echo '<br />';
echo $this->grid;