<?php
$this->inlineScript()->appendFile($this->baseUrl() . '/js/tooltipster-1.2/js/jquery.tooltipster.min.js', 'text/javascript')
                     ->appendFile($this->baseUrl() . '/js/os/associarPesquisar.js ', 'text/javascript');
?>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="painel ui-buttonset">
</div>
<?php if ($this->filtro): ?>
<div id="container_pagination">
    <table class="grid ui-widget ui-widget-content">
        <thead>
            <tr class="ui-widget-header">
                <th>N. da solicitação</th>
                <th>Autor</th>
                <th>Tempo total</th>
                <th>Serviço atual</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->arraySostis as $as): ?>
            <tr class="" name="rowList" value='<?php echo Zend_Json::encode($as); ?>' title="Duplo Click para abrir os detalhes">
                    <input class="nav_grid_check_box nav_check_boxes " name="solicitacao[]" value='<?php echo Zend_Json::encode($as); ?>' type="hidden">
                    <td><?php echo $as['DOCM_NR_DOCUMENTO']; ?></td>
                    <td><?php echo $as['NOME_USARIO_CADASTRO']; ?></td>
                    <td><?php echo $as['PRAZO']; ?></td>
                    <td><?php echo $as['SSER_DS_SERVICO']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot></tfoot>
    </table>
    <br><br>
</div>
<input name="vincular" value="V" type="hidden">
<?php endif; ?>
<fieldset style="display:inline;">
    <legend>Filtro da Caixa</legend>
    <div class="painel">
        <div class="painel">
            <input type="button" title="Último Filtro" name="acao" value="Filtro" id="pesquisar">
            <a title="Novo Filtro" name="acao" value="Filtrar" id="ultimo_filtro"
               href="<?php echo $this->baseUrl(); ?>/os/associar/pesquisar/nova/1">Limpar
                Filtro/Retirar Filtro</a>
            &emsp;&emsp;<span style="color: #2E4557;"
                              id="statusfiltro"><strong><?php if ($this->ultima_pesq == true) echo "Filtro Ativo"; else echo "Filtro Inativo"; ?></strong></span>
        </div>


    </div>
    <div id="pesq_div" style="display: block;">
        <?php echo $this->form; ?>
        <span id="botao_ajuda_recolhe"></span>
    </div>
</fieldset>
<form name="listaOs" action="<?php echo $this->baseUrl(); ?>/os/associar/save" method="post">
<?php if ($this->ultima_pesq == true) { ?>
    <?php if (count($this->data)): ?>
        <div class="painel">
        </div>
        <div id="container_pagination">
        <table class="grid">
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th>N. da solicitação</th>
            <th>Data de cadastro</th>
            <th>Nome do solicitante</th>
            <th>Serviço atual</th>
            <th>Atendente</th>
            <th>Vinculada</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $CateNs = new Zend_Session_Namespace('CateNs');
        $identificador = $CateNs->idGrupo;
        $tipo = 'GRUPO';
        $caso_categoria = new Application_Model_DbTable_SosTbCasoCategoriaSolic();


        foreach ($this->data as $data):
//            Zend_Debug::dump($data);
            $categoriasGrupo = $caso_categoria->getCategoriasDocumentoGrupo($data["SSOL_ID_DOCUMENTO"], $identificador, $tipo);
            $saidaServicoSistema = null;
            if (!is_null($data["OSIS_NM_OCORRENCIA"])) {
                $saidaServicoSistema = $data["OSIS_NM_OCORRENCIA"] . " - " . $data["CTSS_NM_CATEGORIA_SERVICO"] . " - N." . $data["ASIS_IC_NIVEL_CRITICIDADE"];

                if ($data["ASSO_IC_SOLUCAO_PROBLEMA"] == "S") {
                    $tipoProblemaCausaMsg = "Problema";
                } else {
                    $tipoProblemaCausaMsg = "Causa";
                }

                if ($data["ASSO_IC_ATENDIMENTO_EMERGENCIA"] == 'S' && !is_null($data["CORRETIVA"])) {
                    $saidaServicoSistema = $data["OSIS_NM_OCORRENCIA"] . " - <span><strong>" . $data["CTSS_NM_CATEGORIA_SERVICO"] . "</strong></span> - N." . $data["ASIS_IC_NIVEL_CRITICIDADE"] . " Tipo: " . $tipoProblemaCausaMsg;
                }
            }

            $prazo = $this->calculahorasla($data);
            $data['DADOS_INPUT'] = json_encode($data);
            ?>
            <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>">
                <td <?php echo App_View_Helper_CorStatus::corCaixa($this->controller, $data["MOFA_ID_FASE"], $data["SESP_DH_LIMITE_ESP"], $data["TEMPO_TOTAL"], $data["ATENDENTE"]); ?> >
                    <input class="radio_cx nav_grid_check_box nav_check_boxes"
                           id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]"
                           type="radio" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                </td>
                <td>
                    <?php if (isset($this->vinc[$data["SSOL_ID_DOCUMENTO"]])) : ?>
                        <a href="#" class="plus-vinc <?php echo $data["SSOL_ID_DOCUMENTO"] ?>">
                            <img src="<?php echo $this->baseUrl('img/a-plus-icon.png') ?>" alt=""/>
                        </a>
                    <?php endif; ?>
                </td>
                <td><a href="#" class="tooltip"
                       title="<?php echo $data['DOCM_DS_ASSUNTO_DOC']; ?>"><?php echo $this->escape($data["MASCARA_DOCM"]); ?>
                </td>
                <td><?php echo $data['DOCM_DH_CADASTRO']; ?></td>
                <td><?php echo $data['NOME_USARIO_CADASTRO']; ?></td>
                <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                <td><?php echo $this->escape($data["NOME_ATENDENTE"]); ?></td>
                <td><?php echo isset($data["VINCULADA"]) && $data["VINCULADA"] == 1 ? "SIM" : ""; ?></td>
             <!------- Até aqui ------->   
                
                
                <td>
                    <?php
                    $cont = 0;
                    if ($categoriasGrupo != null) {
                        ?>
                        <table>
                            <tr>
                                <?php
                                foreach ($categoriasGrupo as $categorias_p) {
                                    if ($cont % 3 == 0) {
                                        echo '</tr><tr>';
                                    }
                                    ?>
                                    <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR'] ?>"
                                        title="Nome: <?php echo $categorias_p['CATE_NO_CATEGORIA'] ?> - Descrição: <?php echo $categorias_p['CATE_DS_OBSERVACAO'] ?>"></td>
                                    <?php
                                    $cont++;
                                }
                                ?>
                            </tr>
                        </table>
                    <?php } ?>
                </td>
<!--                <td><?php
//                    if ($data["ASSO_IC_ATENDIMENTO_EMERGENCIA"] == 'S') {
                        ?>
                        <img src="<?php // echo $this->baseUrl(); ?>/img/sosti/emergencial.png"
                             title="Demanda de Caráter Emergencial"/>
                    <?php // } ?>
                </td>-->
<!--                <td>
                    <span style="color: <?php // echo $prazo['percentual']['cor'] ?>">
                        <?php // echo $prazo['prazo_restante'][0]."D ".$prazo['prazo_restante'][1]."h ".$prazo['prazo_restante'][2]."m ".$prazo['prazo_restante'][3]."s "."<strong>".$prazo['percentual']['pct']."</strong>% " ?>
                    </span>
                </td>-->
                <!--<td><?php // echo $saidaServicoSistema; ?></td>-->
            </tr>

            <?php if (isset($this->vinc[$data["SSOL_ID_DOCUMENTO"]])) : ?>
<!--                --><?php //Zend_Debug::dump($this->vinc);die;?>
            <?php foreach ($this->vinc[$data["SSOL_ID_DOCUMENTO"]] as $vinc): ?>
                <tr class="vinculados <?php echo $data["SSOL_ID_DOCUMENTO"] ?>">
                    <td style="display: none"
                        colspan="2" <?php echo App_View_Helper_CorStatus::corCaixa($this->controller, $vinc["MOFA_ID_FASE"], $vinc["SESP_DH_LIMITE_ESP"], $vinc["TEMPO_TOTAL"], ''); ?> >
                        <input style="visibility: hidden" class="nav_grid_check_box nav_check_boxes"
                               id="<?php echo $this->escape($vinc["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]"
                               type="checkbox" value="<?php echo $this->escape(json_encode($vinc)); ?>"/>
                    </td>
                    <td style="display: none">
                        <a href="#" class="tooltip"
                           title="<?php echo $vinc['DOCM_DS_ASSUNTO_DOC']; ?>"><?php echo $this->escape($vinc["MASCARA_DOCM"]); ?>
                    </td>
                    <td style="display: none"><?php echo $this->escape($vinc["DOCM_DH_CADASTRO"]); ?></td>
                    <td style="display: none"><?php echo $this->escape($vinc["SSER_DS_SERVICO"]); ?></td>
                    <td style="display: none"><?php echo ($vinc['ATENDENTE'] = ' - ') ? '' : $this->escape($vinc['ATENDENTE']); ?></td>
                    <!--                    <td style="display: none">-->
                    <?php //echo $this->escape($vinc["NOME_ATENDENTE"]); ?><!--</td>-->
                    <td style="display: none">
                        <?php
                        $cont = 0;
                        if ($categoriasGrupo != null) {
                            ?>
                            <table>
                                <tr>
                                    <?php foreach ($categoriasGrupo as $categorias_p) {
                                        if ($cont % 3 == 0) {
                                            echo '</tr><tr>';
                                        }
                                        ?>
                                        <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR'] ?>"
                                            title="Nome: <?php echo $categorias_p['CATE_NO_CATEGORIA'] ?> - Descrição: <?php echo $categorias_p['CATE_DS_OBSERVACAO'] ?>"></td>
                                        <?php
                                        $cont++;
                                    } ?>
                                </tr>
                            </table>
                        <?php
                        }
                        ?>
                    </td>
                    <td style="display: none"><?php if (isset ($vinc["VINCULADA"]) && ($vinc["VINCULADA"] == 1)) {
                            echo "SIM";
                        } else {
                            echo "";
                        } ?></td>
                    <td style="display: none"></td>
                    <td style="display: none;"></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>


        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="8">Total: <?php echo $this->data->getTotalItemCount(); ?>
            </td>
        </tr>
        <tr>
            <td colspan="8">
                <?php echo $this->paginationControl($this->data, null, null, null); ?>
            </td>
        </tr>
        </tfoot>
        </table>
        <div class="painel">
        </div>
    <?php else: ?>
        <?php if ($this->ultima_pesq): ?>
            <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
        <?php else: ?>
            <p><br/>Não existem registros</p>
        <?php endif; ?>
    <?php endif; ?>
    </div>
    <input type="submit" name="Salvar" value="Salvar" />
<?php } else { ?>
    <p><br/><strong>Utilize o filtro informando os parâmetros desejados</strong></p>
<?php } ?>
<div id="esc">
    <?php foreach ($this->arraySostisJson as $k=>$sj): ?>
        <input type="hidden" class="solicit_escolhidas" name="solicit_escolhidas[]" value='<?php echo $sj; ?>' id="<?php echo $k; ?>" />
    <?php endforeach; ?>
</div>
</form>
<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>