<?php 
    $prdc = new Application_Model_DbTable_SadTbPrdcProtDocProcesso();
    $prdi = new Application_Model_DbTable_SadTbPrdiProcessoDigital();
    $mapperDocumento = new Sisad_Model_DataMapper_Documento();
    $processo = $prdc->getDadosEnderecados($this->DocmDocumento[DOCM_ID_DOCUMENTO]);
    $protocolado = $prdc->getDadosProtocolados($this->DocmDocumento[DOCM_ID_DOCUMENTO]);
?>

 <script type="text/javascript">
    $(function() {
            $( "#tabs" ).tabs();
            $( "#tabs" ).tabs("select",GLOBAL_indice_abas);
            $( "#tabs" ).tabs({
               select: function(event, ui) {
                    GLOBAL_indice_abas = ui.index;
               }
            });
            $( "#buttonsetmanifestacao" ).buttonset();
            $( ".abrirAnexo" ).button({
                    icons: {
                        primary: "ui-icon-folder-open"
                    }
                }).attr('style','width: auto; height: 26px;');
                $( ".alertaButton" ).button({
                    icons: {
                        primary: "ui-icon-alert"
                    }
                }).attr('style','width: auto; height: 26px;');
                
                $( ".proc_docs_icon_closed" ).button({
                    icons: {
                        primary: "ui-icon-radio-on"
                    }
                });
                
                $( ".novoDespacho" ).button({
                    icons: {
                        primary: "ui-icon-document"
                    }
                });
                
    });
 </script>
    <div id="tabs">
       <ul>
                <?php
                 if(!$this->DocumentosProcesso){
                ?>
		<li><a href="#tabs-1">Documento</a></li>
                <?php }else{?>
                <li><a href="#tabs-1">Processo</a></li>
                <?php 
                }
                if($this->interessados){?>
                   <li><a href="#tabs-2">Partes</a></li>
                <?php 
                }
                
                if($this->vistas){?>
                   <li><a href="#tabs-9">Vistas</a></li>
                <?php } ?>
                
                <?php 
                    if($processo){
                ?>
                    <li><a href="#tabs-3">Para Postagem</a></li>
                <?php 
                } 
                    if($protocolado){ ?>
                    <li><a href="#tabs-4">Encaminhados</a></li>
                <?php        
                }

                if($this->DocumentosProcesso){
                ?>
                    <li><a href="#tabs-5">Documentos do Processo</a></li>
                <?php } ?>
                
                <li><a href="#tabs-6">Histórico</a></li>
                
                <?php 
                if($this->AnexAnexo){
                    $totalAnexo = "Total de Anexos: ". count($this->AnexAnexo);
                ?>
                    <li><a href="#tabs-7">Anexos</a></li>
                <?php 
                }
                
                $mostraDespacho = false;
                foreach ($this->DocmDocumentoHistorico as $historico){
                  if ($historico['FADM_ID_FASE'] == 1040){
                     $mostraDespacho = true;
                     break;
                     //$contaDespacho = $contaDespacho + 1;
                  }
                }
                
                foreach ($this->DocumentosProcesso as $DocumentosProcesso){
                  if ($DocumentosProcesso['DTPD_ID_TIPO_DOC'] == 39){
                     //$contaDespacho = $contaDespacho + 1;
                      $mostraDespacho = true;
                      break;
                  }
                }
                
                if ($mostraDespacho){?>
                  <li><a href="#tabs-8">Despacho</a></li>
                <?php }?>                    
	</ul>
        <div id="tabs-1">
            <table class="" style=" cursor: default;/*border: 1px solid red; border-collapse: separate; border-bottom: 1px solid red;*/" >
                <tr style="font-size: 12px; font-weight: bold;">
                        <td title="Tipo do documento" colspan="1">
                                <?php echo $this->DocmDocumento["DTPD_NO_TIPO"]?>
                        </td>
                        <td title="Número do documento">
                            Nº:&emsp;<?php echo $this->DocmDocumento["DOCM_NR_DOCUMENTO"]?>
                        </td>
                        </td>
                        <td title="Data e hora de cadastro">
                                D/H criação:&emsp;<?php echo $this->DocmDocumento["DOCM_DH_CADASTRO"]?>
                        </td>
                    </tr>
                    <tr>
                    <tr>
                        <th >Nº Documento Usuário:</th>
                        <td title="Número do documento">
                                <?php echo $this->DocmDocumento["DOCM_NR_DCMTO_USUARIO"]?>
                        </td>
                    </tr>
                    <tr>
                        <th >Assunto do documento: </th>
                        <td colspan="3" title="Número do documento">
                                <?php echo $this->DocmDocumento["AQVP_CD_PCTT"].' - '.$this->DocmDocumento["AQAT_DS_ATIVIDADE"];?>
                        </td>
                    </tr>
                    <?php
                      if($this->objeto){ ?>
                    <tr>
                        <th >Objeto do Processo: </th>
                        <td colspan="3" title="Objeto do Processo">
                                <?php echo $this->objeto;?>
                        </td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <th >Situação:</th>
                        <td title="Número do documento">
                                <?php echo $this->DocmDocumento["TPSD_DS_TIPO_SITUACAO_DOC"]?>
                        </td>
                        <th >Confidencialidade:</th>
                        <td title="Número do documento">
                                <?php echo $this->DocmDocumento["CONF_DS_CONFIDENCIALIDADE"]?>
                        </td>
                    </tr>
                    <tr>
                        <th >Unidade Emissora:</th>
                        <td colspan="3">
                                        <?php //echo $this->DocmDocumento[LOTA_SIGLA_LOTACAO_EMISSORA].' - '.$this->DocmDocumento[LOTA_DSC_LOTACAO_EMISSORA] ?>
                         <?php echo $this->DocmDocumento["LOTA_SIGLA_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $this->DocmDocumento["LOTA_DSC_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $this->DocmDocumento["LOTA_COD_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $this->DocmDocumento["FAMILIA_EMISSORA"] ;?>
                        </td>
                    </tr>
                    <tr>
                        <th >Unidade Redatora:</th>
                        <td colspan="3">
                         <?php echo $this->DocmDocumento["LOTA_SIGLA_LOTACAO_REDATORA"] ;?> -
                            <?php echo $this->DocmDocumento["LOTA_DSC_LOTACAO_REDATORA"] ;?> -
                            <?php echo $this->DocmDocumento["LOTA_COD_LOTACAO_REDATORA"] ;?> -
                            <?php echo $this->DocmDocumento["FAMILIA_REDATORA"] ;?>
                        </td>
                    </tr>
                        <th>Cadastrante:</th>
                        <td colspan="1"><?php echo $this->DocmDocumento["NOME"]?></td>
                        <th>Matrícula:</th>
                        <td colspan="1"><?php echo $this->DocmDocumento["DOCM_CD_MATRICULA_CADASTRO"]?></td>
                    </tr>
                    <?php 
                    
                    if ($this->ProcessosDocumento){?>                    
                       <tr>
                           <th>Inserido no PA número:</th>
                           <td colspan="3"><?php 
                               echo $this->ProcessosDocumento;?>
                           </td>                               
                       </tr>
                    <?php }     
                    
                    if ($this->NumDocPrincipal){?>                    
                       <tr>
                           <th>Vinculada ao documento:</th>
                           <td><?php 
                               echo $this->NumDocPrincipal[0]["DOCM_NR_DOCUMENTO"]; ?>
                           </td>                               
                       </tr>
                    <?php } 
                    
                    if ($this->NumDocVinculado){?>                    
                       <tr>
                           <th>Minuta vinculada:</th>
                           <td><?php 
                               echo $this->NumDocVinculado[0]["DOCM_NR_DOCUMENTO"]; ?>
                           </td>                               
                       </tr>
                    <?php } 
                    
                    ?>
                    <?php if(is_null($this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"])&& ($this->DocmDocumento["DTPD_NO_TIPO"]=="Processo administrativo")){
                                    /*NAO MOSTRA A LINHA "ABRIR:"*/
                            }elseif((!is_null($this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"])&&$this->DocmDocumento["DTPD_NO_TIPO"]=="Processo administrativo")||($this->DocmDocumento["DTPD_NO_TIPO"]!="Processo administrativo")){?>
                            <tr >
                                <th>Abrir:</th>
                                <td><a class="<?php if(is_null($this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"])){
                                                                echo 'alertaButton';
                                                            }else{
                                                                echo 'abrirAnexo';
                                                            } ?>" 
                                       target="_blank" 
                                       title="<?php if(is_null($this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"])){
                                                                echo 'Sem Arquivo';
                                                            }else{
                                                                echo 'Abrir Documento';
                                                            } ?>" 
                                       href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $this->DocmDocumento["DOCM_ID_DOCUMENTO"]; ?>/dcmto/<?php echo $this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"]; ?>/tipo/<?php echo $this->DocmDocumento["DOCM_ID_TP_EXTENSAO"]; ?> "><?php if(is_null($this->DocmDocumento["DOCM_NR_DOCUMENTO_RED"]))if($this->DocmDocumento["DTPD_NO_TIPO"]=="Processo administrativo"){}elseif($this->DocmDocumento["DTPD_NO_TIPO"]!="Processo administrativo"){echo 'Sem Arquivo';}else{echo 'Abrir';} ?></a></td>
                            </tr>
                            <?php }?>
                    </tr>
                    <tr >
                        <th colspan="4">Descrição:</th>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div style="font-size: 10pt; padding-left: 6px;">
                                <?php echo $this->DocmDocumento["DOCM_DS_ASSUNTO_DOC"]?>
                            </div>
                        </td>
                    </tr>
            </table>
        </div>
        
        <?php  if($this->interessados): ?>   
            <div id="tabs-2">
                <div id="mostra_partes">
                    <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                        <legend>Partes Cadastradas</legend>
                          <?php  foreach($this->interessados as $i){
                                    echo $i['NOME']."<br/>";
                                  }
                          ?>
                    </fieldset>
                </div>
            </div>
        <?php endif; ?>

        <?php 
        //Zend_debug::dump($this->vistas); 
        
        if($this->vistas){ ?>   
         <div id="tabs-9">
             <div id="mostra_vistas">
                 <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                     <legend>Quem tem vistas</legend>
                       <?php  foreach($this->vistas as $i){
                                echo $i['NOME']."<br/>";
                              }
                       ?>
                 </fieldset>
             </div>
         </div>
       <?php } ?>
        

            <?php 
                if($processo[0]["NOME_EXTERNO"]){
            ?>
            <div id="tabs-3">
                <?php 
                    foreach ($processo as $value):
                    $postagem = new Application_Model_DbTable_SadTbPostPostagemProcDoc();
                ?>
                <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                   <div style="margin-left: 10px; margin-top: 4px; font-size: 12px; ">
                    <br/><b>Destino:</b>
                        <?php echo $value["DESTINATARIO"] ;?>
                    <br/><b>Destinatário:</b>
                        <?php echo $value["NOME_EXTERNO"] ;?>
                    <br/><b>Endereço:</b>
                        <?php echo $value["POST_DS_ENDERECO_DESTINO"] ;?>
                    <br/><b>Bairro:</b>
                        <?php echo $value["POST_DS_BAIRRO_DESTINO"] ;?>
                    <br/><b>Cidade:</b>
                        <?php echo $value["POST_DS_CIDADE_DESTINO"] ;?>
                    <br/><b>UF:</b>
                        <?php echo $value["POST_CD_UF_DESTINO"] ;?>
                    <br/><b>CEP:</b>
                        <?php echo $value["POST_CD_CEP_DESTINO"] ;?>
                    </div>
                </fieldset>
                <?php 
                endforeach;
                ?>
            </div>
        <?php
            }
            if($protocolado){
        ?>
        <div id="tabs-4">
            <?php 
                foreach ($protocolado as $value):
            ?>
            <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                <legend>Nr Protocolo: <?php echo $value["PRDC_ID_PROTOCOLO"] ;?></legend>
               <div style="margin-left: 10px; margin-top: 4px; font-size: 12px; ">
                    <!--<br/><b>Nr Protocolo:</b>-->
                    <?php // echo $value["PRDC_ID_PROTOCOLO"] ;?>
                    <br/><b>Protocolado Por:</b>
                    <?php echo $value["CRIADOR"] ;?>
                    <br/><b>Em:</b>
                    <?php echo $value["PRDC_DH_PROTOCOLO_DOC_PROC"] ;?>
                    <br/><b>Destino:</b>
                    <?php echo $value["DESTINATARIO"] ;?>
                    <br/><b>Destinatário:</b>
                        <?php echo $value["NOME_EXTERNO"] ;?>
                    <br/><b>Endereço:</b>
                        <?php echo $value["POST_DS_ENDERECO_DESTINO"] ;?>
                    <br/><b>Bairro:</b>
                        <?php echo $value["POST_DS_BAIRRO_DESTINO"] ;?>
                    <br/><b>Cidade:</b>
                        <?php echo $value["POST_DS_CIDADE_DESTINO"] ;?>
                    <br/><b>UF:</b>
                        <?php echo $value["POST_CD_UF_DESTINO"] ;?>
                    <br/><b>CEP:</b>
                        <?php echo $value["POST_CD_CEP_DESTINO"] ;?>
                    </div>
                <?php if($value["PRDC_IC_RECEBIMENTO"] != 'S') { echo 'Protocolo aguardando documento físico!';}?>
            </fieldset>
        <?php 
            endforeach;
            ?>
        </div>
        <?php
            }
            if($this->DocumentosProcesso){
        ?>
         <div id="tabs-5">
            <?php 
            echo 'Quantidade de Documentos no Processo: '.count($this->DocumentosProcesso);
            
            
            echo $this->partial('_partials/documentosprocesso.phtml', array('DocmDocumento' => $this->DocmDocumento, 
                                                                            'DocumentosProcesso' => $this->DocumentosProcesso, 
                                                                            'DocmDocumentoHistorico' => $this->DocmDocumentoHistorico,
                                                                            'MOFA_DH_FASE' => "",
                                                                            'Todos' => 0)); 
              
           // echo '<pre>';
            //var_dump($this->DocmDocumento);
            /*
            foreach ($this->DocumentosProcesso as $DocumentosProcesso):               
            ?>
           <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
               <div style="margin-left: 10px; margin-top: -14px; font-size: 12px; ">
                   <div style="margin-left: 10px; font-size: 12px; ">
                      <p>
                        <br/><b>Tipo:</b>
                            <?php echo $DocumentosProcesso["DTPD_NO_TIPO"] ;?>
                        <br/><b>Número:</b>
                            <?php echo $DocumentosProcesso["DOCM_NR_DOCUMENTO"] ;?>
                        <br/><b>Data de vinculação:</b>
                            <?php echo $DocumentosProcesso["DCPR_DH_VINCULACAO_DOC"] ;?>
                        <br/><b>Assunto:</b>
                            <?php echo $DocumentosProcesso["AQAT_DS_ATIVIDADE"] ;?>
                        <br/><b>Unidade Emissora:</b>
                            <?php echo $DocumentosProcesso["LOTA_SIGLA_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $DocumentosProcesso["LOTA_DSC_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $DocumentosProcesso["LOTA_COD_LOTACAO_EMISSORA"] ;?> -
                            <?php echo $DocumentosProcesso["FAMILIA_EMISSORA"] ;
                            
                            foreach ($this->DocmDocumentoHistorico as $historico){
                              if ($DocumentosProcesso["DCPR_DH_VINCULACAO_DOC"] == $historico["MOFA_DH_FASE"]){?>
                                <br/><b>Por:</b> <?php echo $historico["MOFA_CD_MATRICULA_NOME"];                            
                              }
                            }
                            ?>
                        <br/>
                     </p>
                    <a href="#" class="docs_pro proc_docs_icon_closed" value="<?php echo $this->escape( Zend_Json::encode($DocumentosProcesso) ); ?>"> Detalhe </a>
                   <a class="<?php if(is_null($DocumentosProcesso["DOCM_NR_DOCUMENTO_RED"])){
                                        echo 'alertaButton';
                                   }else{
                                       echo 'abrirAnexo';
                                   } ?>" 
                      target="_blank" 
                      title="<?php if(is_null($DocumentosProcesso["DOCM_NR_DOCUMENTO_RED"])){
                                      echo 'Sem Arquivo';
                                  }else{
                                      echo 'Abrir Documento';
                                  } ?>"
                      href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $this->DocmDocumento["DOCM_ID_DOCUMENTO"]; ?>/dcmto/<?php echo $DocumentosProcesso["DOCM_NR_DOCUMENTO_RED"]; ?> ">
                      <?php if(is_null($DocumentosProcesso["DOCM_NR_DOCUMENTO_RED"])){
                                    echo 'Sem Arquivo';
                            }else{
                                    echo 'Abrir';
                            } ?></a>
                        <?php 
                        $dadosExcluir["IDDOCUMENTOPRINCIPAL"] = $this->DocmDocumento["DOCM_ID_DOCUMENTO"];
                        $dadosExcluir["IDPROCESSO"] = $DocumentosProcesso["ID_PROCESSO"];
                        $dadosExcluir["IDDOCUMENTO"] = $DocumentosProcesso["DOCM_ID_DOCUMENTO"];
                        if(count($this->DocumentosProcesso) > 1){
                            //strtotime(), convertendo a data completa (YYYY-MM-DD HH:MM:SS) em inteiro, depois faz a comparação. 
                            $ultimaMovi = explode(' ',$this->DocmDocumento["MOVI_DH_ENCAMINHAMENTO"]);
                            $data = explode('/',$ultimaMovi[0]);
                            $ultimaMovi = $data[2].'-'.$data[1].'-'.$data[0].' '.$ultimaMovi[1];
                            $ultimaMovi = strtotime($ultimaMovi);
                            
                            $dhVinculacao = explode(' ',$DocumentosProcesso["DCPR_DH_VINCULACAO_DOC"]);
                            $data = explode('/',$dhVinculacao[0]);
                            $dhVinculacao = $data[2].'-'.$data[1].'-'.$data[0].' '.$dhVinculacao[1];
                            $dhVinculacao = strtotime($dhVinculacao);
                            
                            if ($dhVinculacao >= $ultimaMovi){ ?>
                                    <a href="#" class="removerDocsProc proc_docs_icon_closed" onclick="javascript: return false;" id="excluirdocspro" title="Remover documento do Processo" codigo="<?php echo $this->escape(Zend_Json::encode($dadosExcluir))?>"> Remover </a>
                            <?php 
                            }
                        }?>
                       </div>
           </fieldset>
                  
            <?php endforeach; */
            ?>
            </div>
           <?php } ?>
                    
        <div id="tabs-6">
            <?php 
            $ultima_movimentacao = NULL;
            $count = count($this->DocmDocumentoHistorico);
            for( $i = ($count-1); $i >= 0; $i-- ){
                if (
                        strcmp($ultima_movimentacao, $this->DocmDocumentoHistorico[$i]["MOFA_ID_MOVIMENTACAO"]) != 0
                ) {
                     $this->DocmDocumentoHistorico[$i]['MOSTRA_MOVIMENTACAO'] = true;
                }else{
                     $this->DocmDocumentoHistorico[$i]['MOSTRA_MOVIMENTACAO'] = false;
                }
                $ultima_movimentacao = $this->DocmDocumentoHistorico[$i]["MOFA_ID_MOVIMENTACAO"];
            }
            
            foreach ($this->DocmDocumentoHistorico as $historico):
             $numDocumento = $mapperDocumento->getNumeroDocumento($historico['DOCM_ID_DOCUMENTO'],$historico['MOFA_ID_MOVIMENTACAO'],$historico['MOFA_DH_FASE']);  
               if( $historico['MOSTRA_MOVIMENTACAO'] == true ){
                   ?> 
           <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
               <div style="margin-left: 10px; margin-top: 4px; font-size: 12px; ">
                    <b>Enviada em:&emsp;</b><?php echo $historico["MOFA_DH_FASE"]; ?>
                    <br/><b>Pela:</b>
                        <?php echo $historico["LOTA_SIGLA_LOTACAO_ORIGEM"].' - '.$historico["LOTA_DSC_LOTACAO_ORIGEM"]; ?> - <?php echo $historico["MOVI_CD_SECAO_UNID_ORIGEM"]; ?> - <?php echo $historico["FAMILIA_ORIGEM"]; ?>
                    <br/><b>Por:</b>
                        <?php echo $historico["ENCAMINHADOR"]; 
                        if ($this->tipodoc <> 'Minuta'){
                        ?>
                    <br/><b>Para:</b> 
                        <?php echo $historico["LOTA_SIGLA_LOTACAO_DESTINO"].' - '.$historico["LOTA_DSC_LOTACAO_DESTINO"]; ?> - <?php echo $historico["MODE_CD_SECAO_UNID_DESTINO"]; ?> - <?php echo $historico["FAMILIA_DESTINO"]; ?>
                        
                        <?php }
                        if(!is_null($historico["MODP_CD_MAT_PESSOA_DESTINO"])){ ?>
                            <br/><b>Caixa Pessoal de:</b> 
                            <?php echo $historico["MODP_CD_MAT_PESSOA_DESTINO"]; ?>
                        <?php }?>
                    <br/><b>Recebido em&emsp;<?php echo $historico["MODE_DH_RECEBIMENTO"]; ?>&emsp;por:</b> 
                        <?php echo $historico["RECEBEDOR"]; 
                        ?>                      
                    </div>
                
            </fieldset>
            
                <?php 
                
                
                
//                   Zend_Debug::dump($ultima_sgsecao,'$ultima_sgsecao ANTES');
//                Zend_Debug::dump($ultima_cdlotacao,'$ultima_cdlotacao ANTES');
//                
//                Zend_Debug::dump(strcmp($ultima_sgsecao, $historico["MODE_SG_SECAO_UNID_DESTINO"]));
//                Zend_Debug::dump(strcmp($ultima_cdlotacao, $historico["MODE_CD_SECAO_UNID_DESTINO"]));
//                
//                        if( 
//                                strcmp($ultima_sgsecao, $historico["MODE_SG_SECAO_UNID_DESTINO"]) != 0
//                                ||
//                                strcmp($ultima_cdlotacao, $historico["MODE_CD_SECAO_UNID_DESTINO"]) != 0
//                          ){
//                            $mostra_movimentacao = true;
//                            Zend_Debug::dump('mostra');
//                        }
//                        
//                        $ultima_sgsecao =  $historico["MODE_SG_SECAO_UNID_DESTINO"];
//                        $ultima_cdlotacao = $historico["MODE_CD_SECAO_UNID_DESTINO"];
//                        
//                        
//                        Zend_Debug::dump($ultima_sgsecao,'$ultima_sgsecao DEPOIS');
//                        Zend_Debug::dump($ultima_cdlotacao,'$ultima_cdlotacao DEPOIS');
//                   
//                       
//                            $mostra_movimentacao = false;
////                        if( $historico[FADM_ID_FASE] == 1010){
                
                
                }?>
           <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
               <div style="margin-left: 10px; margin-top: 4px; font-size: 12px; ">
                    <b>Fase:</b>
                    <?php echo str_replace(' SISAD', '',$historico["FADM_DS_FASE"]); ?>
                     em  
                    <?php echo $historico["MOFA_DH_FASE"]; 
                    if (($numDocumento)&& in_array($historico["FADM_ID_FASE"] , array(1023,1020))){ //ADIÇÃO DE DOCUMENTO A PROCESSO e AUTUAÇÃO DE PROCESSO ADMINISTRATIVO
                    ?> 
                    <br/><b>Nº documento:</b>
                    <?php echo implode(' , ', $numDocumento); }?>&emsp;
                    <br/><b>Por:</b>
                    <?php echo $historico["MOFA_CD_MATRICULA_NOME"]; ?>&emsp;
                    <br/><b>Descrição:</b>
                    <div style="margin-right: 10px;">
                    +  <?php echo $historico["MOFA_DS_COMPLEMENTO"]; ?> 
                    </div>
                    
                    <?php 
                    if ($this->tipodoc == 'Minuta'){?>
                     <?php 
                         foreach ($this->AnexAnexo as $semMetadados_p) {
                           if ($historico["MOFA_DH_FASE"] == $semMetadados_p["ANEX_DH_FASE"]){ 
                               $aux1 = explode('.',$semMetadados_p["ANEX_NM_ANEXO"]); ?>
                      <b>Anexos:</b>
                      <div style="margin-right: 10px;">
                             <a target="_blank" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $semMetadados_p['ANEX_ID_DOCUMENTO']; ?>/dcmto/<?php echo $semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"]; ?>/extensao/<?php echo $aux1[count($aux1) - 1]; ?>">Anexo </a>
                      </div>
                      <?php }
                         }?>
                      <?php
                    } ?>
                </div>
            </fieldset>
            
            <?php 
            endforeach;
            ?>
            </div>   
               
           <?php 
           if($this->AnexAnexo){
            ?>
           <div id="tabs-7">
            <?php 
               echo $totalAnexo;
               foreach ($this->AnexAnexo as $semMetadados_p) {
            ?>
                <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                <div style="margin-left: 10px; margin-top: -14px; font-size: 12px; ">
                <div style="margin-left: 10px; font-size: 12px; ">
                    <p>
                    <br/><b>Documento Sem Metadado:</b>
                    <br/><b>Tipo de Vinculo:</b> Anexado
                    <br/><b>Data de vinculação:</b>
                    <?php 
                    echo $semMetadados_p["ANEX_DH_FASE"]; ?>
                    </p>
                    <a class="<?php if(is_null($semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"])){
                                        echo 'alertaButton';
                                    }else{
                                        echo 'abrirAnexo';
                                    } 
                              ?>" 
                        target="_blank" 
                        title="<?php if(is_null($semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"])){
                                        echo 'Sem Arquivo';
                                    }else{
                                        echo 'Abrir Documento';
                                    } ?>" 
                        <?php $aux2 = explode('.', $semMetadados_p["ANEX_NM_ANEXO"]); ?>
                        href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $semMetadados_p["ANEX_ID_DOCUMENTO"]; ?>/dcmto/<?php echo $semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"]; ?> /extensao/<?php echo $aux2[count($aux2) - 1]; ?>">
                              <?php if(is_null($semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"])){
                                        echo 'Sem Arquivo';
                                    }else{
                                        echo 'Abrir';
                                    } ?></a>
                       </div>
                </fieldset>
            <?php  } ?>
            </div>
            <?php }?>
            
            <?php if ($mostraDespacho){ ?>
            <div id="tabs-8">
            <?php 
            $ultima_movimentacaoDes = NULL;
            $count = count($this->DocmDocumentoHistorico);
            ?>
               <p>

<!--                <a class="novoDespacho" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/despachodetalhe">Novo Despacho</a>-->
                <a class="novoDespacho" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/despacho/despachodetalhe/S">Novo Despacho</a>
<!--                 <input type="submit" class="ui-button ui-widget ui-state-default" title="Dar um despacho no Documento/Processo" name="acao" value="Novo Despacho"/>-->
               </p>
            <?php  
            
//            for( $i = ($count-1); $i >= 0; $i-- ){
//                //Zend_Debug::dump($this->DocmDocumentoHistorico[$i]["MOFA_ID_MOVIMENTACAO"]);
//                if (strcmp($ultima_movimentacaoDes, $this->DocmDocumentoHistorico[$i]["MOFA_ID_MOVIMENTACAO"]) != 0) {
//                     $this->DocmDocumentoHistorico[$i]['MOSTRA_MOVIMENTACAO'] = true;
//                      //echo "DocmDocumentoHistorico ".$this->DocmDocumentoHistorico[$i]['MOSTRA_MOVIMENTACAO'].'</br>';
//                }else{
//                     $this->DocmDocumentoHistorico[$i]['MOSTRA_MOVIMENTACAO'] = false;
//                }
//                $ultima_movimentacaoDes = $this->DocmDocumentoHistorico[$i]["MOFA_ID_MOVIMENTACAO"];
//            }
            
            //Zend_Debug::dump($this->DocmDocumentoHistorico); exit;
            
            foreach ($this->DocmDocumentoHistorico as $historico){
             //var_dump ("hist mov ".$historico['MOSTRA_MOVIMENTACAO']." fase ".$historico['FADM_ID_FASE'].'</br>');
             
              if( /*$historico['MOSTRA_MOVIMENTACAO'] == true &&*/ $historico['FADM_ID_FASE'] == 1040){
                   ?> 
                <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                    <div style="margin-left: 10px; margin-top: 4px; font-size: 12px; ">
                         <b>Fase:</b>
                         <?php echo str_replace(' SISAD', '',$historico["FADM_DS_FASE"]); ?>
                          em  
                         <?php echo $historico["MOFA_DH_FASE"]; ?> 
                         <br/><b>Por:</b>
                         <?php echo $historico["MOFA_CD_MATRICULA_NOME"]; ?>:&emsp;
                         <br/><b>Descrição:</b>
                         <div style="margin-right: 10px;">
                         +  <?php echo $historico["MOFA_DS_COMPLEMENTO"]; ?> 
                         </div>
                         <div>
                         <?php 
                         foreach ($this->AnexAnexo as $semMetadados_p) {
                           if ($historico["MOFA_DH_FASE"] == $semMetadados_p["ANEX_DH_FASE"]){ ?>
                             <?php $aux3 = explode('.', $semMetadados_p["ANEX_NM_ANEXO"]); ?>
                             <div style="margin-right: 10px;"> 
                             <a target="_blank" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $semMetadados_p['ANEX_ID_DOCUMENTO']; ?>/dcmto/<?php echo $semMetadados_p["ANEX_NR_DOCUMENTO_INTERNO"]; ?> /extensao/<?php echo $aux3[count($aux3) - 1]; ?>">Anexo </a>
                     </div>
                           <?php }
                         }?>
                         </div>
                     </div>
                 </fieldset>
            
            <?php }
                echo $this->partial('_partials/documentosprocesso.phtml', array(
                    'DocmDocumento' => $this->DocmDocumento, 
                    'DocumentosProcesso' => $this->DocumentosProcesso, 
                    'DocmDocumentoHistorico' => $this->DocmDocumentoHistorico,
                    'MOFA_DH_FASE' => $historico["MOFA_DH_FASE"],
                    'Todos' => 1
                    )
                );
                }
                
                ?>
            </div> 
            <?php
            }
            ?>
      </div>
            
 <?php if($this->DocumentosProcesso){ ?>
 <script type="text/javascript" >
     $(function() {
         var xhr_abrir_documentos_processo;
         var dialog_processo_documentos = '';

        $(".docs_pro").click(
            function(){
                var this_a = this;
                
                if(dialog_processo_documentos != ''){
                    //dialog_processo_documentos.html(' ');
                    dialog_processo_documentos.remove();
                }
                
                $("#dialog_proceso_container").html("<div id='dialog_processo_documentos'></div>");
                
                dialog_processo_documentos = $("#dialog_processo_documentos");
                dialog_processo_documentos.dialog({
                title    : 'Detalhe do documento do processo',
                autoOpen : false,
                modal    : false,
                show: 'fold',
                hide: 'fold',
                resizable: true,
                width: 800,
                height: 600,
                position: [300,140,0,0],
                buttons : {
                    Ok: function() {
                        $(this).dialog("close");
                    }
                }
                });
                
                if (xhr_abrir_documentos_processo) {
                    xhr_abrir_documentos_processo.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documentos_processo = $.ajax({
                    url: url,
                    dataType: 'html',
                    type: 'POST',
                    data: $(this).attr('value'),
                    contentType: 'application/json',
                    processData: false, 
                    beforeSend:function() {
                        dialog_processo_documentos.html('');
                    },
                    success: function(data) {
                        dialog_processo_documentos.html(data);

                       obj = dialog_processo_documentos.find("div#tabs")

                       $(obj).addClass('pro_docs_tabs');
                       $(".pro_docs_tabs" ).tabs();

                        dialog_processo_documentos.dialog("open");

                       $(this_a).addClass("ui-state-highlight");
                       $(this_a).button({
                            icons: {
                                primary: "ui-icon-check"
                            }
                        });

                    },
                    complete: function(){

                    },
                    error : function(){

                    }
                });
                
            });
        $('.removerDocsProc').click(function(){
            var excluirdados = $(this).attr('codigo');
            var xhr_excluirDocsPro;
            $("#divexcluirdocspro").dialog({
                title: 'Confirmar',
                modal:true,
                buttons: {
                    "Remover Documento": function() {
                        if (xhr_excluirDocsPro) {
                            xhr_excluirDocsPro.abort();
                        }
                        $( this ).dialog( "close" );

                        url = '<?php echo $this->baseUrl(); ?>/sisad/autuar/removerdocspro';
                        xhr_excluirDocsPro = $.ajax({
                            url: url,
                            dataType: 'html',
                            type: 'POST',
                            data: excluirdados,
                            contentType: 'application/json',
                            processData: false, 
                            beforeSend:function() {
                            },
                            success: function(data) {
                                var dados = $.parseJSON(data);
                                if( dados.Retorno === 1){
                                    var fieldsets = $('#tabs-5, #tabs-8').find('fieldset');
                                    fieldsets.each(
                                        function(){
                                            var fieldset = $(this);
                                            var removerDocsProc = fieldset.find('.removerDocsProc');
                                            var codigo = $(removerDocsProc).attr('codigo');
                                            //console.log(codigo);
                                            //console.log(excluirdados);
                                            if(excluirdados == codigo){
                                                fieldset.remove();
                                            }
                                            if(dados.DocsProcesso <= 1){
                                                removerDocsProc.remove();
                                            }
                                        }
                                    );
                                }else{
                                    alert('Erro 1: Não foi possível excluir documento do Processo.');
                                }
                            },
                            complete: function(){

                            },
                            error : function(){
                                alert('Erro 2: Não foi possível excluir documento do Processo.');
                            }
                        });
                    },
                    Cancelar: function() {
                        $( this ).dialog( "close" );
                    }
                }
            });
        })
        
        $('input[name=acao]').click(
         function(){
             var acao = this.value;
             var cx_unidade = $('form[name=cx_unid_entrada]');
             //console.log(cx_unidade);
             if(acao == 'Novo Despacho'){
                 cx_unidade.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/despacho');
                 
             }
         }
        );

     });
 </script>
 <div id="dialog_proceso_container">
 
 </div>
 <?php } ?>
