<?php 
    $prdc = new Application_Model_DbTable_SadTbPrdcProtDocProcesso();
    $processo = $prdc->getDadosEnderecados($this->DocmDocumento[DOCM_ID_DOCUMENTO]);
    $protocolado = $prdc->getDadosProtocolados($this->DocmDocumento[DOCM_ID_DOCUMENTO]);
?>

 <script type="text/javascript">
    $(function() {
            $( "#tabs" ).tabs();
            $( "#tabs" ).tabs("select",GLOBAL_indice_abas);
            $( "#tabs" ).tabs({
               select: function(event, ui) {
                    GLOBAL_indice_abas = ui.index;
               }
            });
            $( "#buttonsetmanifestacao" ).buttonset();
            $( ".abrirAnexo" ).button({
                    icons: {
                        primary: "ui-icon-folder-open"
                    }
                }).attr('style','width: auto; height: 26px;');
                $( ".alertaButton" ).button({
                    icons: {
                        primary: "ui-icon-alert"
                    }
                }).attr('style','width: auto; height: 26px;');
                
                $( ".proc_docs_icon_closed" ).button({
                    icons: {
                        primary: "ui-icon-radio-on"
                    }
                });
                
    });
 </script>
    <div id="tabs">
       <ul>
           <?php
            if(!$this->DocumentosProcesso){
           ?>
           <li><a href="#tabs-1">Documento</a></li>
           <?php 
             $mensagem = 'Usuário não tem vistas ao documento!';
           }else{?>
           <li><a href="#tabs-1">Processo</a></li>
           <?php 
           $mensagem = 'Usuário não tem vistas ao processo!';
           }
           if($this->vistas){?>
               <li><a href="#tabs-2">Vistas</a></li>
           <?php 
           }?>
	</ul>
        <div id="tabs-1">
            <table class="" style=" cursor: default;/*border: 1px solid red; border-collapse: separate; border-bottom: 1px solid red;*/" >
                <tr style="font-size: 12px; font-weight: bold;">
                        <td title="Tipo do documento" colspan="1">
                                <?php echo $this->DocmDocumento["DTPD_NO_TIPO"]?>
                        </td>
                        <td title="Número do documento">
                            Nº:&emsp;<?php echo $this->DocmDocumento["DOCM_NR_DOCUMENTO"]?>
                        </td>
                        <td title="Data e hora de cadastro">
                                D/H criação:&emsp;<?php echo $this->DocmDocumento["DOCM_DH_CADASTRO"]?>
                        </td>
                      
                </tr> 
                <tr>
                   <th >Confidencialidade</th>
                   <td title="Número do documento">
                           <?php echo $this->DocmDocumento["CONF_DS_CONFIDENCIALIDADE"]?>
                   </td>
                </tr>
            </table>
            <table>
               <tr style="font-size: 12px; font-weight: bold; color: red;">
                 <td>
                   <?php 
                   if ($this->DocmDocumento["CONF_DS_CONFIDENCIALIDADE"] == 'CORREGEDORIA'){
                      echo "Usuário não tem perfil de corregedoria!";
                   }else{
                      echo $mensagem;
                   }?>                   
                 </td>
               </tr>
            </table>
        </div>    
          <?php 
          if($this->vistas){ ?>   
             <div id="tabs-2">
                 <div id="mostra_vistas">
                     <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                         <legend>Quem tem vistas</legend>
                           <?php  foreach($this->vistas as $i){
                                    echo $i['NOME']."<br/>";
                                  }
                           ?>
                     </fieldset>
                 </div>
             </div>
       <?php } ?>
      </div>
