
<div id="container_pagination">
    <div>
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/add">Novo</a>
    </div>
    <?php if (count($this->data)): ?>
    <table class="grid">
        <thead>
            <tr>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/index/ordem/SINS_ID_INDICADOR/direcao/<?php echo $this->direcao ?> ">Editar<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/index/ordem/SINS_DS_INDICADOR/direcao/<?php echo $this->direcao ?> ">Nível de Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/index/ordem/SINS_DS_FORMULA_CALC/direcao/<?php echo $this->direcao ?> ">Fórmula de Cálculo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/index/ordem/SINS_SG_INDICADOR/direcao/<?php echo $this->direcao ?> ">Sigla<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td class="painel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/indicadornivelservico/edit/id/<?php echo $this->escape($data["SINS_ID_INDICADOR"]); ?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["SINS_DS_INDICADOR"]); ?></td>
                    <td><?php echo $this->escape($data["SINS_DS_FORMULA_CALC"]); ?></td>
                    <td><?php echo $this->escape($data["SINS_SG_INDICADOR"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7">Total: <?php echo $this->data->getTotalItemCount()     
                                        ////-- pagination
                                        //-- style
                                        //-- partial
                                        //-- data
                                        ?>
               </td>
            </tr>
            <tr>
                <td colspan="7">
                    <?php echo $this->paginationControl($this->data, null, null, null); ?>
                </td>
            </tr>
        </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>