<table class="legenda ui-widget-content" style="margin-top:1.4em">
             <thead>
                 <tr>
                     <th colspan="2">Legenda de Cores dos Status da Caixa de Atendimento</th>
                 </tr>
             </thead>
             <tbody>
                 <tr>
                     <td class="pedidoInformacao" title="Pedido de informação para solicitação"></td>
                     <td>Pedido de informação para solicitação de serviço</td>
                 </tr>
                 <tr>
                     <td class="respostaPedidoInformacao" title="Resposta ao pedido de informação para solicitação de serviço"></td>
                     <td>Resposta ao pedido de informação para solicitação de serviço</td>
                 </tr>
             </tbody>
 </table>