<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Esta é a <b>Caixa</b> de visualização da equipe que realiza os atendimentos presenciais nas unidades solicitantes.</p>
    <ul>
        <li>Os campos de título (nº. da solicitação, tempo real, nome solicitante etc.) permitem ordenação automática, bastando clicar no campo.</li>
        <li>A ordenação do sistema é da mais antiga para a mais nova.</li>
        <li>Para ver o conteúdo de uma solicitação, clica-se duas vezes onde o cursor estiver posicionado.</li>
        <li>O sistema mostrará a tela <b>Detalhe</b>, onde constam os dados do Documento (solicitação) e o seu Histórico.</li>
        <li>Poderá <b>Encaminhar</b> uma ou mais solicitações para: <i>outro nível de atendimento</i>, <i>grupo de atendimento</i> ou um <i>técnico determinado</i>.</li>
        <li>Clicando em <b>Baixar</b>, as solicitações podem ser baixadas individualmente ou por lote.</li>
        <li>Clicando em <b>Espera</b>, o sistema permite colocar uma ou várias solicitações em espera.</li>
        <li>Ao clicar no botão <b>Nova</b>, o sistema irá direcionar o cadastrante para a tela de cadastro de uma nova solicitação, permitindo a criação e o atendimento.</li>
    <br />
    <p><b>Atenção</b>: Não se esqueça de realizar as descrições quando solicitadas.</p>
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <a id="botao_ajuda_recolhe" href="#" ></a>
</div>
<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.cookie.js'));
?>

<script type="text/javascript">
                
    $(function() {


       
        botao_escolhe_caixa_recolhe_by_id =  $('#botao_escolhe_caixa_recolhe');
        botao_escolhe_caixa_recolhe_by_id.button({
            icons: {
                primary: "ui-icon-arrowthickstop-1-n"
            }
        }).attr('style','position: absolute; right: 0; width: 28px; height: 16px;')
        .attr('title','Recolher escolher nível');

        botao_escolhe_caixa_recolhe_by_id.click(
            function(){
                    $.cookie('mostrar_escolhe_caixa', 'nao');
                    $("#fieldset_escolhe_caixa").hide("blind");
                    $(this).hide("scale");
                    botao_escolhe_caixa_mostra_by_id.show("scale");
            }
        );
            
        botao_escolhe_caixa_mostra_by_id =  $('#botao_escolhe_caixa_mostra');
        botao_escolhe_caixa_mostra_by_id.button({
            icons: {
                primary: "ui-icon-arrowthickstop-1-s"
            }
        }).attr('style','position: absolute; right: 30px; width: 28px; height: 16px;')
        .attr('title','Mostrar escolher nível');

        botao_escolhe_caixa_mostra_by_id.click(
            function(){
                    $.cookie('mostrar_escolhe_caixa', 'sim');
                    $("#fieldset_escolhe_caixa").show("blind");
                    $(this).hide("scale");
                    botao_escolhe_caixa_recolhe_by_id.show("scale");
            }
        );
       if($.cookie('mostrar_escolhe_caixa') === 'nao'){
            $("#fieldset_escolhe_caixa").hide("");
            botao_escolhe_caixa_recolhe_by_id.hide("scale");
       }else{
            botao_escolhe_caixa_mostra_by_id.hide("scale");
       }

    });
</script>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input[type=checkbox]');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
            
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        ); 
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        $('input[name=acao]').click(
            function(){
                var acao = this.value;
                var formhelpdesk = $('form[name=helpdesk]');
                if(acao == 'Encaminhar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhar');
                }else if(acao == 'Baixar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/baixarcaixa');
                }else if(acao == 'Espera'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/esperacaixa');
                }else if(acao == 'Demandar ao TRF1'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/demandartrf');
                }else if(acao == 'Solicitar Informação'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/solicitarinformacao');
                }else if(acao == 'Trocar Serviço'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/trocarservico');
                }else if(acao == 'Excel'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesolexportacao/param/detalhexls');
                }else if(acao == 'PDF'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesolexportacao/param/detalhepdf');
                }
            }
        );
        $('form[name=helpdesk]').submit(
           function(){          
                var solictacaoSelecionada = $("input[type=checkbox][name=solicitacao[]]:checked").val();
                if (solictacaoSelecionada == undefined){ 
                    var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
                    $('#flashMessages').html(mensagem);
                    return false;
                }
           }
        );
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
                    autoOpen : false,
                    modal    : false,
                    show: 'fold',
                    hide: 'fold',
                    resizable: true,
                    width: 800,
                    position: [580,140,0,0],
                    buttons : {
                            Ok: function() {
                                    $(this).dialog("close");
                            }
                    }
       });
    });
</script>
<!--<div id="container_escolhe_caixa">
    <a id="botao_escolhe_caixa_recolhe" href="#"></a>
<a id="botao_escolhe_caixa_mostra"  href="#" ></a>
<fieldset id="fieldset_escolhe_caixa">
    <legend>Escolher Nível</legend>    
<?php// echo $this->form; ?>
    
</fieldset>
</div>-->
<form name="helpdesk" action="" method="post" >

    <?php if (count($this->data)): ?>
    <div class="containerpainel">
        <div class="painel">
<!--            <input type="submit" title="Encaminhar a solicitação" name="acao" value="Encaminhar"/>
            <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
            <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>-->
            <input type="submit" title="Pedir Informação para Solicitação de TI" name="acao" value="Solicitar Informação"/>
            <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
            <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
<!--            <input type="submit" title="Trocar o serviço da solicitação de TI" name="acao" value="Trocar Serviço"/>
            <input type="submit" title="Colocar a solicitação em espera" name="acao" value="Demandar ao TRF1"/>
            <input name="" type="button" onClick='javascript:location.href="<?php //echo $this->baseUrl(); ?>/sosti/helpdesk/atendimentointerno"' value="Nova">-->
        </div>
   </div>
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                    </th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhadasparatrf1/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhadasparatrf1/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhadasparatrf1/ordem/NOME_USARIO_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhadasparatrf1/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/atendimentosecoes/encaminhadasparatrf1/ordem/NOME_ATENDENTE/direcao/<?php echo $this->direcao ?> ">Atendente<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                </tr>
            </thead>
           <tbody>
                <?php $tempoInicial = new App_Sosti_TempoSla(); ?>
                <?php foreach($this->data as $data): ?>
                        <?php
                           $data['DADOS_INPUT'] = Zend_Json::encode($data);
                           $data['TEMPO_TRANSCORRIDO'] = $tempoInicial->tempoTotalHelpdesk($data['MOVIMENTACAO'], '', '07:00:00', '20:00:00');
                        ?>
                    <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                        <td <?php echo App_View_Helper_CorStatus::corCaixa($this->controller, $data["MOFA_ID_FASE"], $data["SESP_DH_LIMITE_ESP"], $tempoInicial->converteHorasFormatadasParaSegundos($data["TEMPO_TRANSCORRIDO"]), $data['ATENDENTE']); ?> >
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                        </td>
                        <td style="width: 25%"><?php echo  $this->escape($data["MASCARA_DOCM"]); ?></td>
<!--                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>-->
                        <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                        <td><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"].' - '.$data['NOME_USARIO_CADASTRO']); ?></td>
                        <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                        <td><?php echo $this->escape($data["ATENDENTE"]); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?></td>
                </tr>
                <tr>
                    <td colspan="7"><?php echo $this->paginationControl($this->data, null, null, null); ?></td>
                </tr>
            </tfoot>
        </table>
        <div class="painel">
        <!--            <input type="submit" title="Encaminhar a solicitação" name="acao" value="Encaminhar"/>
            <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
            <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>-->
            <input type="submit" title="Pedir Informação para Solicitação de TI" name="acao" value="Solicitar Informação"/>
            <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
            <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
        <!--            <input type="submit" title="Trocar o serviço da solicitação de TI" name="acao" value="Trocar Serviço"/>
            <input type="submit" title="Colocar a solicitação em espera" name="acao" value="Demandar ao TRF1"/>
            <input name="" type="button" onClick='javascript:location.href="<?php //echo $this->baseUrl(); ?>/sosti/helpdesk/atendimentointerno"' value="Nova">-->
        </div>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action; ?>"/> 
</form>
<div>
    <?php echo App_View_Helper_CorStatus::corLegenda(); ?>
</div>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
 <div id="dialog-documentos_conteudo"></div>
</div>