<?setlocale (LC_ALL, 'pt_BR.utf8');?>
<div style="width: 700px; margin: 0 auto; display: block;">
<p style="text-align:center">PODER JUDICIÁRIO<br /><strong><? echo $this->descrisaosecsubsec; ?></strong> - PCTT: <? echo $this->codpctt['AQVP_CD_PCTT']; ?></p><br />
<br />
<div style="width: 200px;"><p style="text-align:left"><strong>OFÍCIO/<? echo $this->siglaunidadeemissora; ?>/<? echo $this->data["DOCM_NR_DCMTO_USUARIO"];  ?></strong></div><div style="margin-left: 400px;margin-top: -35px;"><strong><? echo $this->cidade["CIDADE"] . ', '. date("d") . ' de ' . $this->mesportugues(date("F")) . ' de ' . date("Y") . '.'; ?></strong></p></div>
<br />
<br />
<div style="width: 500px;display: block;overflow: hidden; margin: 0 auto 0 auto;">
    <p style="text-align:justify"><? echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'. nl2br($this->data["DOCM_DS_ASSUNTO_DOC"]); ?></p>
</div>
<br />
<br />
<p style="text-align:center"><? echo $this->data["DOCM_CD_SAUDACAO"];?>,</p>
<br />
<p style="text-align:center"><strong><? echo $this->nome.'</strong>'?><br />
<strong><?  echo substr($this->data["DOCM_CD_LOTACAO_GERADORA"], 0,strlen($this->data["DOCM_CD_LOTACAO_GERADORA"])-4);  ?></strong></p>
<br />
<br />
<?
foreach ($this->partes as $partes) {
    echo '
    <p>Senhor(a)
    <br />
    ' . $partes["PARTE"] . '
    <br />
    ' . $partes["CIDADE"] . $partes["ENT_CID"];

    if($partes["CIDADE"] || $partes["ENT_CID"]){
        echo ' - ';
    }

    echo $partes["UF"] . $partes["ENT_UF"];

    echo '</p>';
}
?>
</div>