<script type="text/javascript">
    $(function() {
        $( ".editar" ).button({
                    icons: {
                        primary: "ui-icon-pencil"
                    }
        }).attr('style','width: 40px; height: 16px;');
        $( ".excluir" ).button({
                    icons: {
                        primary: "ui-icon-trash"
                    }
        }).attr('style','width: 40px; height: 16px;');
     });
</script> 

<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/guardiao/acao/add">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th>Alterar</th>
            <th>Excluir</th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_ID_PAPEL/direcao/<?php// echo $this->direcao ?> ">-->ACAO<!--<span class="<?php //echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_NM_PAPEL/direcao/<?php //echo $this->direcao ?> ">-->CONTROLE<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_NM_PAPEL/direcao/<?php //echo $this->direcao ?> ">-->MODULO<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th><!--<a href="guardiao/papel/index/ordem/PAPL_NM_PAPEL/direcao/<?php //echo $this->direcao ?> ">-->SISTEMA<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl(); ?>/guardiao/acao/edit/id/<?php echo $data['ACAO_ID_ACAO_SISTEMA'];?>"><span class="editar"></span></a</td>
            <td><a href="<?php echo $this->baseUrl(); ?>/guardiao/acao/del/id/<?php echo $data['ACAO_ID_ACAO_SISTEMA'];?>"><span class="excluir"></span></a></td>
            <td><?php echo $this->escape($data['ACAO_NM_ACAO_SISTEMA']) ?></td>
            <td><?php echo $this->escape($data['CTRL_NM_CONTROLE_SISTEMA']) ?></td>
            <td><?php echo $this->escape($data['MODL_NM_MODULO']) ?></td>
            <td><?php echo $this->escape($data['MODL_NM_SISTEMA']) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="12">Total: <?php /*echo $this->data->getTotalItemCount()*/?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,'ordem'=> $this->ordem))?>
<?php else:?>
    <div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/guardiao/acao/add">Novo</a></div>
    <p>Não existem registros</p>
<?php endif;?>