
<div id="container_pagination">
    <div>
        <a  class="novo" href="sosti/metaalcancada/form">Novo</a>
    </div>
    <?php if (count($this->data)): ?>
    <table class="grid">
        <thead>
            <tr>
                <th ><a  href="sosti/metaalcancada/index/ordem/SMAN_ID_INDICADOR/direcao/<?php echo $this->direcao ?> ">Editar<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/metaalcancada/index/ordem/SMAN_ID_META/direcao/<?php echo $this->direcao ?> ">Nível de Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/metaalcancada/index/ordem/SMAN_NR_INICIAL_META/direcao/<?php echo $this->direcao ?> ">Nível de Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td class="painel"><a title="Editar" class="editar" href="sosti/indicadornivelservico/form/id/<?php echo $this->escape($data["SMAN_ID_INDICADOR"]); ?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["SMAN_ID_META"]); ?></td>
                    <td><?php echo $this->escape($data["SMAN_NR_INICIAL_META"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
        </tfoot>
    </table>
<?php echo $this->paginationControl($this->data, null, null, null)
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
</div>