<script type="text/javascript">
$(function() {
$(".membros" ).button();
});
</script>

<div class="painel">
<!--        <a  class="novo" href="<//?php echo $this->baseUrl(); ?>/sisad/distribuicao/add">Novo</a>-->
    </div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr> 
<!--                <th >Excluir</th>-->
                <th ><a  href="#">Ação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/list/ordem/ORGJ_CD_ORGAO_JULGADOR/direcao/<?php echo $this->direcao ?> ">Código<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/list/ordem/ORGJ_NM_ORGAO_JULGADOR/direcao/<?php echo $this->direcao ?> ">Descrição<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/list/ordem/ORGJ_DS_ORGAO_JULGADOR/direcao/<?php echo $this->direcao ?> ">Descrição Abreviada<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td >
                        <a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/edit/id/<?php echo $this->escape($data["ORGJ_CD_ORGAO_JULGADOR"]); ?>" >Editar</a>
                    <?php
                        $orgao = $this->escape($data["ORGJ_CD_ORGAO_JULGADOR"]);
                        if ($orgao == 1000 || $orgao == 2000 || $orgao == 3000) {
                        ?>
                        <a title="Membros" class="membros" href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/membrosdesembargadores/orgao/<?php echo $this->escape($data["ORGJ_CD_ORGAO_JULGADOR"]); ?>" >Membros</a>                  
                        <?php
                        }else{
                        ?>
                        <a title="Membros" class="membros" href="<?php echo $this->baseUrl(); ?>/sisad/distribuicao/membrosservidores/orgao/<?php echo $this->escape($data["ORGJ_CD_ORGAO_JULGADOR"]); ?>" >Membros</a>                  
                        <?php
                        }
                        ?>
                    </td>
                    
                    <!--
                    /*
                    * Se o id do orgao for 1000 ou 2000 ou 3000 efetuar busca em 
                    * SAD_TB_CDPA_CONT_DIST_PROC_ADM
                    * 
                    * Os demais efetuar busca em SAD_TB_CCPA_CONT_DIST_COMISSAO
                    */
                    -->
                        
<!--                    <td ><a title="Excluir" class="excluir" href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/del/id/<?php echo $this->escape($data["TPPR_ID_TIPO_PROCESSO"]); ?>" >Excluir</a></td>-->
                    <td><?php echo $this->escape($data["ORGJ_CD_ORGAO_JULGADOR"]); ?></td>
                    <td><?php echo $this->escape($data["ORGJ_NM_ORGAO_JULGADOR"]); ?></td>
                    <td><?php echo $this->escape($data["ORGJ_DS_ORGAO_JULGADOR"]); ?></td>
                    
                </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>
</form>
