<script type="text/javascript">
    var GLOBAL_indice_abas = 0;
    var xhr_abrir_documento;

    var grid_tbody_tr;
    $(function() {

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.dblclick(
                function() {
                    var this_tr = $(this);
                    var input_check_box = $(this).find('input');

                    grid_tbody_tr.each(
                            function() {
                                var this_tr = $(this);
                                var input_check_box = $(this).find('input');

                                input_check_box.removeAttr('checked');
                                this_tr.removeAttr('marcado');
                                this_tr.removeClass('hover');
                            }
                    );

                    var div_dialog_by_id = $("#dialog-documentos_detalhe");
                    value_input_check_box = input_check_box.val();
                    input_check_box.attr('checked', 'checked');
                    this_tr.attr('marcado', 'marcado');
                    this_tr.addClass('hover');

                    if (xhr_abrir_documento) {
                        xhr_abrir_documento.abort();
                    }

                    url = base_url + '/sosti/detalhesolicitacao/detalhesol';
                    xhr_abrir_documento = $.ajax({
                        url: url,
                        dataType: 'html',
                        type: 'POST',
                        data: value_input_check_box,
                        contentType: 'application/json',
                        processData: false,
                        beforeSend: function() {
                            if (!div_dialog_by_id.dialog("isOpen")) {
                                div_dialog_by_id.dialog("open");
                            }
                        },
                        success: function(data) {
                            div_dialog_by_id.html(data);

                        },
                        complete: function() {

                        },
                        error: function() {

                        }
                    });
                }
        );

        $("#dialog-documentos_detalhe").dialog({
            title: 'Detalhe',
            autoOpen: false,
            modal: false,
            show: 'fold',
            hide: 'fold',
            resizable: true,
            width: 800,
            position: [580, 140, 0, 0],
            buttons: {
                Ok: function() {
                    $(this).dialog("close");
                }
            }
        });
        var form_valido = false;
        $('input[name=acao]').click(
                function() {
                    var acao = this.value;
                    var formhelpdesk = $('form[name=relatorios]');
                    if (acao == 'Liberar') {
                        formhelpdesk.attr('action', base_url + '/sosti/faturamento/liberarafericao');
                    }
                }
        );
    });
    $(function() {
    var dates = $( "#DATA_ENTREGA" ).datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
        'Outubro','Novembro','Dezembro'],
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
        nextText: 'Próximo',
        prevText: 'Anterior',
        changeMonth: true,
        numberOfMonths: 1,
        changeMonth: true,
        changeYear: true,
        changeMonth: true,
        onSelect: function( selectedDate ) {
            var option = this.id == "DATA_ENTREGA" ? "minDate" : "maxDate",
            instance = $( this ).data( "datepicker" );
            date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
            dates.not( this ).datepicker( "option", option, date );
        }
    });
});
</script>
<script>
    function verificaNumero(e) {
        if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
            return false;
        }
    }

    $(document).ready(function() {
        $("#PFAF_NR_LOTE").keypress(verificaNumero);

    });
</script>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<form name="relatorios" action="" method="post" >
    <?php
    if (count($this->dados)):
        ?>
        <fieldset>
            <table>
                <tr>
                    <td><label>PF Bruto DSV</label></td>
                    <td><?php echo $this->total['DSV'][7]['PF_BRUTO'] ?></td>
                    <td><label>PF Liquido DSV</label></td>
                    <td><?php echo $this->total['DSV'][7]['PF_LIQUIDO'] ?></td>
                </tr>
                <tr>
                    <td><label>N° do Lote</label><br /><small>Apenas números</small></td>
                    <td><input type="text" name="PFAF_NR_LOTE" id="PFAF_NR_LOTE" maxlength="6"/></td>
                    <td><label>Data Prevista para Entrega</label></td>
                    <td><input type="text" name="PFAF_DH_PREVISAO_RETORNO_LOTE" id="DATA_ENTREGA"/></td>
                </tr>
                <tr>
                    <td><label>Data da Retirada</label></td>
                    <td>
                        <?php
                        $data = new Application_Model_DbTable_Dual();
                        echo $data->sysdateDb();
                        ?>
                    </td>
                </tr>
            </table>
            <div class="painel" style="float: bottom;">
                <input type="submit" title="Liberar lote para aferição" name="acao" value="Liberar Lote"/>
            </div>
        </fieldset>
        <div id="container_pagination">
            <table class="grid">
                <thead>
                    <tr>
                        <th rowspan="2"></th> 
                        <th rowspan="2">Nr do E-Sosti</th> 
                        <th rowspan="2">Status</th> 
                        <th rowspan="2">DH Entrada Caixa</th> 
                        <th rowspan="2">Atendente</th> 
                        <th rowspan="2">DH Baixa</th> 
                        <th colspan="3">Desenvolvimento</th> 
                        <th colspan="3">Aferição</th> 
                        <th rowspan="2">Status TRF</th> 
                    </tr>
                    <tr>
                        <th>Status</th> 
                        <th>PF Bruto</th> 
                        <th>PF Liquido</th> 
                        <th>Status</th> 
                        <th>PF Bruto</th> 
                        <th>PF Liquido</th> 
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->dados as $dados) {
                        $dados["CONTROLLER"] = 'faturamento';
                        $dados["ACTION"] = 'relatorios';
                        $dados['DADOS_INPUT'] = Zend_Json::encode($dados);
                        ?>
                        <tr name="rowList" value="<?php echo $this->escape($dados["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td>
                                <input class="nav_grid_check_box nav_check_boxes"  id="<?php echo $this->escape($dados["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]" type="hidden" value="<?php echo $this->escape($dados["DADOS_INPUT"]); ?>"/>
                            </td> 
                            <td><?php echo $dados["DOCM_NR_DOCUMENTO"]; ?></td>
                            <td><?php
                                if ($dados["STSA_ID_TIPO_SAT"] == NULL) {
                                    echo 'Baixada';
                                } else if ($dados["STSA_ID_TIPO_SAT"] != 6) {
                                    echo 'Avaliada';
                                } else if ($dados["STSA_ID_TIPO_SAT"] == 6) {
                                    echo 'Recusada';
                                }
                                ?>
                            </td>
                            <td><?php echo $dados["ENTRADA_CAIXA"]; ?></td>
                            <td><?php echo $dados["ATENDENTE"]; ?></td>
                            <td><?php echo $dados["DATA_HORA_BAIXA"]; ?></td>
                            <td><?php echo $dados["SCTA_DS_STATUS_DSV"]; ?></td>
                            <td><?php echo floatval(str_replace(',', '.', $dados["PFDS_QT_PF_BRUTO"])); ?></td>
                            <td><?php echo floatval(str_replace(',', '.', $dados["PFDS_QT_PF_LIQUIDO"])); ?></td>
                            <td><?php echo $dados["SCTA_DS_STATUS_AFE"]; ?></td>
                            <td><?php echo floatval(str_replace(',', '.', $dados["PFAF_QT_PF_BRUTO"])); ?></td>
                            <td><?php echo floatval(str_replace(',', '.', $dados["PFAF_QT_PF_LIQUIDO"])); ?></td>
                            <td><?php echo $dados["SCTA_DS_STATUS_TRF"]; ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="15">Total: <?php echo count($this->dados) ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        <?php else: ?>
            <?php if ($this->ultima_pesq): ?>
                <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
            <?php else: ?>
                <p><br/>Não existem registros</p>
            <?php endif; ?>   
        <?php endif; ?>
    </div>
</form>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
    <div id="dialog-documentos_conteudo"></div>
</div>