
<div >
Total de Registros: <?php echo count($this->resultado); ?>
    
       <div>
            <table id="principal" style="border: 1px solid #ccc; margin-top: 10px;" >
                <thead>
                    <tr style="background-color: gainsboro;">
                        <th style="font-weight: bold;"> N. Processo Principal</td>
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Tipo da Juntada </td>
                        <th style="font-weight: bold;"> Data Juntada </td>
                        <th style="font-weight: bold;"> Respons&aacute;vel Juntada </td>
                        <th style="font-weight: bold;"> Respons&aacute;vel Exclus&atilde;o Juntada </td>
                        <th style="font-weight: bold;"> Dt. Exclus&atilde;o Juntada </td>
                    </tr>
                </thead>
            <tbody>
            <?php  foreach($this->resultado as $data): ?>
                    <tr style="border: 1px solid #C3C3C3;">
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['MASC_NR_DOCUMENTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['MASC_NR_DOCUMENTO_FILHO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['TIPO_JUNTADA']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['DH_JUNTADA']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['RESPONSAVEL_JUNTADA']; ?> </td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['RESPONSAVEL_EXCLUSAO']; ?> </td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['DH_EXCLUSAO']; ?> </td>
                    </tr>
             <?php   endforeach; ?>
            </tbody>
            </table>
       </div>
    <br/>
</div>    
   

   