<?php $this->inlineScript()->appendFile($this->baseUrl() . '/js/jquery-ui-timepicker-addon.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/combobox_app_jquery.js' , 'text/javascript');
      $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/sisad/relatorioprocesso.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/datepicker.js', 'text/javascript');
      $this->headLink()->prependStylesheet($this->baseUrl() . '/css/relatorioProcesso.css' );
?>

<script type="text/javascript">
$(function() { 
    
   $("#pesquisaProcessos").submit( function(){
           if( $("#TRF1_SECAO").val() === "0"  ){
               alert('É necessario escolher TRF ou Seção.');
               return false;
           }
           if( $("#SECAO_SUBSECAO").val() === ""  ){
               alert('É necessario escolher uma Seção ou Subseção.');
               return false;
           }
           return true;
});
});

</script>
<div class="help" id="pesq_div" class="span-23" >
    <?php echo $this->form; ?>
</div>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>

<?php if (count($this->resultado) > 0): ?>

<div id="container_pagination">
   
        <div class="painel" id="">
            <input type="button" title="Gerar PDF do Relatório" name="acao" value="PDF" id="pdf" onclick="javascript: location.href='<?php echo $this->baseUrl(); ?>/sisad/relatorioprocesso/apensadosanexadospdf/';" >      
        </div>
    
       <div class="cabecalho">
                <div class="orgao"> 
                   <h3> <strong> <?php echo $this->title; ?> </strong> </h3>
                </div>
                <?php echo $this->partial('_partials/relatorioprocesso/cabecalhoRelatorio.phtml', array(
                                           'cabecalho' => $this->cabecalho )); ?>
        </div>
        
        <div class="dados-resultado">
            <table id="dados-resultado">
                <thead>
                    <tr>
                        <th style="font-weight: bold;"> N. Processo Principal</td>
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Tipo da Juntada </td>
                        <th style="font-weight: bold;"> Data Juntada </td>
                        <th style="font-weight: bold;"> Respons&aacute;vel Juntada</td>
                        <th style="font-weight: bold;"> Respons&aacute;vel Exclus&atilde;o Juntada </td>
                        <th style="font-weight: bold;"> Dt. Exclus&atilde;o Juntada </td>
                    </tr>
                </thead>
            <tbody>
            <?php  
                   foreach($this->resultado as $data):  
                      ?>
                    <tr>
                        <td title="<?php echo $data['NR_PROCESSO']; ?>"> <?php echo $data['MASC_NR_DOCUMENTO']; ?></td>
                        <td title="<?php echo $data['NR_PROCESSO_FILHO']; ?>"> <?php echo $data['MASC_NR_DOCUMENTO_FILHO'] ; ?></td>
                        <td title="Tipo da Juntada"> <?php echo $data['TIPO_JUNTADA']; ?></td>
                        <td title="Data da Juntada"> <?php echo $data['DH_JUNTADA']; ?></td>
                        <td title="Respons&aacute;vel Juntada"> <?php echo $data['RESPONSAVEL_JUNTADA']; ?></td>
                        <td title="Respons&aacute;vel Exclus&atilde;o Juntada"> <?php echo $data['RESPONSAVEL_EXCLUSAO']; ?> </td>
                        <td title="Data Exclus&atilde;o Juntada"> <?php echo $data['DH_EXCLUSAO']; ?> </td>
                    </tr>
             <?php  
                    
                   endforeach; ?>
            </tbody>
            </table>
        </div>
        
        <div class="span-24">
        <?php echo $this->paginationControl($this->resultado, null, null, null); ?>
        </div>
        
        <div class="totais span-24">
            <strong> TOTAL DE PROCESSOS APENSADOS / ANEXADOS / VINCULADOS:  <?php echo $this->resultado->getTotalItemCount(); ?> </strong> <br />
        </div>
</div>
<?php endif; ?>
     
   