
<div >
Total de Registros: <?php echo count($this->resultado); ?>
    
       <div>
            <table id="principal" style="border: 1px solid #ccc; margin-top: 10px;" >
                <thead>
                    <tr style="background-color: gainsboro;">
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Data Arquivamento </td>
                        <th style="font-weight: bold;"> Assunto </td>
                        <th style="font-weight: bold;"> Tempo Guarda Corrente </td>
                        <th style="font-weight: bold;"> Dt. Envio Arquivo Definitivo </td>
                        <th style="font-weight: bold;"> Dt. Provável Descarte </td>
                        <th style="font-weight: bold;"> Partes </td>
                    </tr>
                </thead>
            <tbody>
            <?php  foreach($this->resultado as $data): ?>
                    <tr style="border: 1px solid #C3C3C3;">
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['MASC_NR_DOCUMENTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['DH_ARQUIVAMENTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['ASSUNTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['TEMPO_GUARDA_CORRENTE']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['TEMPO_GUARDA_CORRENTE']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['DH_PROVAVEL_DESCARTE']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['PARTE']; ?></td>
                    </tr>
             <?php   endforeach; ?>
            </tbody>
            </table>
       </div>
    <br/>
</div>    
    
   