               
<div >
Total de Registros: <?php echo count($this->resultado); ?>
    
       <div>
            <table id="principal" style="border: 1px solid #ccc; margin-top: 10px;" >
                <thead>
                    <tr style="background-color: gainsboro;">
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Data Autuação </td>
                        <th style="font-weight: bold;"> Unidade </td>
                        <th style="font-weight: bold;"> Assunto </td>
                        <th style="font-weight: bold;"> Partes </td>
                    </tr>
                </thead>
            <tbody>
            <?php  foreach($this->resultado as $data): ?>
                    <tr style="border: 1px solid #C3C3C3;">
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['MASC_NR_DOCUMENTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['DH_AUTUACAO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['UNIDADE_AUTUADORA']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['ASSUNTO']; ?></td>
                        <td style="border: 1px solid #C3C3C3;"> <?php echo $data['PARTE']; ?></td>
                    </tr>
             <?php   endforeach; ?>
            </tbody>
            </table>
       </div>
    <br/>
</div>    
    <?php echo $this->partial('_partials/relatorioprocesso/mostraSomatorioPorUnidade.phtml', array(
                                         'somatorioUnidades' => $this->somatorioUnidades )); ?>

   
