<?php $this->inlineScript()->appendFile($this->baseUrl() . '/js/jquery-ui-timepicker-addon.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/combobox_app_jquery.js' , 'text/javascript');
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/sisad/relatorioprocesso.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/datepicker.js', 'text/javascript');
      $this->headLink()->prependStylesheet($this->baseUrl() . '/css/relatorioProcesso.css' );
?>
<script type="text/javascript">
 $(function() {
        
       $("#pesquisaProcessos").submit( function(){
               if( $("#TRF1_SECAO").val() === "0"  ){
                   alert('É necessário escolher TRF ou Seção.');
                   return false;
               }
               if( $("#SECAO_SUBSECAO").val() === ""  ){
                   alert('É necessário escolher uma Seção ou Subseção.');
                   return false;
               }
               if( $("#DOCM_CD_LOTACAO_GERADORA").val() === ""  ){
                   alert('É necessário escolher uma Unidade.');
                   return false;
               }
               return true;
               
            });
 });

</script>
<div class="help" id="pesq_div" class="span-23" >
    <?php echo $this->form; ?>
</div>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>

<?php if (count($this->resultado) > 0): ?>

<div id="container_pagination">
   
        <div class="painel" id="">
            <input type="button" title="Gerar PDF do Relatório" name="acao" value="PDF" id="pdf" onclick="javascript: location.href='<?php echo $this->baseUrl(); ?>/sisad/relatorioprocesso/encaminhadosunidadepdf/';" >      
        </div>
    
        <div class="cabecalho">
                <div class="orgao"> 
                   <h3> <strong> <?php echo $this->title; ?> </strong> </h3>
                </div>
                <?php echo $this->partial('_partials/relatorioprocesso/cabecalhoRelatorio.phtml', array(
                                           'cabecalho' => $this->cabecalho )); ?>
        </div>
        
        <div class="dados-resultado">
            <table id="dados-resultado">
                <thead>
                    <tr>
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Data Encaminhamento </td>
                        <th style="font-weight: bold;"> Assunto </td>
                        <th style="font-weight: bold;"> Destino </td>
                        <th style="font-weight: bold;"> Local </td>
                        <th style="font-weight: bold;"> Responsável </td>
                        <th style="font-weight: bold;"> Partes </td>
                    </tr>
                </thead>
            <tbody>
            <?php  foreach($this->resultado as $data):  ?>
                    <tr>
                        <td title="<?php echo $data['NR_PROCESSO']; ?>"> <?php echo $data['MASC_NR_DOCUMENTO']; ?></td>
                        <td title="Data do Encaminhamento"> <?php echo $data['DH_ENCAMINHAMENTO']; ?></td>
                        <td title="Assunto"> <?php echo $data['ASSUNTO']; ?></td>
                        <td title="Destino"> <?php echo $data['SIGLA_LOTACAO_DESTINO']; ?></td>
                        <td title="Localização"> <?php echo $data['LOCAL']; ?></td>
                        <td title="Responsável"> <?php echo $data['RESPONSAVEL']; ?></td>
                        <td title="Parte"> <?php echo $data['PARTE']; ?></td>
                    </tr>
             <?php   endforeach; ?>
            </tbody>
            </table>
        </div>
        
        <div class="span-24">
        <?php echo $this->paginationControl($this->resultado, null, null, null); ?>
        </div>
        
        <div class="totais span-24">
            <strong> TOTAL DE PROCESSOS ENCAMINHADOS: <?php echo $this->resultado->getTotalItemCount(); ?> </strong> <br />
        </div>
</div>
<?php endif; ?>
     
   