 <?php
// Framework CSS
    $this->headLink()
        ->prependStylesheet($this->baseUrl().'/js/farbtastic/farbtastic.css','screen, projection');
// Library JS
  $this->HeadScript()
        ->appendFile($this->baseUrl().'/js/farbtastic/farbtastic.js');
    ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
 
 <script type="text/javascript">
   $(document).ready(function() {
     $('#colorpicker').farbtastic('#color').removeClass('x-form-text').css('background-image','none');
     
     
   });
 </script>
 <form action='nova'  method="POST">
<?php 
    echo $this->form->getElement('CATE_ID_CATEGORIA');
    echo $this->form->getElement('CATE_NM_CATEGORIA');
    echo $this->form->getElement('CATE_SG_SECAO_CATEGORIA');
    echo $this->form->getElement('CATE_CD_LOTACAO_CATEGORIA');
    echo $this->form->getElement('CATE_CD_MATRICULA_CATEGORIA');
    echo $this->form->getElement('CATE_DS_OBSERVACAO');
    echo $this->form->getElement('CATE_IC_ATIVO');
?>
 <input type="text" id="color" name="CATE_DS_DESCRICAO_COR" value="<?php echo $this->cor; ?>" style="background-image: none"/>
<div id="colorpicker"></div>
<?php     
    echo $this->form->getElement('Salvar');
?>
 </form>