<?php
$nomeCampoDespesa = $this->campo;
?>
<script type="text/javascript">
$(function() {
    var despesa = $("#<?php echo $nomeCampoDespesa; ?>").val();
    
    if ( despesa != '') {
        url = '<?php echo $this->baseUrl(); ?>/orcamento/movimentacaocred/ajaxretornadespesa/cod/' + despesa;
        $.ajax({
            url: url,
            dataType: 'html',
            type: 'GET',
            contentType: 'html',
            processData: false,
            success: function(data) {
                $('#<?php echo $nomeCampoDespesa; ?>').after('<p class="description" id="<?php echo $nomeCampoDespesa; ?>_DESCRICAO"></p>');
                $('#<?php echo $nomeCampoDespesa; ?>_DESCRICAO').html(data);
                var erro = $('#<?php echo $nomeCampoDespesa; ?>_DESCRICAO > fieldset').hasClass('invalida');
                if (erro == true) {
                    $('#<?php echo $nomeCampoDespesa; ?>').css('border-color', 'red');
                    $('#<?php echo $nomeCampoDespesa; ?>').after('<p class="description" id="<?php echo $nomeCampoDespesa; ?>_DESCRICAO"  style="color: red">Despesa não encontrada</p>');
                }
            }
        });
    }

    $("#<?php echo $nomeCampoDespesa; ?>").blur(function() {
        $('#<?php echo $nomeCampoDespesa; ?>').css('border-color', '#ccc');
        $('#<?php echo $nomeCampoDespesa; ?>_DESCRICAO').remove();
        $('p[id=<?php echo $nomeCampoDespesa; ?>_DESCRICAO]').remove();
        var despesa = $("#<?php echo $nomeCampoDespesa; ?>").val();
        if (!isNaN(despesa)) {
            if (despesa != '') {
                var description = $('.description').length;
                if(description == 2){
                 $('.description:first').remove();   
                }
                url = '<?php echo $this->baseUrl(); ?>/orcamento/movimentacaocred/ajaxretornadespesa/cod/' + despesa;
                $.ajax({
                    url: url,
                    dataType: 'html',
                    type: 'GET',
                    contentType: 'html',
                    processData: false,
                    success: function(data) {
                        $('#<?php echo $nomeCampoDespesa; ?>').after('<p class="description" id="<?php echo $nomeCampoDespesa; ?>_DESCRICAO"></p>');
                        $('#<?php echo $nomeCampoDespesa; ?>_DESCRICAO').html(data);
                        var erro = $('#<?php echo $nomeCampoDespesa; ?>_DESCRICAO > fieldset').hasClass('invalida');
                        if (erro == true) {
                            $('#<?php echo $nomeCampoDespesa; ?>').css('border-color', 'red');
                            $('#<?php echo $nomeCampoDespesa; ?>').after('<p class="description" id="<?php echo $nomeCampoDespesa; ?>_DESCRICAO" style="color: red">Despesa não encontrada</p>');
                        }
                    }
                });
            } else {
                $('#<?php echo $nomeCampoDespesa; ?>').css('border-color', 'red');
            }
        } else {
            $('#<?php echo $nomeCampoDespesa; ?>').css('border-color', 'red');
            $('#<?php echo $nomeCampoDespesa; ?>').after('<p class="description" id="<?php echo $nomeCampoDespesa; ?>_DESCRICAO" style="color: red">Informe um número de despesa válido.</p>');
        }

    });
});
</script>