<script type="text/javascript">
    $(function() {

        $('.description').first().hide();
        var url = '';
        var radio = $('input:radio[name=TIPO_PROCESSO][checked]').val();
        if (radio != undefined) {
            if (radio == 1) {
                var despesa = $('#REQV_NR_DESPESA').val();
                url = "ajaxprocessofisico/despesa/" + despesa;
            } else {
                url = "ajaxprocessodigital";
            }
            $("#REQV_DS_PROCESSO").autocomplete({
                source: base_url + '/orcamento/rdo/' + url,
                minLength: 5,
                delay: 100,
                select: function(event, ui) {
                    event.preventDefault();
                    $("#REQV_DS_PROCESSO").val(ui.item.label);
                },
                change: function(event, ui) {
                    event.preventDefault();
                    $("#REQV_DS_PROCESSO").val(ui.item.label);
                }
            });
        } else {
            $('#REQV_DS_PROCESSO').attr('readonly', 'readonly')
        }

        $('input:radio[name=TIPO_PROCESSO]').change(function() {
            $('#REQV_DS_PROCESSO').removeAttr('readonly');
            $("#REQV_DS_PROCESSO").val('');
            var radio = $(":input[type=radio][checked]").val();
            var despesa = $('#REQV_NR_DESPESA').val();
            var tipo = this.value;
            if (!despesa) {
                $("#REQV_DS_PROCESSO").val('');
                $('#REQV_DS_PROCESSO').attr('readonly', 'readonly')
                $('input:radio[name=TIPO_PROCESSO]').removeAttr('checked');
                $('#REQV_NR_DESPESA').css('border-color', 'red');
                $('.description').first().css('color', 'red').show();
            } else {
                //$('.description').first().hide();
                $('#REQV_NR_DESPESA').css('border-color', '#ccc');
            }
            if (tipo == 1) {
                url = "ajaxprocessofisico/despesa/" + despesa;
            } else {
                url = "ajaxprocessodigital";
            }
            $("#REQV_DS_PROCESSO").autocomplete({
                source: base_url + '/orcamento/rdo/' + url,
                minLength: 5,
                delay: 100,
                select: function(event, ui) {
                    event.preventDefault();
                    $('#REQV_DS_PROCESSO').val(ui.item.label);
                },
                change: function(event, ui) {
                    event.preventDefault();
                    $('#REQV_DS_PROCESSO').val(ui.item.label);
                }
            });
        });


        var despesa = $("#REQV_NR_DESPESA").val();

        if ( despesa != '') {
            url = '<?php echo $this->baseUrl(); ?>/orcamento/movimentacaocred/ajaxretornadespesa/cod/' + despesa;
            $.ajax({
                url: url,
                dataType: 'html',
                type: 'GET',
                contentType: 'html',
                processData: false,
                success: function(data) {
                    $('#REQV_NR_DESPESA').after('<p class="description" id="REQV_NR_DESPESA_DESCRICAO"></p>');
                    $('#REQV_NR_DESPESA_DESCRICAO').html(data);
                    var erro = $('#REQV_NR_DESPESA_DESCRICAO > fieldset').hasClass('invalida');
                    if (erro == true) {
                        $('#REQV_NR_DESPESA').css('border-color', 'red');
                        $('#REQV_NR_DESPESA').after('<p class="description" id="REQV_NR_DESPESA_DESCRICAO"  style="color: red">Despesa não encontrada</p>');
                    }
                }
            });
        }

        $("#REQV_NR_DESPESA").blur(function() {
            $('#REQV_NR_DESPESA').css('border-color', '#ccc');
            $('#REQV_NR_DESPESA_DESCRICAO').remove();
            $('p[id=REQV_NR_DESPESA_DESCRICAO]').remove();
            var despesa = $("#REQV_NR_DESPESA").val();
            if (!isNaN(despesa)) {
                if (despesa != '') {
                    var description = $('.description').length;
                    if(description == 2){
                     $('.description:first').remove();   
                    }
                    url = '<?php echo $this->baseUrl(); ?>/orcamento/movimentacaocred/ajaxretornadespesa/cod/' + despesa;
                    $.ajax({
                        url: url,
                        dataType: 'html',
                        type: 'GET',
                        contentType: 'html',
                        processData: false,
                        success: function(data) {
                            $('#REQV_NR_DESPESA').after('<p class="description" id="REQV_NR_DESPESA_DESCRICAO"></p>');
                            $('#REQV_NR_DESPESA_DESCRICAO').html(data);
                            var erro = $('#REQV_NR_DESPESA_DESCRICAO > fieldset').hasClass('invalida');
                            if (erro == true) {
                                $('#REQV_NR_DESPESA').css('border-color', 'red');
                                $('#REQV_NR_DESPESA').after('<p class="description" id="REQV_NR_DESPESA_DESCRICAO" style="color: red">Despesa não encontrada</p>');
                            }
                        }
                    });
                } else {
                    $('#REQV_NR_DESPESA').css('border-color', 'red');
                }
            } else {
                $('#REQV_NR_DESPESA').css('border-color', 'red');
                $('#REQV_NR_DESPESA').after('<p class="description" id="REQV_NR_DESPESA_DESCRICAO" style="color: red">Informe um número de despesa válido.</p>');
            }

        });
    });
</script>
