<?php
/**
 * @category	TRF1
 * @package	_partials
 * @copyright	Copyright (c) 2010-2014 Tribunal Regional Federal BRZ (http://www.trf1.jus.br)
 * @author	Anderson Sathler M. Ribeiro [asathler@gmail.com]
 * @license	FREE, keep original copyrights
 * @version	controlada pelo SVN
 * 
 * @return	string							Código HTML que gera a tela de exibição de detalhe de um único registro
 * 
 * @param	array		dados				Contém o array com registros.
 * Nesse caso, a query deve conter aliás para os nomes dos campos utilizados.
 * 
 * @example	echo $this->partial('_partials/tela_detalhe_crud.phtml',
 * 									array(	'msgAjuda'	=> $this->msgAjuda,
 * 											'msgInfo'	=> $this->msgInfo,
 * 											'dados'		=> $this->dados
 * 										)
 * 									);
 */
echo $this->partial('_partials/ajuda_informacao.phtml', array('msgAjuda' => $this->msgAjuda,
    'msgInfo' => $this->msgInfo));

$valor = new Trf1_Orcamento_Valor();
$sinalMoeda = true;

?>

<br />
<div id="detalheTabs" class="tabs">
    <ul>
        <li><a href="#detalhe">Detalhes do registro</a></li>
    </ul>

    <div id="detalhe">
        <p>
            <b>Ano:</b> <?php echo $this->dados['DESP_AA_DESPESA']; ?> <br />
            <b>Seção:</b> <?php echo $this->dados['DESP_CD_UG']; ?> <br />
            <b>Despesa:</b> <?php echo $this->dados['NR_DESPESA']; ?> <br />
            <b>Descrição:</b> <?php echo $this->dados['DESP_DS_ADICIONAL']; ?> <br />
            <b>PTRES:</b> <?php echo $this->dados['DESP_CD_PT_RESUMIDO']; ?> <br />
            <b>Natureza da Despesa:</b> <?php echo $this->dados['DESP_CD_ELEMENTO_DESPESA_SUB']; ?> <br />
            <!-- <b>Nota de Empenho:</b> <?php echo $this->dados['NOEM_CD_NOTA_EMPENHO']; ?> <br /> -->
            <!-- <b>Descriçao da NE:</b> <?php echo $this->dados['NOEM_DS_OBSERVACAO']; ?> <br /> -->
            <b>Valor Empenhado:</b> <?php echo $valor->retornaNumeroFormatadoValor( $this->escape( $this->dados['VR_EMPENHADO'])); ?> <br />
            <b>Valor:</b> <?php echo $valor->retornaNumeroFormatadoValor( $this->escape( $this->dados['VR_EXECUTADO'])); ?> <br />
            <b>Saldo da NE:</b> <?php echo $valor->retornaNumeroFormatadoValor( $this->escape( $this->dados['VR_A_EXECUTAR'])); ?> <br />
        </p>

    </div>
</div>