<?php
echo $this->partial('_partials/ajuda_informacao.phtml', array('msgAjuda' => $this->msgAjuda,
    'msgInfo' => $this->msgInfo));

$valor = new Trf1_Orcamento_Valor();
$sinalMoeda = true;
?>

<!--transforma chave do array em números.-->
<?php
$chaveNc = array_values($this->dados);
?>

<!--usa o numero da NC que está na primeira chave do array para ser o id da div,
desta forma o id fica igual o link que está na tag "tab" no arquivo excluir.phtml.-->
<div id="<?php echo $chaveNc[0] ?>">

    <p>

        <?php
        foreach ($this->dados as $campoNome => $campoConteudo) {

            $conteudo = $this->escape($campoConteudo);

            if (is_numeric(strpos(trim(strtolower($campoNome)), 'valor'))) {
                // Formata o campo valor
                $conteudo = $valor->retornaNumeroFormatadoValor($campoConteudo, $sinalMoeda);
            }

            // Monta cada linha a ser exibida
            $linha = "";
            $linha .= "<strong>";
            $linha .= $this->escape($campoNome);
            $linha .= ":</strong> ";
            $linha .= $conteudo;
            $linha .= "<br />";

            // Apresenta uma linha com cada campo e seu conteúdo
            echo $linha . PHP_EOL;
        }
        ?>

    </p>

</div>