<?php
/**
 * @category	TRF1
 * @package		_partials
 * @copyright	Copyright (c) 2010-2014 Tribunal Regional Federal BRZ (http://www.trf1.jus.br)
 * @author		Anderson Sathler M. Ribeiro [asathler@gmail.com]
 * @license		FREE, keep original copyrights
 * @version		controlada pelo SVN
 * 
 * @return		string							Código HTML que gera a tela de exclusão de registros
 * 
 * @deprecated	string		campos				Nessa versão, tanto a variável $campos quanto $dados são aceitas;
 * Sendo que $campos tem preferência.
 * @deprecated	array		campos				...
 * @deprecated	string		campoDescricao		...
 * @deprecated	array		campoValor			...
 * 
 * @param		array		codigo				Código da chave primária a ser excluída
 * @param		array		dados				Contém o array com registros.
 * Nesse caso, a query deve conter aliás para os nomes dos campos utilizados.
 * 
 * @example		echo	$this->partial('_partials/tela_exclusao.phtml', array(	'msgAjuda'	=> $this->msgAjuda,
 * 																				'msgInfo'	=> $this->msgInfo,
 * 																				'codigo'	=> $this->codigo,
 * 																				'dados'		=> $this->dados,
 * 																				[@deprecated 
 * 																				'campos'	=> array(	array(	'campoDescricao'	=> 'UG para travamento de projeção',
 * 																												'campoValor'		=> $this->travaprojecao['TRVP_CD_UG']),
 * 																										array(	'campoDescricao'	=> 'Data Início',
 * 																												'campoValor'		=> $this->travaprojecao['TRVP_DT_INICIO']),
 * 																										array(	'campoDescricao'	=> 'Data Fim',
 * 																												'campoValor'		=> $this->travaprojecao['TRVP_DT_FIM'])
 * 																									)
 * 																				]
 * 										);
 */

$valor = new Trf1_Orcamento_Valor();
$sinalMoeda = true;

// Define opções
$opcoes = null;
$opcoes [ 'msgAjuda' ] = $this->msgAjuda;
$opcoes [ 'msgInfo' ] = $this->msgInfo;

echo $this->partial ( '_partials/ajuda_informacao.phtml', $opcoes );

// Define informações sobre a ação desta partial
$acao = $this->acao;

// Excluir
$pergunta [ 'excluir' ] = Orcamento_Business_Dados::MSG_EXCLUIR_PERGUNTA;
$verbo [ 'excluir' ] = 'excluídos';
$tabs [ 'excluir' ] = 'exclusaoTabs';

// Restaurar
$pergunta [ 'restaurar' ] = Orcamento_Business_Dados::MSG_RESTAURAR_PERGUNTA;
$verbo [ 'restaurar' ] = 'restaurados';
$tabs [ 'restaurar' ] = 'restauracaoTabs';

if (! $acao) {
    $acao = Orcamento_Business_Dados::ACTION_EXCLUIR;
}

$pergunta = $pergunta [ $acao ];
$verbo = $verbo [ $acao ];
$tabs = $tabs [ $acao ];

// Define chave primária ou composta, conforme a quantidade de campos passados em $this->codigo
$qtdeCamposChave = count ( $this->codigo );
?>

<br />
<h3> <?php echo $pergunta; ?> </h3>

<div id="<?php echo $tabs; ?>" class="tabs">
	<ul>
		<li><a href="#resumo">Resumo</a></li>
		<?php
		foreach ( $this->dados as $registro ) {
			$campos = '';
			for($i = 0; $i < $qtdeCamposChave; $i ++) {
				$campos .= $registro [$this->codigo [$i]] . '-';
				$campos = str_replace('/', '-', $campos);
			}
			$campos = substr ( $campos, 0, - 1 );
			$campos = str_replace(' ', '-', $campos);
			
			echo '<li><a href="#' . $campos . '">' . $campos . '</a></li>' . PHP_EOL;
		}
		?>
	</ul>

	<div id="resumo">
		<h3>Códigos a serem <?php echo $verbo; ?></h3>
		
		<?php
		foreach ( $this->dados as $registro ) {
			$campos = '';
			for($i = 0; $i < $qtdeCamposChave; $i ++) {
				$campos .= $registro [$this->codigo [$i]] . '-';
				$campos = str_replace('/', '-', $campos);
			}
			$campos = substr ( $campos, 0, - 1 );
			
			echo 'Código: ' . $campos . '<br />' . PHP_EOL;
		}
		?>
	</div>
	
	<?php
	foreach ( $this->dados as $registro ) {
		$campos = '';
		for($i = 0; $i < $qtdeCamposChave; $i ++) {
			$campos .= $registro [$this->codigo [$i]] . '-';
			$campos = str_replace('/', '-', $campos);
			
			unset ( $registro [$this->codigo [$i]] );
		}
		$campos = substr ( $campos, 0, - 1 );
		$campos = str_replace(' ', '-', $campos);
		
		// Monta a exibição de cada registro
		echo '<div id="' . $campos . '">' . PHP_EOL;
		
		foreach ( $registro as $campoNome => $campoConteudo ) {
            $conteudo = $this->escape ( $campoConteudo );
            
            if ( is_numeric (strpos(trim(strtolower($campoNome)), 'valor') ) ) {
                // Formata o campo valor
                $conteudo = $valor->retornaNumeroFormatadoValor ( $campoConteudo, $sinalMoeda );
            }
            
            // Monta cada linha a ser exibida
            $linha = "";
            $linha .= "<strong>";
            $linha .= $this->escape ( $campoNome );
            $linha .= ":</strong> ";
            $linha .= $conteudo;
            $linha .= "<br />";
            
            // Apresenta uma linha com cada campo e seu conteúdo
            echo $linha . PHP_EOL;
        }
        
        echo "</div>" . PHP_EOL . PHP_EOL;
	}
	?>
</div>
<br />

<?php
// Define opções
$opcoes = null;
$opcoes [ 'codigo' ] = $this->codigo;
$opcoes [ 'acao' ] = $acao;

echo $this->partial ( '_partials/botoes_exclusao.phtml', $opcoes );