 <script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input[type=checkbox]');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                  grid_tbody_tr.each(
                    function(){
                        var this_tr = $(this);
                        var input_check_box = $(this).find('input');
                        
                        input_check_box.removeAttr('checked');
                        this_tr.removeAttr('marcado');
                        this_tr.removeClass('hover');
                    }
                  );
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    if(! div_dialog_by_id.dialog( "isOpen" )){
                        div_dialog_by_id.dialog("open");
                    }
                },
                success: function(data) {
                    div_dialog_by_id.html(data);
                    
                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        ); 
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        var form_valido = false;
        $('input[name=acao]').click(
            function(){
                var acao = this.value;
                var formhelpdesk = $('form[name=helpdesk]');
                if(acao == 'Encaminhar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/encaminhar');
                }else if(acao == 'Baixar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/baixarcaixa');
                }else if(acao == 'Espera'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/esperacaixa');
                }else if(acao == 'Solicitar Informação'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/solicitarinformacao');
                }else if(acao == 'Trocar Serviço'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/trocarservico');
                }else if(acao == 'Parecer'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/parecer');
                }else if(acao == 'Inserir não Conformidade'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/inserirconformidade');
                }else if(acao == 'Remover Conformidade'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/removerconformidade');
                }else if(acao == 'Gerenciar Extensão de Prazo'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/autorizarextensaoprazo');
                }
            }
        );
        
            
            $('form[name=helpdesk]').submit(
               function(){          
                    
                   if(form_valido){
                       return true;
                   }
                   
                    var solictacaoSelecionada = $("input[type=checkbox][name=solicitacao[]]:checked").val();
                    if (solictacaoSelecionada == undefined){ 
                        var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
                        $('#flashMessages').html(mensagem);
                        return false;
                    }else{
                        return true;
                    }
                    
               }
            );
        
       function getselectedSolicitacoes(elemento)
{
           				elemento.each(
        				 function(i,element) 
        				 {
        				     element = $(this);
        				     if($(element).is(':checked')){
								if($(element).attr('id')!= 'input_check_all_grid')
								{
									//var valor = $(element).val();
									//alert(valor);
									
								    var obj = $.parseJSON(element.val());
								    var docmrs = obj.DOCM_NR_DOCUMENTO;
								    var docID =  obj.SSOL_ID_DOCUMENTO;
								    var movimentacaoID = obj.MOFA_ID_MOVIMENTACAO;
            						docsSelected += docmrs + "<br>";
	               					docsSelectedPost += docmrs+":"+ docID+":"+movimentacaoID+ ","; // numero do documento : id do documento : id da movimentação.
								}
        				     }
        				 });
           				
						console.log(docsSelectedPost);
    					$('#documentosSelecionados').val(docsSelectedPost);
						$('#docsSelecionados').html(docsSelected);
}
       
       
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
                    autoOpen : false,
                    modal    : false,
                    show: 'fold',
                    hide: 'fold',
                    resizable: true,
                    width: 800,
                    position: [580,140,0,0],
                    buttons : {
                            Ok: function() {
                                    $(this).dialog("close");
                            }
                    }
       });

       $('#Salvar').click(function(){
			$('#frmConformidade').submit();
           })
    });
</script>

<script type="text/javascript">
$(function() {
    $("#DOCM_CD_MATRICULA_CADASTRO").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxnomesolicitante",
        minLength: 3,
        delay: 300,
        select: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val(ui.item.value);
                            }
                },
        change: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val(ui.item.value);
                            }
        }

    }).keyup(
            function(){
                if(this.value == ""){
                    $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val('');
                }
    });

    $("#SSOL_CD_MATRICULA_ATENDENTE").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxnomesolicitante",
        minLength: 3,
        delay: 300,
        select: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val(ui.item.value);
                            }
                },
        change: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val(ui.item.value);
                            }
        }

    }).keyup(
            function(){
                if(this.value == ""){
                    $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val('');
                }
    });

    $("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxunidade",
        minLength: 3,
        delay: 500,
        select: function( event, ui ) {
                                if( ui.item.value != null ){ 
                                    $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val(ui.item.value);
                                }
                },
        change: function( event, ui ) {
                                if( ui.item.value != null ){  
                                     $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val(ui.item.value);
                                }
        }
    }).keyup(
            function(){
                if(this.value == ""){
                    $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val('');
                }
    });



    $('#pesquisar')
        .click(function() {
                pesq_div = $("#pesq_div");

                if(pesq_div.css('display') == "none"){
                    pesq_div.show('');
                }else{
                    pesq_div.hide('');
                }
        });

    $('#Filtrar').button();

    $("#botao_ajuda_recolhe").click(
       function(){
            $("#pesq_div").hide();
            $("#pesquisar").show();
    });
});
</script>
<script type="text/javascript">
            $(function() {
                var dates = $( "#DATA_INICIAL, #DATA_FINAL" ).datepicker({
			dateFormat: 'dd/mm/yy',
			dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
			dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
					     'Outubro','Novembro','Dezembro'],
 			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
 			nextText: 'Próximo',
 		        prevText: 'Anterior',
			changeMonth: true,
			numberOfMonths: 1,
			changeMonth: true,
			changeYear: true,
			changeMonth: true,
			onSelect: function( selectedDate ) {
				var option = this.id == "DATA_INICIAL" ? "minDate" : "maxDate",
					instance = $( this ).data( "datepicker" );
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
			}
		});
                
                var dates_cadastro = $( "#DATA_INICIAL_CADASTRO, #DATA_FINAL_CADASTRO" ).datepicker({
			dateFormat: 'dd/mm/yy',
			dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
			dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
					     'Outubro','Novembro','Dezembro'],
 			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
 			nextText: 'Próximo',
 		        prevText: 'Anterior',
			changeMonth: true,
			numberOfMonths: 1,
			changeMonth: true,
			changeYear: true,
			changeMonth: true,
			onSelect: function( selectedDate ) {
				var option = this.id == "DATA_INICIAL_CADASTRO" ? "minDate" : "maxDate",
					instance = $( this ).data( "datepicker" );
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates_cadastro.not( this ).datepicker( "option", option, date );
			}
		});
	    }); 
</script>
<script type="text/javascript">
$(function() {
            $('#SGRS_ID_GRUPO').change(
                function(){
                    $("#SSER_ID_SERVICO").removeAttr('disabled');
                    $.ajax({
                        url: '<?php echo $this->baseUrl(); ?>/sosti/solicitacao/ajaxservicos',
                        dataType: 'html',
                        type: 'POST',
                        data: this.value,
                        contentType: 'application/json',
                        processData: false,
                      beforeSend:function() {
                          $("#SSER_ID_SERVICO").removeClass('erroInputSelect');
                          $("#SSER_ID_SERVICO").html('');
                          $("#SSER_ID_SERVICO").addClass('carregandoInputSelect');
                      },
                      success: function(data) {
                          $("#SSER_ID_SERVICO").html(data);
                          $("#SSER_ID_SERVICO").removeClass('carregandoInputSelect');
                          $("#SSER_ID_SERVICO").focus();
                      },
                      error: function(){
                          $("#SSER_ID_SERVICO").removeClass('x-form-field');
                          $("#SSER_ID_SERVICO").val('Erro ao carregar.');
                          $("#SSER_ID_SERVICO").addClass('erroInputSelect');
                          $("#SSER_ID_SERVICO").html('<option>Erro ao carregar</option>');
                      }
                    });  
                }
            );
            $("#SSOL_NR_TOMBO-label").hide();
            $("#SSOL_NR_TOMBO-element").hide();
            $("#DE_MAT-label").hide();
            $("#DE_MAT-element").hide();
            
            
            $('#SSER_ID_SERVICO').change(
                function(){
                    var unidade = $(this).val().split('|')[1];
                    if(unidade == 'S'){
                        $("#SSOL_NR_TOMBO-label").show();
                        $("#SSOL_NR_TOMBO-element").show();
                        $("#DE_MAT-label").show();
                        $("#DE_MAT-element").show();
                    }else{
                        $("#SSOL_NR_TOMBO-label").hide();
                        $("#SSOL_NR_TOMBO-element").hide();
                        $("#DE_MAT-label").hide();
                        $("#DE_MAT-element").hide();
                    }
                }
            );
            $('#SSOL_NR_TOMBO').focusout(
                function(){
                    $.ajax({
                      //url: "sosti/solicitacao/ajaxdesctombo/id/"+this.value,
                      url: "ajaxdesctombo/id/"+this.value,
                      beforeSend:function() {
                          $("#DE_MAT").removeClass('erroInputTextArea');
                          $("#DE_MAT").val('');
                          $("#DE_MAT").removeClass('x-form-field');
                          $("#DE_MAT").addClass('carregandoTextArea');
                      },
                      success: function(data) {
                          $("#DE_MAT").val(data);
                          $("#DE_MAT").removeClass('carregandoInputTextArea');
                          $("#DE_MAT").addClass('x-form-field');
                          $("#DE_MAT").focus();
                      },
                      error: function(){
                          $("#DE_MAT").removeClass('carregandoInputTextArea');
                          $("#DE_MAT").removeClass('x-form-field');
                          $("#DE_MAT").val('Erro ao carregar.');
                          $("#DE_MAT").addClass('erroInputTextArea');
                      }
                    });  
                }
            );
            
            if( $('#SERVICO-nomecompleto').is(':checked') == true){
                
                $('#SSER_DS_SERVICO').hide();
                $('#SSER_DS_SERVICO-label').hide();
                $('#SSER_DS_SERVICO').attr('disabled', 'disabled');
                
                $('#SSER_ID_SERVICO').show();
                $('#SSER_ID_SERVICO-label').show();
                $('#SSER_ID_SERVICO').removeAttr('disabled');
                var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
                description_obj.show();
               
                
            }else if ( $('#SERVICO-partenome').is(':checked') == true) {
                
                
                $('#SSER_ID_SERVICO').hide();
                $('#SSER_ID_SERVICO-label').hide();
                $('#SSER_ID_SERVICO').attr('disabled', 'disabled');
                var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
                description_obj.hide();
                
                $('#SSER_DS_SERVICO').show();
                $('#SSER_DS_SERVICO-label').show();
                $('#SSER_DS_SERVICO').removeAttr('disabled');
                
            
                
            } 

            
            $('input[type=radio][name=SERVICO]').click(
                function(){
                if(this.value == 'nomecompleto'){
                    
                    $('#SSER_DS_SERVICO').hide();
                    $('#SSER_DS_SERVICO').val("");
                    $('#SSER_DS_SERVICO-label').hide();
                    $('#SSER_DS_SERVICO').attr('disabled', 'disabled');

                    $('#SSER_ID_SERVICO').show();
                    $('#SSER_ID_SERVICO-label').show();
                    $('#SSER_ID_SERVICO').removeAttr('disabled');
                    var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
                    description_obj.show();
                    
                }else if (this.value == 'partenome'){
                    $('#SSER_ID_SERVICO').hide();
                    $('#SSER_ID_SERVICO').val("");
                    $('#SSER_ID_SERVICO-label').hide();
                    $('#SSER_ID_SERVICO').attr('disabled', 'disabled');
                    var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
                    description_obj.hide();

                    $('#SSER_DS_SERVICO').show();
                    $('#SSER_DS_SERVICO-label').show();
                    $('#SSER_DS_SERVICO').removeAttr('disabled');
                }
                //});    
           });
			//MOSTRA A DIV DAS NÃO CONFORMIDADE
			$('.conformidadeshowDescricao').hover(function(){
				var currentID = $(this).attr('id'); //ID DA TD
				var conteudo =  $('#tooltip_'+ currentID).html();
				if(conteudo != ''){
				$('#tooltip_'+currentID).css('visibility','visible');
				}
				});
			$('.conformidadeshowDescricao').mouseleave(function(){
			    var currentID = $(this).attr('id');
			    
			    $('#tooltip_'+currentID).css('visibility','hidden');
				;})
            //ACOES  DO BOTAO SUBMIT LOCALIZADO NO TOPO DO FORMULÁRIO 
            $('#Filtrar2').click(
                function(){
				$('#filtroForm').submit();
                }
                );
			
            $('#Filtrar2').hover(
				function(){
				    $('#Filtrar2').addClass('ui-state-hover');
					},
				function(){
					 $('#Filtrar2').removeClass('ui-state-hover');
						}
                    );
            
            //FIM
	});
 </script>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<form name="gerenciar" action="" method="post" class="painel" >
    <input type="submit" title="Gerenciar Extensão de Prazo" name="gerenciar" value="Extensão de Prazo"/>
    <input type="submit" title="Gerenciar Não Conformidade" name="gerenciar" value="Não Conformidade" />
</form>
<fieldset>
    <legend>Filtro da Caixa</legend>
    <div class="painel">
        <div class="painel" >
            <input type="button" title="Último Filtro" name="acao" value="Filtro" id="pesquisar">
            <a title="Novo Filtro" name="acao" value="Filtrar" id="ultimo_filtro" href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/nova/1" >Limpar Filtro/Retirar Filtro</a>
            &emsp;&emsp;<span style="color: #2E4557;"><strong><?php if( $this->ultima_pesq == true) echo "Filtro Ativo"; else echo "Filtro Inativo"; ?></strong></span>
        </div> 


    </div>
    <div id="pesq_div"  style="display: none;" ><br>
   <input type="button" value="Filtrar" id="Filtrar2" class="ui-button ui-widget ui-state-default ui-corner-all "> 
        <?php echo $this->form; ?>
        <span id="botao_ajuda_recolhe" ></span>
    </div>
</fieldset>
<form name="helpdesk" action="" method="post" >
    <div class="painel">
        <?php if ($this->gerenciar == "Extensão de Prazo"): ?>
            <input type="submit" title="Gerenciar Extensão de Prazo" name="acao" value="Gerenciar Extensão de Prazo"/>
        <?php else: ?>
            <input type="submit" title="Inserir Conformidade" name="acao" value="Inserir não Conformidade" id="conformidade"/>
            <input type="submit" title="Remover Conformidade" name="acao" value="Remover Conformidade" id="removerconformidade"/>
        <?php endif; ?>
    </div>
    <?php if (count($this->data)): ?>
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th><input type="checkbox" name="input_check_all_grid" id="check_all" /></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/ordem/ORDEM_MOV/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <?php if ($this->gerenciar == "Não Conformidade"): ?>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/ordem/NOME_ATENDENTE/direcao/<?php echo $this->direcao ?> ">Não Conformidades<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <?php else: ?>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/gestaodemandasinfraestrutura/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Extensão de Prazo Solicitada<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <?php endif; ?>
               </tr>
            </thead>
                <?php 
                $tempoInicial = new App_Sosti_TempoSla();
		$SosTbMvcoConformidade = new  Application_Model_DbTable_SosTbMvcoConformidade();
		?>
            <tbody>
	        <?php
                    foreach($this->data as $data): 
                ?>
                <?php
                    $descricaoNaoConformidade = "";
                        	$naoConformidadesDescricao = $SosTbMvcoConformidade->getNaoConformidadesDescricao($data['MOFA_ID_MOVIMENTACAO']);//get descrição das conformidades
                           //monta listga da descrição das não conformidades se tiver mais que uma.
                           foreach ($naoConformidadesDescricao as $value) {
                           	
                           	$descricaoNaoConformidade .= "<li> " . $value['SOTC_DS_CONFORMIDADE']."</li>"; 
                           	
                           }
                        	
                        	$data['DADOS_INPUT'] = Zend_Json::encode($data);
                           
                           $data['TEMPO_TRANSCORRIDO'] = $tempoInicial->tempoTotalHelpdesk($data['MOVIMENTACAO'], '', '07:00:00', '20:00:00');
                        ?>
                    <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td <?php echo ($data["MOFA_ID_FASE"] == 1024)?('style="background-color:#666666;" title="Pedido de informação para solicitação de TI."'):('');
                                      echo ($data["SESP_DH_LIMITE_ESP"])?('style="background-color:#0099FF;" title="Solicitação colocada em espera!"'):('');
                                      echo ($data["TEMPO_TOTAL"] > 120)?('style="background-color:#EE4115;" title="Solicitação com o tempo de atendimento ultrapassado!"'):('');  
                                      echo ($data["MOFA_ID_FASE"] == 1019)?('style="background-color:#E88400;" title="Solicitação recusada!"'):(''); ?> >
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                        </td>
                        <td><?php echo $this->escape($data["MASCARA_DOCM"]); ?></td>
                        <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                        <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                        <?php if ($this->gerenciar == "Não Conformidade"): ?>
                            <td class="conformidadeshowDescricao" id="<?php echo $this->escape($data['SSOL_ID_DOCUMENTO']);?>"> <ul><?php echo $descricaoNaoConformidade;?></ul></td>
                        <?php else: ?>
                            <td><?php echo $this->escape($data['SSPA_DT_PRAZO']);?></td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else:?>
        
                <?php if($this->ultima_pesq): ?>
                    <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
                            <?php else: ?>
                            <p><br/>Não existem registros</p>
                <?php endif; ?>
                    
                    
    <?php endif; ?>
    </div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action; ?>"/> 
</form>
<div>
    <?php echo App_View_Helper_CorStatus::corLegenda(); ?>
</div>
<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
    <div id="conformidadeDIV" style = "display: none;">
    <fieldset>
    <legend style='font-weight:normal'>Documento(s) Selecionado(s)</legend>
    <div id="docsSelecionados"></div>
    </fieldset>
    <?php echo $this->formConformidade; ?>
    </div>
</div>