
<div id="container_pagination" style="margin-top: 35px;">

    <?php if (count($this->data) > 0): ?>
        <table class="grid">
            <thead>
                <tr>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/LSBK_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Devolver<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Solicitação<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/LSBK_NR_TOMBO/direcao/<?php echo $this->direcao ?> ">Número do Tombo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/LSBK_TP_TOMBO/direcao/<?php echo $this->direcao ?> "> Tombo Tipo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/LSBK_DT_EMPRESTIMO/direcao/<?php echo $this->direcao ?> ">Data Empréstimo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackuplist/ordem/LSBK_CD_MAT_EMPRESTIMO/direcao/<?php echo $this->direcao ?> ">Matrícula Usuário que Emprestou<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->data as $data): ?>
                    <tr>
                        <td class="painel"><a style="margin-top: 6px;" title="Devolver" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/devolucaobackupedit/DocID/<?php echo $this->escape($data["LSBK_ID_DOCUMENTO"]); ?>/tomboNr/<?php echo $this->escape($data["LSBK_NR_TOMBO"]); ?>" >Devolver</a></td>
                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>
                        <td><?php echo $this->escape($data["LSBK_NR_TOMBO"]); ?></td>
                        <td><?php echo $this->escape($data["LSBK_TP_TOMBO"]); ?></td>
                        <td><?php echo $this->escape($data["LSBK_DT_EMPRESTIMO"]); ?></td>
                        <td><?php echo $this->escape($data["LSBK_CD_MAT_EMPRESTIMO"]); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">
                        Total: <?php echo $this->data->getTotalItemCount() ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
        <p>Não existem registros.</p>
    <?php endif; ?>
</div>