
<div id="container_pagination">
    <div style="margin-bottom: 5px;">
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/add">Novo</a>
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/entradamaterial">Entrada de Material</a>
    </div>
    <?php if (count($this->data)): ?>
        <table class="grid">
            <thead>
                <tr>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/LHDW_ID_HARDWARE/direcao/<?php echo $this->direcao ?> ">Editar<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/LHDW_DS_HARDWARE/direcao/<?php echo $this->direcao ?> ">Descrição<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/LHDW_CD_MATERIAL/direcao/<?php echo $this->direcao ?> ">Código Material<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/SECAO_SUBSECAO/direcao/<?php echo $this->direcao ?> ">Seção/Subseção<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/MARC_DS_MARCA/direcao/<?php echo $this->direcao ?> ">Marca<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/LHDW_CD_MODELO/direcao/<?php echo $this->direcao ?> ">Modelo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/index/ordem/MTEN_QT_ENTRADA_MATERIAL/direcao/<?php echo $this->direcao ?> ">Total<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th >Disponível</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->data as $data):
                    $objHardware = new Application_Model_DbTable_SosTbLhdwMaterialAlmox();
                    $qtd_total = $objHardware->getQtdTotalMaterial($data["LHDW_ID_HARDWARE"]);
                    $qtd_saida = $objHardware->getQtdMaterialSaida($data["LHDW_ID_HARDWARE"]);
                    $resultado = (int)$qtd_total['QTD_TOTAL'] - (int)$qtd_saida['QTD_SAIDA'];
                    $disponivel = ($resultado == 0)?'-':$resultado;
                    ?>
                    <tr>
                        <td class="paInel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/labhardware/edit/id/<?php echo $this->escape($data["LHDW_ID_HARDWARE"]); ?>" >Editar</a></td>
                        <td style="width: 360px;"><?php echo $this->escape($data["LHDW_DS_HARDWARE"]); ?></td>
                        <td><?php echo $this->escape($data["LHDW_CD_MATERIAL"]); ?></td>
                        <td><?php echo $this->escape($data["SECAO_SUBSECAO"]); ?></td>
                        <td><?php echo $this->escape($data["MARC_DS_MARCA"]); ?></td>
                        <td><?php echo $this->escape($data["MODE_DS_MODELO"]); ?></td>
                        <td><?php echo $this->escape(($data["MTEN_QT_ENTRADA_MATERIAL"] == '')?'-':$data["MTEN_QT_ENTRADA_MATERIAL"]); ?></td>
                        <td><?php echo $disponivel; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="8">Total: <?php echo $this->data->getTotalItemCount() ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="8">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
        <p>Não existem registros</p>
    <?php endif; ?>
</div>