<?php
$this->inlineScript()
    ->appendFile($this->baseUrl() . '/js/tooltipster-1.2/js/jquery.tooltipster.min.js', 'text/javascript')
    ->appendFile($this->baseUrl() . '/js/sosti/caixaEntrada.js ', 'text/javascript');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<fieldset>
    <legend>Filtro da Caixa</legend>
    <h3><?= $this->nomeCaixa ?></h3>
    <div class="painel">
        <div class="painel" >
            <input type="button" title="Último Filtro" name="acao" value="Filtro" id="pesquisar">
            <a title="Novo Filtro" name="acao" value="Filtrar" id="ultimo_filtro" href="<?php echo $this->baseUrl(); ?>/sosti/caixapessoal/entrada/nova/1" >Limpar Filtro/Retirar Filtro</a>
            &emsp;&emsp;<span style="color: #2E4557;"><strong><?php if ($this->ultima_pesq == true) echo "Filtro Ativo";
else echo "Filtro Inativo"; ?></strong></span>
        </div> 


    </div>
    <div id="pesq_div"  style="display: none;" >
<?php echo $this->form; ?>
        <span id="botao_ajuda_recolhe" ></span>
    </div>
</fieldset>
<form name="helpdesk" action="" method="post" >
    <div class="painel">
        <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
        <input type="submit" title="Cancelar solicitação" name="acao" value="Cancelar"/>
        <input type="submit" title="Criar Nova Categoria / Categorizar e Descategorização de Solicitações de TI" name="acao" value="Categorias"/>
        <input type="submit" title="Encaminhar a solicitação" name="acao" value="Encaminhar"/>
<!--         <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>-->
<!--        <input name="" type="button" onClick='javascript:location.href="<?php // echo $this->baseUrl();  ?>/sosti/helpdesk/atendimentointerno"' value="Nova">-->
        <input type="submit" title="Dar parecer" name="acao" value="Parecer"/>
<?php if ($this->idGrupo != 0) { ?><a class="ui-button ui-widget ui-state-default ui-corner-left estiloBotao"   href="<?php echo $this->baseUrl(); ?>/sosti/respostapadrao/list/idGrupo/<?= $this->idGrupo ?>">Resposta Padrão</a> <?php } ?>
        <input type="submit" title="Vincular de TI" name="acao" value="Vincular"/>
        <input type="submit" title="Desvincular de TI" name="acao" value="Desvincular"/>
        <input type="submit" title="Pedir Informação para Solicitação de TI" name="acao" value="Solicitar Informação"/>
        <input type="submit" title="Trocar o serviço da solicitação de TI" name="acao" value="Trocar Serviço"/>
        <input type="submit" title="Extensão de prazo para solicitações de TI" name="acao" value="Extensão de Prazo"/>
        <input type="submit" title="Realizar associações de sostis de caixas diversas" name="acao" value="Associar Sostis"/>
    </div>
<?php if (count($this->data)): ?>
        <div id="container_pagination">
            <table class="grid">
                <thead>
                    <tr>
                        <th rowspan="2">
                            <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                        </th>
                        <th rowspan="2"><a href="<?php echo $this->baseUrl(); ?>/sosti/caixapessoal/entrada/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th></th>
                        <th rowspan="2"><a href="<?php echo $this->baseUrl(); ?>/sosti/caixapessoal/entrada/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th rowspan="2"><a href="<?php echo $this->baseUrl(); ?>/sosti/caixapessoal/entrada/ordem/NOME_USARIO_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th rowspan="2"><a href="<?php echo $this->baseUrl(); ?>/sosti/caixapessoal/entrada/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th rowspan="2">Vinculada</th>
                        <th colspan="3">Categorias</th>
                    </tr>
                    <tr>
                        <th>Pessoal</th>
                        <th>Grupo</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $tempoInicial = new App_Sosti_TempoSla(); ?>
                    <?php foreach ($this->data as $data): ?>
                        <?php
                        $caso_categoria = new Application_Model_DbTable_SosTbCasoCategoriaSolic();
                        $categoriasPessoal = $caso_categoria->getCategoriasDocumentoPessoal($data["SSOL_ID_DOCUMENTO"]);

                        if ($data["SNAS_ID_NIVEL"] != NULL) {
                            $identificador = $data["SNAS_ID_NIVEL"];
                            $tipo = 'NIVEL';
                        } else {
                            $identificador = $data["MODE_ID_CAIXA_ENTRADA"];
                            $tipo = 'GRUPO';
                        }
                        $categoriasGrupo = $caso_categoria->getCategoriasDocumentoGrupo($data["SSOL_ID_DOCUMENTO"], $identificador, $tipo);
                        $data['DADOS_INPUT'] = Zend_Json::encode($data);
                        $data['TEMPO_TRANSCORRIDO'] = $tempoInicial->tempoTotalHelpdesk($data['MOVIMENTACAO'], '', '07:00:00', '20:00:00');
                        ?>
                        <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td <?php echo App_View_Helper_CorStatus::corCaixa($this->controller, $data["MOFA_ID_FASE"], $data["SESP_DH_LIMITE_ESP"], $data["TEMPO_TOTAL"], ''); ?> >
                                <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                            </td>
                            <td>
        <?php if (isset($this->vinc[$data["SSOL_ID_DOCUMENTO"]])) : ?>
                                    <a href="#" class="plus-vinc <?php echo $data["SSOL_ID_DOCUMENTO"] ?>">
                                        <img src="<?php echo $this->baseUrl('img/a-plus-icon.png') ?>" alt=""/>
                                    </a>
        <?php endif; ?>
                            </td>
                            <td><a href="#" class="tooltip" title="<?php echo $data['DOCM_DS_ASSUNTO_DOC']; ?>"><?php echo $this->escape($data["MASCARA_DOCM"]); ?></td>
                            <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                            <td><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"] . ' - ' . $data['NOME_USARIO_CADASTRO']); ?></td>
                            <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                            <td><?php if (isset($data["VINCULADA"]) && ($data["VINCULADA"] == 1)) {
            echo "SIM";
        } else {
            echo "";
        } ?></td>
                            <td>
                                        <?php
                                        $cont = 0;
                                        if ($categoriasPessoal != null) {
                                            ?>
                                    <table>
                                        <tr>
                                            <?php
                                            foreach ($categoriasPessoal as $categorias_p) {
                                                if ($cont % 3 == 0) {
                                                    echo '</tr><tr>';
                                                }
                                                ?>
                                                <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR'] ?>" title="Nome: <?php echo $categorias_p['CATE_NO_CATEGORIA'] ?> - Descrição: <?php echo $categorias_p['CATE_DS_OBSERVACAO'] ?>" > </td>
                                        <?php
                                        $cont++;
                                    }
                                    ?>
                                        </tr>
                                    </table>
            <?php
        }
        ?>
                            </td>
                            <td>
                                        <?php
                                        $cont = 0;
                                        if ($categoriasGrupo != null) {
                                            ?>
                                    <table>
                                        <tr>
            <?php
            foreach ($categoriasGrupo as $categorias_p) {
                if ($cont % 3 == 0) {
                    echo '</tr><tr>';
                }
                ?>
                                                <td bgcolor="<?php echo $categorias_p['CATE_DS_DESCRICAO_COR'] ?>" title="Nome: <?php echo $categorias_p['CATE_NO_CATEGORIA'] ?> - Descrição: <?php echo $categorias_p['CATE_DS_OBSERVACAO'] ?>" > </td>
                <?php
                $cont++;
            }
            ?>
                                        </tr>
                                    </table>
                            <?php
                        }
                        ?>
                            </td>
                        </tr>

                        <!--Vinculados-->

                        <?php if (isset($this->vinc[$data["SSOL_ID_DOCUMENTO"]])) : ?>
                            <?php
                            $TempoSlaDesenvolvimento = new App_Sosti_TempoSlaDesenvolvimento();
//                            $PrazoSlaDesenvolvimento = $TempoSlaDesenvolvimento->PrazoSlaDesenvolvimento($this->vinc, 'MOFA_ID_MOVIMENTACAO', 'MOVI_DH_ENCAMINHAMENTO', 'SSPA_DT_PRAZO', 'CORRETIVA', 'ASSO_IC_ATENDIMENTO_EMERGENCIA', 'ASSO_IC_SOLUCAO_PROBLEMA', 'ASSO_IC_SOLUCAO_CAUSA_PROBLEMA', 'ASIS_PRZ_SOL_PROBLEMA', 'ASIS_PRZ_SOL_CAUSA_PROBLEMA', 'ASIS_PRZ_EXECUCAO_SERVICO', $expediente);
                            ?>
                            <?php foreach ($this->vinc[$data["SSOL_ID_DOCUMENTO"]] as $vinc): ?>
                <?php
                $categoriasPessoal = $caso_categoria->getCategoriasDocumentoPessoal($vinc["SSOL_ID_DOCUMENTO"]);
                if ($data["SNAS_ID_NIVEL"] != NULL) {
                    $identificador = $vinc["SNAS_ID_NIVEL"];
                    $tipo = 'NIVEL';
                } else {
                    $identificador = $vinc["MODE_ID_CAIXA_ENTRADA"];
                    $tipo = 'GRUPO';
                }
                $categoriasGrupo = $caso_categoria->getCategoriasDocumentoGrupo($vinc["SSOL_ID_DOCUMENTO"], $identificador, $tipo);
                ?>
                                <tr class="vinculados <?php echo $data["SSOL_ID_DOCUMENTO"] ?>">
                                    <td style="display: none" colspan="2" <?php echo App_View_Helper_CorStatus::corCaixa($this->controller, $vinc["MOFA_ID_FASE"], $vinc["SESP_DH_LIMITE_ESP"], $vinc["TEMPO_TOTAL"], ''); ?> >
                                        <input style="visibility: hidden" class="nav_grid_check_box nav_check_boxes"
                                               id="<?php echo $this->escape($vinc["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]"
                                               type="checkbox" value="<?php echo $this->escape(json_encode($vinc)); ?>"/>
                                    </td>
                                    <td style="display: none">
                                        <a href="#" class="tooltip"
                                           title="<?php echo $vinc['DOCM_DS_ASSUNTO_DOC']; ?>"><?php echo $this->escape($vinc["MASCARA_DOCM"]); ?>
                                    </td>
                                    <td colspan="2" style="display: none"><?php echo $this->escape($vinc["DOCM_CD_MATRICULA_CADASTRO"] . ' - ' . $vinc['NOME_USARIO_CADASTRO']); ?></td>
                                    <!--<td style="display: none"><?php echo ($vinc['ATENDENTE'] = ' - ') ? '' : $this->escape($vinc['ATENDENTE']); ?></td>-->
                                    <td colspan="4" style="display: none"><?php echo $this->escape($vinc["SSER_DS_SERVICO"]); ?></td>
                                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
                        <!--Fim Vinculados-->
    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="9">Total: <?php echo $this->data->getTotalItemCount(); ?></td>
                    </tr>
                    <tr>
                        <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null); ?></td>
                    </tr>
                </tfoot>
            </table>
            <div class="painel">
                <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
                <input type="submit" title="Cancelar solicitação" name="acao" value="Cancelar"/>
                <input type="submit" title="Criar Nova Categoria / Categorizar e Descategorização de Solicitações de TI" name="acao" value="Categorias"/>
                <input type="submit" title="Encaminhar a solicitação" name="acao" value="Encaminhar"/>
    <!--             <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>-->
            <!--        <input name="" type="button" onClick='javascript:location.href="<?php // echo $this->baseUrl(); ?>/sosti/helpdesk/atendimentointerno"' value="Nova">-->
                <input type="submit" title="Dar parecer" name="acao" value="Parecer"/>
            <?php if ($this->idGrupo != 0) { ?><a class="ui-button ui-widget ui-state-default ui-corner-left estiloBotao"   href="<?php echo $this->baseUrl(); ?>/sosti/respostapadrao/list/idGrupo/<?= $this->idGrupo ?>">Resposta Padrão</a> <?php } ?>
                <input type="submit" title="Vincular de TI" name="acao" value="Vincular"/>
                <input type="submit" title="Desvincular de TI" name="acao" value="Desvincular"/>
                <input type="submit" title="Pedir Informação para Solicitação de TI" name="acao" value="Solicitar Informação"/>
                <input type="submit" title="Trocar o serviço da solicitação de TI" name="acao" value="Trocar Serviço"/>
                <input type="submit" title="Extensão de prazo para solicitações de TI" name="acao" value="Extensão de Prazo"/>
                <input type="submit" title="Realizar associações de sostis de caixas diversas" name="acao" value="Associar Sostis"/>
            </div>
    <?php else: ?>

    <?php if ($this->ultima_pesq): ?>
                <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
        <?php else: ?>
                <p><br/>Não existem registros</p>
    <?php endif; ?>


<?php endif; ?>
    </div>

<?php echo $this->partial('_partials/caixahiddeninputs.phtml', array('view' => $this)); ?>

</form>
<div>
<?php echo App_View_Helper_CorStatus::corLegenda(); ?>
</div>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
    <div id="dialog-documentos_conteudo"></div>
</div>

<script>
    $(".plus-vinc").click(function (e) {
        e.preventDefault();
        var id = $(this).attr('class').replace('plus-vinc ', '');
        var tr = $(".vinculados." + id);
        tr.find('td').slideToggle(300);
        if ($(this).find('img').attr('src') == "<?php echo $this->baseUrl('img/a-plus-icon.png') ?>")
            $(this).find('img').attr('src', "<?php echo $this->baseUrl('img/a-minus-icon.png') ?>");
        else
            $(this).find('img').attr('src', "<?php echo $this->baseUrl('img/a-plus-icon.png') ?>");
    });
</script>
