<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesInteressadosDocumentos.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesInteressados.js')); 
?>

<script type="text/javascript">
$(function() {
            $("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
                source: "ajaxunidade",
                minLength: 3,
                delay: 100,
                select: function( event, ui ) {
                            $("#DOCM_CD_LOTACAO_REDATORA").val(ui.item.label);
			}
            });
           
            $("#DOCM_CD_LOTACAO_REDATORA").autocomplete({
                source: "ajaxunidade",
                minLength: 3,
                delay: 100
            });
            $( "#DOCM_ID_TIPO_DOC" ).combobox();
            $( "#combobox-input-text-DOCM_ID_TIPO_DOC" ).attr('style','width: 500px;');


            $("#dialog-message").dialog("destroy");

            $("#dialog-message").dialog({
                    modal: true,
                    width: 380,
                    height: 225,
                    buttons: {
                            Sim: function() {
                               location.href='ativa';           		
                            }, 
                            Não: function() {
                              $(this).dialog('close');           		
                            }
                    }
                    });

            $( "#dialog-message" ).bind( "dialogclose", function(event, ui) { });
      
            $('#ANEXOS').MultiFile({
                STRING: {
                    file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                    remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
                }
            });
       
           $("input[type=radio][name=DESTINO_DOCUMENTO]").click(function(){
              if( $(this).val() == "E"){
                   $(".unidade_destino").show();
                   $(".msg_alerta").html("<br/>Aten&ccedil;&atilde;o: ao encaminhar o Documento para Caixa de Entrada da Unidade o mesmo n&atilde;o poder&aacute; mais ser exclu&iacute;do nem ter seus metadados editados. Certifique-se antes de salvar, que o documento est&aacute; na vers&atilde;o definitiva e n&atilde;o precisar&aacute; mais ser editado. <br/>")
              }else if($(this).val() == "I"){
                   $(".msg_alerta").html("");
                   $(".unidade_destino").hide();
              }
          }); 
      
      
            /**
             * Para transformar o select em um combo de autocomplete via somente java-script
             **/
            $( "#DOCM_ID_PCTT" ).combobox();
            $( "#combobox-input-text-DOCM_ID_PCTT" ).attr('style','width: 700px;');
            $( "#combobox-input-button-DOCM_ID_PCTT" ).attr('style','display: none;');
            $( "#DOCM_ID_TIPO_DOC" ).combobox();
            $( "#combobox-input-text-DOCM_ID_TIPO_DOC" ).attr('style','width: 500px;');

            /**
             * Para apresentar a Lista completa de ASSUNTOS
             */
            var botao_detalhe_pctt = $("<input type='button' name='LST_CPT_PCTT' value='Lista completa de Assuntos' />");
            botao_detalhe_pctt.css('position','relative');
            botao_detalhe_pctt.css('display','inline');
            botao_detalhe_pctt.css('float','right');
            botao_detalhe_pctt.css('top','-58px');
            botao_detalhe_pctt.css('left','-70px');
            botao_detalhe_pctt.button();
            $( "#DOCM_ID_PCTT-element").append(botao_detalhe_pctt);
            botao_detalhe_pctt.click(
                function(){
                    if($('#detalhe_pctt').attr('id') == undefined){
                        var detalhe_pctt = $("<div id='detalhe_pctt'></div>");
                        var select = $( "#DOCM_ID_PCTT" );
                        select.css('display','block');
                        select.css('width','680px');
                        select.css('height','480px');
                        select.attr('size','20');
                        detalhe_pctt.append(select);
                        $('body').append(detalhe_pctt);
                        detalhe_pctt.dialog({
                                    title: 'Lista completa de Assuntos',
                                    modal: true,
                                    width: 700,
                                    height: 600,
                                    buttons: {
                                            OK: function() {
                                              $("#DOCM_ID_PCTT").css('display','none');
                                              selected = $("#DOCM_ID_PCTT").children( ":selected" );
                                              $( "#combobox-input-text-DOCM_ID_PCTT" ).val(selected.text());
                                              $( "#DOCM_ID_PCTT-element" ).append(select);
                                              $(this).dialog('close');  
                                              $( "#combobox-input-text-DOCM_ID_PCTT" ).focus();
                                            }
                                    }
                                    });
                        detalhe_pctt.dialog('open');
                    }else{
                        $("#DOCM_ID_PCTT" ).css('display','block');
                        $('#detalhe_pctt').append($("#DOCM_ID_PCTT" ));
                        $('#detalhe_pctt').dialog('open');
                    }
                }
            );
            
            //mostra/esconde o botao de vistas de acordo com a confidencialidade
            $confidenc = $('#DOCM_ID_CONFIDENCIALIDADE');
            if( $confidenc.val() != "0") { 
                $("input[name='cadVistas']").show();
            }
            
            $confidenc.change( function(){
                   if( $(this).val() != "0" ){
                       $("input[name='cadVistas']").show();
                   }else{
                       $("input[name='cadVistas']").hide();
                   }
            }); 
            
            $("form[name='cadastroInterno']").submit( function(){
                
                if( ($confidenc.val() != "0" && $("input[name='REPLICA_VISTAS']").is(':checked') == false ) ){
                   var $qtdeVistas = $("#vistas_adicionadas").find("input[type='hidden']");
                   if( $qtdeVistas.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma pessoa/unidade com vistas ao documento");
                      return false;
                   }
                }
                
                //publico e restrito as partes necessitam de ter parte cadastrada
                if($confidenc.val() == "0" || $confidenc.val() == "1" ||  $("input[name='REPLICA_VISTAS']").is(':checked') == true ){
                    //precisa ter parte
                   var $qtdePartes = $("#partes_adicionadas").find("input[type='hidden']");
                   if( $qtdePartes.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma parte no documento");
                      return false;
                   }
                }
                $(this).attr("action", "save");
                return true;
            });
            
   });
</script>
<?php  if( $this->alert): ?>
<div id="dialog-message" title="Aten&ccedil;&atilde;o" style="display: none; ">
<p>
        <span class="" style="float:left; margin:0 7px 50px 0;"></span>
        <?php echo $this->alert; ?>			
</p>
</div>
<? endif; ?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>
<div id=""><?php echo $this->alert; ?></div>

<form name="cadastroInterno" action="" method="POST" enctype="multipart/form-data" >
<?php 
    echo $this->form->DOCM_ID_DOCUMENTO;
    echo $this->form->DOCM_NR_DOCUMENTO;
    echo $this->form->DOCM_NR_SEQUENCIAL_DOC;
    echo $this->form->DOCM_DH_CADASTRO;
    echo $this->form->DOCM_CD_MATRICULA_CADASTRO;
    echo $this->form->DOCM_SG_SECAO_GERADORA;
    echo $this->form->DOCM_CD_LOTACAO_GERADORA;
    echo $this->form->DOCM_SG_SECAO_REDATORA;
    echo $this->form->DOCM_CD_LOTACAO_REDATORA;
    echo $this->form->DOCM_ID_TIPO_DOC;
    echo $this->form->DOCM_NR_DCMTO_USUARIO;
    echo $this->form->DOCM_ID_PCTT;
    echo $this->form->DOCM_DS_ASSUNTO_DOC;
    echo $this->form->DOCM_DS_PALAVRA_CHAVE;
    echo $this->form->DOCM_ID_TIPO_SITUACAO_DOC;
    echo $this->form->DOCM_ID_CONFIDENCIALIDADE; ?>
    

<div id="dialog_cadastra_parte_doc" style="display: none;">  
    <?php echo $this->partial('_partials/cadastrapartesinteressados.phtml',            
                  array( 'form' => $this->formParte));?>
                             
</div>   
<div id="partes_adicionadas" style="display: none;"> </div>
<div id="vistas_adicionadas" style="display: none;"> </div>


<fieldset style="margin-top: 10px; width: 250px;">
    <legend> Cadastro de Vistas / Partes </legend>
    <input type="button" value="Cadastrar partes"  class="ui-button ui-widget ui-state-default ui-corner-all cadPartes" name="cadPartes" title="Cadastrar Partes ao Documento" role="button" aria-disabled="false" style="margin: 10px 0px;"/>
    <input type="button" value="Cadastrar vistas"  class="ui-button ui-widget ui-state-default ui-corner-all cadVistas" name="cadVistas" title="Cadastrar Vistas ao Documento" role="button" aria-disabled="false" style="margin: 10px 0px; display: none;"/>
</fieldset>

<?php
    echo $this->form->DOCM_DS_HASH_RED;
    echo $this->form->DOCM_NR_DOCUMENTO_RED;
?>
<strong>Anexos</strong></br>
<input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" accept="pdf" maxlength="20" />
Até 20 Anexos. </br>
Somente serão aceitos arquivos com o formato PDF. </br>
Soma dos arquivos até 50 Megas.</p>

<?php echo $this->form->DESTINO_DOCUMENTO; ?>
<span class="unidade_destino" style="display: none;"> <?php echo $this->formCaixa->UNIDADE; ?> </span>

<span class="msg_alerta"> </span>
</br>
<input type="submit" name="salvar" value="Salvar" />
<?php echo $this->form->OBRIGATORIO; ?>
</form>
