<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <ul>
        <li>Ordenar por <b>Grupo de Serviço</b> e verificar se os dados cadastrados estão corretos.</li>
        <li>Havendo erro, clicar no botão <b>Editar</b> para corrigir a descrição e os dados do serviço.</li>
        <li>Para cadastrar um novo serviço clique no botão <b>Novo</b>.</li>
    </ul>

<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>

<div style="margin-bottom: 5px;">
    <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/marca/add">Novo</a>
</div>
<?php if (count($this->data)): ?>
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th width="8%"><a  href="<?php echo $this->baseUrl(); ?>/sosti/marca/index/ordem/MARC_ID_MARCA/direcao/<?php echo $this->direcao ?> ">Editar</a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/marca/index/ordem/MARC_DS_MARCA/direcao/<?php echo $this->direcao ?> ">Descrição da Marca<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->data as $data): ?>
                    <tr>
                        <td class="painel">
                            <a title="Editar" style="margin-top: 6px;" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/marca/edit/id/<?php echo $this->escape($data["MARC_ID_MARCA"]); ?>" >Editar</a>
                        </td>
                        <td><?php echo $this->escape($data["MARC_DS_MARCA"]); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">
                        Total: 
                        <?php echo $this->data->getTotalItemCount() ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
        <p>Não existem registros.</p>
    <?php endif; ?>
</div>