<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Permite encaminhar a requisição para o segundo nível de atendimento, onde a mesma será analisada.</p>
    <ul>
    <li>Ao <b>Salvar</b> o encaminhamento, o sistema limpa a tela e permite que o atendente cadastre uma nova solicitação ou clique no botão <b>Próxima</b> para atender um chamado existente na Caixa de Atendimento.</li>
    </ul>
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>

<?php echo $this->form; ?>