<div>
    <a  class="novo" href="sosti/helpdesk/form">Novo</a>
</div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th >Ações</th>
                <th ><a  href="sosti/helpdesk/index/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/helpdesk/index/ordem/MOFA_DH_FASE/direcao/<?php echo $this->direcao ?> ">Data/hora<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/helpdesk/index/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/helpdesk/index/ordem/DOCM_CD_MATRICULA_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="sosti/helpdesk/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td><input  name="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]) ?>" type="checkbox" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]) ?>"/></td>
                    <td><?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?></td>
                    <td><?php echo $this->escape($data["MOFA_DH_FASE"]); ?></td>
                    <td><?php echo $this->escape($data["TEMPO_TOTAL"]); ?></td>
                    <td><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="7">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
    </table>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
</div>