<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <ul>
        <li><b>Encaminhar</b>: Permite encaminhar a requisição para o segundo nível de atendimento, onde a mesma será analisada.</li>
        <li>A opção <b>Baixar</b> permite buscar uma solicitação que acabou de ser gravada.</li>
        <li>Uma solicitação pode ser colocada em <b>Espera</b> pelo atendente, devido ao usuário não estar disponível para que o atendimento seja executado.</li>
        <li>As solicitações colocadas em Espera retornam a caixa de atendimento no dia seguinte, como a mais antiga.</li>
    </ul>

<!--<a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>
<!--        SOLICITAÇÕES VINCULADAS             -->
            <?php 
               $count = count($this->DocmListaVinculados);
               if($count != 0){
            ?>
               <fieldset style="border: 1px solid #A6C9E2; margin-right: 15px;">
                   <h3 style="color: red;"> Está solicitação está vinculada,
                            isto é, todas as solicitações sofrerão a mesma ação. </h3>
                    <div style="margin-left: 10px; margin-top: -14px; font-size: 12px; ">
                        <div style="margin-left: 10px; font-size: 12px; ">
                            <p>
                                <br/><b>Solicitação Principal:</b> <?php echo $this->DocmDocumentoVinculacao['DOCM_NR_DOCUMENTO']?>
                                <br/><b>Data de vinculação:</b> <?php  echo $this->DocmDocumentoVinculacao['VIDC_DH_VINCULACAO']?>
                            </p>
                            <br>
                            Solicitações Filhas
                            <?php 
                                foreach ($this->DocmListaVinculados as $solicVinculadas) {
                                    if (strcmp($this->DocmDocumentoVinculacao["DOCM_NR_DOCUMENTO"], $solicVinculadas["DOCM_NR_DOCUMENTO"])) {
                                        echo $solicVinculadas["DOCM_NR_DOCUMENTO"]."<br>";?>
                                   <?php }
                                }
                            ?>
                        </div>
                    </div>
               </fieldset>
            <?php }?>
<!--        FIM SOLICITAÇÕES VINCULADAS            -->
<form method="post" action="<?php echo $this->baseUrl(); ?>/sosti/helpdesk/index">
    <div class="painel">
        <input type="submit" title="Encaminhar a solicitação" name="acao" value="Encaminhar"/>
        <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
        <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>
    </div>
    <?php echo $this->form; ?>
</form>