<?php
if($this->Caixas):  
    foreach ($this->Caixas as $value) : 
?>
    <option value="<?php echo $value["LOTA_SIGLA_SECAO"].'|'.$value["LOTA_COD_LOTACAO"]; ?>"><?php echo $value["LOTA_SIGLA_LOTACAO"].' - '.$value["LOTA_DSC_LOTACAO"].' - '.$value["LOTA_COD_LOTACAO"].' - '.$value["LOTA_SIGLA_SECAO"]; ?></option>   
<?php 
    endforeach;
    else: 
?>
        <option value="">Sem caixa </option>  
<?php
endif;
?>