<?php
if ($this->arrayMembros):
    ?>
    <option value="">Selecione um membro</option>  
    <?php
    foreach ($this->arrayMembros as $value) :
        ?>
        <option value="<?php echo $value["PMAT_CD_MATRICULA"]; ?>">
            <?php echo $value["PMAT_CD_MATRICULA"] . ' - ' . $value["PNAT_NO_PESSOA"]; ?>
        </option>   
        <?php
    endforeach;
else:
    ?>
    <option value="">Não exite membros</option>
<?php
endif;
