<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p></p>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->


<?php if (count($this->data)): ?>
<table class="grid">
    <thead>
        <tr>
<!--            <th >Encaminhar</th>-->
<!--            <th >Status</th>-->
            <th >Número</th>
            <th >Autor</th>
            <th >Tipo</th>
            <th >Data Criação</th>
        </tr>
    </thead>
    <tbody id="documentosList">
        <?php
        
        foreach($this->data as $dados):
            foreach($dados as $data):
            if (is_null($data["MODE_DH_RECEBIMENTO"]))  $lido =  "naolido"; else $lido = '';
            ?>
            <tr>
<!--                <td>
                    <span class="<?php //echo $lido; ?>"></span>
                </td>-->
<!--                    <td> <input name="documento[]" type="checkbox" checked="checked" ></input></td>-->
                    <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>
                    <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                    <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
                    <td> <?php echo $this->escape($data["DOCM_DH_CADASTRO"]) ?></td>
    <!--                <td> <?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>-->
            </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="7">Total: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
</table>
<?php echo $this->paginationControl($this->data, null, null, null)
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
<?php echo $this->formAutuardcmto; ?>
