<?php
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
        $(function(){ 
            $('#ANEXOS').MultiFile({
                STRING: {
                    file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                    remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
                }
            });
        });
    </script>

<form method="POST" action="despacho" enctype="multipart/form-data" >
<?php if (count($this->data)): ?>
<div class="container_pagination_fixed">
<table class="grid">
    <thead>
        <tr>
            <th >Tipo</th>
            <th >Número</th>
            <th >Encaminhador</th>
            <th >Data/Hora Encaminhamento</th>
        </tr>
    </thead>
    <tbody id="documentosList">
        <?php
            //Zend_Debug::dump($this->data);
        foreach($this->data as $data):
            ?>
            <tr>
                    <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--                    <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                    <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                    <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                    <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
    <!--                <td> <?php //echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>-->
            </tr>
<!--            <input type="hidden" name="<?php //echo $documentos[$cont] ?>" value="<?php //echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?>">-->
            <?php ?>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td>
        </tr>
<!--        <tr>
            <td colspan="4"><?php //echo $this->paginationControl($this->data, null, null, null)?></td>
        </tr>-->
    </tfoot>
</table>
</div>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>
    <input type="hidden" value="submitDespacho" name="acao" />
<?php 
    echo $this->formDespacho->getElement('MOFA_DS_COMPLEMENTO'); 
?>
    <b>Anexos</b></br>
        <input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" maxlength="20" />
        Até 20 Anexos. </br>
        Soma dos arquivos até 50 Megas.</p>
        <span class="msg_alerta"> </span>
    </p>
    <span class="msg_alerta"> </span>
    <input type="submit" name="salvar" value="Salvar" />
</form>