<?php
$this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
$this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        var orgao = '';
        var GLOBAL_indice_abas =  0;
        var xhr_abrir_documento; 
        function distribuir(PRDI_ID_PROCESSO_DIGITAL,IMDI_CD_COMISSAO){
            url = '<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/impedimento/IMDI_CD_COMISSAO/'+IMDI_CD_COMISSAO+'/PRDI_ID_PROCESSO_DIGITAL/'+PRDI_ID_PROCESSO_DIGITAL;
            $.ajax({
                url: url,
                //                method:
                //                    data:{matricula:usuariosMAT, }
                success: function(data){
                    
                    //monta um formulario com os mombros e um check box
                    $('#dialog-impedimento').dialog(
                    {
                        height: 400,
                        width:500,
                        title:'Membros Impedidos para a Distribuição Eletrônica',
                        buttons: {
                            "Salvar": function() {
                                var $form = $('form#distribuicao');
                                $.ajax({
                                    type: "POST",
                                    url: base_url + '/sisad/distribuicao/impedir',
                                    dataType: "json",
                                    data: $form.serialize(),
                                    success: function(data){
                                        if(data.success){
                                            
                                            $('#flashMessagesDiv').html('<div class="success"><strong>Sucesso:</strong> '+data.mensagem+'</div>');
                                        }else{
                                            $('#flashMessagesDiv').html('<div class="error"><strong>Erro:</strong> '+data.mensagem+'</div>');
                                        }
                                        $("#dialog-impedimento").scrollTop(0);
                                    }
                                });
                            },
                            "Fechar": function() {
                                $( this ).dialog( "close" );
                            }
                        }

                    }
                );
                    $('#dialog-impedimento').html('');                   
                    $('#dialog-impedimento').html(data);
                    $('#dialog-impedimento').dialog('open');
                    $('#dialog-impedimento').attr('css','overflow:auto;');
                },
                error : function(){
                    alert('Erro 1: Não foi possível excluir documento do Processo.');
                }
            });
        }
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
            $('.impedimento').hide();
            $('.promocao').hide();
        });
        //AUTO COMPLETA DO ORGAO JULGADOR
        $(function() {
            $("#nome_orgao").autocomplete({
                
                source: base_url+"/sisad/distribuicao/ajaxorgaojulgador",
                minLength: 3,
                delay: 300,
                select: function (event, ui){
                    orgao = ui.item.orgj_cd_orgao_julgador;
                    //preenche campo hiden
                    $('#ORGJ_CD_ORGAO_JULGADOR').val(orgao);
                    if(orgao==1000 || orgao==2000 || orgao==3000){
                        $('.impedimento').hide();
                        $('.promocao').show();
                    }else{
                        $('.impedimento').show();
                        $('.promocao').hide();
                    }
                    $("#matricula_membro").hide();
                    $("#matricula_membro").html('');
                    $("#GRUPO_DISTRIBUICAO-distautomatica").attr('checked', 'checked');
                    $("#flashMessagesView").html('');
                }
            });
        });
        
        
        $(function(){
            $("#dialog-documentos_detalhe").dialog({
                title    : 'Detalhe',
                autoOpen : false,
                modal    : false,
                show: 'fold',
                hide: 'fold',
                resizable: true,
                width: 800,
                height: 600,
                position: [580,140,0,0],
                buttons : {
                    Ok: function() {
                        $(this).dialog("close");
                    }
                }
            });
            
            grid_tbody_tr = $("table.grid > tbody > tr");
            grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_dados_documento = $(this).find('input');

                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_dados_documento = input_dados_documento.val();
                //input_dados_documento.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');

                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }

                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documento = $.ajax({
                    url: url,
                    dataType: 'html',
                    type: 'POST',
                    data: value_input_dados_documento,
                    contentType: 'application/json',
                    processData: false, 
                    beforeSend:function() {
                        div_dialog_by_id.dialog("open");
                        div_dialog_by_id.html('');
                    },
                    success: function(data) {
                        
                        div_dialog_by_id.html(data);

                        //                        var span_id_leitura = $(this_tr).find('span[id=leitura]');
                        //                        span_id_leitura.removeClass('naolido');
                        //                        span_id_leitura.addClass('lido');
                        //                        span_id_leitura.attr('title','Documento lido');
                        //                        $(this_tr).removeClass('naolidoTr');
                        //                        $(this_tr).addClass('lidoTr');

                        //console.log(value_input_check_box);

                        //                        datainput = jQuery.parseJSON(value_input_check_box);
                        //
                        //                        datainput.CLASS_LIDO = 'lido';
                        //                        datainput.CLASS_LIDO_TR = 'lidoTr';
                        //                        datainput.MSG_LIDO = 'Documento lido';
                        //
                        //                        datainput_atualizado = JSON.stringify(datainput, null, null);
                        //                        input_check_box.val(datainput_atualizado)

                    },
                    complete: function(){

                    },
                    error : function(){

                    }
                });
            }
        );
        
        
        
        
            if($("#GRUPO_DISTRIBUICAO-distautomatica").attr('checked') ){
                $("#matricula_membro").hide();   
                $("#matricula_membro-label").hide(); 
            }else{
                $("#matricula_membro").show();   
                $("#matricula_membro-label").show();
            }
        
        
        
            $("#GRUPO_DISTRIBUICAO-distautomatica").click(
            function(){
                $("#matricula_membro").hide();
                $("#matricula_membro-label").hide(); 
                $("#matricula_membro").html('');
            }
        ); 
            $("#GRUPO_DISTRIBUICAO-distmanual").click(
       
            function(){
                if($("#ORGJ_CD_ORGAO_JULGADOR").val()!=''){
                    $.ajax({

                        url:  base_url+'/sisad/caixaunidade/ajaxpessoasorgao/ORGJ_CD_ORGAO_JULGADOR/'+orgao,
                        beforeSend:function() {
                            $("#matricula_membro").show();
                            $("#matricula_membro-label").show();
                            $("#matricula_membro").removeClass('erroInputSelect');
                            $("#matricula_membro").html("");
                            $("#matricula_membro").addClass('carregandoInputSelect');
                        },
                        success: function(data) {
                            $("#flashMessagesView").html('');
                            $("#matricula_membro").html(data);
                            $("#matricula_membro").removeClass('carregandoInputSelect');                            
                        },
                        error: function(){
                            $("#GRUPO_DISTRIBUICAO-distautomatica").attr('checked', 'checked');
                            $("#flashMessagesView").html("<div class='error'><strong>Erro:</strong> Não foi possivel buscar os membros do orgão</div>");
                            $("#matricula_membro").removeClass('x-form-field');
                            $("#matricula_membro").addClass('erroInputSelect');
                        }
                    });
                }else{
                    $("#GRUPO_DISTRIBUICAO-distautomatica").attr('checked', 'checked');
                    $("#flashMessagesView").html("<div class='notice'><strong>Erro:</strong> Escolha primeiro o orgão julgador</div>");
                }
            }
        ); 
        });
    </script>
    <h3>Ajuda&ensp;</h3>
    <ul>
        <li>A distribuição realizada em um <i>Processo Administrativo</i> implica em movimenta-lo para uma <i>unidade</i> ou um <i>Orgão Julgador</i>.</li>
    </ul>
    <span id="botao_ajuda_recolhe" ></span>
</div>

<?php if (count($this->data)): ?>
    <form method="POST" action="distribuir" enctype="multipart/form-data" >
        <input type="hidden" value="submitParecer" name="acao" />

        <p>
            <?= $this->formDistribuir->ORGJ_CD_ORGAO_JULGADOR; ?>
            <?= $this->formDistribuir->nome_orgao; ?>
            Digite o código do orgão ou pedaco do nome do orgão. 
            <?= $this->formDistribuir->GRUPO_DISTRIBUICAO; ?>
            <?= $this->formDistribuir->matricula_membro; ?>



        </p>

        <div class="container_pagination_fixed">
            <table class="grid">
                <thead>
                    <tr>
                        <th >Tipo</th>
                        <th >Número</th>
                        <th >Encaminhador</th>
                        <th >Data/Hora Encaminhamento</th>
                        <th class='impedimento' style="display: none;">Impedimento</th>
                        <th class='promocao' style="display: none;">Promo&ccedil;&atilde;o</th>
                    </tr>
                </thead>
                <tbody id="documentosList">
                    <?php
                    //Zend_Debug::dump($this->data);
                    foreach ($this->data as $data):
                        $dadosInput = Zend_Json::encode($data);
                        ?>
                        <tr>
                            <td> 
                                <!--                                DADOS UTILIZADOS PELO CLICK DUPLO-->
                                <input type="hidden" name="documento[]" id="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" value='<?= $dadosInput ?>'/> 
                                <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?>
                            </td>
                            <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>
                            <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                            <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
                            <td class='impedimento' style="display: none;"> <input id="Distribuir" name="acao" type="button" class="novo" value="Impedimento" onclick="distribuir('<?= $data["PRDI_ID_PROCESSO_DIGITAL"]; ?>',orgao);"/></td>
                            <td class='promocao' style="display: none;">  <input type="checkbox" name="promo-<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]) ?>" title="Adcionar titulo" value="S"/></td>
                        </tr>
                        <?php ?>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">Total: <?php echo $this->data->getTotalItemCount() ?></td>
                    </tr>
            <!--        <tr>
                        <td colspan="4"><?php //echo $this->paginationControl($this->data, null, null, null)                ?></td>
                    </tr>-->
                </tfoot>
            </table>
        </div>
        <span class="msg_alerta"> </span>

        <span class="msg_alerta"> </span>
        <br/>
        <input id="Distribuir" name="acao" type="submit" class="novo" value="Distribuir"/>
    </form>
    <div id="dialog-impedimento"></div>
    <!-- CLICK DUPLO MOSTRA HISTORICO DO DOCUMENTO -->
    <div id="dialog-documentos_detalhe">
        <div id="dialog-documentos_conteudo"></div>
    </div>
<?php else: ?>
    <p>Não existem registros</p>
<?php endif; ?>

