<?php
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->headScript()->appendFile($this->baseUrl() . '/js/default/sosti/add.js', 'text/javascript');
//    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/cadastroDocumentoGrupo.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/default/sosti/cx_unidade_encaminhar.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/addLista.js'));
    $this->inlineScript()->appendFile($this->baseUrl() . '/js/jquery-ui-timepicker-addon.js', 'text/javascript');
?>
        
<div id="flashMessagesView">
     <?php echo $this->flashMessagesView; ?>
    <div class="<?php echo  $this->flashMessages['status']; ?>">
        <strong><?php echo  $this->flashMessages['label']; ?></strong><?php echo $this->flashMessages['message']; ?>
    </div>
        
</div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>
                
<form method="POST" name="encaminhamento" enctype="multipart/form-data" >
    <!--Acao submit do form alterada pela Jquery-->
     <input type="hidden" name="acao" value="" />
    <?php if (count($this->data)): ?>
    <div class="container_pagination_fixed">
    <table class="grid">
        <thead>
            <tr>
                <th >Tipo</th>
                <th >Número</th>
                <th >Encaminhador</th>
                <th >Data/Hora Encaminhamento</th>
            </tr>
        </thead>
        <tbody id="documentosList" >
            <?php
                //Zend_Debug::dump($this->data);
            foreach($this->data as $data):
                ?>
                 <tr data-options='{"existe":{"restricao":"<?php echo $data['restricao'] ?>","unidades":[<? echo $data['vistas'] ?>]}}' class="documentos">
                        <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--                        <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                        <td style="width: 15%" title= "<?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?>" > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                        <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                        <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
                </tr>
                <?php ?>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
        </tfoot>
    </table>
   
    </div>
    <?php echo $this->formInterno->getElement('TIPO_MOVIMENTACAO'); ?>
    <div id="internaunidade">
        <!--<input type="hidden" name="acao" value="" />-->
        <?php 
            echo $this->formInterno->getElement('MODE_SG_SECAO_UNID_DESTINO'); 
            echo $this->formInterno->getElement('SECAO_SUBSECAO'); 
            echo $this->formInterno->getElement('MODE_CD_SECAO_UNID_DESTINO'); ?>
           <span class="msgInfo" style="display: none; padding: 10px 0px;"> </span>
        <?php echo $this->formInterno->getElement('MOFA_DS_COMPLEMENTO'); ?>
    <b>Anexos</b></br>
        <input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" accept="pdf" maxlength="20" />
        Até 20 Anexos. </br>
        Somente serão aceitos arquivos com o formato PDF. </br>
        Soma dos arquivos até 50 Megas.</p>
    </p>
    <input type="submit" name="tipoAcao" value="Salvar" />
    </div>
    <?php if($this->PermissaoLista){?>
        <div id="internalista">
            <!--<input type="hidden" name="acao" value="" />-->
            <?php echo $this->formDivulgar->getElement('LIST_ID_COMPONENTE'); ?>
            <?php echo $this->partial('aviso/addLista.phtml', array('form' => $this->form)); ?>
            <div id="partes_adicionadas"> </div>
            <?php echo $this->formDivulgar->getElement('LIST_DT_INICIO_DIVULGACAO'); ?>
            <?php echo $this->formDivulgar->getElement('LIST_DT_FIM_DIVULGACAO'); ?>
            <?php echo $this->formDivulgar->getElement('Salvar'); ?>
        </div>
    <?}?>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>

    
</form>