<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Nesta tela, devemos marcar os documentos que serão encaminhados ao setor de Protocolo/SECAM e clicarmos no botão <b>Enviar</b>.</p>
    <p>O sistema mostrará a tela com o número do protocolo gerado e surgirá um terceiro ícone, demonstrando que este documento teve os seus metadados enviados aos setor de Protocolo/SECAM, onde os servidores aguardarão o recebimento dos documentos físicos.</p>
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);
                    
                    var span_id_leitura = $(this_tr).find('span[id=leitura]');
                    span_id_leitura.removeClass('naolido');
                    span_id_leitura.addClass('lido');
                    span_id_leitura.attr('title','Documento lido');
                    $(this_tr).removeClass('naolidoTr');
                    $(this_tr).addClass('lidoTr');
                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );
            
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        
                             
        $(".nav_check_boxes").keypress(
            function(e) {
                
            code = e.keyCode ? e.keyCode : e.which;

            var KEY_CODE_h = 104;
            var KEY_CODE_ESC = 27;
            var KEY_CODE_UP = 38;
            var KEY_CODE_w = 115;
            var KEY_CODE_DOWN = 40;
            var KEY_CODE_s = 119;


            if(code.toString() == KEY_CODE_h) {
                $("#dialog-documentos_detalhe").dialog("open");
                $(this).focus();
            }
            if(code.toString() == KEY_CODE_ESC) {
                $("#dialog-documentos_detalhe").dialog("close");
                $(this).focus();
            }

            var current_checkbox_index;
            var this_navigation = this;
            var first_checkbox_index = 0;
            var last_checkbox_index;
                
            $(".nav_check_boxes").each(
                function(index){
                    last_checkbox_index =  index;
                    if(this_navigation == this){
                        current_checkbox_index = index;
                    }
                }
            );
                
            if(code.toString() == KEY_CODE_DOWN ||  code.toString() == KEY_CODE_s) {

                var next_checkbox_index;
                var checkbox_achado = false;
                $(".nav_check_boxes").each(
                    function(index){
                        if(checkbox_achado == true){
                            next_checkbox_index = index;
                            checkbox_achado = false;
                        }
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == last_checkbox_index){
                                next_checkbox_index = last_checkbox_index;
                            }
                        }

                    }
                );
                $(".nav_check_boxes").each(
                    function(index){
                        if( index == next_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == next_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
                
            if( code.toString() == KEY_CODE_UP || code.toString() == KEY_CODE_w ) {

                var previews_checkbox_index;
                var checkbox_achado = false;
                $(".nav_check_boxes").each(
                    function(index){
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == first_checkbox_index){
                                previews_checkbox_index = first_checkbox_index;
                            }
                        }
                        if(checkbox_achado == false){
                            previews_checkbox_index = index;
                        }
                    }
                );
                $(".nav_check_boxes").each(
                    function(index){
                        if( index == previews_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == previews_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
        });
            
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=cx_unid_entrada]');
            if(acao == 'Protocolar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/protocolar');
            }
        }
    );
    $('form[name=cx_unid_entrada]').submit(
       function(){
            var formulario_valido = true;
            var documentoSelecionado = $(".nav_check_boxes:checked").val();
            if (documentoSelecionado == undefined){                   
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha um Documento!</div>";
                flashMessages_by_id.hide();
                flashMessages_by_id.html(mensagem);
                flashMessages_by_id.show('pulsate');
                flashMessages_by_id.delay(2000).hide('puff');
                return false;
            }
            grid_tbody_tr.each(
                function(){
                    var this_tr = $(this);
                    var input_check_box = this_tr.find('input');
                    var is_checked_input = input_check_box.attr('checked');
                    if(is_checked_input != undefined){
                        var span_id_leitura = $(this_tr).find('span[id=leitura]');
                        if(span_id_leitura.hasClass('naolido')){
                            var mensagem = "<div class='notice'><strong>Alerta:</strong> Não é possível realizar ações sobre documentos <strong>não</strong> recebidos.</div>";
                            flashMessages_by_id.hide();
                            flashMessages_by_id.html(mensagem);
                            flashMessages_by_id.show('pulsate');
                            flashMessages_by_id.delay(6000).hide('puff');
                            formulario_valido = false;
                        }
                    }
                }
            );
            if(!formulario_valido){
                return false;
            }
        }
     );
     $("#dialog-documentos_detalhe").dialog({
        title    : 'Detalhe',
            autoOpen : false,
            modal    : false,
            show: 'fold',
            hide: 'fold',
            resizable: true,
            width: 800,
            position: [580,140,0,0],
            buttons : {
                Ok: function() {
                        $(this).dialog("close");
                }
            }
        });
    });
    function pergunta(){
    if (confirm('Tem certeza que quer enviar este formulário?')){
       document.cx_unid_entrada.submit()
    } 
</script>
<?php 
    $Prdc = new Application_Model_DbTable_SadTbPrdcProtDocProcesso();
if (count($this->data)): ?>
<form method="POST" action="" name="cx_unid_entrada">
    <div class="painel">
    <input type="submit" title="Enviar Documento/Processo Fisico Para o Protocolo" name="acao" value="Protocolar" onclick="pergunta()"/>
    </div>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th>Qtd Docs</th>
                <th>Preferencia de Postagem</th>
                <th>Destino</th>
                <th>Destinatário</th>
            </tr>
        </thead>
            <tbody>
            <?php
            $cont = 0;
                foreach($this->data as $dados): ?>
                    <tr title="Duplo click para Abrir" class="grid_rows <?php echo $this->escape($dados_input["CLASS_LIDO_TR"]); ?>" name="rowList" value="<?php echo $this->escape($dados["PRDC_ID_POSTAGEM_PROC_DOC"]); ?>" > 
                        <td>
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($dados_input["DOCM_ID_DOCUMENTO"]); ?>" name="idpostagem[]" type="checkbox" value="<?php echo $this->escape($dados["PRDC_ID_POSTAGEM_PROC_DOC"]); ?>"/>
                        </td>
                        <td> <?php echo $this->escape($dados["QTD"]) ?></td>
                        <td> <?php echo $this->escape($dados["TPPO_DS_TIPO_POSTAGEM"]) ?></td>
                        <td> <?php echo $this->escape($dados["PJUR_NO_FANTASIA"]) ?></td>
                        <td> <?php echo $this->escape($dados["POST_NM_DESTINATARIO_EXTERNO"]) ?></td>
                    </tr>
            <?php 
                $cont++;
                endforeach;
            ?>
            </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $cont; ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)?>
                </td>
            </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
</div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action;     ?>"/>        
</form>

<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>