<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>A <b>Ordenação</b> é uma funcionalidade que está presente em todas as telas dos sistemas do projeto e-Admin.</p>
    <p>O sistema permite ordenar os dados pelos campos do menu conforme a descrição:</p>
    <ul>
        <li><b>Tipo</b> - Mostra o tipo do documento conforme consta na tabela.</li>
        <li><b>Número</b> - Numeração única de documentos na Primeira Região.</li>
        <li><b>Data</b> - Data de criação ou tramitação do documento.</li>
        <li><b>Origem</b> - É a unidade de criação ou de origem do documento encaminhado.</li>
        <li><b>Autor</b> ou cadastrante - É o nome do responsável pelo documento.</li>
        <li><b>Tempo</b> - Mostra o tempo em que o documento foi criado ou tempo de tramitação.</li>
    </ul>
    <p><b>Encaminhar </b></p>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->


<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input[type=checkbox]');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
                   
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=cx_unid_ranscunho]');
            if(acao == 'Encaminhar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/encaminhar');
            }else if(acao == 'Parecer'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/parecer');
            }else if(acao == 'Arquivar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/arquivar');
            }else if(acao == 'Pesquisa'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/pesquisa');
            }else if(acao == 'Cancelar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/cancelar');
            }
        }
    );
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sisad/detalhedcmto/detalhedcmto';
                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );
    $('form[name=cx_unid_ranscunho]').submit(
       function(){
            var documentoSelecionado = $(".nav_check_boxes:checked").val();
            if (documentoSelecionado == undefined){                   
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha um Documento!</div>";
                flashMessages_by_id.hide();
                flashMessages_by_id.html(mensagem);
                flashMessages_by_id.show('pulsate');
                flashMessages_by_id.delay(2000).hide('puff');
                return false;
            }
       }
    );
    
    $("input[type=checkbox][name=input_check_all_grid]").click(
        function(){
            if($(this).attr('checked')){
                $(".nav_check_boxes").attr('checked','checked');
                $("tr[name=rowList]").addClass('hover');
            }else{
                $(".nav_check_boxes").removeAttr('checked');
                 $("tr[name=rowList]").removeClass('hover');
            }
        }
    );
    
     $("#dialog-documentos_detalhe").dialog({
                    title    : 'Detalhe',
                            autoOpen : false,
                            modal    : false,
                            show: 'fold',
                            hide: 'fold',
                            resizable: true,
                            width: 800,
                            position: [580,140,0,0],
                            buttons : {
                                    Ok: function() {
                                            $(this).dialog("close");
                                    }
                            }
     });
    });
</script>
<div class="help" id="msg_ajuda" style="display: none;" >
    <script>
        $(function(){botao_ajuda_by_id.show();})
    </script>
    <strong>Ajuda:&ensp;</strong>   
    <ul>
        <li>A caixa de rascunhos da unidade recebe documentos recêm cadastrados da unidade.</li>
        <li>Dê um duplo click para abrir o documento.</li>
        <li>Ao encaminhar um ou mais documentos os mesmos podem ser observados na caixa de encaminhados.</li>
    </ul>
</div>

<?php if (count($this->data)): ?>
<form method="POST" action="" name="cx_unid_ranscunho">
    <div class="painel">
    <input type="submit" title="Encaminha Documento/Processo"         name="acao" value="Encaminhar" />
<!--    <input type="submit" title="Dar um parecer no Documento/Processo" name="acao" value="Parecer"/>-->
    <input type="submit" title="Arquivar um Documento/Processo" disabled="disabled"        name="acao" value="Arquivar"/>
    <input type="submit" title="Pesquisa Documento/Processo" disabled="disabled"           name="acao" value="Pesquisa"/>
    <input type="submit" title="Cancelar Documento/Processo" disabled="disabled"           name="acao" value="Cancelar"/>
    </div>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th ></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/DTPD_NO_TIPO/direcao/<?php echo $this->direcao ?> ">Tipo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">Número<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/DOCM_DH_CADASTRO/direcao/<?php echo $this->direcao ?> ">Data<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/LOTA_SIGLA_LOTACAO/direcao/<?php echo $this->direcao ?> ">Origem<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/ENCAMINHADOR/direcao/<?php echo $this->direcao ?> ">Autor<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/rascunhos/ordem/DOCM_DH_CADASTRO/direcao/<?php echo $this->direcao ?> ">Tempo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
       <tbody>
            <?php foreach ($this->data as $data): ?>
                <tr title="Duplo click para Abrir" name="rowList" value="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>">
                    <td>
                        <input  class="nav_check_boxes" id="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" name="documento[]" type="checkbox" value="<?php  echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                    </td>
<!--                    <td><span  class="<?php // echo $this->escape($data["CLASS_LIDO"]); ?>" title="<?php //echo $this->escape($data["MSG_LIDO"]); ?>"></span></td>-->
                    <td></td>
                    <td><?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
                    <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>
                    <td><?php echo $this->escape($data["DOCM_DH_CADASTRO"]) ?></td>
                    <td><?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>
                    <td><?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                    <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]) ?></td>
<!--                    <td><a class="<?php //echo $this->escape($data["CLASS_ARQUIVO"]); ?>" target="_blank" title="<?php //echo $this->escape($data["MSG_ARQUIVO"]); ?>" href="<?php //echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/<?php //echo $this->escape($data["DOCM_NR_DOCUMENTO_RED"]) ?> "></a></td>-->
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)
                //-- pagination
                //-- style
                //-- partial
                //-- data
                ?></td>
            </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
</div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action;     ?>"/>   
</form>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
 <div id="dialog-documentos_conteudo"></div>
</div>
