<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input[type=radio]');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
                grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );   
        $("input[type=radio][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        $('input[name=acao]').click(
            function(){
                var acao = this.value;
                var formhelpdesk = $('form[name=helpdesk]');
                if(acao == 'Avaliar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/avaliacaoadd');
                }else if(acao == 'em Atendimento'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/tipo/atendimento');
                }else if(acao == 'Pedido de Informação'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/tipo/informacao');
                }else if(acao == 'Pedido de Informação do Desenvolvedor'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/tipo/informacaodsv');
                }else if(acao == 'Para Avaliação'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/tipo/avaliar');
                }else if(acao == 'Incluir Informação'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pedidoinformacaoadd');
                }else if(acao == 'Solicitar Informação ao Usuário Cadastrante'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/solicitarinformacao');
                }else if(acao == 'Avaliadas'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/tipo/avaliadas');
        			}
            }
        );
//        $('form[name=helpdesk]').submit(
//           function(){          
//                var solictacaoSelecionada = $("input[type=radio][name=solicitacao[]]:checked").val();
//                if (solictacaoSelecionada == undefined){ 
//                    var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
//                    $('#flashMessages').html(mensagem);
//                    return false;
//                }
//           }
//        );
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
                    autoOpen : false,
                    modal    : false,
                    show: 'fold',
                    hide: 'fold',
                    resizable: true,
                    width: 800,
                    position: [580,140,0,0],
                    buttons : {
                            Ok: function() {
                                    $(this).dialog("close");
                            }
                    }
       });
    });
</script>
<form name="helpdesk" action="" method="post" >
    <div class="painel">
        <?php 
            if($this->tipo === 'avaliar'){
        ?>
            <input type="submit" title="Avaliar a solicitação" name="acao" value="Avaliar"/>
            <fieldset>
                <legend>Solicitações</legend>
                <input type="submit" title="Solicitações Avaliadas" name="acao" value="Avaliadas"/>
                <input type="submit" title="Solicitações em Atendimento" name="acao" value="em Atendimento"/>
                <input type="submit" title="Solicitações com Pedido de Informação" name="acao" value="Pedido de Informação"/>
                <input type="submit" title="Solicitações com Pedido de Informação do Desenvolvedor" name="acao" value="Pedido de Informação do Desenvolvedor"/>
            </fieldset>
        
        <?php 
            }else if($this->tipo === 'atendimento'){
        ?>
            <fieldset>
                <legend>Solicitações</legend>
                <input type="submit" title="Solicitações Avaliadas" name="acao" value="Avaliadas"/>
                <input type="submit" title="Solicitações Para Avaliação" name="acao" value="Para Avaliação"/>
                <input type="submit" title="Solicitações com Pedido de Informação" name="acao" value="Pedido de Informação"/>
                <input type="submit" title="Solicitações com Pedido de Informação do Desenvolvedor" name="acao" value="Pedido de Informação do Desenvolvedor"/>
            </fieldset>
        <?php 
        }else if($this->tipo === 'informacao'){
        ?>
            <fieldset>
                <legend>Solicitações</legend>
                <input type="submit" title="Incluir Informação na Solicitação à TI" name="acao" value="Incluir Informação"/>
                <input type="submit" title="Solicitações Avaliadas" name="acao" value="Avaliadas"/>
                <input type="submit" title="Solicitações em Atendimento" name="acao" value="em Atendimento"/>
                <input type="submit" title="Solicitações Para Avaliação" name="acao" value="Para Avaliação"/>
                <input type="submit" title="Solicitações com Pedido de Informação do Desenvolvedor" name="acao" value="Pedido de Informação do Desenvolvedor"/>
                
            </fieldset>
        <?php 
        }else if($this->tipo === 'informacaodsv'){
        ?>
            <fieldset>
                <legend>Solicitações</legend>
                <input type="submit" title="Incluir Informação na Solicitação à TI" name="acao" value="Incluir Informação"/>
                <input type="submit" title="Solicitar Informação ao Usuário Cadastrante" name="acao" value="Solicitar Informação ao Usuário Cadastrante"/>
                <input type="submit" title="Solicitações Avaliadas" name="acao" value="Avaliadas"/>
                <input type="submit" title="Solicitações em Atendimento" name="acao" value="em Atendimento"/>
                <input type="submit" title="Solicitações Para Avaliação" name="acao" value="Para Avaliação"/>
                <input type="submit" title="Solicitações com Pedido de Informação" name="acao" value="Pedido de Informação"/>
            </fieldset>
        <?php 
        }else if($this->tipo === 'avaliadas'){
        ?>
            <fieldset>
                <legend>Solicitações</legend>
                <input type="submit" title="Solicitações em Atendimento" name="acao" value="em Atendimento"/>
                <input type="submit" title="Solicitações Para Avaliação" name="acao" value="Para Avaliação"/>
                <input type="submit" title="Solicitações com Pedido de Informação" name="acao" value="Pedido de Informação"/>
                <input type="submit" title="Solicitações com Pedido de Informação do Desenvolvedor" name="acao" value="Pedido de Informação do Desenvolvedor"/>
            </fieldset>
        <?php 
        }
        ?>
    </div>
    
<?php if (count($this->data)): ?>
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th>
<!--                        <input type="radio" name="input_check_all_grid" id="check_all" /> -->
                    </th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/ordem/TEMPO_TOTAL/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/ordem/NOME_USARIO_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sisad/caixaunidade/solicitacoesdaunidade/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data as $data): ?>
                    <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>"  style="<?php if($data["ESPERA_FLAG"] >= 0 && !is_null($data["ESPERA_FLAG"])) echo "color: #008000;"?>">
                <?php 
                    if($this->tipo === 'avaliar'){
                ?>
                        <td><input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="radio" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/></td>
                <?php 
                    }else if($this->tipo === 'atendimento'){
                ?>
                        <td><input style="display: none;" class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/></td>
                <?php 
                }else if($this->tipo === 'informacao' || $this->tipo === 'informacaodsv'){
                ?>
                        <td><input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/></td>
                <?php 
                }else if($this->tipo === 'avaliadas'){
                ?>
                        <td><input style="display: none;" class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/></td>
                <?php 
                }
                ?>
<!--                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>-->
                        <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                        <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                        <td><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"].' - '.$data['NOME_USARIO_CADASTRO']); ?></td>
                        <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?></td>
                </tr>
                <tr>
                    <td colspan="7"><?php echo $this->paginationControl($this->data, null, null, null); ?></td>
                </tr>
            </tfoot>
        </table>
    
    </div>
<?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    <input name="module" type="hidden"  value="<?php echo $this->module; ?>"/>   
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action; ?>"/> 
    <input name="tipo"     type="hidden"  value="<?php echo $this->tipo; ?>"/> 
 </form>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
 <div id="dialog-documentos_conteudo"></div>
</div>