<?php //var_dump($this->data); exit;?>
<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/transporte/motorista/add">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th width="50px">Alterar</th>          
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/motorista/index/ordem/MOTO_CD_MATR_MOTORISTA/direcao/<?php echo $this->direcao ?> ">Matrícula<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/motorista/index/ordem/COU_COD_NOME/direcao/<?php echo $this->direcao ?> ">Nome<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/motorista/index/ordem/LOTA_SIGLA_LOTACAO/direcao/<?php echo $this->direcao ?> ">Lotação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data):?>
        <tr>
            <td class="painel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/transporte/motorista/edit/id/<?php echo $data->MOTO_ID_MOTORISTA ?>" >Editar</a></td>                    
            <td><?php echo $this->escape($data["MOTO_CD_MATR_MOTORISTA"]) ?></td>
            <td><?php echo $this->escape($data["COU_COD_NOME"]) ?></td>
            <td><?php echo $this->escape($data["LOTA_SIGLA_LOTACAO"]) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="7">Total: <?php echo $this->data->getTotalItemCount()?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,
                                                                   'ordem'=> $this->ordem))
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif;?>