<?php
$this->inlineScript()
        ->appendFile($this->baseUrl() . '/js/sosti/extensaoDePrazo.js', 'text/javascript');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Esta <b>Caixa</b> permite Gerenciar a extensão de prazo.</p>
    <ul>
        <li>Para ver o conteúdo de uma solicitação, clica-se duas vezes onde o cursor estiver posicionado.</li>
        <li>O sistema mostrará a tela <i>Detalhe</i>, onde constam os dados do Documento (solicitação) e o seu <i>Histórico</i>.</li>
    </ul>
    <p>Após a escolha da(s) solicitação(ões) poderá clicar em Gerenciar Extensão de Prazo e decidir se aceita ou não descrevendo os motivos.</p>

    <br />
    <span id="botao_ajuda_recolhe" ></span>
</div>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<form name="helpdesk" action="" method="post" >
    <?php if (count($this->data)): ?>
        <div class="painel">
            <input type="submit" title="Gerenciar Extensão de Prazo" name="acao" value="Gerenciar Extensão de Prazo"/>
            <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
            <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
        </div>
        <div id="container_pagination">
            <table class="grid">
                <thead>
                    <tr>
                        <th><input type="checkbox" name="input_check_all_grid" id="check_all" /></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th >Prazo atual</th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSPA_DT_PRAZO_SOLICITADO/direcao/<?php echo $this->direcao ?> ">Extensão de Prazo Solicitada<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    /**
                     * Configurações do horário de expediente
                     */
                    $SosTbGrexGrupoServExped = new Application_Model_DbTable_SosTbGrexGrupoServExped();
                    $tempoSla = new App_Sosti_TempoSla();
                    $expedienteNormal = $SosTbGrexGrupoServExped->getExpedientePorGrupoPorNomeExpediente(2, "NORMAL");
                    $expedienteEmergencia = $SosTbGrexGrupoServExped->getExpedientePorGrupoPorNomeExpediente(2, "EMERGENCIAL");

                    $expediente = array('NORMAL' => array('INICIO' => $expedienteNormal["INICIO"], 'FIM' => $expedienteNormal["FIM"]), 'EMERGENCIAL' => array('INICIO' => $expedienteEmergencia['INICIO'], 'FIM' => $expedienteEmergencia['FIM']));
                    $expediente["NORMAL"]["DIA_UTIL_SEGUNDOS"] = $tempoSla->converteHorasParaSegundos($expediente["NORMAL"]["FIM"]) - $tempoSla->converteHorasParaSegundos($expediente["NORMAL"]["INICIO"]);
                    $expediente["EMERGENCIAL"]["DIA_UTIL_SEGUNDOS"] = $tempoSla->converteHorasParaSegundos($expediente["EMERGENCIAL"]["FIM"]) - $tempoSla->converteHorasParaSegundos($expediente["EMERGENCIAL"]["INICIO"]);
                    $expediente["NORMAL"]["DIA_UTIL_HORAS"] = $expediente["NORMAL"]["DIA_UTIL_SEGUNDOS"] / 60 / 60;
                    $expediente["EMERGENCIAL"]["DIA_UTIL_HORAS"] = $expediente["EMERGENCIAL"]["DIA_UTIL_SEGUNDOS"] / 60 / 60;

                    $SLA = $tempoSla->TempoTotalPedidoInfor($this->data, 'MOFA_ID_MOVIMENTACAO', 'MOVIMENTACAO', 'DATA_ATUAL', '', 'ASSO_IC_ATENDIMENTO_EMERGENCIA', $expediente);

                    $TempoSlaDesenvolvimento = new App_Sosti_TempoSlaDesenvolvimento();
                    $PrazoSlaDesenvolvimento = $TempoSlaDesenvolvimento->PrazoSlaDesenvolvimento($this->data, 'MOFA_ID_MOVIMENTACAO', 'MOVIMENTACAO', 'SSPA_DT_PRAZO', 'CORRETIVA', 'ASSO_IC_ATENDIMENTO_EMERGENCIA', 'ASSO_IC_SOLUCAO_PROBLEMA', 'ASSO_IC_SOLUCAO_CAUSA_PROBLEMA', 'ASIS_PRZ_SOL_PROBLEMA', 'ASIS_PRZ_SOL_CAUSA_PROBLEMA', 'ASIS_PRZ_EXECUCAO_SERVICO', $expediente);
                    
                    foreach ($this->data as $data):

                        $data['DADOS_INPUT'] = Zend_Json::encode($data);
                        $data['TEMPO_TRANSCORRIDO'] = $tempoSla->FormataSaidaSegundos($SLA[$data['MOFA_ID_MOVIMENTACAO']]["TEMPO_UTIL_TOTAL"], $SLA[$data['MOFA_ID_MOVIMENTACAO']]["DIA_UTIL_HORAS"]);
                        $saidaPrazo = null;
                        $cor = null;
                        $prazosegundo = null;
                        $percentualrestante = null;
                        $prazototal = null;

                        if (!is_null($PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]['PRAZO_SEGUNDOS_UTEIS'])) {

                            $prazosegundo = $PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]['PRAZO_SEGUNDOS_UTEIS'];
                            $restante = $PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]['PRAZO_SEGUNDOS_UTEIS'] - $SLA[$data['MOFA_ID_MOVIMENTACAO']]["TEMPO_UTIL_TOTAL"];
                            $percentualrestante = $restante * 100 / $prazosegundo;
                            $percentualrestante = (float) sprintf('%.1f', $percentualrestante);
                            if ($percentualrestante >= 80) {
                                $cor = "green";
                                $legenda = "Verde: prazo restante >= 80% e prazo restante <= 100%.";
                            } else
                            if ($percentualrestante >= 60) {
                                $cor = "purple";
                                $legenda = "Roxo: prazo restante >= 60% e prazo restante < 80%.";
                            } else
                            if ($percentualrestante >= 40) {
                                $cor = "blue";
                                $legenda = "Azul: prazo restante >= 40% e prazo restante < 60%";
                            } else
                            if ($percentualrestante >= 20) {
                                $cor = "#CD950C";
                                $legenda = "Amarelo: prazo restante >= 20% e prazo restante < 40%";
                            } else
                            if ($percentualrestante > 0) {
                                $cor = "orange";
                                $legenda = "Laranjado: prazo restante > 0% e prazo restante < 20%";
                            } else
                            if ($percentualrestante <= 0) {
                                $cor = "red";
                                $legenda = "Vermelho: prazo restante < 0%";
                            }
                            if (!is_null($PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]["PRAZO_DATA"])) {
                                $saidaPrazo = $PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]["PRAZO_DATA"];
                            } else {
                                $saidaPrazo = $this->escape($tempoSla->FormataSaidaSegundos($restante, $SLA[$data['MOFA_ID_MOVIMENTACAO']]["DIA_UTIL_HORAS"]));
                            }
                            $prazototal = $this->escape($tempoSla->FormataSaidaSegundos($PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]['PRAZO_SEGUNDOS_UTEIS'], $SLA[$data['MOFA_ID_MOVIMENTACAO']]["DIA_UTIL_HORAS"]));
                        } else if (!is_null($PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]['SSPA_DT_PRAZO'])) {
                            $dataInicial = $data['MOVIMENTACAO'];
                            $timeStampInicial = (int) mktime(substr($dataInicial, 11, 2), substr($dataInicial, 14, 2), substr($dataInicial, 17, 2), substr($dataInicial, 3, 2), substr($dataInicial, 0, 2), substr($dataInicial, 6, 4));
                            $dataPrazo = $data['SSPA_DT_PRAZO'];
                            $timeStampFinal = (int) mktime(substr($dataPrazo, 11, 2), substr($dataPrazo, 14, 2), substr($dataPrazo, 17, 2), substr($dataPrazo, 3, 2), substr($dataPrazo, 0, 2), substr($dataPrazo, 6, 4));
                            $dataAtual = $data['DATA_ATUAL'];
                            $timeStampAtual = (int) mktime(substr($dataAtual, 11, 2), substr($dataAtual, 14, 2), substr($dataAtual, 17, 2), substr($dataAtual, 3, 2), substr($dataAtual, 0, 2), substr($dataAtual, 6, 4));
                            $prazosegundo = $timeStampFinal - $timeStampInicial;
                            $restante = $timeStampFinal - $timeStampAtual;
                            $percentualrestante = $restante * 100 / $prazosegundo;
                            $percentualrestante = (float) sprintf('%.1f', $percentualrestante);
                            if ($percentualrestante >= 80) {
                                $cor = "green";
                                $legenda = "Verde: prazo restante >= 80% e prazo restante <= 100%.";
                            } else
                            if ($percentualrestante >= 60) {
                                $cor = "purple";
                                $legenda = "Roxo: prazo restante >= 60% e prazo restante < 80%.";
                            } else
                            if ($percentualrestante >= 40) {
                                $cor = "blue";
                                $legenda = "Azul: prazo restante >= 40% e prazo restante < 60%";
                            } else
                            if ($percentualrestante >= 20) {
                                $cor = "#CD950C";
                                $legenda = "Amarelo: prazo restante >= 20% e prazo restante < 40%";
                            } else
                            if ($percentualrestante > 0) {
                                $cor = "orange";
                                $legenda = "Laranjado: prazo restante > 0% e prazo restante < 20%";
                            } else
                            if ($percentualrestante <= 0) {
                                $cor = "red";
                                $legenda = "Vermelho: prazo restante < 0%";
                            }
                            $saidaPrazo = $dataPrazo;
                        } else if ($PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]["PRAZO_CORRIDO_PADRAO"] == true) {
                            $dataInicial = $data['MOVIMENTACAO'];
                            $timeStampInicial = (int) mktime(substr($dataInicial, 11, 2), substr($dataInicial, 14, 2), substr($dataInicial, 17, 2), substr($dataInicial, 3, 2), substr($dataInicial, 0, 2), substr($dataInicial, 6, 4));
                            $dataPrazo = $PrazoSlaDesenvolvimento[$data['MOFA_ID_MOVIMENTACAO']]["PRAZO_DATA"];
                            $timeStampFinal = (int) mktime(substr($dataPrazo, 11, 2), substr($dataPrazo, 14, 2), substr($dataPrazo, 17, 2), substr($dataPrazo, 3, 2), substr($dataPrazo, 0, 2), substr($dataPrazo, 6, 4));
                            $dataAtual = $data['DATA_ATUAL'];
                            $timeStampAtual = (int) mktime(substr($dataAtual, 11, 2), substr($dataAtual, 14, 2), substr($dataAtual, 17, 2), substr($dataAtual, 3, 2), substr($dataAtual, 0, 2), substr($dataAtual, 6, 4));
                            $prazosegundo = $timeStampFinal - $timeStampInicial;
                            $restante = $timeStampFinal - $timeStampAtual;
                            $percentualrestante = $restante * 100 / $prazosegundo;
                            $percentualrestante = (float) sprintf('%.1f', $percentualrestante);
                            if ($percentualrestante >= 80) {
                                $cor = "green";
                                $legenda = "Verde: prazo restante >= 80% e prazo restante <= 100%.";
                            } else
                            if ($percentualrestante >= 60) {
                                $cor = "purple";
                                $legenda = "Roxo: prazo restante >= 60% e prazo restante < 80%.";
                            } else
                            if ($percentualrestante >= 40) {
                                $cor = "blue";
                                $legenda = "Azul: prazo restante >= 40% e prazo restante < 60%";
                            } else
                            if ($percentualrestante >= 20) {
                                $cor = "#CD950C";
                                $legenda = "Amarelo: prazo restante >= 20% e prazo restante < 40%";
                            } else
                            if ($percentualrestante > 0) {
                                $cor = "orange";
                                $legenda = "Laranjado: prazo restante > 0% e prazo restante < 20%";
                            } else
                            if ($percentualrestante <= 0) {
                                $cor = "red";
                                $legenda = "Vermelho: prazo restante < 0%";
                            }
                            $saidaPrazo = $dataPrazo;
                        }

                        $saidaServicoSistema = null;
                        if (!is_null($data["OSIS_NM_OCORRENCIA"])) {
                            $saidaServicoSistema = $data["OSIS_NM_OCORRENCIA"] . " - " . $data["CTSS_NM_CATEGORIA_SERVICO"] . " - N." . $data["ASIS_IC_NIVEL_CRITICIDADE"];

                            if ($data["ASSO_IC_SOLUCAO_PROBLEMA"] == "S") {
                                $tipoProblemaCausaMsg = "Problema";
                            } else {
                                $tipoProblemaCausaMsg = "Causa";
                            }

                            if ($data["ASSO_IC_ATENDIMENTO_EMERGENCIA"] == 'S' && !is_null($data["CORRETIVA"])) {
                                $saidaServicoSistema = $data["OSIS_NM_OCORRENCIA"] . " - <span><strong>" . $data["CTSS_NM_CATEGORIA_SERVICO"] . "</strong></span> - N." . $data["ASIS_IC_NIVEL_CRITICIDADE"] . " Tipo: " . $tipoProblemaCausaMsg;
                            }
                        }
                        ?>
                        <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td>
                                <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                            </td>
                            <td><?php echo $this->escape($data["MASCARA_DOCM"]); ?></td>
                            <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                            <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                            <td title="<?= $legenda ?>" style=" color: <?= ($cor) ? $cor : '' ?>;" >
                                <?= $saidaPrazo ?>
                                <span class="gridtdprazo" title="" style="float: right;float: bottom; color: <?= $cor ?>; ">
                                    <strong><?= (!is_null($percentualrestante)) ? $percentualrestante . '%' : '' ?></strong>
                                </span>
                            </td>
                            <td><?php echo $this->escape($data['SSPA_DT_PRAZO_SOLICITADO']); ?></td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <?php echo $this->paginationControl($this->data, null, null, null); ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div class="painel">
                <input type="submit" title="Gerenciar Extensão de Prazo" name="acao" value="Gerenciar Extensão de Prazo"/>
                <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
                <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
            </div>
        <?php else: ?>

            <?php if ($this->ultima_pesq): ?>
                <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
            <?php else: ?>
                <p><br/>Não existem registros</p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php echo $this->partial('_partials/caixahiddeninputs.phtml', array('view' => $this)); ?>
</form>
<div id="dialog-documentos_detalhe">
</div>