<?php
$this->inlineScript()
        ->appendFile($this->baseUrl() . '/js/sosti/extensaoDePrazo.js', 'text/javascript');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function() {
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Esta <b>Caixa</b> permite Gerenciar a extensão de prazo.</p>
    <ul>
        <li>Para ver o conteúdo de uma solicitação, clica-se duas vezes onde o cursor estiver posicionado.</li>
        <li>O sistema mostrará a tela <i>Detalhe</i>, onde constam os dados do Documento (solicitação) e o seu <i>Histórico</i>.</li>
    </ul>
    <p>Após a escolha da(s) solicitação(ões) poderá clicar em Gerenciar Extensão de Prazo e decidir se aceita ou não descrevendo os motivos.</p>

    <br />
    <span id="botao_ajuda_recolhe" ></span>
</div>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<form name="helpdesk" action="" method="post" >
    <?php if (count($this->data)): ?>
        <div class="painel">
            <input type="submit" title="Gerenciar Extensão de Prazo" name="acao" value="Gerenciar Extensão de Prazo"/>
            <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
            <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
        </div>
        <div id="container_pagination">
            <table class="grid">
                <thead>
                    <tr>
                        <th><input type="checkbox" name="input_check_all_grid" id="check_all" /></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/MOVI_DH_ENCAMINHAMENTO/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/sla/autorizaextensaoprazo/ordem/SSPA_DT_PRAZO_SOLICITADO/direcao/<?php echo $this->direcao ?> ">Extensão de Prazo Solicitada<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    </tr>
                </thead>
                <?php
                $tempoInicial = new App_Sosti_TempoSla();
                ?>
                <tbody>
                    <?php
                    foreach ($this->data as $data):
                        $data['DADOS_INPUT'] = Zend_Json::encode($data);
                        $data['TEMPO_TRANSCORRIDO'] = $tempoInicial->tempoTotalHelpdesk($data['MOVIMENTACAO'], '', '07:00:00', '20:00:00');
                        ?>
                        <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td>
                                <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                            </td>
                            <td><?php echo $this->escape($data["MASCARA_DOCM"]); ?></td>
                            <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                            <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                            <td><?php echo $this->escape($data['SSPA_DT_PRAZO_SOLICITADO']); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <?php echo $this->paginationControl($this->data, null, null, null); ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div class="painel">
                <input type="submit" title="Gerenciar Extensão de Prazo" name="acao" value="Gerenciar Extensão de Prazo"/>
                <input type="submit" title="Gerar PDF" name="acao" value="PDF"/>
                <input type="submit" title="Gerar Excel" name="acao" value="Excel"/>
            </div>
        <?php else: ?>

            <?php if ($this->ultima_pesq): ?>
                <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
            <?php else: ?>
                <p><br/>Não existem registros</p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php echo $this->partial('_partials/caixahiddeninputs.phtml', array('view' => $this)); ?>
</form>
<div id="dialog-documentos_detalhe">
</div>