<script>

    $(function(){
        $('.detalhes').click(function(){
            currentID = $(this).attr('id');
            $('#loc'+currentID).toggle();
    
        });
        $('#solic').submit(function(){
    
            $('#Pesquisar').attr('value', 'Pesquisando...');
            $('#Pesquisar').attr('Disabled', 'Disabled');
            $('#info').removeClass('grid');
        });
    });
</script>
<style type="text/css">

    table{
        margin-top: 30px;
    }

    tbody tr:first-child th{
        background-color: #e1e1e1;
        border-top: 2px solid #ccc;
    }
    
    tbody tr:nth-child(2) th{
        background-color: #f0f0f0;
        border-top: 1px solid #fff;
    }
    
    tbody tr:last-child td{
        text-align: right;
        font-weight: 700;
    }
    
</style>
<div id="container_pagination">
    <table class="grid2">
        <thead>
            <tr>
                <th colspan="5">
                    Relatório Detalhado de Movimentação de Licenças de Software
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="5">
                    Total <?php echo $this->data->getTotalItemCount() ?>
                </td>
            </tr>
            <tr>
                <td colspan="5">
                    <?php echo $this->paginationControl($this->data, null, null, null); ?>
                </td>
            </tr>
        </tfoot>
        <?php if (count($this->data)): ?>
            <?php
            $objlicencasHistorico = new Application_Model_DbTable_SosTbLtpsTipoSoftware ();
            foreach ($this->data as $data):
                $RowsLicenca = $objlicencasHistorico->getSoftwareTipoLicencaHistorico($data["LTPS_ID_TP_SOFTWARE"]);
                ?>
                <tbody>
                    <tr>
                        <th colspan="5">
                            <?php echo $this->escape($data["LTPS_DS_TP_SOFTWARE"]); ?>
                        </th>
                    </tr>
                    <tr>
                        <th>Solicitação Número</th>
                        <th>Descrição Software</th>
                        <th>Número Tombo</th>
                        <th>Matrícula Solicitante</th>
                        <th>Setor</th>
                    </tr>
                    <?php
                    $i = 0;
                    foreach ($RowsLicenca as $LicencaInfo):
                        ?>
                        <tr>
                            <td><?php echo $LicencaInfo['DOCM_NR_DOCUMENTO'] ?></td>
                            <td><?php echo $LicencaInfo['LSFW_DS_SOFTWARE'] ?></td>
                            <td><?php echo $LicencaInfo['SSOL_NR_TOMBO'] ?></td>
                            <td><?php echo $LicencaInfo['DOCM_CD_MATRICULA_CADASTRO'] . ' - ' . $LicencaInfo['NOME_CADASTRO'] ?></td>
                            <td><?php echo $LicencaInfo['LOTA_SIGLA_LOTACAO'] ?></td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                    <tr>
                        <td colspan="5">Total Licenças Usadas: <?php echo $i; ?></td>
                    </tr>
                </tbody>
            <?php endforeach; ?>
        <?php else: ?>
            <h3>Não existem registros.</h3>
        <?php endif; ?>
    </table>
</div>