<script>
    $(function(){
        $('.detalhes').click(function(){
            currentID = $(this).attr('id');
            $('#loc'+currentID).toggle();
    
        });
        
        /**
         * Configurando entrada de dados no campo
         */
        $('#NR_TOMBO').keyup(function(){
            if(isNaN($(this).val())){
                $(this).val('');
            }else{
                var x = $(this).val().replace(".","");
                $(this).val(x);
            }
        });
    });
</script>

<div id="container_pagination">
    <?php echo $this->form->setAction($this->baseUrl('sosti/labrelatorios/solicitacoesportombo/NR_TOMBO/'.$this->nrtombo)); ?>
    <?php if (count($this->data)): ?>
        <table class="grid">
            <thead>
                <tr>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labrelatorios/solicitacoesportombo/ordem/SSES_NR_TOMBO/direcao/<?php echo $this->direcao ?>/NR_TOMBO/<?php echo $this->nrtombo; ?> ">Detalhes<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labrelatorios/solicitacoesportombo/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?>/NR_TOMBO/<?php echo $this->nrtombo; ?> ">Documento<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labrelatorios/solicitacoesportombo/ordem/SSES_NR_TOMBO/direcao/<?php echo $this->direcao ?>/NR_TOMBO/<?php echo $this->nrtombo; ?> ">Número do Tombo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labrelatorios/solicitacoesportombo/ordem/SSES_SG_TIPO_TOMBO/direcao/<?php echo $this->direcao ?>/NR_TOMBO/<?php echo $this->nrtombo; ?> "> Tombo Tipo<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/labrelatorios/solicitacoesportombo/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?>/NR_TOMBO/<?php echo $this->nrtombo; ?> ">Serviço<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->data as $data): ?>
                    <tr>
                        <td class="painel" ><a style="margin: 4px;" title="Detalhes de Localização" class="detalhes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>">Detalhes</a></td>
                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>
                        <td><?php echo $this->escape($data["NU_TOMBO"]); ?></td>
                        <td><?php //echo $this->escape($data["SSES_SG_TIPO_TOMBO"]); ?> T </td>
                        <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                    </tr>
                    <tr id="loc<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" style="display:none;">
                        <td colspan="6">
                            <fieldset>
                                <legend>Detalhes
                                </legend>
                                <div><strong>Seção:</strong> <?php echo $this->escape($data["DOCM_SG_SECAO_GERADORA"]); ?></div>
                                <div><strong>Lotação:</strong> <?php echo $this->escape($data["LOTA_DSC_LOTACAO"]); ?></div>
                                <div><strong>Data Cadastro:</strong> <?php echo $this->escape($data["DATA_CADASTRO"]); ?></div>
                                <div><strong>Documento Número:</strong> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></div>
                                <div><strong>Matrícula Cadastro:</strong> <?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"]); ?></div>
                                <div><strong>Assunto:</strong> <?php echo $data["DOCM_DS_ASSUNTO_DOC"]; ?></div>
                                <div><strong>Arquivado:</strong> <?php echo html_entity_decode($this->escape($data["DOCM_ARQUIVADO"])); ?></div>
                                <div><strong>Email Externo:</strong> <?php echo $this->escape($data["SSOL_DS_EMAIL_EXTERNO"]); ?></div>
                                <div><strong>Telefone Externo:</strong> <?php echo $this->escape($data["SSOL_NR_TELEFONE_EXTERNO"]); ?></div>
                            </fieldset>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php
            echo $this->data->getTotalItemCount()
            ////-- pagination
            //-- style
            //-- partial
            //-- data
            ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">
    <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
        <p>Não existem registros.</p>
<?php endif; ?>
</div>