<?php if($this->dashboardSosti == 'ATIVO'){ ?>
<?php
$this->headLink()
        ->appendStylesheet($this->baseUrl('/css/dashboard.css'), 'screen');
$this->inlineScript()
        ->appendFile($this->baseUrl('/js/highcharts.js'))
        ->appendFile($this->baseUrl('/js/dashboard/dadosBar.js'))
        ->appendFile($this->baseUrl('/js/dashboard/dadosColumn.js'))
        ->appendFile($this->baseUrl('/js/dashboard/dadosPie.js'))
        ->appendFile($this->baseUrl('/js/dashboard/dadosGrid.js'))
        ->appendFile($this->baseUrl('/js/dashboard/graficoPie.js'))
        ->appendFile($this->baseUrl('/js/dashboard/dashboard.js'))
;
?>
<div class="g-tools span-24 first last">
    <?php
    
    $module = 'sosti';
    $config = new Zend_Config_Ini(APPLICATION_PATH . '/configs/dashboardSosti.ini', 'production');

    $j = 0;
    foreach ($config->$module->dashboard as $cfg):
        $tam = ($j % 2 != 0) ? '11' : '12';
        $id = 'amg_' . $j;
        $idg = 'g_' . $j;
        $rodape = '';
        $params = '';

        if (isset($cfg->params) && $cfg->params != '') {
            $params = '/' . $cfg->params;
        }
        if ($cfg->footer != '') {
            $rodape = '<div class="footer">' . $cfg->footer . '</div>';
        }
        ?>
        <div id="<?php echo $id; ?>" class="grafico portlet portlet-cinza span-<?php echo $tam; ?> " data-grafico="<?php echo $cfg->type; ?>" data-url="<?php echo $this->url(array('module' => $cfg->module, 'controller' => $cfg->controller, 'action' => $cfg->action)), $params; ?>">
            <h3><?php echo $cfg->title; ?></h3>
            <div id="<?php echo $idg; ?>" class="content" style="min-height:240px;">
            </div>
            <?php echo $rodape; ?>
        </div> 
        <?php
        $j++;
    endforeach;
    ?>
</div>
<?php }       
?>