<?php
/**
  $this->documento;
 */
?>
<div style="margin-left: 20px" id="resumo_metadados_leitura-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
    <!-- O CONTEÚDO VEM DINAMICAMENTE PELO JQUERY -->
</div>
<div id="visualizador_pdf-<?= $this->documento['DOCM_ID_DOCUMENTO'] ?>">
    <!-- O CONTEÚDO VEM DINAMICAMENTE PELO JQUERY -->
</div>

<div class="span-4" id="loading">
    <div style="margin: 1px 0 0 30px;" class="span-1 last"><img src="<?= $this->baseUrl() ?>/img/ajax-loader_1.gif"/></div><div class="span-2"><strong>Aguarde...</strong></div>
</div>
