<?php 
    $this->inlineScript()->appendFile($this->baseUrl() . '/js/tooltipster-1.2/js/jquery.tooltipster.min.js', 'text/javascript');
?>
<script>
    $(document).ready(function() {
        $('.tooltip').tooltipster({
            fixedWidth: 650,
            position: 'bottom-left'
        });
    });
</script>

<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    
<p><b>Garantia Desenvolvimento<span style="text-decoration: underline;"></span></b></p>
<p>&nbsp;</p>
<p><b><i>A &nbsp;funcionalidades de Garantia &nbsp;afeta as seguintes funcionalidades: </i></b></p>
<ul>
<li>- <b>Encaminhamento da Caixa de Gest&atilde;o de Demandas de TI.</b></li>
</ul>
<p>Nesta funcionalidade &eacute; poss&iacute;vel solicitar garantia por meio de uma justificativa. &Eacute; necess&aacute;rio somente selecionar o <i>checkbox</i>: solicitar garantia. E justificar seu pedido.</p>
<ul>
<li><b>- Baixa da Caixa de Desenvolvimento e Sustenta&ccedil;&atilde;o.</b></li>
</ul>
<p>Caso a justificativa seja aceita pelo atendente &nbsp;que baixar a solicita&ccedil;&atilde;o a negocia&ccedil;&atilde;o de garantia &eacute; terminada e a solicita&ccedil;&atilde;o &eacute; considerada garantia.</p>
<p>Caso contr&aacute;rio a solicita&ccedil;&atilde;o que &nbsp;o pedido de garantia for &nbsp;negado constar&aacute; na caixa de diverg&ecirc;ncia para negocia&ccedil;&atilde;o posterior, por meio das op&ccedil;&otilde;es de concordo &nbsp;e discordo.</p>
<p>Cada gerente &eacute; respons&aacute;vel por sanar as diverg&ecirc;ncias de seus respectivos sistemas.<span style="text-decoration: underline;"></span></p>
<ul>
<li><b>- Diverg&ecirc;ncia Garantia. </b></li>
</ul>
<p>Nesta caixa constam todas as solicita&ccedil;&otilde;es que entraram em diverg&ecirc;ncia.</p>
<p>Existe a a&ccedil;&atilde;o de avaliar, onde constam as op&ccedil;&otilde;es concordo e discordo.</p>
<p>Caso a op&ccedil;&atilde;o de concordo for selecionada a solicita&ccedil;&atilde;o <b><i>n&atilde;o</i></b> ser&aacute; considerada garantia, caso contr&aacute;rio <b><i>sim</i></b>.</p>
<p>At&eacute; o momento do fechamento do SLA &eacute; poss&iacute;vel alterar a decis&atilde;o de concord&acirc;ncia. Ap&oacute;s o fechamento essas solicita&ccedil;&otilde;es n&atilde;o ser&atilde;o mais listadas.<span style="text-decoration: underline;"></span></p>
    
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>
<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){
        
        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input[type=checkbox]');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                  grid_tbody_tr.each(
                    function(){
                        var this_tr = $(this);
                        var input_check_box = $(this).find('input');
                        
                        input_check_box.removeAttr('checked');
                        this_tr.removeAttr('marcado');
                        this_tr.removeClass('hover');
                    }
                  );
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    if(! div_dialog_by_id.dialog( "isOpen" )){
                        div_dialog_by_id.dialog("open");
                    }
                },
                success: function(data) {
                    div_dialog_by_id.html(data);
                    
                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        ); 
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
            
            
        var form_valido = false;
        var acao = '';
        $('input[name=acao]').click(
            function(){
                acao = this.value;
                var formhelpdesk = $('form[name=helpdesk]');
                if(acao == 'Avaliar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/garantia/concordar');
                }else if(acao == 'Editar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/garantia/concordar');
                }
           }
        );
        
        $("#Filtrar").click( 
            function(){
                form_valido = true;
            }
        );
        
        $('form[name=helpdesk]').submit(
           function(){
                
               if(form_valido){
                   return true;
               }
               
               var solictacaoSelecionada = $("input[type=checkbox][name=solicitacao[]]:checked").val();
                if (solictacaoSelecionada == undefined){ 
                    var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
                    $('#flashMessages').html(mensagem);
                    return false;
                }else{
                    if(acao == 'Editar'){
                        var contador = 0;
                        var checados = $("input[type=checkbox][name=solicitacao[]]:checked");
                        checados.each(
                            function(){
                                contador++;
                            }
                        );
                        if(contador == 1){
                            return true;
                        }else{
                            var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha somente uma solicitação para edição.</div>";
                            $('#flashMessages').html(mensagem);
                            return false;
                        }
                    }else{
                        return true;
                    }
                }
                
           }
        );
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
                    autoOpen : false,
                    modal    : false,
                    show: 'fold',
                    hide: 'fold',
                    resizable: true,
                    width: 800,
                    position: [580,140,0,0],
                    buttons : {
                            Ok: function() {
                                    $(this).dialog("close");
                            }
                    }
       });
    });
</script>

<script type="text/javascript">
$(function() {
    $("#DOCM_CD_MATRICULA_CADASTRO").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxnomesolicitante",
        minLength: 3,
        delay: 300,
        select: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val(ui.item.value);
                            }
                },
        change: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val(ui.item.value);
                            }
        }

    }).keyup(
            function(){
                if(this.value == ""){
                    $("#DOCM_CD_MATRICULA_CADASTRO_VALUE").val('');
                }
    });

    $("#SSOL_CD_MATRICULA_ATENDENTE").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxnomesolicitante",
        minLength: 3,
        delay: 300,
        select: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val(ui.item.value);
                            }
                },
        change: function( event, ui ) {
                            if( ui.item.value != null ){ 
                                $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val(ui.item.value);
                            }
        }

    }).keyup(
            function(){
                if(this.value == ""){
                    $("#SSOL_CD_MATRICULA_ATENDENTE_VALUE").val('');
                }
    });

    $("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
        source: base_url+"/sosti/solicitacao/ajaxunidade",
        minLength: 3,
        delay: 500,
        select: function( event, ui ) {
                                if( ui.item.value != null ){ 
                                    $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val(ui.item.value);
                                }
                },
        change: function( event, ui ) {
                                if( ui.item.value != null ){  
                                     $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val(ui.item.value);
                                }
        }
    }).keyup(
            function(){
                if(this.value == ""){
                    $("#DOCM_CD_LOTACAO_GERADORA_VALUE").val('');
                }
    });



    $('#pesquisar')
        .click(function() {
                var pesq_div = $("#pesq_div");

                if(pesq_div.css('display') == "none"){
                    pesq_div.show('');
                }else{
                    pesq_div.hide('');
                }
        });

    $('#Filtrar').button();

    $("#botao_ajuda_recolhe").click(
       function(){
            $("#pesq_div").hide();
            $("#pesquisar").show();
    });
});
</script>
<script type="text/javascript">
            $(function() {
                var dates = $( "#DATA_INICIAL, #DATA_FINAL" ).datepicker({
			dateFormat: 'dd/mm/yy',
			dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
			dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
					     'Outubro','Novembro','Dezembro'],
 			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
 			nextText: 'Próximo',
 		        prevText: 'Anterior',
			changeMonth: true,
			numberOfMonths: 1,
			changeMonth: true,
			changeYear: true,
			changeMonth: true,
			onSelect: function( selectedDate ) {
				var option = this.id == "DATA_INICIAL" ? "minDate" : "maxDate",
					instance = $( this ).data( "datepicker" );
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
			}
		});
                
                var dates_cadastro = $( "#DATA_INICIAL_CADASTRO, #DATA_FINAL_CADASTRO" ).datepicker({
			dateFormat: 'dd/mm/yy',
			dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
			dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
					     'Outubro','Novembro','Dezembro'],
 			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
 			nextText: 'Próximo',
 		        prevText: 'Anterior',
			changeMonth: true,
			numberOfMonths: 1,
			changeMonth: true,
			changeYear: true,
			changeMonth: true,
			onSelect: function( selectedDate ) {
				var option = this.id == "DATA_INICIAL_CADASTRO" ? "minDate" : "maxDate",
					instance = $( this ).data( "datepicker" );
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates_cadastro.not( this ).datepicker( "option", option, date );
			}
		});
	    }); 
</script>
<script type="text/javascript">
/**
* Tratamento campos de pesquisa por serviço
*/
$(function() {
    if( $('#SERVICO-nomecompleto').is(':checked') == true){
                
        $('#SSER_DS_SERVICO').hide();
        $('#SSER_DS_SERVICO-label').hide();
        $('#SSER_DS_SERVICO').attr('disabled', 'disabled');

        $('#SSER_ID_SERVICO').show();
        $('#SSER_ID_SERVICO-label').show();
        $('#SSER_ID_SERVICO').removeAttr('disabled');
        var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
        description_obj.show();

    }else if ( $('#SERVICO-partenome').is(':checked') == true) {

        $('#SSER_ID_SERVICO').hide();
        $('#SSER_ID_SERVICO-label').hide();
        $('#SSER_ID_SERVICO').attr('disabled', 'disabled');
        var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
        description_obj.hide();

        $('#SSER_DS_SERVICO').show();
        $('#SSER_DS_SERVICO-label').show();
        $('#SSER_DS_SERVICO').removeAttr('disabled');
    } 
    $('input[type=radio][name=SERVICO]').click(
    function(){
        if(this.value == 'nomecompleto'){

            $('#SSER_DS_SERVICO').hide();
            $('#SSER_DS_SERVICO').val("");
            $('#SSER_DS_SERVICO-label').hide();
            $('#SSER_DS_SERVICO').attr('disabled', 'disabled');

            $('#SSER_ID_SERVICO').show();
            $('#SSER_ID_SERVICO-label').show();
            $('#SSER_ID_SERVICO').removeAttr('disabled');
            var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
            description_obj.show();

        }else if (this.value == 'partenome'){
            $('#SSER_ID_SERVICO').hide();
            $('#SSER_ID_SERVICO').val("");
            $('#SSER_ID_SERVICO-label').hide();
            $('#SSER_ID_SERVICO').attr('disabled', 'disabled');
            var description_obj = $('#SSER_ID_SERVICO-element').find('.description');
            description_obj.hide();

            $('#SSER_DS_SERVICO').show();
            $('#SSER_DS_SERVICO-label').show();
            $('#SSER_DS_SERVICO').removeAttr('disabled');
        }

    });
}); 
</script>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<fieldset style="display:inline;">
    <legend>Filtro da Caixa</legend>
    <div class="painel">
        <div class="painel" >
            <input type="button" title="Último Filtro" name="acao" value="Filtro" id="pesquisar">
            <a title="Novo Filtro" name="acao" value="Filtrar" id="ultimo_filtro" href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/nova/1" >Limpar Filtro/Retirar Filtro</a>
            &emsp;&emsp;<span style="color: #2E4557;"><strong><?php if( $this->ultima_pesq == true) echo "Filtro Ativo"; else echo "Filtro Inativo"; ?></strong></span>
        </div> 
    </div>
    <div id="pesq_div"  style="display: none;" >
        <?php echo $this->form; ?>
        <span id="botao_ajuda_recolhe" ></span>
    </div>
</fieldset>
<form name="helpdesk" action="" method="post" >
    <?php if (count($this->data)): ?>
    <div class="painel">
        <input type="submit" title="Avaliar a justificativa de Recusa da garantia" name="acao" value="Avaliar"/>
    </div>
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th><input type="checkbox" name="input_check_all_grid" id="check_all" /></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/NEGA_DS_JUST_ACEITE_RECUSA/direcao/<?php echo $this->direcao ?> ">Just. Recusa<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/NEGA_IC_CONCORDANCIA/direcao/<?php echo $this->direcao ?> ">Concordância<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/NEGA_DS_JUSTIFICATIVA_CONCOR/direcao/<?php echo $this->direcao ?> ">Just. Concordância<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/garantia/index/ordem/VINCULADA/direcao/<?php echo $this->direcao ?> ">Vinc.<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach($this->data as $data):
                    
                ?>
                    <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                        <td>
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape(Zend_Json::encode(array("SSOL_ID_DOCUMENTO"=>$data["SSOL_ID_DOCUMENTO"],"MOVI_ID_MOVIMENTACAO"=>$data["NEGA_ID_MOVIMENTACAO"]))); ?>"/>
                        </td>
                        <td><a class="tooltip" title="<?php echo $data["DOCM_DS_ASSUNTO_DOC"]; ?>"><?php echo $this->escape($data["MASCARA_DOCM"]); ?></td>
                        <td style="font-size: 12px; padding-left: 20px;"><a class="tooltip" title="<?php echo nl2br($data["NEGA_DS_JUST_ACEITE_RECUSA"]); ?>"><?php echo substr($this->decodehtmlentities($data["NEGA_DS_JUST_ACEITE_RECUSA"]),0,100)."..."; ?></a></td>
                        <td><?php if($data["NEGA_IC_CONCORDANCIA"] == "D"){echo "discordo";}else if($data["NEGA_IC_CONCORDANCIA"] == "C"){echo "concordo";} ?></td>
                        <td style="font-size: 12px; padding-left: 20px;"><a class="tooltip" title="<?php echo nl2br($data["NEGA_DS_JUSTIFICATIVA_CONCOR"]); ?>"><?php echo substr($this->decodehtmlentities($data["NEGA_DS_JUSTIFICATIVA_CONCOR"]),0,100)."..."; ?></a></td>
                        <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                        <td><?php if($data["VINCULADA"] == "0"){echo "Não";}else{echo "Sim";} ?></td>
                        </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="8">Total: <?php echo $this->data->getTotalItemCount(); ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="8">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
        <div class="painel">
            <input type="submit" title="Avaliar a justificativa de Recusa da garantia" name="acao" value="Avaliar"/>
        </div>
        <div>
</div>
    <?php else:?>
        
                <?php if($this->ultima_pesq): ?>
                    <p><br/><strong>Não existem registros para os parametros de filtro informados</strong></p>
                            <?php else: ?>
                            <p><br/>Não existem registros</p>
                <?php endif; ?>
                    
                    
    <?php endif; ?>
    </div>

    <?php echo $this->partial('_partials/caixahiddeninputs.phtml',array('view'=> $this));?>
    
</form>
    <div id="dialog-documentos_detalhe">
     <div id="dialog-documentos_conteudo"></div>
    </div>
