<table>
<?php $grupo = $this->descricaoGrupo; ?>
<?php 
    $reg1 = explode(':',$grupo[0]["CXEN_DS_CAIXA_ENTRADA"]); 
    $reg2 = explode(' - ', $reg1[1]);   
?>
<tr><td rowspan="6"><img width="80" height="76" src="<?php echo $this->baseUrl(); ?>/img/BrasaoBrancoRelatorio.jpg" /></td></tr>
<tr><td>PODER JUDICIÁRIO</td><td>Data e Hora da Emissão: <?php echo $this->dataHoraAtual; ?></td></tr>
    <tr><td colspan="6"><?php echo $this->title; ?></td></tr>
    <tr><td colspan="6"><?php echo $reg2[0]; ?></td></tr>
    <tr><td colspan="6"><?php echo substr($reg1[0], 0, -5); ?></td></tr>
    <?php echo ($this->descricaoNivel)?('<tr><th colspan="6">'.$this->descricaoNivel.'</th></tr>'):(''); ?>
</table>
<br />
<table style="border: 1px solid #C3C3C3;">
    <thead>
        <tr>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">N. da solicitação</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">Serviço atual</a></th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">Primeiro atendente</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">Data início</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">Primeiro atendimento</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">Tempo atendimento</th>
         </tr>
    </thead>
    <tbody> 
        <?php foreach($this->data as $data): ?>
            <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data['DOCM_NR_DOCUMENTO'].'.'); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["NOME_ATENDENTE"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["DATA_PRIMEIRO_ATENDIMENTO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["TEMPO_TRANSCORRIDO_MINUTOS"]); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6">TOTAL GERAL DE SOLICITAÇÕES: <?php echo count($this->data); ?>
           </td>
        </tr>
    </tfoot>
</table>