<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<?php $grupo = $this->descricaoGrupo; ?>
<?php 
    $reg1 = explode(':',$grupo[0]["CXEN_DS_CAIXA_ENTRADA"]); 
    $reg2 = explode(' - ', $reg1[1]);   
?>
<table border="1">
    <tr><th colspan="6"><?php echo $this->title; ?></th></tr>
    <tr><th colspan="6"><?php echo $reg2[0]; ?></th></tr>
    <tr><th colspan="6"><?php echo substr($reg1[0], 0, -5); ?></th></tr>
    <?php echo ($this->descricaoNivel)?('<tr><th colspan="6">'.$this->descricaoNivel.'</th></tr>'):(''); ?>
</table>
<div>
    <table border="1">
        <thead>
              <tr>
                <th>N. da solicitação</th>
                <th>Serviço atual</a></th>
                <th>Primeiro atendente</th>
                <th>Data início</th>
                <th>Primeiro atendimento</th>
                <th>Tempo atendimento</th>
             </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                    <td><?php echo $this->escape($data['DOCM_NR_DOCUMENTO'].'.'); ?></td>
                    <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                    <td><?php echo $this->escape($data["NOME_ATENDENTE"]); ?></td>
                    <td><?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO"]); ?></td>
                    <td><?php echo $this->escape($data["DATA_PRIMEIRO_ATENDIMENTO"]); ?></td>
                    <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO_MINUTOS"]); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6">Total: <?php echo count($this->data); ?>
               </td>
            </tr>
        </tfoot>
    </table>
</div>