<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<table>
    <?php $grupo = $this->grupo; 
          $reg1 = explode(':',$grupo[0]["CXEN_DS_CAIXA_ENTRADA"]); 
          $reg2 = explode(' - ', $reg1[1]); 
    ?>
    <tr><th rowspan="6"><img width="80" height="76" src="<?php echo $this->baseUrl(); ?>/img/BrasaoBrancoRelatorio.jpg" /></th></tr>
    <tr><td>PODER JUDICIÁRIO</td><td>Data e Hora da Emissão: <?php echo $this->horaAtual; ?></td></tr>
    <tr><td><?php echo $reg2[0]; ?></td></tr>
    <tr><td><?php echo substr($reg1[0], 0, -5); ?></td></tr>
    <tr><td><?php echo $this->descricaoNivel; ?></td></tr>
    <tr><td><?php echo 'Solicitações Finalizadas por Período: '.$this->titulo; ?></td></tr>
</table>
<br />
<table style="border: 1px solid #C3C3C3;">
    <thead>
          <tr>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">N. DA SOLICITAÇÃO</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">SERVIÇO ATUAL</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">DATA INÍCIO</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">DATA DA BAIXA</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">ATENDENTE</th>
            <th align="left" style="border: 1px solid #C3C3C3; padding: 3px;">AVALIAÇÃO</th>
         </tr>
    </thead>
    <tbody>
                  
        <?php foreach($this->data as $data): ?>                                                                                                     
            <tr name="rowList" >
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["DOCM_DH_CADASTRO"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["MOFA_DH_FASE"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["NOME_USARIO_BAIXA"]); ?></td>
                <td style="border: 1px solid #C3C3C3; padding: 3px;"><?php echo $this->escape($data["STSA_DS_TIPO_SAT"]); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
<!--    <tfoot>
        <tr>
            <td >TOTAL GERAL DE SOLICITAÇÕES: < ?php echo count($this->data); ?>
           </td>
        </tr>
    </tfoot>-->
</table>
<!-- tfoot foi comentado pois estava gerando warning e quando o relatório possuia muitos registros não gerava corretamente -->
<p> TOTAL GERAL DE SOLICITAÇÕES: <?php echo count($this->data); ?> </p>