<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<table border="1">
    <?php $grupo = $this->grupo; 
          $reg1 = explode(':',$grupo[0]["CXEN_DS_CAIXA_ENTRADA"]); 
          $reg2 = explode(' - ', $reg1[1]); 
    ?>
    <tr><th colspan="9"><center><?php echo 'SOLICITAÇÕES FINALIZADAS POR PERÍODO: '.$this->titulo; ?></center></th></tr>
    <tr><th colspan="9"><center>DATA E HORA DA EMISSÃO: <?php echo $this->horaAtual; ?></center></th></tr>
    <tr><th colspan="9"><center><?php echo $reg2[0]; ?></center></th></tr>
    <tr><th colspan="9"><center><?php echo substr($reg1[0], 0, -5); ?></center></th></tr>
    <?php echo ($this->descricaoNivel)?('<tr><th colspan="9"><center>'.$this->descricaoNivel.'</center></th></tr>'):(''); ?>
    
</table>
<div>
<table border="1">
    <thead>
          <tr>
            <th>N. da solicitação</th>
            <th>Serviço atual</th>
            <th>Data início</th>
            <th>Data da baixa</th>
            <th>Atendente</th>
            <th>Solicitante</th>
            <th>Tempo total</th>
            <th>Tempo minutos</th>
            <th>Avaliação</th>
         </tr>
    </thead>
    <tbody>
        <?php $descricaoSatisfacao = new Application_Model_DbTable_SosTbSsolSolicitacao(); ?>
        <?php foreach($this->data as $data): ?>  
            <?php
               $data['DADOS_INPUT'] = Zend_Json::encode($data);
               $tempoInicial = new App_Sosti_TempoSla();
               $data['TEMPO_TRANSCORRIDO'] = $tempoInicial->tempoTotalHelpdesk($data['MOVIMENTACAO'], $data["MOFA_DH_FASE"], '07:00:00', '20:00:00');
               $data['TEMPO_TRANSCORRIDO_MINUTOS'] = (float) sprintf('%.2f',($tempoInicial->converteHorasFormatadasParaSegundos($data['TEMPO_TRANSCORRIDO']))/60);
            ?>
            <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                <td><?php echo $this->escape($data['DOCM_NR_DOCUMENTO'].'.'); ?></td>
                <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                <td><?php echo $this->escape($data["DOCM_DH_CADASTRO"]); ?></td>
                <td><?php echo $this->escape($data["MOFA_DH_FASE"]); ?></td>
                <td><?php echo $this->escape($data["NOME_USARIO_BAIXA"]); ?></td>
                <td><?php echo $this->escape($data["NOME_USARIO_CADASTRO"]); ?></td>
                <td><?php echo $this->escape($data['TEMPO_TRANSCORRIDO']); ?></td>
                <td><?php echo $this->escape($data['TEMPO_TRANSCORRIDO_MINUTOS']); ?></td>
                <td><?php echo $this->escape($data["STSA_DS_TIPO_SAT"]); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="9">Total: <?php echo $this->total; ?>
           </td>
        </tr>
    </tfoot>
</table>
</div>