<?php
$datas = json_decode($this->data, false);
$userNs = new Zend_Session_Namespace('userNs');
?>
<style>
    #container{
        margin: 0 auto;
        font-family: arial;
        width: 210mm;
        height: 297mm;

    }
    table#header{
        width: 100%;
    }
    table#header td.orgao{
        font-size: 13px;
    }
    table#header td.brasao{

        background-image: url(<?= $this->baseUrl(); ?>/img/JusticaTRF.jpg);
        background-position: center;
        background-repeat: no-repeat;
        height: 97px;
        width: 271px;
    }
    table#header td.date-time{
        text-align: right;
        font-size: 13px;
    }
    table.titulo-tabela{
     font-size: 14px;
    }
    
    
    table.titulo-tabela td.col1{
        text-align: center;
        text-decoration: underline;
        font-weight: bold;
    }
    table.titulo-tabela td.col2{
        font-weight: bold;
    }
    table.titulo-tabela td.col3{
        font-weight: bold;
        padding-top: 30px;
        padding-left: 120px;
    }

   table.titulo-dados{
     font-size: 18px;
     margin-left: 5px;
    }
   
   
  .borda{
  border: 1px solid #000;     
    }
    
    

</style>

<body>

<watermarkimage src="<?= $this->baseUrl(); ?>/img/JusticaTRFMarcaDagua.png" alpha="2" size="300,100"/>

    <table class="titulo-tabela" border="0">
        <tr>
            <td  class="col2">Período Informado: <?php echo $datas->DATA_INICIAL . " a " . $datas->DATA_FINAL; ?></bold></td>    
        </tr>

        <tr>
            <td  class="col2">Seção/Subseção: <?php echo $userNs->codSec . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" . $userNs->descrisaosecsubsec; ?></td> 
        </tr>
        <tr>
            <td class="col3"> <?php echo $this->titulo; ?></td>
        </tr>
    </table>
    
<br/>
    <table class="titulo-dados" border="0" cellspacing="0">
        <tr>
            <td colspan="2" style="text-align: right">Mês</td>
            <td rowspan="2" class="borda">JAN</td>
            <td rowspan="2" class="borda">FEV</td>
            <td rowspan="2" class="borda">MAR</td>
            <td rowspan="2" class="borda">ABR</td>
            <td rowspan="2" class="borda">MAI</td>
            <td rowspan="2" class="borda">JUN</td>
            <td rowspan="2" class="borda">JUL</td>
            <td rowspan="2" class="borda">AGO</td>
            <td rowspan="2" class="borda">SET</td>
            <td rowspan="2" class="borda">OUT</td>
            <td rowspan="2" class="borda">NOV</td>
            <td rowspan="2" class="borda">DEZ</td>
            <td rowspan="2" >Total Geral</td>
        </tr>
        
        <tr>
           <td class="borda">Cód.</td>
           <td class="borda" style="width: 200px;">Descrição</td>
        </tr>
        
        <tr>
            <td class="borda">9</td>
            <td class="borda">SEDEX</td>
            <td class="borda">99</td>
            <td class="borda">89</td>
            <td class="borda">86</td>
            <td class="borda">120</td>
            <td class="borda">144</td>
            <td class="borda">160</td>
            <td class="borda">77</td>
            <td class="borda">10</td> 
            <td class="borda">99</td>
            <td class="borda">89</td>
            <td class="borda">86</td>
            <td class="borda">120</td>
            <td class="borda">1176</td>
            
        </tr>
         <tr>
             <td colspan="2" style="text-align: right">Total:</td>
           
            <td class="borda">99</td>
            <td class="borda">89</td>
            <td class="borda">86</td>
            <td class="borda">120</td>
            <td class="borda">144</td>
            <td class="borda">160</td>
            <td class="borda">77</td>
            <td class="borda">10</td> 
            <td class="borda">99</td>
            <td class="borda">89</td>
            <td class="borda">86</td>
            <td class="borda">120</td>
            <td class="borda">1176</td>
         </tr>
     </table>

  
</body>