
 <div id="dialog_cadastra_parte">
        <ul style="list-style: none; padding: 8px 0px 2px 0px;" >
            <li class="li_parte pessTRF"> 
               <span class=" inputParte"> <?php  echo $this->form->PAPD_CD_MATRICULA_INTERESSADO; ?> </span>
            </li>
         </ul>
      <table id="selecionados_redatores"  style="margin-top: 20px; width: 80%; display: none;" class="grid tabela">
     
            <thead> 
                <tr>
                    <th colspan="2"> Redatores adicionados </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2"><a href='#' class='removerTodos' rel='' >Remover todos</a></td>
                </tr>
           </tbody>
      </table>
     
      <table id="selecionados_participantes"  style="margin-top: 20px; width: 80%; display: none;" class="grid tabela">
     
            <thead> 
                <tr>
                    <th colspan="2"> Participantes adicionados </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2"><a href='#' class='removerTodos' rel='' >Remover todos</a></td>
                </tr>
           </tbody>
      </table>
 </div> 
