
 <div id="dialog_cadastra_parte_vista_encaminha">
         <?php  echo $this->form->TIPO_PARTE; ?>
        <ul style="list-style: none; padding: 8px 0px 2px 0px;" >
            <li class="li_parte pessTRF" style=" margin: 0px;"> 
               <span class=" inputParte"> <?php  echo $this->form->PAPD_CD_MATRICULA_INTERESSADO; ?> </span>
            </li>
            <li class="li_parte pessExterna" style=" margin: 0px;">
               <span class=" inputParte"> <?php  echo $this->form->PAPD_ID_PESSOA_FISICA; ?> </span>
            </li> 
            <li class="li_parte pessJuridica" style=" margin: 0px;">
               <span class="inputParte"> <?php  echo $this->form->PAPD_ID_PESSOA_JURIDICA; ?> </span>
            </li>
            <li class="li_parte unidade" style=" margin: 0px;">
               <span class="inputParte"> <?php  echo $this->form->TRF1_SECAO; ?> </span>
            </li> 
            <li class="li_parte unidade" style=" margin: 0px;">
               <span class="inputParte"> <?php  echo $this->form->UNIDADE_PARTE; ?> </span>
            </li> 
        </ul>


     
      <table id="selecionados_partes_vistas_encam"  style="margin-top: 20px; width: 100%; display: none;" class="grid tabela">
     
            <thead> 
                <tr>
                    <th>Remover</th>
                    <th>Pessoa</th>
                    <th>Partes</th>
                    <th>Vistas</th>
                    <th>Encaminhar</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5"><a href='#' class='removerTodos' rel='' >Remover todos</a></td>
                </tr>
           </tbody>
      </table>
     
 </div> 
