<?php
/**
 * Contém view da action específica
 * 
 * e-Admin
 * e-Orçamento
 * View
 * 
 * @author Anderson Sathler M. Ribeiro <asathler@gmail.com>
 */

/**
 * Disponibiliza as informações a serem exibidas na view
 *
 * @category Orcamento
 * @package Orcamento_View_Index_Erro
 * @author Anderson Sathler M. Ribeiro <asathler@gmail.com>
 * @license Creative Commons Atribuição 3.0 não adaptada
 *          <http://creativecommons.org/licenses/by/3.0/deed.pt_BR>
 * @ignore Este código é livre para uso dentro do TRF! Fora do TRF pode apenas
 *         servir como fonte de estudo ou base para futuros códigos-fonte sem
 *         nenhuma restrição, salvo pelas informações de @copyright e @author
 *         que devem ser mantidas inalteradas.
 * @copyright Tribunal Regional Federal ©2007-2014 <http://www.trf1.jus.br>
 */
// Recebe os dados do erro
$erro = $this->erro;

// Cria variáveis para melhoria da leitura desta view
$titulo = $erro [ 'msg' ];
$codigo = $erro [ 'cod' ];

// Exibe informações do objeto erro
$bErro = $erro [ 'bErro' ];
$erroCod = $erro [ 'erroCod' ];
$erroMsg = $erro [ 'erroMsg' ];
$erroLinha = $erro [ 'erroLinha' ];
$erroOrigem = $erro [ 'erroOrigem' ];
$erroTrace = $erro [ 'erroTrace' ];

// Ajusta o título com o código parametrizado, se houver
$sTitulo = "";
$sTitulo .= " $titulo ";
if ( $codigo != '' ) {
    $sTitulo .= " [$codigo] ";
}

// Ajusta a mensagem do objeto de erro, se houver
$sErro = "";
$sErro .= " $erroMsg ";
if ( $erroCod != '' ) {
    $sErro .= " [$erroCod] ";
}

// Exibe informações sobre o usuário
$usuario = $erro [ 'usuario' ];
$perfil = $erro [ 'perfil' ];
$ug = $erro [ 'ug' ];
$responsavel = $erro [ 'responsavel' ];

// Exibe informações da requisição
$modulo = $erro [ 'modulo' ];
$controle = $erro [ 'controle' ];
$acao = $erro [ 'acao' ];
$parametros = $erro [ 'parametros' ];
?>

<h1><strong> Erro na aplicação </strong></h1>
<h2><font color='red'> Descrição do erro: </font></h2>

<p>
<font color='red'>
<strong> <?php echo $sTitulo; ?> </strong><br />
<?php echo $sErro; ?>
</font>
</p>

<?php
if ( $erroTrace ) {
    ?>
<h3> Rastreabilidade </h3>
<pre>
<?php echo $erroTrace; ?>
</pre>

<p>
<?php echo $erroOrigem . ' [' . $erroLinha . ']'; ?>
</p>
    <?php
    }
?>

<h3> Parâmetros da requisição </h3>
<pre>
'módulo': <?php echo $modulo; ?> 
'controle': <?php echo $controle; ?> 
'ação': <?php echo $acao; ?> 
'parâmetros': <?php echo $parametros; ?> 
</pre>

<h3> Informações do usuário </h3>
<pre>
'usuário': <?php echo $usuario; ?> 
'perfil': <?php echo $perfil; ?> 
'ug': <?php echo $ug; ?> 
'responsavel': <?php echo $responsavel; ?> 
</pre>