<?php
   $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
   $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
   $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
   $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesInteressados.js'));
   $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesVistasAutuar.js'));
?>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
?>

<script type="text/javascript">
	$(function() {
            $("#PRDI_CD_MATR_SERV_RELATOR").autocomplete({
                source: '<?php echo $this->baseUrl(); ?>/sisad/autuar/ajaxservidores',
                minLength: 3,
                delay: 100 
            });
            $("#PRDI_CD_JUIZ_RELATOR_PROCESSO").autocomplete({
                source: '<?php echo $this->baseUrl(); ?>/sisad/autuar/ajaxjuizesdesembargadores',
                minLength: 3,
                delay: 500 
            });

            $( "#PRDI_ID_AQVP" ).combobox();
            $( "#combobox-input-text-PRDI_ID_AQVP" ).attr('style','width: 730px;');
            $( "#combobox-input-button-PRDI_ID_AQVP" ).attr('style','display: none;');
            
            
            if( $("#RELATOR-N").attr('checked') == 'checked'){
                $("#PRDI_CD_MATR_SERV_RELATOR").hide('');
                $("#PRDI_CD_MATR_SERV_RELATOR-label").hide('');
                $("#PRDI_CD_JUIZ_RELATOR_PROCESSO").hide('');
                $("#PRDI_CD_JUIZ_RELATOR_PROCESSO-label").hide('');
            }
            $("input[name=RELATOR]").click(
                function(){
                    if(this.value === 'S'){
                        $("#PRDI_CD_MATR_SERV_RELATOR").show('');
                        $("#PRDI_CD_MATR_SERV_RELATOR-label").show('');
                        $("#PRDI_CD_JUIZ_RELATOR_PROCESSO").show('');
                        $("#PRDI_CD_JUIZ_RELATOR_PROCESSO-label").show('');
                    }else{
                        $("#PRDI_CD_MATR_SERV_RELATOR").hide('');
                        $("#PRDI_CD_MATR_SERV_RELATOR-label").hide('');
                        $("#PRDI_CD_JUIZ_RELATOR_PROCESSO").hide('');
                        $("#PRDI_CD_JUIZ_RELATOR_PROCESSO-label").hide('');
                    }
                }
            );
            
            //mostra/esconde o botao de vistas de acordo com a confidencialidade
            $confidenc = $('#DOCM_ID_CONFIDENCIALIDADE');
            if( $confidenc.val() != "0") { 
                $("input[name='cadVistas']").show();
            }
            
            $confidenc.change( function(){
                   if( $(this).val() != "0" ){
                       $("input[name='cadVistas']").show();
                   }else{
                       $("input[name='cadVistas']").hide();
                   }
            });
            
            $('#autuarForm').submit(function (){
                
                if( (/^(0|1)$/.test( $('#DOCM_ID_CONFIDENCIALIDADE').val())) ||  $("input[name='REPLICA_VISTAS']").is(':checked') == true ) { 
                   if($confidenc.val() == "0"){
                        $("#vistas_adicionadas").html("");  ///retiro todas as vistas, para procs publicos
                   }
                   var $qtdePartes = $("#partes_adicionadas").find("input[type='hidden']");
                   if( $qtdePartes.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma parte no Processo");
                      return false;
                   }
                }
                
                if(  $('#DOCM_ID_CONFIDENCIALIDADE').val() != "0"  && $("input[name='REPLICA_VISTAS']").is(':checked') == false  ){ 
                    //precisa ter vistas cadastradas
                   var $qtdeVistas = $("#vistas_adicionadas").find("input[type='hidden']");
                   if( $qtdeVistas.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma pessoa/unidade com vistas ao Processo");
                      return false;
                   }
                }
                
                
                $(this).attr("action", "autuar");
                return true;
                  
            });
                
	});
        
        
        
</script>

<?php if (count($this->data)): ?>
<div class="container_pagination_fixed">
<table class="grid">
    <thead>
        <tr>
            <th >Tipo</th>
            <th >Número</th>
            <th >Encaminhador</th>
            <th >Data/Hora Encaminhamento</th>
        </tr>
    </thead>
    <tbody id="documentosList">
        <?php
            //Zend_Debug::dump($this->data);
        foreach($this->data as $data):
            ?>
            <tr>
                    <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--                    <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                    <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                    <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                    <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
                    <input type="hidden" name="idDcmto" class="idDcmto" value="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]) ?>" />
                    <input type="hidden" name="confidencialidade" class="" rel="<?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?>" value="<?php echo $this->escape($data["DOCM_ID_CONFIDENCIALIDADE"]) ?>" />
            </tr>
            <?php ?>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td>
        </tr>
    </tfoot>
</table>
</div>
<?php else:?>
    <p>N&atilde;o existem registros</p>
<?php endif; ?>

<form id="autuarForm" method="post" action="" enctype="multipart/form-data">
    
    <?php 
            echo $this->formAutuardcmto->getElement("PRDI_ID_AQVP"); 
            echo $this->formAutuardcmto->getElement("PRDI_DS_TEXTO_AUTUACAO"); 
            /*INICIO Realizado o comentario pois processo de distribuicao foi realizado*/
//            echo $this->formAutuardcmto->getElement("RELATOR"); 
//            echo $this->formAutuardcmto->getElement("PRDI_CD_MATR_SERV_RELATOR"); 
//            echo $this->formAutuardcmto->getElement("PRDI_CD_JUIZ_RELATOR_PROCESSO"); 
            /*INICIO Realizado o comentario pois processo de distribuicao foi realizado*/
            echo $this->formAutuardcmto->getElement("DOCM_DS_PALAVRA_CHAVE"); 
            
            echo $this->formAutuardcmto->getElement("DOCM_ID_CONFIDENCIALIDADE"); 
     ?>
    
<span id="msg_sigiloso"> </span>
<fieldset style="margin-top: 10px; width: 250px;">
    <legend> Cadastro de Partes/Vistas  </legend>
    <input type="button" value="Cadastrar Partes"  class="ui-button ui-widget ui-state-default ui-corner-all cadPartes" name="cadPartes" title="Cadastrar Interessados ao Processo" role="button" aria-disabled="false" style="margin: 10px 0px;"/>
    <input type="button" value="Cadastrar Vistas"  class="ui-button ui-widget ui-state-default ui-corner-all cadVistas" name="cadVistas" title="Cadastrar Vistas ao Processo" role="button" aria-disabled="false" style="margin: 10px 0px; display:none; "/>
</fieldset>
  
<div id="dialog_cadastra_parte_doc">  
    <?php echo $this->partial('_partials/cadastrapartesinteressados.phtml',            
                  array( 'form' => $this->formParte));?>
                             
    <div id="partes_documentos" style="display:none;"> 
       <?php echo $this->action('partesvistasdocumentos', 'partes', 'sisad', array('tipo' => '1', 'descricao' => 'partes', 'remover' => 'S')); ?>
    </div>  
    
    <div id="vistas_documentos" style="display:none;"> 
       <?php echo $this->action('partesvistasdocumentos', 'partes', 'sisad', array('tipo' => '3', 'descricao' => 'vistas', 'remover' => 'S')); ?>
    </div> 
</div> 

<div id="partes_adicionadas" style="display: none;"> </div>
<div id="vistas_adicionadas" style="display: none;"> </div>
         

<?php   
   echo $this->formAutuardcmto->getElement("DOCM_ID_TIPO_SITUACAO_DOC"); 
   echo $this->formAutuardcmto->getElement("acao"); 
   echo $this->formAutuardcmto->getElement("Salvar");  
?>
    
    
    
</form>
