<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p> Este programa cadastra tipos de processo.
    <ul>
        <li>Para cadastrar um novo tipo de processo click em botão novo.</li>
        <li>Para alterar a descrição do tipo de processo click no botão editar do respectivo tipo. 
            <br> <strong>Atenção:</strong> ao alterar a descrição do tipo processos já cadastrados vão referenciar a nova descrição.</li>
        <li>A permissão de alteração dos tipos de processo é da UNIDADE ADMINISTRATIVA DICAD DO TRF1 e seus respectivos servidores ou autorizados.</li>
        <li>Essa funcionalidade possui auditoria.</li>
    </ul>
    </p>
    <span id="botao_ajuda_recolhe" ></span>
</div>    

<div class="painel">
        <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/add">Novo</a>
    </div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th >Editar</th>
<!--                <th >Excluir</th>-->
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/list/ordem/TPPR_ID_TIPO_PROCESSO/direcao/<?php echo $this->direcao ?> ">Código do Tipo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/list/ordem/TPPR_DS_DESCRICAO_PROCESSO/direcao/<?php echo $this->direcao ?> ">Descrição do Tipo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/list/ordem/TPRR_IC_ATIVO/direcao/<?php echo $this->direcao ?> ">Ativo?<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td ><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/edit/id/<?php echo $this->escape($data["TPPR_ID_TIPO_PROCESSO"]); ?>" >Editar</a></td>
<!--                    <td ><a title="Excluir" class="excluir" href="<?php echo $this->baseUrl(); ?>/sisad/tipoprocesso/del/id/<?php echo $this->escape($data["TPPR_ID_TIPO_PROCESSO"]); ?>" >Excluir</a></td>-->
                    <td><?php echo $this->escape($data["TPPR_ID_TIPO_PROCESSO"]); ?></td>
                    <td><?php echo $this->escape($data["TPPR_DS_DESCRICAO_PROCESSO"]); ?></td>
                    <td><?php echo $this->escape($data["IC_ATIVO"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Total: <?php echo $this->data->getTotalItemCount()     
                                            ////-- pagination
                                            //-- style
                                            //-- partial
                                            //-- data
                                            ?>
                   </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <?php echo $this->paginationControl($this->data, null, null, null); ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>
<?php //exit(alksdçfkasçdlkfj); ?>
</form>