<script type="text/javascript">
    $(function() {
        $( ".novo" ).button({
                    icons: {
                        primary: ""
                    }
        });
     });
     
    $(function(){
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                }
            }
        );
        
        $("#PSPA_ID_PERFIL").focus(
            function(){
                if($(this).val("")){
                    $("#MODL_NM_MODULO").val("");
                }
            }
        );
        
        $('input[name=acao]').click(
            function(){
                var acao = this.value;
                var sistemapapel = $('form[name=perfilpapel]');
                if(acao == 'Associar'){
                    sistemapapel.attr('action','<?php echo $this->baseUrl(); ?>/guardiao/perfilpapel/form');
                }
            }
        );
        
        
        var grid_tbody_tr;
        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
            
        
    
    });
</script>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<form id="form" name="perfilpapel" action="<?php echo $this->baseUrl(); ?>/guardiao/perfilpapel/form" method="post">

<?php echo $this->form->PSPA_ID_PERFIL;?>
<?php echo $this->form->MODL_NM_MODULO;?>

<?php if (count($this->data)): ?>
<div style="margin-bottom: 15px;"><br/><input id="ALTERAR" name="acao" type="submit" class="novo" value="Alterar"/> </div>
<!--<div style="margin-bottom: 30px; margin-top: -25px;"><a  class="novo" href="guardiao/papelsistema/form">Voltar</a> </div>-->
<table class="grid">
    <thead>
        <tr>
            <th ><input type="checkbox" name="input_check_all_grid" id="check_all" /> </th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAS_ID_PAPEL_SISTEMA/direcao/<?php //echo $this->direcao ?> ">-->Código<!--<span class="<?php //echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAP_NM_PAPEL/direcao/<?php //echo $this->direcao ?> ">-->Nome Papel<!--<span class="<?php //echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a>--></th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAP_DS_FINALIDADE/direcao/<?php //echo $this->direcao ?> ">-->Descrição da Finalidade do papel<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc'); ?>"></span></a>--></th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAP_DS_FINALIDADE/direcao/<?php //echo $this->direcao ?> ">-->Módulo<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc'); ?>"></span></a>--></th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAP_DS_FINALIDADE/direcao/<?php //echo $this->direcao ?> ">-->Controle<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc'); ?>"></span></a>--></th>
            <th ><!--<a href="guardiao/papelsistema/form/ordem/APAP_DS_FINALIDADE/direcao/<?php //echo $this->direcao ?> ">-->Ação<!--<span class="<?php// echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc'); ?>"></span></a>--></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <?php $i++;?>
        <tr class="<?php if($data['PSPA_ID_PERFIL_PAPEL']!="")echo 'hover'; ?>" <?php if($data['PSPA_ID_PERFIL_PAPEL']!="")echo "marcado = 'marcado'"; ?>>
            <td>
                <input class="nav_check_boxes" type="checkbox" name="papeis[<?php echo $i; ?>][1]" <?php if($data['PSPA_ID_PERFIL_PAPEL']!="")echo "checked='checked'"; ?> value="<?php if($data['PSPA_ID_PERFIL_PAPEL']==""){ echo $data['PAPL_ID_PAPEL']." - ".$data['PSPA_ID_PERFIL_PAPEL']." - associar";}else{ echo $data['PAPL_ID_PAPEL']." - ".$data['PSPA_ID_PERFIL_PAPEL']." - associado";}?>">
                <input type="hidden" name="papeis[<?php echo $i; ?>][2]" value="<?php if($data['PSPA_ID_PERFIL_PAPEL']==""){ echo $data['PAPL_ID_PAPEL']." - ".$data['PSPA_ID_PERFIL_PAPEL']." - dissociado";}else{ echo $data['PAPL_ID_PAPEL']." - ".$data['PSPA_ID_PERFIL_PAPEL']." - associado";} ?>" > 
            </td>
            <td><?php echo $this->escape($data['PAPL_ID_PAPEL']) ?></td> 
            <td><?php echo $this->escape($data['PAPL_NM_PAPEL']) ?></td> 
            <td><?php echo $this->escape($data['PAPL_DS_FINALIDADE']) ?></td>           
            <td><?php echo $this->escape($data['MODL_NM_MODULO']) ?></td>           
            <td><?php echo $this->escape($data['CTRL_NM_CONTROLE_SISTEMA']) ?></td>           
            <td><?php echo $this->escape($data['ACAO_NM_ACAO_SISTEMA']) ?></td>           
        </tr>
        <?php endforeach;?>
    </tbody>
    <tfoot><tr><td colspan="7">Quantidade de Papel Sistema: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
</table>
<?php //echo $this->paginationControl($this->data, null, null, null)?>
</form>
<?php endif; ?>
