<?php //var_dump($this->data); exit;?>
<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/transporte/acidente/add">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th width="200px">Alterar</th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_ID_ACIDENTE/direcao/<?php echo $this->direcao ?> ">Identificador<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_NR_PROC_ADM/direcao/<?php echo $this->direcao ?> ">Nr Processo Adm<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_NR_BOLETIM_OCORRENCIA/direcao/<?php echo $this->direcao ?> ">Nr BO<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_DS_FATO/direcao/<?php echo $this->direcao ?> ">Descrição Fato<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_DH_FATO/direcao/<?php echo $this->direcao ?> ">Data-Hora Fato<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_DT_COMUNICACAO/direcao/<?php echo $this->direcao ?> ">Data Comunicação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_ID_MOTORISTA/direcao/<?php echo $this->direcao ?> ">Id Motorista<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_ID_VEICULO/direcao/<?php echo $this->direcao ?> ">Id Veiculo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_ID_PROC_FSPR/direcao/<?php echo $this->direcao ?> ">Processo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_CD_MATR_USER/direcao/<?php echo $this->direcao ?> ">Cadastrado por<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/acidente/index/ordem/ACID_DH_ACIDENTE/direcao/<?php echo $this->direcao ?> ">Data-Hora<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td class="painel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/transporte/acidente/edit/id/<?php echo $data->ACID_ID_ACIDENTE ?>" >Editar</a></td>
            <td><?php echo $this->escape($data->ACID_ID_ACIDENTE) ?></td>
            <td><?php echo $this->escape($data->ACID_NR_PROC_ADM) ?></td>
            <td><?php echo $this->escape($data->ACID_NR_BOLETIM_OCORRENCIA) ?></td>
            <td><?php echo $this->escape($data->ACID_DS_FATO) ?></td>
            <td><?php echo $this->escape($data->ACID_DH_FATO) ?></td>
            <td><?php echo $this->escape($data->ACID_DT_COMUNICACAO) ?></td>
            <td><?php echo $this->escape($data->ACID_ID_MOTORISTA) ?></td>
            <td><?php echo $this->escape($data->ACID_ID_VEICULO) ?></td>
            <td><?php echo $this->escape($data->ACID_ID_PROC_FSPR) ?></td>
            <td><?php echo $this->escape($data->ACID_CD_MATR_USER) ?></td>
            <td><?php echo $this->escape($data->ACID_DH_ACIDENTE) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="12">Total: <?php echo $this->data->getTotalItemCount()?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,
                                                                   'ordem'=> $this->ordem))
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif;?>