<?php if ($this->pessoasDaUnidade): ?>
    <option value="" selected="selected" ></option>
    <?php
    foreach ($this->pessoasDaUnidade as $value) :
        ?>
        <option value="<?php echo $value['PMAT_CD_MATRICULA']; ?>"><?php echo $value['PMAT_CD_MATRICULA']. ' - ' .$value['PNAT_NO_PESSOA']; ?></option>   
        <?php endforeach; ?>
<?php else:
    ?>
    <option value="">INFORME PRIMEIRO A UNIDADE ADMINISTRATIVA</option>  
<?php
endif;
?>