<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?php echo 'e-Admin - ' . $this->escape($this->title); ?></title>
		
		<?php
		// Adiciona favicon
		$this->headLink(array(	'rel'	=> 'shortcut icon',
								'href'	=> $this->baseUrl() . '/img/trf1.ico',
								'type'	=> 'image/x-icon'
								), 'PREPEND');
		
		// Framework CSS
		$this->headLink()
				->prependStylesheet($this->baseUrl().'/css/blueprint/print.css','print')
				->prependStylesheet($this->baseUrl().'/css/blueprint/screen.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/js/jquery-ui-1.8.14/css/custom-theme/jquery-ui-1.8.14.custom.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/css/layout.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/css/form.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/js/wijmo-open/development-bundle/themes/wijmo/jquery.wijmo.wijsuperpanel.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/js/wijmo-open/development-bundle/themes/wijmo/jquery.wijmo.wijmenu.css','screen, projection')
				->appendStylesheet($this->baseUrl().'/css/orcamento.css','screen, projection')
				;
		// Library JS
		$this->HeadScript()
				->appendFile($this->baseUrl().'/js/jquery-ui-1.8.14/js/jquery-1.6.2.min.js')
				->appendFile($this->baseUrl().'/js/jquery-ui-1.8.14/js/jquery-ui-1.8.14.custom.min.js')
				->appendFile($this->baseUrl().'/js/wijmo-open/development-bundle/external/jquery.bgiframe-2.1.3-pre.js')
				->appendFile($this->baseUrl().'/js/wijmo-open/development-bundle/wijmo/jquery.wijmo.wijutil.js')
				->appendFile($this->baseUrl().'/js/wijmo-open/development-bundle/wijmo/jquery.wijmo.wijmenu.js')
				->appendFile($this->baseUrl().'/js/wmenu/jquery.wmenu.js')
				->appendFile($this->baseUrl().'/js/orcamento.js')
				->prependFile($this->baseUrl().'/js/jquery-1.8.2.js')
				->appendFile($this->baseUrl() . '/js/jquery-ui-timepicker-addon.js', 'text/javascript')
				;
				
		echo $this->headLink();
		echo $this->headScript();
		echo $this->inlineScript();
		?>
	</head>
	
	<body>
		<div id="geral">
			<div id="topo">
				<div class="span-4" id="loading" style="z-index: 5000; position: absolute; top:90px; left: 350px; display: none; ">
					<div style="margin: 1px 0 0 30px;" class="span-1 last"><img src="<?php echo $this->baseUrl()?>/img/ajax-loader_1.gif"/></div><div class="span-2"><strong>Aguarde...</strong></div>
				</div>
				
				<a href="<?php echo $this->baseUrl().'/admin'?>"><h1><abbr title="Sistema de Gestão Administrativa Integrada">e-Admin</abbr></h1></a>
				
				<div id="tools">
					<div id="user">
						<div class="span-10 last first" id="tools-usuario" style="float:right;">
							<div id="user-name" class="span-10 last">
								<?php $userNamespace = new Zend_Session_Namespace('userNs'); ?>
								<div id="icoAdmin"><a href="#" class="icoAdminlink" rel="mudarUsuario"></a></div>
								<div id="nome">
									<?php echo strtoupper($userNamespace->siglalotacao); ?> - <?php echo $userNamespace->descicaolotacao; ?> - <?php echo $userNamespace->codlotacao; ?><br/>
									<?php echo strtoupper($userNamespace->matricula); ?> - <?php echo $userNamespace->nome; ?>
								</div>
								
								<div id="unidade"></div>
								
								<div id="mudarUsuario">
									<ul>
										<li><a href="#">administrar</a></li>
										<li><a href="#">outro</a></li>
										<!--<li><a href="#" class="sair">sair</a></li>-->
										<a href="<?php echo $this->baseUrl(); ?>/login/logout" class="sair">sair</a>
									</ul>
								</div>
							</div>
						</div>
					</div><!--user-->
				</div><!--administrativa-->
			</div><!--topo-->
			
			<div id="menu">
				<?php
				$userNamespace = new Zend_Session_Namespace('userNs');
				$acl = Zend_Registry::get('Zend_Acl');
				echo $this->navigation()->menu()->setAcl($acl)->setRole($userNamespace->perfil);
				$this->borderContainer()->captureStart('masterLayout',
														array(	'design' => 'headline',
																'gutters' => true,
																'livesplitters' => true,));
				?>
			</div><!--menu-->
			
			<div id="container">
			<div id="conteudo" >
				<span title="Tempo até que a sessão expire" id="contador" style="right: 0; top: 20px; float: right; position: relative; z-index: 0; color: #999999;"></span>
				<span title="Informações sobre está página" id='botao_informacao' class="botao_informacao_icon"></span>
				<span title="Ajuda desta página" id='botao_ajuda' class="ajuda_icon"></span>
				<div id="flashMessages"><?php echo $this->flashMessages(); ?></div>
				
				<h2><?php echo $this->escape($this->telaTitle); ?></h2>
				
				<?php echo $this->layout()->content; ?>
				</div><!--conteudo-->
			</div><!--container-->
		</div><!-- geral -->
		
		<div id="rodape">
			<div id="rodapeinfo">
				<p>
					<strong>TRIBUNAL REGIONAL FEDERAL DA PRIMEIRA REGIÃO</strong><br />
					<br />
					<strong>SECIN</strong> - Secretaria de Tecnologia da Informação<br />
					<strong>DISAD</strong> - Divisão de Sistemas Administrativos
				</p>
				
				<p>&copy; 2008-2014 - Tribunal Regional Federal de 1&ordf; Regi&atilde;o. Todos os direitos reservados.</p>
				
				<p><?php echo $this->tempoResposta; ?></p>
			</div>
		</div><!--rodape-->
	</body>
</html>