<?php if (count($this->data)): ?>
<div><a  class="novo" href="sisad/faseadm/form">Novo</a> </div>
<table class="grid">
    <thead>
        <tr>
            <th >Ações</th>
            <th ><a class="<?php if($this->direcao == 'ASC') echo 'ordemASC';  else echo 'ordemDESC'; if($this->ordem == 'FADM_DS_FASE') echo ' ui-state-hover';?> "  href="sisad/faseadm/index/ordem/FADM_DS_FASE/direcao/<?php echo $this->direcao ?> ">Descrição</a></th>
            <th ><a class="<?php if($this->direcao == 'ASC') echo 'ordemASC';  else echo 'ordemDESC'; if($this->ordem == 'FADM_IC_FASE_ATIVA') echo ' ui-state-hover';?>" href="sisad/faseadm/index/ordem/FADM_IC_FASE_ATIVA/direcao/<?php echo $this->direcao ?> ">Fase Ativa</a></th>
            <th ><a class="<?php if($this->direcao == 'ASC') echo 'ordemASC';  else echo 'ordemDESC'; if($this->ordem == 'FADM_IC_DCTO_FASE') echo ' ui-state-hover';?>" href="sisad/faseadm/index/ordem/FADM_IC_DCTO_FASE/direcao/<?php echo $this->direcao ?> ">Documento da Fase</a></th>
        </tr>
    </thead>
     
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td class="painel"><a style="height: 20px; width: 28px;" title="Editar" class="editar" href="sisad/faseadm/form/id/<?php echo $data->FADM_ID_FASE ?>"></a>
            <!--<a style="height: 20px; width: 28px;" title="Excluir" class="excluir" href="sisad/faseadm/form/id/<?php //echo $data->FADM_ID_FASE ?>" ></a>--></td>
            <td><?php echo $this->escape($data->FADM_DS_FASE) ?></td>
            <td><?php echo $this->escape($data->FADM_IC_FASE_ATIVA) ?></td>
            <td><?php echo $this->escape($data->FADM_IC_DCTO_FASE) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
</table>
<?php echo $this->paginationControl($this->data, null, null, null)
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif; ?>