<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.maskedinput-1.3.js'));
?>
<script>
    $(function(){
        botao_ajuda_by_id.delay(200).show('scale');
    })
</script>
<script type="text/javascript">
    $(function() {
        
        $("#PJUR_NO_RAZAO_SOCIAL").autocomplete({
            source: base_url+"/sisad/protocolo/ajaxnomedestinatario",
            minLength: 3,
            delay: 300
        });
        $( ".editar" ).button({
                    icons: {
                        primary: "ui-icon-pencil"
                    }
        }).attr('style','width: 40px; height: 16px;');
        $( ".excluir" ).button({
                    icons: {
                        primary: "ui-icon-trash"
                    }
        }).attr('style','width: 40px; height: 16px;');
        
        $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=malote]');
            if(acao == 'Cadastrar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/addMalote');
            }
        }
    );
    /*
     * Mascaras
     */
    $("#PJUR_NR_CNPJ").mask("99.999.999/9999-99");
    $("#PEND_NR_CEP").mask("99999-999");
     });
</script> 

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<!--<div class="help" id="msg_ajuda" style="display: none; " >
    <h3>Ajuda&ensp;</h3>
     <p>Endereçamento de Documentos para Postagem</p>
     <ul>
         <li><b>Órgão Destino</b> - constam todos os órgãos cadastrados  pelas Secam’s 1ªreg.</li>
         <li><b>Destinatário</b> - neste campo pode-se digitar o nome da pessoa que irá receber o documento.</li>
         <li><b>Tratamento</b> - escolher a forma de tratamento para o destinatário.</li>
         <li><b>Endereço</b> - o endereço será mostrado caso ele exista, ou permitida a sua digitação.</li>
         <li><b>CEP</b> - o sistema irá trazer, não existindo poderá ser digitado</li>
         <li><b>Preferência de Postagem</b> - conforme definido pelos Correios poderá ser solicitado pelo usuário, no entanto, caberá ao setor de protocolo definir o melhor tipo de postagem.</li>
     </ul>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<form method="POST" action="" name="malote" >
        <?php 
        echo $this->formAdd->TIPO; 
        echo $this->formAdd->MAPO_SG_SECSUBSEC_ORIGEM;  
        echo $this->formAdd->MAPO_SG_SECSUBSEC_DESTINO;  
        echo $this->formAdd->MAPO_NR_MALOTE;  
        echo $this->formAdd->MAPO_IC_ATIVO;  
        echo $this->formAdd->Salvar; 
        ?>
</form>
