<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p></p>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_check_box = $(this).find('input');
                var is_checked_input = input_check_box.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_check_box.attr('checked','checked');
                    this_tr.attr('marcado','marcado');
                    this_tr.addClass('hover');
                }else{
                    input_check_box.removeAttr('checked');
                    this_tr.removeAttr('marcado');
                    this_tr.removeClass('hover');
                }
                input_check_box.focus();
            }
        );
        
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                    $("tr[name=rowList]").addClass('hover');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                     $("tr[name=rowList]").removeClass('hover');
                }
            }
        );
        
                             
        $(".nav_check_boxes").keypress(
            function(e) {
                
                code = e.keyCode ? e.keyCode : e.which;
                
                var KEY_CODE_h = 104;
                var KEY_CODE_ESC = 27;
                var KEY_CODE_UP = 38;
                var KEY_CODE_w = 115;
                var KEY_CODE_DOWN = 40;
                var KEY_CODE_s = 119;
                
                
                if(code.toString() == KEY_CODE_h) {
                    $("#dialog-documentos_detalhe").dialog("open");
                    $(this).focus();
                }
                if(code.toString() == KEY_CODE_ESC) {
                    $("#dialog-documentos_detalhe").dialog("close");
                    $(this).focus();
                }
                
                var current_checkbox_index;
                var this_navigation = this;
                var first_checkbox_index = 0;
                var last_checkbox_index;
                
                $(".nav_check_boxes").each(
                    function(index){
                        last_checkbox_index =  index;
                        if(this_navigation == this){
                            current_checkbox_index = index;
                        }
                    }
                );
                
                if(code.toString() == KEY_CODE_DOWN ||  code.toString() == KEY_CODE_s) {
                    
                    var next_checkbox_index;
                    var checkbox_achado = false;
                    $(".nav_check_boxes").each(
                        function(index){
                            if(checkbox_achado == true){
                                next_checkbox_index = index;
                                checkbox_achado = false;
                            }
                            if( index == current_checkbox_index){
                                checkbox_achado = true;
                                if(index == last_checkbox_index){
                                    next_checkbox_index = last_checkbox_index;
                                }
                            }
                        
                        }
                    );
                    $(".nav_check_boxes").each(
                        function(index){
                            if( index == next_checkbox_index){
                                $("tr[name=rowList]").each(
                                    function(index){
                                        if( index == next_checkbox_index ){
                                            $("tr[name=rowList]").removeClass('hover_nav');
                                            $(this).addClass('hover_nav');
                                        }
                                    }
                                );
                                $(this).focus();
                            }
                        }
                    );
                }
                
                if( code.toString() == KEY_CODE_UP || code.toString() == KEY_CODE_w ) {
                    
                    var previews_checkbox_index;
                    var checkbox_achado = false;
                    $(".nav_check_boxes").each(
                        function(index){
                            if( index == current_checkbox_index){
                                checkbox_achado = true;
                                if(index == first_checkbox_index){
                                    previews_checkbox_index = first_checkbox_index;
                                }
                            }
                            if(checkbox_achado == false){
                                previews_checkbox_index = index;
                            }
                        }
                    );
                    $(".nav_check_boxes").each(
                        function(index){
                            if( index == previews_checkbox_index){
                                $("tr[name=rowList]").each(
                                    function(index){
                                        if( index == previews_checkbox_index ){
                                            $("tr[name=rowList]").removeClass('hover_nav');
                                            $(this).addClass('hover_nav');
                                        }
                                    }
                                );
                                $(this).focus();
                            }
                        }
                    );
                }
        });
            
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=protocolo]');
            if(acao == 'Pesquisar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/entrada');
            }else if(acao == 'Receber'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/receber');
            }
        }
    );
    });
</script>

<form method="POST" action="" name="protocolo">
        <b>Nr: Protocolo / Código de Barras</b></br>
        <input type="text" title="Código de Barras Protocolo" name="protocolo"  style="width: 350px"/>
    <div class="painel">
        <input type="submit" title="Pesquisar" name="acao" value="Pesquisar" />
    </div>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <b>Protocolo: </b> <?php echo $this->protocolo; ?> <br/>
    <b>Remetente: </b> <?php echo $this->remetente; ?><br/>
    <div class="painel">
        <input type="submit" title="Confirmar" name="acao" value="Receber" />
    </div>  
    <table class="grid">
        <thead>
            <tr>
                <th>Recebido</th>
                <th>Docs no Pacote</th>
                <th>Nome Destinatário</th>
                <th>Destinatário</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $data): 
                
                ?>
                <tr> 
                    <td>
                        <?php 
                            if($data["PRDC_IC_RECEBIMENTO"] != 'S'){ 
                        ?> 
                            <input type="hidden" title="cdPostagem" name="cdPostagem" id="<?php echo $this->escape($data["PRDC_ID_PROTOCOLO"]) ?>" value="<?php echo $this->escape($data["PRDC_ID_PROTOCOLO"]) ?>"/>
                            <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["DADOS_INPUT"]); ?>" name="dados_input[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>" title="Pacotes aguardando Recebimento"/>
                        <?php
                            }else { ?> 
                                <span id="leitura" class="recebido" title="Postagem com Documento Físico Já Recebida!"></span>
                        <?php
                            }
                        ?>
                    </td>
                    <td> <?php echo $this->escape($data["QTD"]) ?></td>
                    <td> <?php echo $this->escape($data["POST_NM_DESTINATARIO_EXTERNO"]) ?></td>
                    <td> <?php echo $this->escape($data["PJUR_NO_FANTASIA"]) ?></td>
                </tr>
            <?php endforeach; ?>
     
        </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)?></td>
            </tr>
        </tfoot>
    </table>
    <?php else:?>
        <p>** Insira um Nr de Protocolo para pesquisa</p>
    <?php endif; ?>
</div>
</form>