<script>
    $(function(){
        botao_ajuda_by_id.delay(200).show('scale');
    })
</script>
<script type="text/javascript">
    $(function() {
        $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=protocolo]');
            if(acao == 'Cadastrar Novo'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/addfaixapostagem');
            }
        }
    );
     });
</script> 

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<!--<div class="help" id="msg_ajuda" style="display: none; " >
    <h3>Ajuda&ensp;</h3>
     <p>Endereçamento de Documentos para Postagem</p>
     <ul>
         <li><b>Órgão Destino</b> - constam todos os órgãos cadastrados  pelas Secam’s 1ªreg.</li>
         <li><b>Destinatário</b> - neste campo pode-se digitar o nome da pessoa que irá receber o documento.</li>
         <li><b>Tratamento</b> - escolher a forma de tratamento para o destinatário.</li>
         <li><b>Endereço</b> - o endereço será mostrado caso ele exista, ou permitida a sua digitação.</li>
         <li><b>CEP</b> - o sistema irá trazer, não existindo poderá ser digitado</li>
         <li><b>Preferência de Postagem</b> - conforme definido pelos Correios poderá ser solicitado pelo usuário, no entanto, caberá ao setor de protocolo definir o melhor tipo de postagem.</li>
     </ul>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<form method="POST" action="" name="protocolo" >
    <fieldset>
    <legend>Pesquisa de Faixas de Postagem</legend>
    <?php 
        echo $this->formAdd->TIPO; 
        echo $this->formAdd->SELECT_ID_TIPO_POSTAGEM;  
        echo $this->formAdd->Consultar; 
    ?>
</fieldset>
    <br/>
    <?php 
        if (count($this->data)): 
    ?>
    <div class="painel"><input type="submit" title="Cadastrar novo Orgão / Endereço" name="acao" value="Cadastrar Novo" class="carrinhoMenu"/></div>
    <table class="grid">
        <thead>
            <tr>
                <th>Nr Inicial</th>
                <th>Nr Final</th>
                <th>Letra Inicial</th>
                <th>Letra Final</th>
                <th>DH Inclusão</th>
                <th>Ultimo Número</th>
                <th>Nr de Segurança</th>
                <th>Ativo</th>
                <th>Responsável</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
            <?php $i++;?>
            <tr>
                <td><?php echo $this->escape($data['FPDP_NR_NUMERO_INICIAL']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_NR_NUMERO_FINAL']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_DS_LETRA_INICIAL']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_DS_LETRA_FINAL']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_DH_INCLUSAO_POSTAGEM']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_NR_ULTIMO_NUMERO']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_NR_SEGURANCA_POSTAGEM']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_IC_POSTAGEM_ATIVO']) ?></td>           
                <td><?php echo $this->escape($data['FPDP_CD_MATRICULA_INCLUSAO']) ?></td>           
            </tr>
            <?php endforeach;?>
        </tbody>
        <tfoot><tr><td colspan="9">Quantidade: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
    </table>
    <?php //echo $this->paginationControl($this->data, null, null, null)?>
<?php endif; ?>
</form>
