<style>
    .containerMalote{
        overflow: auto;
        max-height: 400px;
        max-width: 167px;
    }
</style>

<script>
    $(function(){
        botao_ajuda_by_id.delay(200).show('scale');
    })
</script>
<script type="text/javascript">
    $(function() {
        $("#MAPO_SG_SECSUBSEC_DESTINO").autocomplete({
            source: base_url+"/sisad/protocolo/ajaxnomesecsubsecajax",
            minLength: 3,
            delay: 300
        });
        
        $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=protocolo]');
            if(acao == 'Cadastrar Novo'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/addmalote');
            }
        }
    );
     });
</script> 

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<!--<div class="help" id="msg_ajuda" style="display: none; " >
    <h3>Ajuda&ensp;</h3>
     <p>Endereçamento de Documentos para Postagem</p>
     <ul>
         <li><b>Órgão Destino</b> - constam todos os órgãos cadastrados  pelas Secam’s 1ªreg.</li>
         <li><b>Destinatário</b> - neste campo pode-se digitar o nome da pessoa que irá receber o documento.</li>
         <li><b>Tratamento</b> - escolher a forma de tratamento para o destinatário.</li>
         <li><b>Endereço</b> - o endereço será mostrado caso ele exista, ou permitida a sua digitação.</li>
         <li><b>CEP</b> - o sistema irá trazer, não existindo poderá ser digitado</li>
         <li><b>Preferência de Postagem</b> - conforme definido pelos Correios poderá ser solicitado pelo usuário, no entanto, caberá ao setor de protocolo definir o melhor tipo de postagem.</li>
     </ul>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<form method="POST" action="" name="protocolo" >
    <fieldset>
        <legend>Pesquisa de Malotes Cadastrados</legend>
        <?php 
        echo $this->formAdd->TIPO; 
        echo $this->formAdd->MAPO_SG_SECSUBSEC_ORIGEM;  
        echo $this->formAdd->MAPO_SG_SECSUBSEC_DESTINO;  
        echo $this->formAdd->Consultar; 
        ?>
    </fieldset>
    <br/>
    <?php 
        if (count($this->data)): 
    ?>
    <div class="painel"><input type="submit" title="Cadastrar novo Orgão / Endereço" name="acao" value="Cadastrar Novo" class="carrinhoMenu"/></div>
    <div class="containerMalote">
        <table class="grid" style="width: 150px;">
            <thead>
                <tr>
                    <th>Numeros Cadastrados</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data as $data): ?>
                    <tr>
                        <td><?php echo $this->escape($data['MAPO_NR_MALOTE']) ?></td>           
                    </tr>
                <?php endforeach;?>
            </tbody>
            <tfoot><tr><td colspan="9">Quantidade: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
        </table>
    </div>
<?php endif; ?>
</form>
