<?php 
    $tppoTipoPostagem = new Application_Model_DbTable_SadTbTppoTipoPostagem();
    $getTipoPostagem = $tppoTipoPostagem->getTipoPostagem();
?>

<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p></p>
    
    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>
    <span id="botao_ajuda_recolhe" ></span>
</div>-->

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_radio = $(this).find('input');
                var is_checked_input = input_radio.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_radio.attr('checked','checked');
                }else{
                    input_radio.removeAttr('checked');
                }
                input_radio.focus();
            }
        );
        
    grid_tbody_tr.dblclick(
        function(){
            var this_tr = $(this);
            var input_radio = $(this).find('input');

            var div_dialog_by_id =  $("#dialog-documentos_detalhe");
            value_input_radio = input_radio.val();
            input_radio.attr('checked', 'checked');

            if (xhr_abrir_documento) {
                xhr_abrir_documento.abort();
            }

            url = '<?php echo $this->baseUrl(); ?>/sisad/protocolo/postar';
            xhr_abrir_documento = $.ajax({
            url: url,
            dataType: 'html',
            type: 'POST',
            data: value_input_radio,
            contentType: 'application/json',
            processData: false, 
            beforeSend:function() {
                div_dialog_by_id.dialog("open");
            },
            success: function(data) {
                div_dialog_by_id.html(data);

                var span_id_leitura = $(this_tr).find('span[id=leitura]');
                span_id_leitura.removeClass('naolido');
                span_id_leitura.addClass('lido');
                span_id_leitura.attr('title','Pacote de Documentos / Processos com Dados de Postagem!');
                $(this_tr).removeClass('naolidoTr');
                $(this_tr).addClass('lidoTr');
            },
            complete: function(){

            },
            error : function(){

            }
            });
            }
        );
        
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
            autoOpen : false,
            modal    : false,
            show: 'fold',
            hide: 'fold',
            resizable: true,
            width: 800,
            position: [580,140,0,0],
            buttons : {
                    Ok: function() {
                            $(this).dialog("close");
                    }
            }
        });
        
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                }
            }
        );
        
                             
        $(".nav_check_boxes").keypress(
            function(e) {
                
            code = e.keyCode ? e.keyCode : e.which;

            var KEY_CODE_h = 104;
            var KEY_CODE_ESC = 27;
            var KEY_CODE_UP = 38;
            var KEY_CODE_w = 115;
            var KEY_CODE_DOWN = 40;
            var KEY_CODE_s = 119;

            if(code.toString() == KEY_CODE_h) {
                $("#dialog-documentos_detalhe").dialog("open");
                $(this).focus();
            }
            if(code.toString() == KEY_CODE_ESC) {
                $("#dialog-documentos_detalhe").dialog("close");
                $(this).focus();
            }

            var current_checkbox_index;
            var this_navigation = this;
            var first_checkbox_index = 0;
            var last_checkbox_index;

            $(".nav_check_boxes").each(
                function(index){
                    last_checkbox_index =  index;
                    if(this_navigation == this){
                        current_checkbox_index = index;
                    }
                }
            );

            if(code.toString() == KEY_CODE_DOWN ||  code.toString() == KEY_CODE_s) {

                var next_checkbox_index;
                var checkbox_achado = false;
                $(".nav_check_boxes").each(
                    function(index){
                        if(checkbox_achado == true){
                            next_checkbox_index = index;
                            checkbox_achado = false;
                        }
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == last_checkbox_index){
                                next_checkbox_index = last_checkbox_index;
                            }
                        }
                    }
                );
                $(".nav_radio").each(
                    function(index){
                        if( index == next_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == next_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
                
            if( code.toString() == KEY_CODE_UP || code.toString() == KEY_CODE_w ) {

                var previews_checkbox_index;
                var checkbox_achado = false;
                $(".nav_radio").each(
                    function(index){
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == first_checkbox_index){
                                previews_checkbox_index = first_checkbox_index;
                            }
                        }
                        if(checkbox_achado == false){
                            previews_checkbox_index = index;
                        }
                    }
                );
                $(".nav_radio").each(
                    function(index){
                        if( index == previews_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == previews_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
        });
            
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=protocolo]');
            if(acao == 'Pesquisar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/postagem');
            }else if(acao == 'Confirmar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/protocolo/receber');
            }
        }
    );
    });
</script>
<?php 
    $userNamespace = new Zend_Session_Namespace('userNs');
?>
<form method="POST" action="" name="protocolo">
    <fieldset>
        <legend>Nova Pesquisa</legend>
        <b>Nr: Protocolo / Código de Barras</b></br>
        <input type="text" title="Código de Barras Protocolo" name="protocolo"  style="width: 350px"/>
    <div class="painel">
        <input type="submit" title="Pesquisar" name="acao" value="Pesquisar" />
    </div>
    </fieldset>
<?php if (count($this->data)): 
    ?>
<div id="container_pagination">
    <b>Protocolo: </b> <?php echo $this->protocolo; ?> </br>
    <b>Remetente: </b> <?php echo $this->remetente; ?> 
    <table class="grid">
        <thead>
            <tr>
                <th>
                    Postagem 
                </th>
               <th>Docs no Pacote</th>
               <th>Tipo de Postagem</th>
               <th>A/C</th>
               <th>Destinatário</th>
            </tr>
        </thead>
                <tbody>
                <?php foreach ($this->data as $data): ?>
                    <tr> 
                        <td>
                            <?php if($data["POST_CD_CORREIO_ENVIO"] != NULL){ ?>
                                <input type="hidden" title="nrprotocolo" name="nrprotocolo" id="<?php echo $this->escape($data["PRDC_ID_POSTAGEM_PROC_DOC"]) ?>" value="<?php echo $this->escape($data["DADOS_INPUT"]) ?>"/>
                                <span id="leitura" class="recebido" title="Pacote de Documentos / Processos com Dados de Postagem!"></span>
                            <?php }else{ ?>
                                <input class="nav_grid_check_box nav_radio" id="<?php echo $this->escape($data["DADOS_INPUT"]); ?>" name="documento[]" type="radio" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                            <?php } ?>
                        </td>
                        <td> <?php echo $this->escape($data["QTD"]) ?></td>
                        <td> <?php echo $this->escape($data["TPPO_DS_TIPO_POSTAGEM"]) ?></td>
                        <td> <?php echo $this->escape($data["POST_NM_DESTINATARIO_EXTERNO"]) ?></td>
                        <td> <?php echo $this->escape($data["PJUR_NO_FANTASIA"]) ?></td>
                    </tr>
    <?php endforeach; ?>
            </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
            </tr>
            <tr>
                <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)?></td>
            </tr>
        </tfoot>
    </table>
    <?php else:?>
        <p>** Insira um Nr de Protocolo para pesquisa</p>
    <?php endif; ?>
</div>
</form>

<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>