<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
?>
<script type="text/javascript">
$(function() {
        $( "select#SSER_ID_GRUPO" ).combobox();
        $( "#combobox-input-text-SSER_ID_GRUPO" ).css('width', '800px');
        $( "#combobox-input-button-SSER_ID_GRUPO" ).css('left', '-20px');
        $( "#combobox-input-button-SSER_ID_GRUPO" ).css('top', '5px' );
});
</script>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <ul>
        <li>Ordenar por <b>Grupo de Serviço</b> e verificar se os dados cadastrados estão corretos.</li>
        <li>Havendo erro, clicar no botão <b>Editar</b> para corrigir a descrição e os dados do serviço.</li>
        <li>Para cadastrar um novo serviço clique no botão <b>Novo</b>.</li>
    </ul>
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>
<div class="painel">
    <a  class="novo" href="<?php echo $this->baseUrl(); ?>/sosti/servico/add">Novo</a>
</div>
<?php echo $this->form; ?>
<?php if (count($this->data)): ?>
<div id="container_pagination">

    <table class="grid">
        <thead>
            <tr>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_ID_SERVICO/direcao/<?php echo $this->direcao ?> ">Editar<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SGRS_DS_GRUPO/direcao/<?php echo $this->direcao ?> ">Grupo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Descrição do Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_ID_GRUPO/direcao/<?php echo $this->direcao ?> ">Grupo de Serviço<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_IC_ATIVO/direcao/<?php echo $this->direcao ?> ">Ativo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_IC_VISIVEL/direcao/<?php echo $this->direcao ?> ">Visível<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_IC_TOMBO/direcao/<?php echo $this->direcao ?> ">Tombo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_IC_ANEXO/direcao/<?php echo $this->direcao ?> ">Anexo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                <th ><a  href="<?php echo $this->baseUrl(); ?>/sosti/servico/index/ordem/SSER_IC_VIDEOCONFERENCIA/direcao/<?php echo $this->direcao ?> ">Videoconferência<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $data): ?>
                <tr>
                    <td class="painel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/sosti/servico/edit/id/<?php echo $this->escape($data["SSER_ID_SERVICO"]); ?>" >Editar</a></td>
                    <td><?php echo $this->escape($data["SSER_ID_GRUPO"]." - ".$data["SGRS_DS_GRUPO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                    <td><?php echo $this->escape($data["SGRS_DS_GRUPO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_IC_ATIVO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_IC_VISIVEL"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_IC_TOMBO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_IC_ANEXO"]); ?></td>
                    <td><?php echo $this->escape($data["SSER_IC_VIDEOCONFERENCIA"]); ?></td>
               </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="9">Total: <?php echo $this->data->getTotalItemCount()     
                                        ////-- pagination
                                        //-- style
                                        //-- partial
                                        //-- data
                                        ?>
               </td>
            </tr>
            <tr>
                <td colspan="9">
                    <?php echo $this->paginationControl($this->data, null, null, null); ?>
                </td>
            </tr>
        </tfoot>
    </table>
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
    </div>