<?php if (count($this->data)): ?>
<div class="painel"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/add">Novo</a></div>
<table class="grid">
    <thead>
        <tr>
            <th> </th>
            <th width="150px"><a href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/index/ordem/VEIC_CD_PLACA/direcao/<?php echo $this->direcao ?> ">Placa<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="100px"><a href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/index/ordem/MODE_DS_MODELO/direcao/<?php echo $this->direcao ?> ">Modelo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="100px"><a href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/index/ordem/MARC_DS_MARCA/direcao/<?php echo $this->direcao ?> ">Marca<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="100px"><a href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/index/ordem/VEIC_NR_RENAVAM/direcao/<?php echo $this->direcao ?> ">Nº Renavam<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
            <th width="200px"><a href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/index/ordem/VEIC_NR_TOMBO/direcao/<?php echo $this->direcao ?> ">Nº Tombo<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>           
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $data): ?>
        <tr>
            <td class="painel"><a title="Editar" class="editar" href="<?php echo $this->baseUrl(); ?>/transporte/veiculo/edit/id/<?php echo $data->VEIC_ID_VEICULO ?>" >Editar</a></td>                    
            <td><?php echo $this->escape($data["VEIC_CD_PLACA"]) ?></td>
            <td><?php echo $this->escape($data["MODE_DS_MODELO"]) ?></td>
            <td><?php echo $this->escape($data["MARC_DS_MARCA"]) ?></td>
            <td><?php echo $this->escape($data["VEIC_NR_RENAVAM"]) ?></td>
            <td><?php echo $this->escape($data["VEIC_NR_TOMBO"]) ?></td>            
        </tr>        
        <?php endforeach; ?>
    </tbody>
    <tfoot><tr><td colspan="11">Total: <?php echo $this->data->getTotalItemCount()?></td></tr></tfoot>
</table>
<br />
<?php echo $this->paginationControl($this->data, null, null, array('filtro'=>$this->filtro,
                                                                   'ordem'=> $this->ordem))
//-- pagination
//-- style
//-- partial
//-- data
?>
<?php else:?>
    <p>Não existem registros</p>
<?php endif;?>