<?php $this->inlineScript()->appendFile($this->baseUrl() . '/js/jquery-ui-timepicker-addon.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/combobox_app_jquery.js' , 'text/javascript');
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/relatoriossolicitacoes.js', 'text/javascript'); 
      $this->inlineScript()->appendFile($this->baseUrl() . '/js/datepicker.js', 'text/javascript'); 
?>

<style>
    .cabecalho{ font-size: 12px; color: #172E40; font-weight: bold; }
    .orgao_unidade{ padding: 3px 0px; }
    .unidade_periodo{ margin: 5px 0px; }
    h3{ margin: 0px; padding: 3px 0px; font-weight: normal;} 
    .totais{  font-size: 11px; color: #172E40;}
    
</style>

<div class="help" id="pesq_div" class="span-23" >
    <?php echo $this->form; ?>
</div>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>

<?php if (count($this->resultado) > 0): ?>

<div id="container_pagination" >
   
        <div class="painel" id="">
        
            <input type="button" title="Gerar PDF do Relatório" name="acao" value="PDF" id="pdf" onclick="javascript: location.href='<?php echo $this->baseUrl(); ?>/sosti/relatoriossolicitacoes/solicitacoesunidadeperiodopdf/';" >      

            <div class="cabecalho">
                    <div class="orgao"> 
                        TRIBUNAL REGIONAL FEDERAL DA 1&ordf; REGI&Atilde;O <br/>
                        SECRETARIA DE TECNOLOGIA DA INFORMAÇÃO <br/>
                       
                    </div>
                    <div class="unidade_periodo"> 
                        <h3>Unidade Solicitante: 
                            <?php echo $this->cabecalho['unidadeSolicitante'] ;?> 
                        </h3>
                        <?php if (!empty($this->cabecalho['DATA_INICIAL']) && !empty($this->cabecalho['DATA_FINAL'])  ): ?>
                        <h3> Per&iacute;odo: <?php echo $this->cabecalho['DATA_INICIAL']; ?> a <?php echo $this->cabecalho['DATA_FINAL']; ?>  </h3>
                        <?php endif; ?>
                    </div>
                </div>
        </div>
        
        <div style="border: 1px solid #ccc;">
            <table class="grid">
                <thead>
                    <tr>
                        <th style="font-weight: bold;"> N. Processo </td>
                        <th style="font-weight: bold;"> Data Autuação </td>
                        <th style="font-weight: bold;"> Assunto/Descrição </td>
                        <th style="font-weight: bold;"> Partes </td>
                    </tr>
                </thead>
            </tbody>
            <?php  foreach($this->resultado as $data): Zend_Debug::dump($data); ?>
            
                    <tr>
                        <td> <?php echo $data['NR_PROCESSO']; ?></td>
                        <td> <?php echo $data['DATA_AUTUACAO']; ?></td>
                        <td> <?php echo $data['ASSUNTO']; ?></td>
                    </tr>
             <?php   endforeach; ?>
              
            </tbody>
            </table>
        </div>
    <br/>
           <?php echo $this->paginationControl($this->resultado, null, null, null); ?>
<?php endif; ?>
     

</div>