<?php
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
    $this->headScript()->appendFile($this->baseUrl().'/js/tinymce/jscripts/tiny_mce/tiny_mce.js')
                       ->appendFile($this->baseUrl().'/js/tinymceForm.js');
?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<script type="text/javascript">
$(function() {
        var radio;
        botao_ajuda_by_id.delay(200).show('scale');
        tinyMCE.triggerSave();
        
        $('#ANEXOS').MultiFile({
            STRING: {
                file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
            }
       });

        $("input[type=radio][name=RADIO_TIPO_ARQUIVO]").click(
        function(){
              radio = $(this).val();
              if( $(this).val() == "D"){
                   $(".arquivo").show();
                   $("#editorHtml").hide();
                   $(".PreVisualizar").hide();                   
              }else if($(this).val() == "E"){
               //alert(<?php echo $this->UltimoAnexoExtensao; ?>);   
               if (<?php echo $this->UltimoAnexoExtensao; ?> == 4) {
                 var input_check_box = $(this).find('input');
                 value_input_check_box = input_check_box.val();

                   url = '<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperarhtml/id/<?php echo $this->UltimoAnexoId; ?>/dcmto/<?php echo $this->UltimoAnexoRed; ?>/tipo/<?php echo $this->UltimoAnexoExtensao; ?>';
                   $.ajax({
                         url: url,
                         dataType: 'json',
                         type: 'POST',
                         data: value_input_check_box,
                         contentType: 'application/json',
                         processData: false, 
                         beforeSend:function() {
                         },
                         success: function(data) {
                           if (data.success){
                              tinyMCE.activeEditor.setContent(data['arquivo']);
                           } else {
                             //alert(data.erro);                             
                             $(".msg_alerta").html("<br/>Aten&ccedil;&atilde;o: Não foi possível recuperar última versão em <i>EDITOR</i> da minuta .<br/>")
                           }
                         },
                         complete: function(){

                         },
                         error : function(data){                                  
                         }
                    });
                 
               }
                    $(".arquivo").hide();
                    $("#editorHtml").show();
                    $(".PreVisualizar").show();
              }
          }); 
          
          $( "#PreVisualizar").click(
              function(){
                  var url = base_url+'/sisad/Formulariominuta/visualizar';
                  $( "#InserirVersao").attr('action', url);
                  $( "#InserirVersao").submit();
              }
          );

         $( "#Salvar").click(
             function(){
              var descricao = $.trim($("#MOFA_DS_COMPLEMENTO" ).val());
               
              if( descricao == "" ) {
                 alert("É necessário preencher a descrição");
                return false;   
              }
             
             if (radio == undefined){
               alert("É necessário escolher o Tipo de armazenamento do documento.");
               return false;                     
             }else if (radio == 'D'){                      
               if($('input[type=file][name=ANEXOS[]]').val() == ""){
                 alert("É necessário incluir o arquivo.");
                 return false;
               }
             }else if (radio == 'E'){
              
               var conteudo =  tinyMCE.get('elm2').getContent();
               if(conteudo == ""){
                 alert("É necessário incluir o texto.");
                 return false;
               }
             }

             $( "#InserirVersao").attr('action','saveversao');
             $( "#InserirVersao").submit();
             });
});          
    </script>

<form name="InserirVersao" method="POST" action="" enctype="multipart/form-data" id="InserirVersao">
     <?php 
     if (count($this->data)): ?>
          <div class="">
          <table class="grid">
              <thead>
                  <tr>
                      <th >Tipo</th>
                      <th >Número</th>
                      <th >Encaminhador</th>
                      <th >Data/Hora Encaminhamento</th>
                  </tr>
              </thead>
              <tbody id="documentosList">
                  <?php
                  foreach($this->data as $data):
                      ?>
                      <tr>
                              <td> <?php echo $this->escape($data["DTPD_NO_TIPO"]) ?></td>
<!--                              <td> <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?></td>-->
                              <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                              <td> <?php echo $this->escape($data["ENCAMINHADOR"]) ?></td>
                              <td> <?php echo $this->escape($data["MOVI_DH_ENCAMINHAMENTO_CHAR"]) ?></td>
                      </tr>
                      <?php ?>
                  <?php endforeach; ?>
              </tbody>
              <tfoot>
                  <tr>
                      <td colspan="4">Total: <?php echo $this->data->getTotalItemCount() ?></td>
                  </tr>
              </tfoot>
          </table>
          </div>
     <?php else:?>
         <p>Não existem registros</p>
     <?php endif; ?>
    <input type="hidden" value="submitVersao" name="acao" />
<?php 
    echo $this->formVersaoMinuta->getElement('MOFA_DS_COMPLEMENTO');     
    echo $this->formVersaoMinuta->RADIO_TIPO_ARQUIVO;
?>
    <h2>
    <span class="msg_alerta" style="color: red"> </span>
    </h2>
    
    <div id="editorHtml" style="display: none;"> 
      <textarea class="html" id="elm2" cols="60" rows="50" name="TEXTO_HTML" ></textarea>
    </div>
    
    <div class="arquivo" style="display: none;">
       <b>Inserir Documento:</b></br>
<!--           <input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" accept="doc|docx|rtf|html|odt|pdf" maxlength="20" />-->
       <input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" maxlength="20" />
           <!--Somente serão aceitos arquivos com o formato DOC, DOCX, ODT, RTF e PDF. </br>-->
           </br>
           Soma dos arquivos até 50 Megas.</p>
           <span class="msg_alerta"> </span>
       </p>
    </div>
    <input id="Salvar" type="submit" name="Salvar" value="Salvar" />
    <input class="PreVisualizar" id="PreVisualizar" style="display: none;" type="submit" name="PreVisualizar" value="Pré-Visualizar" />
</form>