<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/partesInteressados.js'));
     //$this->inlineScript()->appendFile(($this->baseUrl().'/js/abcd.js')); 
?>

<script type="text/javascript">
$(function() {
            var caminho = '<?php echo $this->baseUrl(); ?>/sisad/cadastrodcmto/ajaxunidade';
            $("#DOCM_CD_LOTACAO_GERADORA").autocomplete({
                source: caminho,
                minLength: 3,
                delay: 100,
                select: function( event, ui ) {
                            $("#DOCM_CD_LOTACAO_REDATORA").val(ui.item.label);
			}
            });
           
            $("#DOCM_CD_LOTACAO_REDATORA").autocomplete({
                source: caminho,
                minLength: 3,
                delay: 100
            });
            $( "#DOCM_ID_TIPO_DOC" ).combobox();
            $( "#combobox-input-text-DOCM_ID_TIPO_DOC" ).attr('style','width: 500px;');


            $("#dialog-message").dialog("destroy");

            $("#dialog-message").dialog({
                    modal: true,
                    width: 380,
                    height: 225,
                    buttons: {
                            Sim: function() {
                               location.href='ativa';           		
                            }, 
                            Não: function() {
                              $(this).dialog('close');           		
                            }
                    }
                    });

            $( "#dialog-message" ).bind( "dialogclose", function(event, ui) { });
      
            $('#ANEXOS').MultiFile({
                STRING: {
                    file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                    remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
                }
            });
       
           $("input[type=radio][name=DESTINO_DOCUMENTO]").click(function(){
              if( $(this).val() == "E"){
                   $(".unidade_destino").show();
                   $(".msg_alerta").html("<br/>Aten&ccedil;&atilde;o: ao encaminhar o Documento para Caixa de Entrada da Unidade o mesmo n&atilde;o poder&aacute; mais ser exclu&iacute;do nem ter seus metadados editados. Certifique-se antes de salvar, que o documento est&aacute; na vers&atilde;o definitiva e n&atilde;o precisar&aacute; mais ser editado. <br/>")
              }
          }); 
          
    
            /**
             * Para transformar o select em um combo de autocomplete via somente java-script
             **/
            $( "#DOCM_ID_PCTT" ).combobox();
            $( "#combobox-input-text-DOCM_ID_PCTT" ).attr('style','width: 700px;');
            $( "#combobox-input-button-DOCM_ID_PCTT" ).attr('style','display: none;');
            $( "#DOCM_ID_TIPO_DOC" ).combobox();
            $( "#combobox-input-text-DOCM_ID_TIPO_DOC" ).attr('style','width: 500px;');

            /**
             * Para apresentar a Lista completa de ASSUNTOS
             */
            var botao_detalhe_pctt = $("<input type='button' name='LST_CPT_PCTT' value='Lista completa de Assuntos' />");
            botao_detalhe_pctt.css('position','relative');
            botao_detalhe_pctt.css('display','inline');
            botao_detalhe_pctt.css('float','right');
            botao_detalhe_pctt.css('top','-58px');
            botao_detalhe_pctt.css('left','-70px');
            botao_detalhe_pctt.button();
            $( "#DOCM_ID_PCTT-element").append(botao_detalhe_pctt);
            botao_detalhe_pctt.click(
                function(){
                    if($('#detalhe_pctt').attr('id') == undefined){
                        var detalhe_pctt = $("<div id='detalhe_pctt'></div>");
                        var select = $( "#DOCM_ID_PCTT" );
                        select.css('display','block');
                        select.css('width','680px');
                        select.css('height','480px');
                        select.attr('size','20');
                        detalhe_pctt.append(select);
                        $('body').append(detalhe_pctt);
                        detalhe_pctt.dialog({
                                    title: 'Lista completa de Assuntos',
                                    modal: true,
                                    width: 700,
                                    height: 600,
                                    buttons: {
                                            OK: function() {
                                              $("#DOCM_ID_PCTT").css('display','none');
                                              selected = $("#DOCM_ID_PCTT").children( ":selected" );
                                              $( "#combobox-input-text-DOCM_ID_PCTT" ).val(selected.text());
                                              $( "#DOCM_ID_PCTT-element" ).append(select);
                                              $(this).dialog('close');  
                                              $( "#combobox-input-text-DOCM_ID_PCTT" ).focus();
                                            }
                                    }
                                    });
                        detalhe_pctt.dialog('open');
                    }else{
                        $("#DOCM_ID_PCTT" ).css('display','block');
                        $('#detalhe_pctt').append($("#DOCM_ID_PCTT" ));
                        $('#detalhe_pctt').dialog('open');
                    }
                }
            );
            
            //mostra/esconde o botao de vistas de acordo com a confidencialidade
            $confidenc = $('#DOCM_ID_CONFIDENCIALIDADE');
            if( $confidenc.val() != "0") { 
                $("input[name='cadVistas']").show();
            }
            
            $confidenc.change( function(){
                   if( $(this).val() != "0" ){
                       $("input[name='cadVistas']").show();
                   }else{
                       $("input[name='cadVistas']").hide();
                   }
            }); 
            
            $("form[name='cadastroInterno']").submit( function(){
                if ($("#DESTINO_DOCUMENTO-E:checked").val() == undefined){   
                    alert("É necessário escolher para qual Unidade - Entrada será enviado o documento.");
                    return false;                                   
                }
                
                var $confidenc = $('#DOCM_ID_CONFIDENCIALIDADE');
                if( $confidenc.val() != "0"){
                    //precisa ter vistas cadastradas
                   var $qtdeVistas = $("#vistas_adicionadas").find("input[type='hidden']");
                   if( $qtdeVistas.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma pessoa/unidade com vistas ao documento.");
                      return false;
                   }
                }else{
                    //precisa ter parte
                   var $qtdePartes = $("#partes_adicionadas").find("input[type='hidden']");
                   if( $qtdePartes.length <= 0 ){
                      alert("É necessário cadastrar pelo menos uma parte no documento público.");
                      return false;
                   }
                }
                $(this).attr("action", "savecadastro");
                return true;
            });   
            
            /*estava no .js partesVistasMinuta mas não funcionou no treinamento*/
            $(".cadPartes, .cadVistas ").button();
             var $cadPartes = $(".cadPartes");
             var $cadVistas = $(".cadVistas");

            $cadPartes.click( function (){
                // seto as configuracoes da dialog de partes
                $.data(document.body,'config',
                    {
                        containerPartes: $("#partes_adicionadas"),  // div com os campos escondidos relacionados as partes inseridas pelo usuario
                        tabela: $("#selecionados_partes tbody"),            // tabela que mostra o nome das partes na dialog
                        containerPartesDocumentos: $("#partes_documentos"), // div com as partes ja cadastradas nos documentos, se houver
                        descParte: 'linha_partes',                     // classe inserida a cada parte adicionada
                        tipoParte: '1'
                    }
                );
                    $("#selecionados_partes").show();
                    $("#selecionados_vistas").hide();
                    $("#dialog_cadastra_parte_doc").dialog('option', 'title','Cadastro de Partes');
                    $("#dialog_cadastra_parte_doc").dialog('open');
                    
             });
             
             $cadVistas.click( function (){
                // seto as configuracoes da dialog de vistas
                $.data(document.body,'config',
                    {
                        containerPartes: $("#vistas_adicionadas"),  // div com os campos escondidos relacionados as partes inseridas pelo usuario
                        tabela: $("#selecionados_vistas tbody"),            // tabela que mostra o nome das partes na dialog
                        containerPartesDocumentos: $("#vistas_documentos"), // div com as partes ja cadastradas nos documentos, se houver
                        descParte: 'linha_vistas',                     // classe inserida a cada parte adicionada
                        tipoParte: '3'
                    }
                );
                    $("#selecionados_vistas").show();
                    $("#selecionados_partes").hide();
                    $("#dialog_cadastra_parte_doc").dialog('option', 'title','Cadastro de Vistas');
                    $("#dialog_cadastra_parte_doc").dialog('open');
                    
             });


            $("#dialog_cadastra_parte_doc").dialog({
                        autoOpen : false,
                        modal    : false,
                        show: 'fold',
                        hide: 'fold',
                        resizable: true,
                        width: 800,
                        height: 600,
                        position: [300,50,0,0],
                        buttons : {
                                Ok: function() {
                                        $(this).dialog("close");
                                }
                        },
                        open: function (){
                            var config = $.data(document.body,'config');
                            var conf = $("#DOCM_ID_CONFIDENCIALIDADE").val();
                            config.containerPartesDocumentos.show();
                            
                            if (/^(3|4)$/.test(conf)){  
                                $("option[value=U]").hide();
                                $("tr.partes_unidade").remove();
                            }else{
                                $("option[value=U]").show();
                            }
                        },
                        close: function() {
                            var config = $.data(document.body,'config');
                            $containerParte = config.containerPartes,
                            $containerParteDocs = config.containerPartesDocumentos,
                            $tipoParte = $("."+config.descParte+""),
                            $inputs = $tipoParte.find("input[type='hidden']").clone(); //busco os campos hidden de acordo com a classe (linha_parte, linha_interessado)
                            $containerParte.html($inputs);  //adiciono todas as partes/interessados na div dentro do form
                            config.containerPartesDocumentos.hide(); //escondo a div das partes que ja veem cadastradas nos documentos
                            $.data(document.body,'config',''); // zero a variavel config para quando abrir novamente a dialog setar os novos valores
                       }
            });
   });
</script>
<?php  if( $this->alert): ?>
<div id="dialog-message" title="Aten&ccedil;&atilde;o" style="display: none; ">
<p>
        <span class="" style="float:left; margin:0 7px 50px 0;"></span>
        <?php echo $this->alert; ?>			
</p>
</div>
<? endif; ?>
<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<div id=""><?php echo $this->alert; ?></div>
<form name="cadastroInterno" action="" method="POST" enctype="multipart/form-data" >
<?php 
    echo $this->form->DOCM_ID_DOCUMENTO;
    echo $this->form->DOCM_NR_DOCUMENTO;
    echo $this->form->DOCM_NR_SEQUENCIAL_DOC;
    echo $this->form->DOCM_DH_CADASTRO;
    echo $this->form->DOCM_CD_MATRICULA_CADASTRO;
    echo $this->form->DOCM_SG_SECAO_GERADORA;
    echo $this->form->DOCM_CD_LOTACAO_GERADORA;
    echo $this->form->DOCM_SG_SECAO_REDATORA;
    echo $this->form->DOCM_CD_LOTACAO_REDATORA;
    echo $this->form->DOCM_ID_TIPO_DOC;
    echo $this->form->DOCM_NR_DCMTO_USUARIO;
    echo $this->form->DOCM_ID_PCTT;
    echo $this->form->DOCM_DS_ASSUNTO_DOC;
    echo $this->form->DOCM_DS_PALAVRA_CHAVE;
    echo $this->form->DOCM_ID_TIPO_SITUACAO_DOC;
    echo $this->form->DOCM_ID_CONFIDENCIALIDADE; ?>
    

<div id="dialog_cadastra_parte_doc" style="display: none;">  
    <?php echo $this->partial('_partials/cadastrapartesinteressados.phtml',            
                  array( 'form' => $this->formParte));?>
                             
    <div id="partes_documentos" style="display:none;"> 
       <?php echo $this->action('partesvistasdocumentos', 'partes', 'sisad', array('tipo' => '1', 'descricao' => 'partes')); ?>
</div>   
    
    <div id="vistas_documentos" style="display:none;"> 
       <?php echo $this->action('partesvistasdocumentos', 'partes', 'sisad', array('tipo' => '3', 'descricao' => 'vistas')); ?>
    </div> 
                             
</div>   
<div id="partes_adicionadas"> </div>
<div id="vistas_adicionadas"> </div>


<fieldset style="margin-top: 10px; width: 250px;">
    <legend> Cadastro de Vistas / Partes </legend>
    <input type="button" value="Cadastrar partes"  class="ui-button ui-widget ui-state-default ui-corner-all cadPartes" name="cadPartes" title="Cadastrar Partes ao Documento" role="button" aria-disabled="false" style="margin: 10px 0px;"/>
    <input type="button" value="Cadastrar vistas"  class="ui-button ui-widget ui-state-default ui-corner-all cadVistas" name="cadVistas" title="Cadastrar Vistas ao Documento" role="button" aria-disabled="false" style="margin: 10px 0px; display: none;"/>
</fieldset>

<?php 
  if($this->NR_DOCUMENTO_RED && $this->ID_TP_EXTENSAO == 4){?>
<!--    <div>
      <h2>
       <td> <a target="_blank" title="Abrir Documento" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/id/<?php echo $this->ID_DOCUMENTO; ?>/dcmto/<?php echo $this->NR_DOCUMENTO_RED; ?> /tipo/<?php echo $this->ID_TP_EXTENSAO; ?>"> Versão Escolhida </a> 
      </h2>
    </div>-->
  <h2>
   <span> Ao salvar o cadastro do documento, será gerado um PDF do documento HTML (EDITOR) </span> 
  </h2>
   <?php }else{ 
    echo $this->form->DOCM_DS_HASH_RED; 
  } 
    echo $this->form->DOCM_NR_DOCUMENTO_RED;
?>
<strong>Anexos</strong></br>
<input id="ANEXOS" type="file" name="ANEXOS[]"  class="Multi" accept="pdf" maxlength="20" />
Até 20 Anexos. </br>
Somente serão aceitos arquivos com o formato PDF. </br>
Soma dos arquivos até 50 Megas.</p>

 <?php 
    echo $this->form->DESTINO_DOCUMENTO;
 ?>  
<span class="unidade_destino" style="display: none;"> <?php echo $this->formCaixa->UNIDADE; ?> </span>
<span class="msg_alerta"> </span>
</br>
<input type="submit" name="salvar" value="Salvar" />
<?php echo $this->form->OBRIGATORIO; ?>
</form>
