<div id="dialog_TipoDemanda">
    <?php echo $this->form->TIPO_PESSOA; ?>
    <ul style="list-style: none; padding: 0px 0px 0px 0px;" >
        <li class="li_parte pessTRF"> 
            <span class=" inputParte"> <?php echo $this->form->COMP_CD_MATRICULA_TRF; ?> </span>
        </li>
        <li class="li_parte pessExterna">
            <span class=" inputParte"> <?php echo $this->form->COMP_ID_PESSOA_FISICA; ?> </span>
        </li> 
        <li class="li_parte pessJuridica">
            <span class="inputParte"> <?php echo $this->form->COMP_ID_PESSOA_JURIDICA; ?> </span>
        </li>
        <li class="li_parte unidade">
            <span class="inputParte"> <?php echo $this->form->TRF1_SECAO; ?> </span>
        </li> 
        <li class="li_parte unidade">
            <span class="inputParte"> <?php echo $this->form->UNIDADE_PESSOA; ?> </span>
        </li> 
    </ul>
    <table id="TipoDemanda_selecionadas"  style="margin-top: 20px; width: 80%; display: none;" class="grid tabela">

        <thead> 
            <tr>
                <th colspan="2"> Tipo de Demanda Adicionadas </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="2"><a href='#' class='removerTodosTipoDemanda' rel='' >Remover todos</a></td>
            </tr>
        </tbody>
    </table>
</div> 
