<script type="text/javascript">
    $(function() {
        $( ".novo" ).button({
                    icons: {
                        primary: ""
                    }
        });
     });
</script> 
<?php echo $this->form;?>
<div class="painel" style="margin-left: 100px; margin-top: -43px;"><a title="Novo" class="novo" href="<?php echo $this->baseUrl(); ?>/guardiao/modulo/index">Voltar</a></div>
