<?php
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.maskedinput-1.3.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MetaData.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/jquery.MultiFile.js'));
    $this->inlineScript()->appendFile(($this->baseUrl() . '/js/combobox_app_jquery.js'));
    //$this->inlineScript()->appendFile($this->baseUrl() . '/js/sosti/solicitacoesServicosGraficos/index.js', 'text/javascript');

?>
<script type="text/javascript">
    
    $(function() {
        
        $("#SSOL_NR_TELEFONE_EXTERNO").mask("(99)9999-9999");
        $('#combobox-input-text-SSER_ID_SERVICO').attr('style','width:650px');
        
      
        $('#SGRS_ID_GRUPO').change( function(){
            $('#SSER_ID_SERVICO').empty();
            $('#combobox-input-text-SSER_ID_SERVICO').val('');

            var valorRaw = $('#SGRS_ID_GRUPO').val();
            if(valorRaw != ''){
                var obj = jQuery.parseJSON(valorRaw);
                var grupoID = obj.SGRS_ID_GRUPO;

                url = base_url+'/sosti/solicitacao/ajaxservicos';
                    $.ajax({
                            url:url,
                            type: 'get',
                            data: 'grupoID='+grupoID,
                            dataType:'html',
                            error:function(){
                                alert('error');
                            },
                            success:function(data){
                                $('#SSER_ID_SERVICO').html(data);
                                $('#combobox-input-text-SSER_ID_SERVICO').attr('style','width:650px');
                            }
                    });  
                }
        });
        
        
        $('#ANEXOS').MultiFile({
                STRING: {
                    file: '<em title="Clique para Remover" onclick="$(this).parent().prev().click()">$file</em>',
                    remove: '<img class="excluirpdf" title="Clique para Remover" height="16" width="16"/>'
                }
        });  
        
        $("form[name=save]").submit( function(){
            var $descricao = $.trim( $("#DOCM_DS_ASSUNTO_DOC").val() );
            
            if( $descricao == ""){
                alert('É necessário preencher a Descrição do Serviço.');
                return false;
            }

            var $local = $.trim( $("#SSOL_ED_LOCALIZACAO").val() );
            if( $local == ""){
                alert('É necessário preencher um Local de Atendimento.');
                return false;
            }
            
            //$(this).attr("action", "save");
            return true;
        });
               
    });
</script>

<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<form name="save" action="save" method="POST" enctype="multipart/form-data" >
  
<?php
        echo $this->form->SSOL_ID_DOCUMENTO;
        echo $this->form->UNIDADE;
        echo $this->form->SSOL_NM_USUARIO_EXTERNO;
        echo $this->form->SSOL_NR_TELEFONE_EXTERNO;
        echo $this->form->SSOL_DS_EMAIL_EXTERNO;
        echo $this->form->SSOL_ED_LOCALIZACAO;
        echo $this->form->SSOL_ID_TIPO_CAD;
        echo $this->form->SGRS_ID_GRUPO;
        echo $this->form->SSER_ID_SERVICO;
        echo $this->form->SSOL_QT_ITEM_PEDIDO;
        echo $this->form->DOCM_DS_ASSUNTO_DOC;
        echo $this->form->SSOL_DS_OBSERVACAO;
        echo $this->form->SSOL_HH_INICIO_ATEND;
        echo $this->form->SSOL_HH_FINAL_ATEND;
        echo $this->form->DOCM_NR_DOCUMENTO_RED;
        echo $this->partial('_partials/anexosQualquerExtensao.phtml');
?>
    
    <input type="submit" name="salvar" value="Salvar" />
    <?php echo $this->form->OBRIGATORIO; ?>
</form>
  
