<script src="<?php echo $this->baseUrl() . '/js/sosti/detalheTarefa.js' ?>"></script>
<div class="span-4" id="loadingTarefa" style="display: none; ">
    <div style="margin: 1px 0 0 30px;" class="span-1 last">
        <img src="<?php echo $this->baseUrl()?>/img/ajax-loader_1.gif"/>
    </div>
    <div class="span-2"><strong>Aguarde...</strong></div>
</div>
<div id="message"></div>
<div id="grid"></div>
<div id="form"></div>
<input type="hidden" id="idDocumento" name="idDocumento" value="<?php echo $this->arrayDocumento["SSOL_ID_DOCUMENTO"];?>" />
<input type="hidden" id="idMovimentacao" name="idMovimentacao" value="<?php echo $this->arrayDocumento["MOFA_ID_MOVIMENTACAO"];?>" />
 