<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>-->

<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/cadastroDocumentoGrupo.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/cadastroDocumento.js')); 
?>

<form name="addComponente" action="savecomponente" method="POST" enctype="multipart/form-data">

    <fieldset>
        <?php echo $this->form->GRDV_DS_GRUPO_DIVULGACAO; ?>
        <?php echo $this->partial('aviso/cadastrocomponente.phtml', array('form' => $this->form)); ?>
        <div id="partes_adicionadas"> </div>

        <?php echo $this->form->GRDV_ID_GRUPO_DIVULGACAO; ?>
        <?php echo $this->form->Salvar; ?>
    </fieldset>
    
    <br/>
    <br/>
    <div id="container_pagination">
    <table class="grid">
        <thead>
            <tr>
                <th colspan="9">Componentes Atuais do Grupo</th>
            </tr>
            
        </thead>

        <tbody>
            <?php foreach($this->data as $data): ?>
        <tr>
                <td><?php echo $this->escape($data["COMPONENTE"]) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot><tr><td colspan="10">Total: <?php echo $this->data->getTotalItemCount() ?></td></tr></tfoot>
    </table>
    <?php echo $this->paginationControl($this->data, null, null, null)?>
    </div>

</form>