
 <div id="dialog_cadastra_parte">
      <table id="selecionados_partes"  style="margin-top: 20px; width: 80%; display: none;" class="grid tabela">
     
            <thead> 
                <tr>
                    <th colspan="2"> Documentos a serem adicionados </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2"><a href='#' class='removerTodos' rel='' >Remover todos</a></td>
                </tr>
           </tbody>
      </table>
 </div> 
