<!--<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>-->

<?php 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/combobox_app_jquery.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MetaData.js'));
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/jquery.MultiFile.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/cadastroDocumentoGrupo.js')); 
     $this->inlineScript()->appendFile(($this->baseUrl().'/js/addPermDivulgacao.js')); 
?>

<form name="addPermDivul" action="" method="POST" enctype="multipart/form-data">

    <?php echo $this->form->DOCM_ID_TIPO_DOC; ?>
    <?php echo $this->partial('aviso/addDoc.phtml', array('form' => $this->form)); ?>
    <div id="partes_adicionadas"> </div>

    <?php echo $this->form->Salvar; ?>

</form>