<h2>Seja Bem-Vindo ao Sistema e-Sisad!</h2>
<h3>Selecione uma opção no menu acima.</h3>
<!--<ul>
    <li>Formulários
        <ul>
            <li>Cadastro de solicitação</li>
        </ul>
    </li>
    <li>Cadastros
        <ul>
            <li>Fase ADM</li>
            <li>Cadastro documento</li>
        </ul>
    </li>
    <li>Caixa unidade
        <ul>
            <li>Rascunhos</li>
            <li>Entrada</li>
            <li>Encaminhados</li>
        </ul>
    </li>
    <li>Caixa pessoal
        <ul>
            <li>Rascunhos</li>
            <li>Entrada</li>
            <li>Encaminhados</li>
        </ul>
    </li>
</ul>-->
<?php
//$dados = $this->navigation()->findOneByLabel('Sisad');
//$dados = $this->navigation()->menu()->renderMenu(null, array(
//    'minDepth' => 0,
//    'maxDepth' => 0,
//    'onlyActiveBranch' => true,
//    'renderParents' => false));
?>
<?php //Zend_Debug::dump($dados) ?>
    <?php  //echo $dados; ?>