<?php
echo	$this->partial('_partials/ajuda_informacao.phtml',
		array(	'msgAjuda'	=> $this->msgAjuda,
				'msgInfo'	=> $this->msgInfo));

echo $this->partial('_partials/ajax_despesa.phtml', array('campo' => 'SOLA_NR_DESPESA'));
echo	$this->formulario;

// seta o valor do campo tipo baseado na url
$this->formulario->SOLA_TP_SOLICITACAO->setValue( $this->tipo );

?>

<?php if($this->despesa != ""): ?>

<style>
    .tiposolicitacao {
        margin-top: 10px;
        text-align: left;
        padding: 5px;
        background-color: green;
        color: white;
        width: 300px;
        height: 25px;
        font-weight: bold;
    }

    .tipoacrescimo {
        margin-top: 10px;
        text-align: left;
        padding: 5px;
        background-color: yellow;
        color: black;
        width: 300px;
        height: 25px;
        font-weight: bold;
    }

</style>

<script type="text/javascript">

	var base = '<?= $this->base; ?>';
	var despesa = '<?= $this->despesa; ?>';
    var acrescimo = '<?= $this->acrescimo; ?>';
    var tipo = '<?= $this->tipo ?>';

    $(function() {

		$('#SOLA_TP_SOLICITACAO').val(<?= $this->tipo ?>);

    	$('#SOLA_VL_SOLICITADO').click(function(){
    		$('#SOLA_VL_SOLICITADO').val('');
    	});

    	$('#SOLA_VL_ATENDIDO').click(function(){
    		$('#SOLA_VL_ATENDIDO').val('');
    	});


    	if(despesa != ''){
    		$('#SOLA_NR_DESPESA').val('<?= $this->despesa; ?>');
        	$('#SOLA_NR_DESPESA').blur();
        }

        if(base != "") {
        	$('#SOLA_VL_PROPOSTA_ORIGINAL').attr('readonly', true);
        	$('#SOLA_VL_PROPOSTA_ORIGINAL').attr('style', 'background: rgb(222, 222, 222);');
        	
    		$('#SOLA_VL_PROPOSTA_ORIGINAL').val('<?= $this->base; ?>');
    		$('#SOLA_VL_PROPOSTA_ORIGINAL').blur();
        }

        if(acrescimo != "") {

            $('#SOLA_VL_PROPOSTA_ORIGINAL-label').text('Valor original da proposta inicial:');
            $('#SOLA_VL_PROPOSTA_ORIGINAL').val('<?= $this->acrescimo; ?>');
            $('#SOLA_VL_PROPOSTA_ORIGINAL').blur();
        }

        if(tipo == 0) {
            $('#SOLA_DS_JUSTIFICATIVA_SETORIAL-element').after( '<dd class="tiposolicitacao">Tipo de solicitação de ajuste: Ajuste de Base</dd>' );
        }

        if(tipo == 1) {
            $('#SOLA_DS_JUSTIFICATIVA_SETORIAL-element').after( '<dd class="tipoacrescimo">Tipo de solicitação de ajuste: Acréscimo</dd>' );
        }

    });

</script>

<?php endif; ?>