<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<?php echo $this->partial('_partials/ajuda.phtml', array('msgAjuda' => $this->msgAjuda)); ?>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
    
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
            function(){
                grid_tbody_tr.removeClass('hover_nav');
                
                var this_tr = $(this);
                var is_checked_tr = $(this).attr('marcado');
                
                var input_radio = $(this).find('input');
                var is_checked_input = input_radio.attr('checked');
                
                if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                    input_radio.attr('checked','checked');
                }else{
                    input_radio.removeAttr('checked');
                }
                input_radio.focus();
            }
        );
        
        $("input[type=checkbox][name=input_check_all_grid]").click(
            function(){
                if($(this).attr('checked')){
                    $(".nav_check_boxes").attr('checked','checked');
                }else{
                    $(".nav_check_boxes").removeAttr('checked');
                }
            }
        );
        
        $(".nav_check_boxes").keypress(
            function(e) {
                
            code = e.keyCode ? e.keyCode : e.which;

            var KEY_CODE_h = 104;
            var KEY_CODE_ESC = 27;
            var KEY_CODE_UP = 38;
            var KEY_CODE_w = 115;
            var KEY_CODE_DOWN = 40;
            var KEY_CODE_s = 119;

            if(code.toString() == KEY_CODE_h) {
                $("#dialog-documentos_detalhe").dialog("open");
                $(this).focus();
            }
            if(code.toString() == KEY_CODE_ESC) {
                $("#dialog-documentos_detalhe").dialog("close");
                $(this).focus();
            }

            var current_checkbox_index;
            var this_navigation = this;
            var first_checkbox_index = 0;
            var last_checkbox_index;

            $(".nav_check_boxes").each(
                function(index){
                    last_checkbox_index =  index;
                    if(this_navigation == this){
                        current_checkbox_index = index;
                    }
                }
            );

            if(code.toString() == KEY_CODE_DOWN ||  code.toString() == KEY_CODE_s) {

                var next_checkbox_index;
                var checkbox_achado = false;
                $(".nav_check_boxes").each(
                    function(index){
                        if(checkbox_achado == true){
                            next_checkbox_index = index;
                            checkbox_achado = false;
                        }
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == last_checkbox_index){
                                next_checkbox_index = last_checkbox_index;
                            }
                        }
                    }
                );
                $(".nav_radio").each(
                    function(index){
                        if( index == next_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == next_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
                
            if( code.toString() == KEY_CODE_UP || code.toString() == KEY_CODE_w ) {

                var previews_checkbox_index;
                var checkbox_achado = false;
                $(".nav_radio").each(
                    function(index){
                        if( index == current_checkbox_index){
                            checkbox_achado = true;
                            if(index == first_checkbox_index){
                                previews_checkbox_index = first_checkbox_index;
                            }
                        }
                        if(checkbox_achado == false){
                            previews_checkbox_index = index;
                        }
                    }
                );
                $(".nav_radio").each(
                    function(index){
                        if( index == previews_checkbox_index){
                            $("tr[name=rowList]").each(
                                function(index){
                                    if( index == previews_checkbox_index ){
                                        $("tr[name=rowList]").removeClass('hover_nav');
                                        $(this).addClass('hover_nav');
                                    }
                                }
                            );
                            $(this).focus();
                        }
                    }
                );
            }
        });
            
    $('input[name=acao]').click(
        function(){
            var acao = this.value;
            var cx_unid_ranscunho = $('form[name=etiqueta]');
            if(acao == 'Pesquisar'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/etiqueta/criar');
            }else if(acao == 'Imprimir'){
                cx_unid_ranscunho.attr('action','<?php echo $this->baseUrl(); ?>/sisad/etiqueta/imprimir');
            }
        }
    );
    });
    
    function mascara_dataInicio(dataInicio){ 
          var mydata = ''; 
          mydata = mydata + dataInicio; 
          if (mydata.length == 2){ 
              mydata = mydata + '/'; 
              document.forms[0].dataInicio.value = mydata; 
          } 
          if (mydata.length == 5){ 
              mydata = mydata + '/'; 
              document.forms[0].dataInicio.value = mydata; 
          } 
          if (mydata.length == 10){ 
              verifica_dataInicio(); 
          } 
      } 
    function mascara_dataFim(dataFim){ 
          var mydata = ''; 
          mydata = mydata + dataFim; 
          if (mydata.length == 2){ 
              mydata = mydata + '/'; 
              document.forms[0].dataFim.value = mydata; 
          } 
          if (mydata.length == 5){ 
              mydata = mydata + '/'; 
              document.forms[0].dataFim.value = mydata; 
          } 
          if (mydata.length == 10){ 
              verifica_dataFim(); 
          } 
      } 
           
    function verifica_dataInicio () { 

        dia = (document.forms[0].dataInicio.value.substring(0,2)); 
        mes = (document.forms[0].dataInicio.value.substring(3,5)); 
        ano = (document.forms[0].dataInicio.value.substring(6,10)); 

        situacao = ""; 
        // verifica o dia valido para cada mes 
        if ((dia < 01)||(dia < 01 || dia > 30) && (  mes == 04 || mes == 06 || mes == 09 || mes == 11 ) || dia > 31) { 
            situacao = "falsa"; 
        } 

        // verifica se o mes e valido 
        if (mes < 01 || mes > 12 ) { 
            situacao = "falsa"; 
        } 

        // verifica se e ano bissexto 
        if (mes == 2 && ( dia < 01 || dia > 29 || ( dia > 28 && (parseInt(ano / 4) != ano / 4)))) { 
            situacao = "falsa"; 
        } 

        if (document.forms[0].dataInicio.value == "") { 
            situacao = "falsa"; 
        } 

        if (situacao == "falsa") { 
            alert("Data inválida!"); 
            document.forms[0].dataInicio.focus(); 
        } 
     } 
    function verifica_dataFim () { 

        dia = (document.forms[0].dataFim.value.substring(0,2)); 
        mes = (document.forms[0].dataFim.value.substring(3,5)); 
        ano = (document.forms[0].dataFim.value.substring(6,10)); 

        situacao = ""; 
        // verifica o dia valido para cada mes 
        if ((dia < 01)||(dia < 01 || dia > 30) && (  mes == 04 || mes == 06 || mes == 09 || mes == 11 ) || dia > 31) { 
            situacao = "falsa"; 
        } 

        // verifica se o mes e valido 
        if (mes < 01 || mes > 12 ) { 
            situacao = "falsa"; 
        } 

        // verifica se e ano bissexto 
        if (mes == 2 && ( dia < 01 || dia > 29 || ( dia > 28 && (parseInt(ano / 4) != ano / 4)))) { 
            situacao = "falsa"; 
        } 

        if (document.forms[0].dataFim.value == "") { 
            situacao = "falsa"; 
        } 

        if (situacao == "falsa") { 
            alert("Data inválida!"); 
            document.forms[0].dataFim.focus(); 
        } 
     } 
</script>
<form method="POST" action="" name="etiqueta">
        <b>Protocolos criados - DE: </b>
        <input type="text" title="Data Inicio da Pesquisa" name="dataInicio"  OnKeyUp="mascara_dataInicio(this.value)" maxlength="10" />
        <b>ATÉ: </b>
        <input type="text" title="Data Fim da Pesquisa" name="dataFim"  OnKeyUp="mascara_dataFim(this.value)" maxlength="10" />
    <div class="painel">
        <input type="submit" title="Pesquisar" name="acao" value="Pesquisar" /></input>
    </div><br/>
<?php if (count($this->data)): ?>
<div id="container_pagination">
    <div class="painel">
        <input type="submit" title="Imprimir" name="acao" value="Imprimir" /></input>
    </div>
    <table class="grid">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                </th>
                <th><a>N° Protocolo</a></th>
                <th><a>Qtd Pacote</a></th>
                <th><a>Destinatário</a></th>
                <th><a>Destino</a></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->data as $data):
                ?>
                <tr class="grid_rows <?php echo $this->escape($data["CLASS_LIDO_TR"]); ?>" name="rowList" value="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" > 
                    <td>
                        <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["DOCM_ID_DOCUMENTO"]); ?>" name="documento[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                    </td>
                    <td> <?php echo $this->escape($data["PRDC_ID_PROTOCOLO"]) ?></td>
                    <td> <?php echo $this->escape($data["QTD"]) ?></td>
                    <td> <?php echo $this->escape($data["POST_NM_DESTINATARIO_EXTERNO"]) ?></td>
                    <td> <?php echo $this->escape($data["PJUR_NO_FANTASIA"]) ?></td>
                </tr>
        <?php endforeach; ?>
           </tbody>
        <tfoot>
        <tr>
            <td colspan="9">Total: <?php echo $this->data->getTotalItemCount() ?></td>
        </tr>
        <tr>
            <td colspan="9"><?php echo $this->paginationControl($this->data, null, null, null)
            ?></td>
        </tr>
        </tfoot>
    </table>
    
    <?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
</form>

<div id="dialog-documentos_detalhe">
    <div id="dialog-documentos_conteudo"></div>
</div>