
<div style="width: 1000px; margin: 0 auto; display: block;">
    <table  style="font-size: 12px;" border="1" class="" style="width: 1000px;" >
        <thead>
            <tr>
            <th>Número do Sosti</th>
            <th>Descrição do Serviço</th>
            <th>Nome do Atendente</th>
            <th>Data do Encaminhamento</th>
            <th>Descrição da Última Fase</th>
            </tr>
        </thead>
            
        <tbody>