<style>
    div.assinaturaDocumento h3,h4,h5 {
        font-size: 12px;
        margin-bottom: 3px;
    }

    div.assinaturaDocumento p {
        margin: 0 0 5px 0;
    }
    div.assinaturaDocumento li {
        margin: 10px 0;
    }
    div.detalheAssinatura {
        background: #f7f7f7;
        padding: 10px 10px;
        line-height: 1.7em;
        overflow: hidden;
    }
    div.detalheAssinatura ul{
        padding:0;
        margin-left: 0;
    }
    div.detalheAssinatura ul li {
        float: left;
        margin:5px 0px;
        list-style-position: inside;
        width: 270px;
        padding: 5px 5px 5px 0px;
        overflow: hidden;
        white-space: nowrap;
        text-indent: 16px;
    }
    .assinaturaValida {
        color: #00cc00;
    }
    .assinaturaInvalida {
        color: #ff0000;
    }

    .caixaAssinatura {
        border-bottom: 2px solid #d5d5d5;
        margin-bottom: 10px;
    }
</style>
<div class="assinaturaDocumento">
    <h3>Número:</h3>
    <p>2013/tr/coger/4 </p>
    <h3>Tipo:</h3>
    <p>Processo administrativo</p>
    <h3>Assunto:</h3>
    <p>30.01.02.06 - AVALIAÇÃO DE SERVIÇOS PRESTADOS</p>
    <h3>Assinaturas:</h3>

    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>




                </div>
            </li>
        </ul>
    </div>
    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>




                </div>
            </li>
        </ul>
    </div>
    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>




                </div>
            </li>
        </ul>
    </div>
    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>

                    <h4>Detalhe da assinatura:</h4>
                    <div class="detalheAssinatura">
                        <h5>Ementa:</h5>
                        <p>Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.</p>
                        <h5>Texto:</h5>
                        <p>Ao contrário do que se acredita, Lorem Ipsum não é simplesmente um texto randômico. Com mais de 2000 anos, suas raízes podem ser encontradas em uma obra de literatura latina clássica datada de 45 AC. Richard McClintock, um professor de latim do Hampden-Sydney College na Virginia, pesquisou uma das mais obscuras palavras em latim, consectetur, oriunda de uma passagem de Lorem Ipsum, e, procurando por entre citações da palavra na literatura clássica, descobriu a sua indubitável origem. Lorem Ipsum vem das seções 1.10.32 e 1.10.33 do "de Finibus Bonorum et Malorum" (Os Extremos do Bem e do Mal), de Cícero, escrito em 45 AC. Este livro é um tratado de teoria da ética muito popular na época da Renascença. A primeira linha de Lorem Ipsum, "Lorem Ipsum dolor sit amet..." vem de uma linha na seção 1.10.32.
                            O trecho padrão original de Lorem Ipsum, usado desde o século XVI, está reproduzido abaixo para os interessados. Seções 1.10.32 e 1.10.33 de "de Finibus Bonorum et Malorum" de Cicero também foram reproduzidas abaixo em sua forma exata original, acompanhada das versões para o inglês da tradução feita por H. Rackham em 1914.</p>
                        <h5>Aquivo principal:</h5>
                        <a href="#">Nome do arquivo principal.pdf</a>
                        <h5>Anexos:</h5>
                        <ul>
                            <li>
                                <a href="#">Nome do anexo 1.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome dds.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do sdf asfd dsaf dsaf sadf sdaf sadf dsaf dsf anexo 3.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome dsda.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do a.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nomsd.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                        </ul>
                    </div>


                </div>
            </li>
        </ul>
    </div>
    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>

                    
                </div>
            </li>
        </ul>
    </div>
    <div class="caixaAssinatura">
        <ul>
            <li>
                <div>
                    <h4>Autor:</h4>
                    <p>TR18482PS - LEIDISON SIQUEIRA BARBOSA</p>
                    <h4>Certificado:</h4>
                    <p>Token 123456</p>
                    <h4>Data:</h4>
                    <p>16/04/2013 15:55:21</p>
                    <p ><strong>Assinatura <span class="assinaturaValida">válida</span></strong></p>

                    <a href="#">Fechar detalhes da assinatura</a>

                    <h4>Detalhe da assinatura:</h4>
                    <div class="detalheAssinatura">
                        <h5>Ementa:</h5>
                        <p>Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.</p>
                        <h5>Texto:</h5>
                        <p>Ao contrário do que se acredita, Lorem Ipsum não é simplesmente um texto randômico. Com mais de 2000 anos, suas raízes podem ser encontradas em uma obra de literatura latina clássica datada de 45 AC. Richard McClintock, um professor de latim do Hampden-Sydney College na Virginia, pesquisou uma das mais obscuras palavras em latim, consectetur, oriunda de uma passagem de Lorem Ipsum, e, procurando por entre citações da palavra na literatura clássica, descobriu a sua indubitável origem. Lorem Ipsum vem das seções 1.10.32 e 1.10.33 do "de Finibus Bonorum et Malorum" (Os Extremos do Bem e do Mal), de Cícero, escrito em 45 AC. Este livro é um tratado de teoria da ética muito popular na época da Renascença. A primeira linha de Lorem Ipsum, "Lorem Ipsum dolor sit amet..." vem de uma linha na seção 1.10.32.
                            O trecho padrão original de Lorem Ipsum, usado desde o século XVI, está reproduzido abaixo para os interessados. Seções 1.10.32 e 1.10.33 de "de Finibus Bonorum et Malorum" de Cicero também foram reproduzidas abaixo em sua forma exata original, acompanhada das versões para o inglês da tradução feita por H. Rackham em 1914.</p>
                        <h5>Aquivo principal:</h5>
                        <a href="#">Nome do arquivo principal.pdf</a>
                        <h5>Anexos:</h5>
                        <ul>
                            <li>
                                <a href="#">Nome do anexo 1.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome dds.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do sdf asfd dsaf dsaf sadf sdaf sadf dsaf dsf anexo 3.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome dsda.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do a.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nomsd.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                            <li>
                                <a href="#">Nome do anexo 4.pdf</a>
                            </li>
                        </ul>
                    </div>


                </div>
            </li>
        </ul>
    </div>
</div>