<script type="text/javascript">
                
    $(function() {
        
        $("#CXEN_ID_TIPO_CAIXA").change(
            function(){

                value_tipo_caixa = $(this).val();
                /*acha a tag option selecionada*/
                option = $(this).find("option[value="+value_tipo_caixa+"]");
                /*pega o label do option*/
                option_label = option.html();

                desc_caixa_tipo =  desc_caixa_padrao+' '+ option_label; 

                $("#CXEN_DS_CAIXA_ENTRADA").val(desc_caixa_tipo );

                $("select#TRF1_SECAO").val('');
                $("select#SECAO_SUBSECAO").html('');
                $("select#CXGS_ID_GRUPO").html('');

            }
        );
           
        $("select#TRF1_SECAO").change(
            function () {
                if(this.value === ''){
                    $("select#SECAO_SUBSECAO").html('');
                    $("select#CXGS_ID_GRUPO").html('');
                    return;
                }
                var secao = $(this).val().split('|')[0];
                var lotacao = $(this).val().split('|')[1];
                var tipolotacao = $(this).val().split('|')[2];
                $.ajax({
                    url: base_url + '/sosti/caixagruposervico/ajaxsubsecoes/secao/'+secao+ '/lotacao/'+lotacao+'/tipo/'+tipolotacao,
                    dataType : 'html',
                    beforeSend:function() {
                        $("select#SECAO_SUBSECAO").html('');
                        $("select#CXGS_ID_GRUPO").html('');

                    },
                    success: function(data) {
                        $('select#SECAO_SUBSECAO').html(data);
                    },
                    error: function(){
                      
                        $('select#SECAO_SUBSECAO').html('<option>Erro ao carregar</option>');
                    }
                });
            }
        );
            
        var desc_caixa_padrao = $("#CXEN_DS_CAIXA_ENTRADA").val();
        var desc_caixa_tipo = "";
        $("select#SECAO_SUBSECAO").change(
            function () {
                if(this.value === ''){
                    $("select#CXGS_ID_GRUPO").html('');
                    return;
                }
                $.ajax({
                    url: '<?php echo $this->baseUrl(); ?>/sosti/caixagruposervico/ajaxgruposervicoporpai',
                    dataType: 'html',
                    type: 'POST',
                    data: this.value,
                    contentType: 'application/json',
                    processData: false,
                  beforeSend:function() {
                      $("select#CXGS_ID_GRUPO").html('');
                  },
                  success: function(data) {

                      $("select#CXGS_ID_GRUPO").html('');
                      if(data === '[]'){
                          var option_object = $("<option></option>");
                            /**
                             *  Valor do option do select
                             *  @param option_value
                             */
                            option_value = ''
                            option_object.attr('value',option_value);
                            /**
                             *  Label do option do select
                             *  @param option_label
                             */
                            option_label = "NÃO EXITE GRUPOS DE SERVIÇO CADASTRADOS PARA ESSA SEÇÃO/SUBSEÇÃO/TRF1"
                            option_object.html(option_label);

                            $("select#CXGS_ID_GRUPO").append(option_object);
                      }else{
                          data = jQuery.parseJSON(data);
                          $.each(data, function(key, val) {
                                var option_object = $("<option></option>");
                                /**
                                 *  Valor do option do select
                                 *  @param option_value
                                 */
                                option_value = JSON.stringify(val, null, null);
                                option_object.attr('value',option_value);
                                /**
                                 *  Label do option do select
                                 *  @param option_label
                                 */
                                //option_label = val.SGRS_DS_GRUPO; 
                                option_label = val.SGRS_DS_GRUPO + ' UNIDADE RESP.: ' + val.LOTA_SIGLA_LOTACAO + ' - ' + val.LOTA_DSC_LOTACAO + ' - ' + val.LOTA_COD_LOTACAO + ' - ' + val.LOTA_SIGLA_SECAO;
                                option_object.html(option_label);

                                unidade_responsavel =  val.LOTA_SIGLA_LOTACAO + ' - ' + val.LOTA_DSC_LOTACAO + ' - ' + val.LOTA_COD_LOTACAO + ' - ' + val.LOTA_SIGLA_SECAO;
                                $("select#CXGS_ID_GRUPO").append(option_object);
                            });

                      }
                  },
                  error: function(){

                  }
                });
                secao_subsecao = jQuery.parseJSON($(this).val());
//                desc_caixa = $("#CXEN_DS_CAIXA_ENTRADA").val();
//                $("#CXEN_DS_CAIXA_ENTRADA").val(desc_caixa_tipo+' DO(A): '+ secao_subsecao.LOTA_DSC_LOTACAO + ' - ' + secao_subsecao.LOTA_COD_LOTACAO + ' - ' + secao_subsecao.LOTA_SIGLA_SECAO);
           }
       );

    });
</script>

<?php echo $this->form; ?>