<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>Sobre inclusão de informação solicitadas pelo Desenvolvimento e Sustentação:</p>
    <ul>
        <li>Para <b>incluir</b> informação para o <b>Desenvolvimento</b> basta selecionar as solicitações desejadas, clicar no botão <b>Incluir Informação ao Desenvolvimento</b> e seguir os procedimentos da próxima página.</li>
        <li>Mas se desejar <b>solicitar</b> informação ao <b>usuário cadastrante</b> antes de responder o desenvolvimento e sustentação basta selecionar as solicitações desejadas, clicar no botão <b>Solicitar Informação ao Usuário Cadastrante</b></li>
        <li>Mesmo que o <b>usuário cadastrante não responda</b> a solicitação de informação você poderá responder a solicitação de informação do Desenvolvimento.</li>
    </ul>
    <span id="botao_ajuda_recolhe" ></span>
</div>

<script type="text/javascript">
    var arrayDestinos = {
        "Incluir Informação" : base_url + "/sosti/minhassolicitacoes/pedidoinformacaoadd"
        ,"Solicitar Informação ao Usuário Cadastrante" : base_url + "/sosti/solicitacao/solicitarinformacao"
    };
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento;

    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(function(){
            grid_tbody_tr.removeClass('hover_nav');

            var this_tr = $(this);
            var is_checked_tr = $(this).attr('marcado');

            var input_check_box = $(this).find('input[type=checkbox]');
            var is_checked_input = input_check_box.attr('checked');

            if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
                input_check_box.attr('checked','checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
            }else{
                input_check_box.removeAttr('checked');
                this_tr.removeAttr('marcado');
                this_tr.removeClass('hover');
            }
            input_check_box.focus();
        });
        grid_tbody_tr.dblclick(function(){
            var this_tr = $(this);
            var input_check_box = $(this).find('input');

            var div_dialog_by_id =  $("#dialog-documentos_detalhe");
            value_input_check_box = input_check_box.val();
            input_check_box.attr('checked', 'checked');
            this_tr.attr('marcado','marcado');
            this_tr.addClass('hover');

            if (xhr_abrir_documento) {
                xhr_abrir_documento.abort();
            }

            url = base_url + '/sosti/detalhesolicitacao/detalhesol/act/<?php echo $this->action; ?>';
            xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false,
                beforeSend: function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){

                },
                error : function(){

                }
            });
        });
        $("input[type=checkbox][name=input_check_all_grid]").click(function(){
            if($(this).attr('checked')){
                $(".nav_check_boxes").attr('checked','checked');
                $("tr[name=rowList]").addClass('hover');
            }else{
                $(".nav_check_boxes").removeAttr('checked');
                $("tr[name=rowList]").removeClass('hover');
            }
        });
        $('input[name=acao]').click(function(){

            var acao = this.value;
            var formhelpdesk = $('form[name=helpdesk]');
            formhelpdesk.attr('action',arrayDestinos[acao]);
        });
        $('form[name=helpdesk]').submit(function(){
            var solictacaoSelecionada = $("input[type=checkbox][name=solicitacao[]]:checked").val();
            if (solictacaoSelecionada == undefined){
                var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
                $('#flashMessages').html(mensagem);
                return false;
            }
        });
        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
            autoOpen : false,
            modal    : false,
            show: 'fold',
            hide: 'fold',
            resizable: true,
            width: 800,
            position: [580,140,0,0],
            buttons : {
                Ok: function() {
                    $(this).dialog("close");
                }
            }
        });
    });
</script>
<input type="hidden" id="cx" value="<?php echo $this->action; ?>" />
<form name="helpdesk" action="" method="post" >
    <div class="painel">
        <input type="submit" title="Incluir Informação ao Desenvolvimento" name="acao" value="Incluir Informação"/>
        <input type="submit" title="Solicitar Informação ao Usuário Cadastrante" name="acao" value="Solicitar Informação ao Usuário Cadastrante"/>
    </div>
    <?php if (count($this->data)): ?>
        <div id="container_pagination">
            <table class="grid">
                <thead>
                    <tr>
                        <th><input type="checkbox" name="input_check_all_grid" id="check_all" /></th>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/desenvolvimentosustentacao/index/ordem/DOCM_NR_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/desenvolvimentosustentacao/index/ordem/TEMPO_TOTAL/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/desenvolvimentosustentacao/index/ordem/NOME_USARIO_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/desenvolvimentosustentacao/index/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                        <th><a href="<?php echo $this->baseUrl(); ?>/sosti/desenvolvimentosustentacao/index/ordem/NOME_ATENDENTE/direcao/<?php echo $this->direcao ?> ">Atendente<span class="<?php echo ($this->direcao == 'ASC') ? ('ordenacaodesc') : ('ordenacaoasc'); ?>"></span></a></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->data as $data): ?>
                        <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" >
                            <td <?php
                echo ($data["SESP_DH_LIMITE_ESP"]) ? ('style="background-color:#0099FF;" title="Solicitação colocada em espera!"') : ('');
                // echo ($data["TEMPO_TOTAL"] > 120)?('style="background-color:#EE4115;" title="Solicitação com o tempo de atendimento ultrapassado!"'):('');
                echo ($data["MOFA_ID_FASE"] == 1019) ? ('style="background-color:#E88400;" title="Solicitação recusada!"') : ('');
                        ?> >
                                <input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/>
                            </td>
        <!--                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>-->
                            <td style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>
                            <td><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                            <td><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"] . ' - ' . $data['NOME_USARIO_CADASTRO']); ?></td>
                            <td><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                            <td><?php echo $this->escape($data["NOME_ATENDENTE"]); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <?php echo $this->paginationControl($this->data, null, null, null); ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        <?php else: ?>
            <p>Não existem registros</p>
        <?php endif; ?>
    </div>
    <div class="painel">
        <input type="submit" title="Incluir Informação ao Desenvolvimento" name="acao" value="Incluir Informação"/>
        <input type="submit" title="Solicitar Informação ao Usuário Cadastrante" name="acao" value="Solicitar Informação ao Usuário Cadastrante"/>
    </div>
    <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>
    <input name="action"     type="hidden"  value="<?php echo $this->action; ?>"/>
</form>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
    <div id="dialog-documentos_conteudo"></div>
</div>