<div id="flashMessagesView"><?php echo $this->flashMessagesView; ?></div>
<div class="help" id="msg_ajuda" style="display: none; " >
    <script>
        $(function(){
            botao_ajuda_by_id.delay(200).show('scale');
        })
    </script>
    <h3>Ajuda&ensp;</h3>
    <p>A <b>avaliação</b> será obrigatória e deve ser realizada assim que receberem o aviso de baixa da solicitação na sua Caixa Pessoal. 
       Por meio dessa avaliação, serão gerados os relatórios para pagamento a empresa.
    </p>
    <ul>
        <li>Basta marcar a solicitação que deseja avaliar e clique no botão <b>Avaliar</b>.</li>
        <li style="font-weight: bold;">Solicitaçoes baixadas há mais de 10 dias aparecerão em <span style="color: red">vermelho</span> </li>
    </ul>
    
    
<!--    <a target="_blank" title="Documento de ajuda completo" href="<?php echo $this->baseUrl(); ?>/sisad/gerenciared/recuperar/dcmto/472880100233">Ajuda completa.</a>-->
    <span id="botao_ajuda_recolhe" ></span>
</div>

<script type="text/javascript">
    
    var GLOBAL_indice_abas =  0;
    var xhr_abrir_documento; 
      
    var grid_tbody_tr;
    $(function(){

        grid_tbody_tr = $("table.grid > tbody > tr");
        grid_tbody_tr.click(
		function(){
			grid_tbody_tr.removeClass('hover_nav');
                
			var this_tr = $(this);
			var is_checked_tr = $(this).attr('marcado');
                
			var input_check_box = $(this).find('input[type=checkbox]');
			var is_checked_input = input_check_box.attr('checked');
                
			if( (is_checked_input == undefined && is_checked_tr == undefined) || (is_checked_input != undefined && is_checked_tr == undefined) ){
				input_check_box.attr('checked','checked');
				this_tr.attr('marcado','marcado');
				this_tr.addClass('hover');
			}else{
				input_check_box.removeAttr('checked');
				this_tr.removeAttr('marcado');
				this_tr.removeClass('hover');
			}
			input_check_box.focus();
		}
	);
        
        grid_tbody_tr.dblclick(
            function(){
                var this_tr = $(this);
                var input_check_box = $(this).find('input');
                
                var div_dialog_by_id =  $("#dialog-documentos_detalhe");
                value_input_check_box = input_check_box.val();
                input_check_box.attr('checked', 'checked');
                this_tr.attr('marcado','marcado');
                this_tr.addClass('hover');
                
                if (xhr_abrir_documento) {
                    xhr_abrir_documento.abort();
                }
                
                url = '<?php echo $this->baseUrl(); ?>/sosti/detalhesolicitacao/detalhesol';
                                xhr_abrir_documento = $.ajax({
                url: url,
                dataType: 'html',
                type: 'POST',
                data: value_input_check_box,
                contentType: 'application/json',
                processData: false, 
                beforeSend:function() {
                    div_dialog_by_id.dialog("open");
                },
                success: function(data) {
                    div_dialog_by_id.html(data);

                },
                complete: function(){
                    
                },
                error : function(){
                    
                }
                });
            }
        );   
        
        $("input[type=checkbox][name=input_check_all_grid]").click(
		function(){
			if($(this).attr('checked')){
				$(".nav_check_boxes").attr('checked','checked');
				$("tr[name=rowList]").addClass('hover');
			}else{
				$(".nav_check_boxes").removeAttr('checked');
				$("tr[name=rowList]").removeClass('hover');
			}
		}
	);
        var form_valido = false;
        
        $('input[name=acao]').click(
            function(){
                var acao = this.value;
                var formhelpdesk = $('form[name=helpdesk]');
                    if(acao == 'Avaliar'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/avaliacaoadd');
                }else if(acao == 'Solicitar Informação ao Usuário Cadastrante'){
                    formhelpdesk.attr('action','<?php echo $this->baseUrl(); ?>/sosti/solicitacao/solicitarinformacao');
                }
            }
        );
        
        
        
        $('form[name=helpdesk]').submit(
		function(){
                
			if(form_valido){
				return true;
			}
               
			var solictacaoSelecionada = $("input[type=checkbox][name=solicitacao[]]:checked").val();
			if (solictacaoSelecionada == undefined){ 
				var mensagem = "<div class='notice'><strong>Alerta:</strong> Escolha uma solicitação!</div>";
				$('#flashMessages').html(mensagem);
				return false;
			}else{
				return true;
			}
                
		}
	);
		     grid_tbody_tr = $("table.grid > tbody > tr");
                       grid_tbody_tr.each(function(i,val){
                       var $this = $(this).find('input[type=checkbox]').attr('value');
                       var objeto = jQuery.parseJSON($this);
                       var fase = objeto.MOFA_ID_FASE;
                       if(fase == 1056){
                        $(this).find('td').first().addClass('pedidoCancelamento');
                      }});

        $("#dialog-documentos_detalhe").dialog({
            title    : 'Detalhe',
			autoOpen : false,
			modal    : false,
			show: 'fold',
			hide: 'fold',
			resizable: true,
			width: 800,
			position: [580,140,0,0],
			buttons : {
				Ok: function() {
					$(this).dialog("close");
				}
			}
		});
    });
</script>




<?php if (count($this->data)): ?>
<form name="helpdesk" action="" method="post" >
    <div class="painel">
        <input type="submit" title="Solicitar Informa&ccedil;&atilde;o ao Usuário Cadastrante" name="acao" value="Solicitar Informação ao Usuário Cadastrante"/>
        <input type="submit" title="Avaliar a solicitação" name="acao" value="Avaliar"/>
        
<!--        <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
        <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>
        <input name="" type="button" onClick='javascript:location.href="<?php //echo $this->baseUrl(); ?>/sosti/solicitacao/form"' value="Nova">-->
    </div>
    
    <div id="container_pagination">
        <table class="grid">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="input_check_all_grid" id="check_all" /> 
                    </th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/SSOL_ID_DOCUMENTO/direcao/<?php echo $this->direcao ?> ">N. da solicitação<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/DATA_FASE/direcao/<?php echo $this->direcao ?> ">Data Baixa<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/TEMPO_TOTAL/direcao/<?php echo $this->direcao ?> ">Tempo total<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/NOME_USARIO_CADASTRO/direcao/<?php echo $this->direcao ?> ">Nome do solicitante<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/SSER_DS_SERVICO/direcao/<?php echo $this->direcao ?> ">Serviço atual<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                    <th><a href="<?php echo $this->baseUrl(); ?>/sosti/minhassolicitacoes/pendenteavaliacao/ordem/ENCAMINHADORR/direcao/<?php echo $this->direcao ?> ">Analista Responsável<span class="<?php echo ($this->direcao == 'ASC')?('ordenacaodesc'):('ordenacaoasc');  ?>"></span></a></th>
                </tr>
            </thead>
            <tbody>
                <?php 
                
                foreach($this->data as $data): 
                    
                    $tc             = $data["DIAS_BAIXA"];
                    
                    if ($tc > 10)
                    {
                        $font = "style='color:red;'";
                    }
                    ?>
                    <tr name="rowList" value="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]); ?>"  style="<?php if($data["ESPERA_FLAG"] >= 0 && !is_null($data["ESPERA_FLAG"])) echo "color: #008000;"?>">
                        <td style="color:red;"><input class="nav_grid_check_box nav_check_boxes" id="<?php echo $this->escape($data["SSOL_ID_DOCUMENTO"]);?>" name="solicitacao[]" type="checkbox" value="<?php echo $this->escape($data["DADOS_INPUT"]); ?>"/></td>
<!--                        <td><?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]); ?></td>-->
                        <td <?=$font?> style="width: 15%" title= <?php echo $this->escape($data["DOCM_NR_DOCUMENTO"]) ?> > <?php echo $this->escape($data["MASC_NR_DOCUMENTO"]) ?></td>                  
                        <td <?=$font?>><?php echo $this->escape($data["DATA_FASE"]); ?></td>
                        <td <?=$font?>><?php echo $this->escape($data["TEMPO_TRANSCORRIDO"]); ?></td>
                        <td <?=$font?>><?php echo $this->escape($data["DOCM_CD_MATRICULA_CADASTRO"].' - '.$data['NOME_USARIO_CADASTRO']); ?></td>
                        <td <?=$font?>><?php echo $this->escape($data["SSER_DS_SERVICO"]); ?></td>
                        <td <?=$font?>><?php echo $this->escape($data["ENCAMINHADORR"]); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">Total: <?php echo $this->data->getTotalItemCount(); ?></td>
                </tr>
                <tr>
                    <td colspan="7"><?php echo $this->paginationControl($this->data, null, null, null); ?></td>
                </tr>
            </tfoot>
        </table>
    
    </div>
    
    <div class="painel">
        <input type="submit" title="Pedir informação para solicitação de TI" name="acao" value="Solicitar Informação"/>
        <input type="submit" title="Avaliar a solicitação" name="acao" value="Avaliar"/>
        
<!--        <input type="submit" title="Baixar a solicitação" name="acao" value="Baixar"/>
        <input type="submit" title="Colocar a solicitação em spera" name="acao" value="Espera"/>
        <input name="" type="button" onClick='javascript:location.href="<?php //echo $this->baseUrl(); ?>/sosti/solicitacao/form"' value="Nova">-->
    </div>
     <input name="controller" type="hidden"  value="<?php echo $this->controller; ?>"/>        
    <input name="action"     type="hidden"  value="<?php echo $this->action; ?>"/>
</form>
<?php else:?>
        <p>Não existem registros</p>
    <?php endif; ?>
<div id="dialog-documentos_detalhe">
    <img style="display: none; position: absolute; z-index: 5000; top: 5px; left: 15px;" class="loading" id="load" alt="" src="public/img/loading.gif" />
 <div id="dialog-documentos_conteudo"></div>
</div>